#!/usr/bin/env python3
"""Re-derive character_drops.json from THIS repo's own roster data.

The rule (user, 2026-07-25): a character with fewer than six fully-evolved
Pokemon obtainable in this game is not offered here -- unless a legendary or
mythical is on the roster, which exempts them. They keep their table slot and
are hidden from the menu (saves store the character INDEX).

Why this script exists: the drop list was originally computed by the audit's
`per_game_threshold.py`, which reads the audit's `final_rosters.json`. That file
does NOT include this repo's `roster_additions.json` overlay or wave 5, so its
answer drifts from what the ROM actually enforces in both directions -- it once
left 18 Legends: Arceus wardens selectable with one final evolution each. Derive
the threshold from `rosters_mapped.json` (post-overlay, post-removal, what the
emitter turns into characters.h) and the two facts stay in sync.

Run before emit_characters.py; it rewrites character_drops.json in place.
"""
import importlib.util
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))


def _load(name):
    spec = importlib.util.spec_from_file_location(name, os.path.join(HERE, name + ".py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main():
    docs = _load("emit_roster_docs")
    emit = _load("emit_characters")

    mapped = json.load(open(os.path.join(HERE, "rosters_mapped.json")))
    kids = docs.evolution_children()
    collapse, siblings = docs.form_tables()

    def finals_of(base):
        """Same walk emit_roster_docs uses for the doc rows -- keep them
        identical, or the docs and the threshold disagree about who is thin."""
        out, stack, seen = set(), [base], set()
        while stack:
            cur = stack.pop()
            if cur in seen:
                continue
            seen.add(cur)
            children = kids.get(cur, [])
            if not children:
                out.add(cur if docs.regional_form(cur) else collapse.get(cur, cur))
            stack.extend(children)
            stack.extend(siblings.get(cur, ()))
        return {s for s in out if not kids.get(s)}

    dropped, kept = [], 0
    for key, info in sorted(mapped.items()):
        name = re.sub(r"\s*\(anime\)$", "", key)
        species = info["species"]
        if any(s in emit.LEGENDARY_BASES for s in species):
            kept += 1
            continue                      # legendary/mythical exemption
        finals = set()
        for base in species:
            finals |= finals_of(base)
        if len(finals) < 6:
            dropped.append((name, len(finals)))
        else:
            kept += 1

    path = os.path.join(HERE, "character_drops.json")
    old = set()
    if os.path.isfile(path):
        old = set(json.load(open(path)).get("unselectable", []))
    new = sorted(n for n, _ in dropped)

    json.dump({"_comment": "Characters that stay in the table (saves store the "
                           "INDEX) but are not offered in this game: fewer than "
                           "six fully-evolved members of their roster exist in "
                           "its dex, and no legendary exempts them. GENERATED by "
                           "derive_drops.py -- do not hand-edit.",
               "unselectable": new},
              open(path, "w"), indent=1, sort_keys=True, ensure_ascii=False)

    print("%d characters, %d offered, %d hidden" % (len(mapped), kept, len(new)))
    for n, c in sorted(dropped, key=lambda x: x[1]):
        print("   %-16s %d final%s" % (n, c, "" if c == 1 else "s"))
    for n in sorted(set(new) - old):
        print("   + newly hidden: %s" % n)
    for n in sorted(old - set(new)):
        print("   - now offered:  %s" % n)


if __name__ == "__main__":
    main()
