#!/usr/bin/env python3
"""Generate src/data/pokemon/pre_evolution.h -- the reverse of gEvolutionTable.

GENERATED. Never hand-edit the output; regenerate it.

WHY. GetFirstEvolution (src/level_scaling.c) used to answer "what evolves into
this?" by scanning the whole of gEvolutionTable -- NUM_SPECIES * EVOS_PER_MON
comparisons per walk-back step, finding nothing at all for a species with no
pre-evolution. It has nine callers, including the catch gate. Measured through
the wild-encounter path: ~3.3M cycles, ~0.2 s of GBA time per fired encounter.

This table makes the lookup O(1) per step. It lives in ROM rather than being
built at boot because EWRAM has under 1 KB free in this tree -- a 2,964-byte
runtime cache overflows it and the link fails with "cannot move location counter
backwards".

⚠️ SEMANTICS ARE COPIED EXACTLY, INCLUDING THE ODD PART. The old scan took the
LOWEST species index whose evolution row targets the species, and it did NOT
filter by method or skip empty entries. Two consequences that must be preserved:

  * mega entries count, so a mega form's pre-evolution is its base form;
  * gEvolutionTable rows are ZERO-FILLED to EVOS_PER_MON, so a row with fewer
    real entries still "targets" SPECIES_NONE. The lowest such row is Bulbasaur
    (one real evolution, nine zero slots), so the old code answered
    GetFirstEvolution(SPECIES_NONE) == SPECIES_BULBASAUR. That is strange, but
    some caller may lean on it, and preserving it keeps this a pure speedup.

The zero-fill is why this cannot simply read the parsed entries: the padding is
invisible in the source and has to be modelled.

Correctness is not argued, it is CHECKED: GetFirstEvolutionReference is kept in
level_scaling.c and CM_REQ_VERIFY_PREEVO sweeps every species through both
implementations (tools/mgba_scripts/pre_evolution_e2e.lua).
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))

EVOS_PER_MON = 10


def read(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        return f.read()


def species_ids():
    """SPECIES_* -> numeric id, via audit_rosters.py's resolver."""
    src = read(os.path.join(HERE, "audit_rosters.py"))
    ns = {"__file__": os.path.join(HERE, "audit_rosters.py")}
    exec(compile(src.split("def main()")[0], "species_ids", "exec"), ns)
    ids, _raw = ns["species_ids"]()
    return ids


def main():
    ids = species_ids()
    num_species = ids.get("NUM_SPECIES")
    if not num_species:
        sys.exit("emit_pre_evolution: could not resolve NUM_SPECIES")

    text = read(os.path.join(TARGET, "src/data/pokemon/evolution.h"))
    body = re.search(
        r"gEvolutionTable\[NUM_SPECIES\]\[EVOS_PER_MON\]\s*=\s*\{(.*?)^\};",
        text, re.S | re.M).group(1)

    # Parse each row's real entries, in source order.
    rows = [(m.start(), m.group(1)) for m in re.finditer(r"\[(SPECIES_\w+)\]\s*=", body)]
    entries = {}
    for t in re.finditer(r"\{\s*(EVO_\w+)\s*,\s*[^,]+?\s*,\s*(SPECIES_\w+)", body):
        src = None
        for pos, name in rows:
            if pos < t.start():
                src = name
            else:
                break
        if src:
            entries.setdefault(src, []).append(t.group(2))
    if not entries:
        sys.exit("emit_pre_evolution: parsed 0 evolution rows")

    # Model the table exactly: species index -> EVOS_PER_MON slots, real entries
    # first, the remainder zero-filled (SPECIES_NONE == 0).
    pre = [0] * num_species
    claimed = [False] * num_species
    for j in range(1, num_species):
        const = None
        for name, val in ids.items():
            if val == j and name in entries:
                const = name
                break
        targets = [ids.get(e, 0) for e in entries.get(const, [])] if const else []
        targets = targets[:EVOS_PER_MON]
        targets += [0] * (EVOS_PER_MON - len(targets))   # the zero-fill
        for target in targets:
            if 0 <= target < num_species and not claimed[target]:
                claimed[target] = True
                pre[target] = j

    # Sanity: a table where nothing has a pre-evolution would make the fast path
    # a no-op and every test still pass.
    have = sum(1 for i in range(1, num_species) if pre[i])
    if have < 300:
        sys.exit("emit_pre_evolution: only %d species have a pre-evolution -- "
                 "the parse is broken and GetFirstEvolution would silently "
                 "become the identity function" % have)

    id_to_const = {}
    for name, val in ids.items():
        if name.startswith("SPECIES_") and val is not None:
            id_to_const.setdefault(val, name)

    out = os.path.join(TARGET, "src/data/pokemon/pre_evolution.h")
    lines = [
        "// GENERATED by tools/character_mode/emit_pre_evolution.py -- do not hand-edit.",
        "//",
        "// gPreEvolutionSpecies[X] is the species that evolves INTO X, or SPECIES_NONE.",
        "// It is the reverse of gEvolutionTable and replaces the full-table scan that",
        "// GetFirstEvolution used to do on every call (nine callers, including the",
        "// catch gate; ~0.2 s of GBA time per fired wild encounter).",
        "//",
        "// Semantics match the scan it replaced EXACTLY, including two quirks: mega",
        "// evolution entries count, and the zero-filled tail of each row means",
        "// SPECIES_NONE resolves to the lowest padded row (Bulbasaur).",
        "//",
        "// Proven equivalent for every species by CM_REQ_VERIFY_PREEVO",
        "// (tools/mgba_scripts/pre_evolution_e2e.lua), not by inspection.",
        "",
        "const u16 gPreEvolutionSpecies[NUM_SPECIES] =",
        "{",
    ]
    for i in range(num_species):
        if pre[i]:
            lines.append("    [%s] = %s,"
                         % (id_to_const.get(i, str(i)), id_to_const.get(pre[i], str(pre[i]))))
    lines.append("};")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s (%d species have a pre-evolution, of %d)"
          % (out, have, num_species))


if __name__ == "__main__":
    main()
