#!/usr/bin/env python3
"""Give EVERY species a complete set of battle graphics.

The species-graphics tables are designated-initializer arrays
(`SPECIES_SPRITE(X, ...)` -> `[SPECIES_X] = ...`). Species with no row therefore
get a ZERO entry -- a NULL pointer -- and the battle engine dereferences it the
moment that Pokemon is sent out:

    sprite->anims = gMonFrontAnimsPtrTable[species];   // NULL
    ...
    -> "Jumped to invalid address"

That is not hypothetical: 120 Gen 9 species (Toedscruel, Annihilape, Armarouge,
Baxcalibur, Ceruledge, ...) shipped WITH front/back/palette art but with no entry
in gMonFrontAnimsPtrTable, so every one of them hard-crashed the game on send-out.
The randomizer (GetTrainerPokemon) can pick any species, so this was reachable
from an ordinary trainer battle.

This fills every gap:
  - real art missing  -> the CircledQuestionMark placeholder already in the ROM
  - anims missing     -> a shared single-frame animation
Nothing that already has a row is touched. Idempotent via ROWEGFX markers.
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
M = "ROWEGFX"

def read(p):  return open(os.path.join(ROOT, p), encoding="utf-8").read()
def write(p, s): open(os.path.join(ROOT, p), "w", encoding="utf-8").write(s)
def strip_block(text, tag):
    return re.sub(r"\n?// %s-START %s.*?// %s-END %s\n?" % (M, tag, M, tag), "\n", text, flags=re.S)
def wrap(tag, block):
    return ("// %s-START %s (generated by tools/character_mode/fix_species_graphics.py)\n"
            "%s// %s-END %s\n" % (M, tag, block, M, tag))

# ---- resolve every SPECIES_* to a number
sp = read("include/constants/species.h")
names = re.findall(r"#define\s+(SPECIES_\w+)\s", sp)
tmp = "/tmp/_rowegfx.c"
open(tmp, "w").write('#include "constants/species.h"\n' + "\n".join(names) + "\nNUM_SPECIES\n")
out = subprocess.run(["cpp", "-I", os.path.join(ROOT, "include"), "-P", tmp],
                     capture_output=True, text=True).stdout
lines = [l.strip() for l in out.split("\n") if l.strip()]
name2id, id2name = {}, {}
for n, l in zip(names, lines):
    try:
        v = eval(l)
    except Exception:
        continue
    name2id[n] = v
    id2name.setdefault(v, n)          # first spelling wins; aliases exist
NUM = eval(lines[len(names)])

# ---- which species already have a row in each table?
TABLES = [
    # (table, file, row-regex, tag, emit(name) -> row text)
    ("gMonFrontPicTable", "src/data/pokemon_graphics/front_pic_table.h",
     r"SPECIES_\w*SPRITE\((\w+),", "front",
     lambda n: "    SPECIES_SPRITE(%s, gMonFrontPic_CircledQuestionMark),\n" % n),
    ("gMonBackPicTable", "src/data/pokemon_graphics/back_pic_table.h",
     r"SPECIES_\w*SPRITE\((\w+),", "back",
     lambda n: "    SPECIES_SPRITE(%s, gMonBackPic_CircledQuestionMark),\n" % n),
    ("gMonPaletteTable", "src/data/pokemon_graphics/palette_table.h",
     r"SPECIES_\w*PAL\((\w+),", "pal",
     lambda n: "    SPECIES_PAL(%s, gMonPalette_CircledQuestionMark),\n" % n),
    ("gMonShinyPaletteTable", "src/data/pokemon_graphics/shiny_palette_table.h",
     r"SPECIES_\w*PAL\((\w+),", "shinypal",
     lambda n: "    SPECIES_PAL(%s, gMonShinyPalette_CircledQuestionMark),\n" % n),
    ("gMonFrontAnimsPtrTable", "src/data/pokemon_graphics/front_pic_anims.h",
     r"ANIM_CMD(?:_FULL)?\((\w+)[,)]|\[SPECIES_(\w+)\]", "anims",
     lambda n: "    ANIM_CMD_FULL(%s, sAnims_RoweGeneric),\n" % n),
]

dry = "--dry-run" in sys.argv
total = 0
for tname, path, pat, tag, emit in TABLES:
    text = strip_block(read(path), tag)
    m = re.search(re.escape(tname) + r"\s*\[[^\]]*\]\s*=\s*\{(.*?)\n\};", text, re.S)
    if not m:
        print("!! %s not found in %s" % (tname, path)); continue
    have = set()
    for mm in re.finditer(pat, m.group(1)):
        g = mm.group(1) or mm.group(2)
        if not g: continue
        key = g if g.startswith("SPECIES_") else "SPECIES_" + g
        if key in name2id: have.add(name2id[key])
    missing = [i for i in range(1, NUM) if i in id2name and i not in have]
    print("%-24s %4d rows, %4d missing" % (tname, len(have), len(missing)))
    total += len(missing)
    if dry or not missing:
        if not dry: write(path, text)
        continue
    rows = "".join(emit(id2name[i][len("SPECIES_"):]) for i in missing)
    close = text.find("\n};", m.start())
    text = text[:close + 1] + wrap(tag, rows) + text[close + 1:]
    write(path, text)

# ---- the shared fallback animation the anims rows point at
if not dry:
    path = "src/data/pokemon_graphics/front_pic_anims.h"
    text = strip_block(read(path), "genericanim")
    anchor = "const union AnimCmd *const *const gMonFrontAnimsPtrTable[] ="
    if "sAnims_RoweGeneric[]" not in text:   # the DEFINITION, not the rows that reference it
        block = ("static const union AnimCmd *const sAnims_RoweGeneric[] ={\n"
                 "    sAnim_GeneralFrame0,\n"
                 "};\n\n")
        i = text.index(anchor)
        text = text[:i] + wrap("genericanim", block) + text[i:]
        write(path, text)

print("\n%d gaps filled" % total)
