#!/usr/bin/env python3
"""Import character sprites from donor decomps (pokefirered etc.) into ROWE.

For each manifest entry this script:
  - builds a 9-frame 16x32 overworld sheet (16px wide, frames stacked
    vertically so gbagfx's tile order is frame-major) from the donor's
    people sprite; 3-frame standing sprites get their facing frames
    duplicated into the walk slots (character glides instead of striding)
  - copies the donor trainer front pic (64x64) and its palette
  - generates all C wiring inside CHARMODE-SPRITES marker blocks:
    OBJ_EVENT_GFX id, graphics info, pic table, INCBINs, palette tag,
    TRAINER_PIC id, front pic tables/anims, graphics.h externs

Idempotent: re-running replaces the marker blocks.
Run AFTER editing MANIFEST; then re-run emit_characters.py and make.
"""
import os
import re
import shutil
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR_FR = os.environ.get(
    "FRLG_DONOR",
    "/tmp/claude-1000/-home-jbfish00-Documents-Pokemon-Rowe-Alteration/"
    "d861755c-2ee7-4188-8126-ad647883e68d/scratchpad/pokefirered")
DONOR_PT = os.environ.get(
    "PLAT_DONOR",
    "/tmp/claude-1000/-home-jbfish00-Documents-Pokemon-Rowe-Alteration/"
    "d861755c-2ee7-4188-8126-ad647883e68d/scratchpad/platinum")
DONOR_HNS = os.environ.get(
    "HNS_DONOR",
    "/tmp/claude-1000/-home-jbfish00-Documents-Pokemon-Rowe-Alteration/"
    "d861755c-2ee7-4188-8126-ad647883e68d/scratchpad/hns")
# DiegoWT's "Gen 5 Characters in Gen 4 OW style" pack (Eevee Expo resource
# 370, https://eeveeexpo.com/resources/370/) - credit DiegoWT in CREDITS.
DONOR_EP4 = os.environ.get(
    "EP4_DONOR",
    "/tmp/claude-1000/-home-jbfish00-Documents-Pokemon-Rowe-Alteration/"
    "d861755c-2ee7-4188-8126-ad647883e68d/scratchpad/owpack370/OW PACK")
# Individual fan sheets checked into the repo (see CREDITS_CHARACTER_MODE.md)
DONOR_SHEETS = os.path.join(HERE, "donor_sheets")

MS = "// CHARMODE-SPRITES-START {tag} (generated by tools/character_mode/import_sprites.py)"
ME = "// CHARMODE-SPRITES-END {tag}"

# Manifest entries: (NAME, ow_source, front_source)
#   ow_source:    ("frlg", "people-relative.png") or ("rowe", "repo-relative.png") or None
#   front_source: ("frlg", "front_pic_stem") or None (None = ROWE already has a
#                 TRAINER_PIC for this character; no import needed)
MANIFEST = [
    # --- Gen I from pokefirered (3-frame standing sets; glide walk) ---
    ("BLUE", ("hns", "graphics/object_events/pics/people/gym_leaders/blue.png"),     ("frlg", "champion_rival")),
    ("LANCE", ("hns", "graphics/object_events/pics/people/elite_four/lance.png"),    ("frlg", "elite_four_lance")),
    ("LORELEI",  ("frlg", "lorelei.png"),  ("frlg", "elite_four_lorelei")),
    ("BRUNO", ("hns", "graphics/object_events/pics/people/elite_four/bruno.png"),    ("frlg", "elite_four_bruno")),
    ("AGATHA",   ("frlg", "agatha.png"),   ("frlg", "elite_four_agatha")),
    ("KOGA", ("hns", "graphics/object_events/pics/people/elite_four/koga.png"),     ("frlg", "leader_koga")),
    ("BROCK", ("hns", "graphics/object_events/pics/people/gym_leaders/brock.png"),    ("frlg", "leader_brock")),
    ("MISTY", ("hns", "graphics/object_events/pics/people/gym_leaders/misty.png"),    ("frlg", "leader_misty")),
    ("LT_SURGE", ("hns", "graphics/object_events/pics/people/gym_leaders/surge.png"), ("frlg", "leader_lt_surge")),
    ("ERIKA", ("hns", "graphics/object_events/pics/people/gym_leaders/erika.png"),    ("frlg", "leader_erika")),
    ("SABRINA", ("hns", "graphics/object_events/pics/people/gym_leaders/sabrina.png"),  ("frlg", "leader_sabrina")),
    ("BLAINE", ("hns", "graphics/object_events/pics/people/gym_leaders/blaine.png"),   ("frlg", "leader_blaine")),
    ("GIOVANNI", ("hns", "graphics/object_events/pics/people/rockets/giovanni.png"), ("frlg", "leader_giovanni")),
    # --- Gen III from ROWE's own NPC sheets (9-frame real walking) ---
    ("STEVEN",   ("rowe", "graphics/object_events/pics/people/steven.png"), None),
    ("WALLACE",  ("rowe", "graphics/object_events/pics/people/wallace.png"), None),
    ("WALLY",    ("rowe", "graphics/object_events/pics/people/wally.png"), None),
    ("ROXANNE",  ("rowe", "graphics/object_events/pics/people/gym_leaders/roxanne.png"), None),
    ("BRAWLY",   ("rowe", "graphics/object_events/pics/people/gym_leaders/brawly.png"), None),
    ("WATTSON",  ("rowe", "graphics/object_events/pics/people/gym_leaders/wattson.png"), None),
    ("FLANNERY", ("rowe", "graphics/object_events/pics/people/gym_leaders/flannery.png"), None),
    ("NORMAN",   ("rowe", "graphics/object_events/pics/people/gym_leaders/norman.png"), None),
    ("WINONA",   ("rowe", "graphics/object_events/pics/people/gym_leaders/winona.png"), None),
    ("TATE",     ("rowe", "graphics/object_events/pics/people/gym_leaders/tate.png"), None),
    ("LIZA",     ("rowe", "graphics/object_events/pics/people/gym_leaders/liza.png"), None),
    ("JUAN",     ("rowe", "graphics/object_events/pics/people/gym_leaders/juan.png"), None),
    ("SIDNEY",   ("rowe", "graphics/object_events/pics/people/elite_four/sidney.png"), None),
    ("PHOEBE",   ("rowe", "graphics/object_events/pics/people/elite_four/phoebe.png"), None),
    ("GLACIA",   ("rowe", "graphics/object_events/pics/people/elite_four/glacia.png"), None),
    ("DRAKE",    ("rowe", "graphics/object_events/pics/people/elite_four/drake.png"), None),
    ("MAXIE",    ("rowe", "graphics/object_events/pics/people/team_magma/maxie.png"), None),
    ("ARCHIE",   ("rowe", "graphics/object_events/pics/people/team_aqua/archie.png"), None),
    # --- Gen IV from sinnoh-remakes/pokeemerald-platinum ---
    # OWs are 9-frame 32x32 sheets; Lucas/Dawn have real walk+run pairs.
    ("LUCAS",    ("platrun", "graphics/object_events/pics/people/lucas/walking.png",
                             "graphics/object_events/pics/people/lucas/running.png"),
                 ("plat", "lucas_dp")),
    ("DAWN",     ("platrun", "graphics/object_events/pics/people/dawn/walking.png",
                             "graphics/object_events/pics/people/dawn/running.png"),
                 ("plat", "dawn_dp")),
    ("BARRY",    ("plat", "graphics/object_events/pics/people/barry_pt.png"), ("plat", "barry_dp")),
    ("CYNTHIA",  ("plat", "graphics/object_events/pics/people/cynthia_pt.png"), ("plat", "cynthia_dp")),
    ("ROARK",    ("plat", "graphics/object_events/pics/people/roark_pt.png"), ("plat", "roark_dp")),
    ("GARDENIA", ("plat", "graphics/object_events/pics/people/gardenia_pt.png"), ("plat", "gardenia_dp")),
    ("MAYLENE",  ("plat", "graphics/object_events/pics/people/maylene_pt.png"), ("plat", "maylene_dp")),
    ("CRASHER_WAKE", ("plat", "graphics/object_events/pics/people/crasher_wake_pt.png"), ("plat", "crasher_wake_dp")),
    ("FANTINA",  ("plat", "graphics/object_events/pics/people/fantina_pt.png"), ("plat", "fantina_dp")),
    ("BYRON",    ("plat", "graphics/object_events/pics/people/byron_pt.png"), ("plat", "byron_dp")),
    ("CANDICE",  ("plat", "graphics/object_events/pics/people/candice_pt.png"), ("plat", "candice_dp")),
    ("VOLKNER",  ("plat", "graphics/object_events/pics/people/volkner_pt.png"), ("plat", "volkner_dp")),
    ("AARON",    ("plat", "graphics/object_events/pics/people/aaron_pt.png"), None),
    ("BERTHA",   ("plat", "graphics/object_events/pics/people/bertha_pt.png"), ("plat", "bertha_dp")),
    ("FLINT",    ("plat", "graphics/object_events/pics/people/flint_pt.png"), None),
    ("LUCIAN",   ("plat", "graphics/object_events/pics/people/lucian_pt.png"), ("plat", "lucian_dp")),
    ("CYRUS",    ("plat", "graphics/object_events/pics/people/cyrus_pt.png"), ("plat", "cyrus_dp")),
    ("MARS",     ("plat", "graphics/object_events/pics/people/mars_pt.png"), ("plat", "mars_dp")),
    ("JUPITER",  ("plat", "graphics/object_events/pics/people/jupiter_pt.png"), ("plat", "jupiter_dp")),
    ("SATURN",   ("plat", "graphics/object_events/pics/people/saturn_pt.png"), ("plat", "saturn_dp")),
    # --- Gen II from PokemonHnS-Development/pokemonHnS (9-frame walking) ---
    # HnS reskins the player: brendan/ = Ethan, may/ = Kris (real walk+run).
    ("ETHAN",    ("hnsrun", "graphics/object_events/pics/people/brendan/walking.png",
                            "graphics/object_events/pics/people/brendan/running.png"),
                 ("hns", "brendan")),
    ("KRIS",     ("hnsrun", "graphics/object_events/pics/people/may/walking.png",
                            "graphics/object_events/pics/people/may/running.png"),
                 ("hns", "may")),
    ("FALKNER",  ("hns", "graphics/object_events/pics/people/gym_leaders/falkner.png"), ("hns", "leader_falkner")),
    ("BUGSY",    ("hns", "graphics/object_events/pics/people/gym_leaders/bugsy.png"),   ("hns", "leader_bugsy")),
    ("WHITNEY",  ("hns", "graphics/object_events/pics/people/gym_leaders/whitney.png"), ("hns", "leader_whitney")),
    ("MORTY",    ("hns", "graphics/object_events/pics/people/gym_leaders/morty.png"),   ("hns", "leader_morty")),
    ("CHUCK",    ("hns", "graphics/object_events/pics/people/gym_leaders/chuck.png"),   ("hns", "leader_chuck")),
    ("JASMINE",  ("hns", "graphics/object_events/pics/people/gym_leaders/jasmine.png"), ("hns", "leader_jasmine")),
    ("PRYCE",    ("hns", "graphics/object_events/pics/people/gym_leaders/pryce.png"),   ("hns", "leader_pryce")),
    ("CLAIR",    ("hns", "graphics/object_events/pics/people/gym_leaders/clair.png"),   ("hns", "leader_clair")),
    ("JANINE",   ("hns", "graphics/object_events/pics/people/gym_leaders/janine.png"),  ("hns", "janine")),
    ("WILL",     ("hns", "graphics/object_events/pics/people/elite_four/will.png"),     ("hns", "elite_four_will")),
    ("KAREN",    ("hns", "graphics/object_events/pics/people/elite_four/karen.png"),    ("hns", "elite_four_karen")),
    ("SILVER",   ("hns", "graphics/object_events/pics/people/special/silver.png"),      None),
    ("ARCHER",   ("hns", "graphics/object_events/pics/people/rockets/archer.png"),      ("hns", "archer")),
    ("ARIANA",   ("hns", "graphics/object_events/pics/people/rockets/ariana.png"),      ("hns", "ariana")),
    # --- Gen V from DiegoWT's Essentials pack (4x4 grid, 64x64 cells) ---
    # Sheets identified visually: GymLeader01/_2/_3 = Chili/Cilan/Cress,
    # 09 = Cheren (B2W2), 10 = Roxie, 11 = Marlon; SevenSage7 = Ghetsis;
    # PlasmaScientist = Colress. Protagonists have real walk+run pairs.
    ("HILDA",    ("ep4run", "BW Protagonists/trProtag_GirlWalk.png",
                            "BW Protagonists/trProtag_GirlRun.png"), None),
    ("NATE",     ("ep4run", "B2W2 Protagonists/trProtag_BoyWalk.png",
                            "B2W2 Protagonists/trProtag_BoyRun.png"), None),
    ("ROSA",     ("ep4run", "B2W2 Protagonists/trProtag_GirlWalk.png",
                            "B2W2 Protagonists/trProtag_GirlRun.png"), None),
    ("ALDER",    ("ep4", "trChampion01.png"), None),
    ("IRIS",     ("ep4", "trChampion02.png"), None),
    ("SHAUNTAL", ("ep4", "trElite4_1.png"), None),
    ("GRIMSLEY", ("ep4", "trElite4_2.png"), None),
    ("CAITLIN",  ("ep4", "trElite4_3.png"), None),
    ("MARSHAL",  ("ep4", "trElite4_4.png"), None),
    ("CHILI",    ("ep4", "trGymLeader01.png"), None),
    ("CILAN",    ("ep4", "trGymLeader01_2.png"), None),
    ("CRESS",    ("ep4", "trGymLeader01_3.png"), None),
    ("LENORA",   ("ep4", "trGymLeader02.png"), None),
    ("BURGH",    ("ep4", "trGymLeader03.png"), None),
    ("ELESA",    ("ep4", "trGymLeader04.png"), None),
    ("CLAY",     ("ep4", "trGymLeader05.png"), None),
    ("SKYLA",    ("ep4", "trGymLeader06.png"), None),
    ("BRYCEN",   ("ep4", "trGymLeader07.png"), None),
    ("DRAYDEN",  ("ep4", "trGymLeader08.png"), None),
    ("CHEREN",   ("ep4", "trRival01.png"), None),
    ("ROXIE",    ("ep4", "trGymLeader10.png"), None),
    ("MARLON",   ("ep4", "trGymLeader11.png"), None),
    ("BIANCA",   ("ep4", "trRival02.png"), None),
    ("HUGH",     ("ep4", "trRival03.png"), None),
    ("N",        ("ep4", "trTeamPlasmaN.png"), None),
    ("GHETSIS",  ("ep4", "trTeamPlasmaSevenSage7.png"), None),
    ("COLRESS",  ("ep4", "trTeamPlasmaScientist.png"), None),
    # --- individual fan sheets (donor_sheets/, white-keyed boxes) ---
    # Ash by StreakOfSprites (deviantart.com/streakofsprites), FRLG style.
    # Boxes: face S/N/W then walk S1 S2 N1 N2 W1 W2.
    ("ASH",      ("boxes", "ash_streakofsprites.png",
                  [(6, 9, 22, 28), (113, 9, 129, 28), (7, 68, 23, 87),
                   (24, 9, 40, 28), (41, 9, 57, 28), (132, 9, 148, 28),
                   (150, 9, 166, 28), (26, 69, 42, 87), (45, 68, 62, 87)]),
                 None),
]

# Battle back sprites: 64x256 donors (4 frames of 64x64, Emerald-style
# throw animation). HnS reskins the player, so brendan=Ethan and may=Kris.
BACK_MANIFEST = [
    ("ETHAN", "hns",  "graphics/trainers/back_pics/brendan.png"),
    ("KRIS",  "hns",  "graphics/trainers/back_pics/may.png"),
    ("LUCAS", "plat", "graphics/trainers/back_pics/lucas.png"),
    ("DAWN",  "plat", "graphics/trainers/back_pics/dawn.png"),
    ("BARRY", "plat", "graphics/trainers/back_pics/barry.png"),
]

# frame width per character (pixels); default 16. Platinum sheets are 32.
FRAME_W = {n: 32 for n in ("LUCAS","DAWN","BARRY","CYNTHIA","ROARK","GARDENIA",
    "MAYLENE","CRASHER_WAKE","FANTINA","BYRON","CANDICE","VOLKNER","AARON",
    "BERTHA","FLINT","LUCIAN","CYRUS","MARS","JUPITER","SATURN")}
FRAME_W.update({n: 32 for n in ("HILDA","NATE","ROSA","ALDER","IRIS",
    "SHAUNTAL","GRIMSLEY","CAITLIN","MARSHAL","CHILI","CILAN","CRESS",
    "LENORA","BURGH","ELESA","CLAY","SKYLA","BRYCEN","DRAYDEN","CHEREN",
    "ROXIE","MARLON","BIANCA","HUGH","N","GHETSIS","COLRESS","ASH")})

PAL_TAG_BASE = 0x1180  # after ROWE's last used tag (0x1161 Hilbert)


def camel(name):
    return "".join(p.title() for p in name.split("_"))


def snake(name):
    return "cm_" + name.lower()


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def write(p, s):
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


def replace_block(path, tag, block, anchor_re, before=True):
    text = read(path)
    start, end = MS.format(tag=tag), ME.format(tag=tag)
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    wrapped = "%s\n%s\n%s\n" % (start, block.rstrip("\n"), end)
    m = list(re.finditer(anchor_re, text, re.M))
    assert m, (path, anchor_re)
    pos = m[-1].start() if before else m[-1].end()
    if not before:
        wrapped = "\n" + wrapped
    write(path, text[:pos] + wrapped + text[pos:])


def png_to_jasc(img, path):
    pal = (img.getpalette() or [])[:48]
    pal = pal + [0] * (48 - len(pal))  # pad short palettes to 16 colors
    lines = ["JASC-PAL", "0100", "16"]
    for i in range(16):
        lines.append("%d %d %d" % tuple(pal[i*3:i*3+3]))
    write(path, "\r\n".join(lines) + "\r\n")


# The player avatar drives the full BrendanMayNormal (24-entry) animation
# table, whose walk/run anims reference frames 0-17. ROWE's auto-run in
# particular seeks the Run anims (frames 9-17); an NPC-style sprite that
# only supplies 9 frames indexes past its pic table and crashes. So build
# an 18-frame pic table where every walk/run frame maps back to one of the
# three facing frames (S=0, N=1, side=2) - the character glides, but never
# reads out of bounds. This mirrors ROWE's own Hilbert player costume.
NUM_PLAYER_FRAMES = 18
# 3-frame standing donors: everything maps to the facing frames (glide).
GLIDE_MAP = [0, 1, 2, 0, 0, 1, 1, 2, 2, 0, 1, 2, 0, 0, 1, 1, 2, 2]
# 9-frame walking donors: real walk frames; run block reuses walk frames.
WALK_MAP = [0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8]
assert len(GLIDE_MAP) == len(WALK_MAP) == NUM_PLAYER_FRAMES


def normalize_indexed(img):
    """Compact a P-mode png to <=16 palette slots, background at index 0.

    Some donors store 8-bit colormaps with sparse high indexes even though
    they use few colors. gbagfx needs 4bpp (16 slots, index 0 transparent)."""
    data = list(img.getdata())
    if max(data) < 16:
        return img
    used = []
    for px in data:
        if px not in used:
            used.append(px)
    bg = img.info.get("transparency", data[0])  # corner pixel fallback
    if len(used) > 16:
        # genuinely more than 16 colors: quantize, then rotate bg to slot 0
        rgb = img.convert("RGB")
        q = rgb.quantize(colors=16, method=Image.FASTOCTREE)
        qdata = list(q.getdata())
        qbg = qdata[0] if img.info.get("transparency") is None else \
            q.getpixel((0, 0))
        qpal = q.getpalette()[:48]
        order = [qbg] + [i for i in range(16) if i != qbg]
        remap = {old: new for new, old in enumerate(order)}
        newpal = []
        for old in order:
            newpal += qpal[old*3:old*3+3]
        out = Image.new("P", img.size)
        out.putpalette(newpal)
        out.putdata([remap[px] for px in qdata])
        out.info["transparency"] = 0
        return out
    if bg in used:
        used.remove(bg)
    used.insert(0, bg)
    remap = {old: new for new, old in enumerate(used)}
    pal = img.getpalette()
    newpal = []
    for old in used:
        newpal += pal[old*3:old*3+3]
    out = Image.new("P", img.size)
    out.putpalette(newpal + [0] * (48 - len(newpal)))
    out.putdata([remap[px] for px in data])
    out.info["transparency"] = 0
    return out


def slice_frames(img, fw):
    fh = img.height
    assert fh == 32, (img.size,)
    assert max(img.getdata()) < 16, "png uses >16 palette slots"
    return [img.crop((i*fw, 0, (i+1)*fw, fh)) for i in range(img.width // fw)]


def save_sheet(frames, fmap, palette, transparency, fw, dst_png):
    fh = 32
    sheet = Image.new("P", (fw, fh*NUM_PLAYER_FRAMES))
    sheet.putpalette(palette)
    for i, m in enumerate(fmap):
        sheet.paste(frames[m], (0, i*fh))
    if transparency is not None:
        sheet.save(dst_png, transparency=transparency)
    else:
        sheet.save(dst_png)


def build_ow_sheet(src_png, dst_png, fw=16):
    img = normalize_indexed(Image.open(src_png))
    assert img.mode == "P", src_png
    frames = slice_frames(img, fw)
    n = len(frames)
    if n >= 9:
        fmap = WALK_MAP
    elif n >= 3:
        fmap = GLIDE_MAP
    else:
        raise SystemExit("unexpected frame count %d in %s" % (n, src_png))
    save_sheet(frames, fmap, img.getpalette(), img.info.get("transparency"),
               fw, dst_png)
    return img


def build_ow_sheet_walkrun(walk_png, run_png, dst_png, fw=16):
    walk = normalize_indexed(Image.open(walk_png))
    run = normalize_indexed(Image.open(run_png))
    assert walk.mode == "P" and run.mode == "P"
    wf = slice_frames(walk, fw)
    rf = slice_frames(run, fw)
    assert len(wf) >= 9 and len(rf) >= 9, (walk_png, run_png)
    frames = wf[:9] + rf[:9]
    fmap = list(range(18))  # real walk 0-8 + real run 9-17
    save_sheet(frames, fmap, walk.getpalette(), walk.info.get("transparency"),
               fw, dst_png)
    return walk


# --- Essentials Gen-4 grid sheets (DiegoWT pack): 256x256 RGBA, 4x4 grid of
# 64x64 cells. Rows are directions (0=down, 1=left, 2=right, 3=up); columns
# are animation frames (0 stand, 1 step, 2 stand, 3 other step). pokeemerald
# only needs down/up/left (east is the west anim x-flipped).
EP4_ORDER = [(0, 0), (3, 0), (1, 0),          # face S, N, W
             (0, 1), (0, 3), (3, 1), (3, 3),  # walk S1 S2 N1 N2
             (1, 1), (1, 3)]                  # walk W1 W2


def ep4_frames(path):
    """Cells hold DS-scale (~54px) sprites; a 0.5x box downscale lands them
    at GBA proportions (~21x27) inside a 32x32 frame. Cell size is derived
    from the sheet (a few sheets use 68px columns); the halved cell is then
    bottom-center anchored into the 32x32 frame."""
    im = Image.open(path).convert("RGBA")
    cw, ch = im.width // 4, im.height // 4
    frames = []
    for r, c in EP4_ORDER:
        cell = im.crop((c*cw, r*ch, (c+1)*cw, (r+1)*ch))
        half = cell.resize((cw//2, ch//2), Image.BOX)
        cv = Image.new("RGBA", (max(32, half.width), max(32, half.height)), 0)
        cv.alpha_composite(half, ((cv.width - half.width)//2,
                                  cv.height - half.height))
        x0 = (cv.width - 32)//2
        frames.append(cv.crop((x0, cv.height - 32, x0 + 32, cv.height)))
    return frames


def ep4_to_indexed_sheet(frames, dst_png):
    """Compose 32x32 RGBA frames vertically and index to 16 colors, bg=0."""
    fh = 32
    rgba = Image.new("RGBA", (32, fh*len(frames)), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        rgba.alpha_composite(f, (0, i*fh))
    opaque = []
    for px in rgba.getdata():
        c = px[:3]
        if px[3] >= 128 and c not in opaque:
            opaque.append(c)
    if len(opaque) > 15:
        # quantize opaque pixels to 15 colors, keep transparency mask
        mask = [px[3] >= 128 for px in rgba.getdata()]
        q = rgba.convert("RGB").quantize(colors=15, method=Image.MEDIANCUT)
        qpal, qdata = q.getpalette()[:45], list(q.getdata())
        pal = [255, 0, 255] + qpal
        data = [qd + 1 if m else 0 for qd, m in zip(qdata, mask)]
    else:
        lut = {c: i + 1 for i, c in enumerate(opaque)}
        pal = [255, 0, 255]
        for c in opaque:
            pal += list(c)
        data = [lut[px[:3]] if px[3] >= 128 else 0 for px in rgba.getdata()]
    out = Image.new("P", rgba.size)
    out.putpalette(pal + [0] * (768 - len(pal)))
    out.putdata(data)
    out.info["transparency"] = 0
    out.save(dst_png, transparency=0)
    return out


def build_ow_sheet_ep4(src_png, dst_png):
    frames = ep4_frames(src_png)
    return ep4_to_indexed_sheet([frames[m] for m in WALK_MAP], dst_png)


def build_ow_sheet_boxes(src_png, boxes, dst_png):
    """Nine hand-picked boxes (face S/N/W, walk S1 S2 N1 N2 W1 W2) from a
    fan sheet with a solid background color (taken from pixel 0,0)."""
    im = Image.open(src_png).convert("RGB")
    bg = im.getpixel((0, 0))
    frames = []
    for bx in boxes:
        cell = im.crop(tuple(bx))
        fr = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
        ox, oy = (32 - cell.width)//2, 32 - cell.height - 1
        for y in range(cell.height):
            for x in range(cell.width):
                c = cell.getpixel((x, y))
                if abs(c[0]-bg[0]) + abs(c[1]-bg[1]) + abs(c[2]-bg[2]) > 30:
                    fr.putpixel((ox + x, oy + y), c + (255,))
        frames.append(fr)
    return ep4_to_indexed_sheet([frames[m] for m in WALK_MAP], dst_png)


def build_ow_sheet_ep4run(walk_png, run_png, dst_png):
    frames = ep4_frames(walk_png) + ep4_frames(run_png)
    return ep4_to_indexed_sheet(frames, dst_png)


def main():
    ow_dir = os.path.join(TARGET, "graphics/object_events/pics/people")
    fp_dir = os.path.join(TARGET, "graphics/trainers/front_pics")
    tp_dir = os.path.join(TARGET, "graphics/trainers/palettes")

    for name, ow, front in MANIFEST:
        s = snake(name)
        fw = FRAME_W.get(name, 16)
        if ow[0] == "frlg":
            src = os.path.join(DONOR_FR, "graphics/object_events/pics/people", ow[1])
            img = build_ow_sheet(src, os.path.join(ow_dir, s + ".png"), fw)
        elif ow[0] == "rowe":
            img = build_ow_sheet(os.path.join(TARGET, ow[1]),
                                 os.path.join(ow_dir, s + ".png"), fw)
        elif ow[0] == "plat":
            img = build_ow_sheet(os.path.join(DONOR_PT, ow[1]),
                                 os.path.join(ow_dir, s + ".png"), fw)
        elif ow[0] == "hns":
            img = build_ow_sheet(os.path.join(DONOR_HNS, ow[1]),
                                 os.path.join(ow_dir, s + ".png"), fw)
        elif ow[0] == "platrun":
            img = build_ow_sheet_walkrun(os.path.join(DONOR_PT, ow[1]),
                                         os.path.join(DONOR_PT, ow[2]),
                                         os.path.join(ow_dir, s + ".png"), fw)
        elif ow[0] == "hnsrun":
            img = build_ow_sheet_walkrun(os.path.join(DONOR_HNS, ow[1]),
                                         os.path.join(DONOR_HNS, ow[2]),
                                         os.path.join(ow_dir, s + ".png"), fw)
        elif ow[0] == "ep4":
            img = build_ow_sheet_ep4(os.path.join(DONOR_EP4, ow[1]),
                                     os.path.join(ow_dir, s + ".png"))
        elif ow[0] == "ep4run":
            img = build_ow_sheet_ep4run(os.path.join(DONOR_EP4, ow[1]),
                                        os.path.join(DONOR_EP4, ow[2]),
                                        os.path.join(ow_dir, s + ".png"))
        elif ow[0] == "boxes":
            img = build_ow_sheet_boxes(os.path.join(DONOR_SHEETS, ow[1]),
                                       ow[2],
                                       os.path.join(ow_dir, s + ".png"))
        else:
            raise SystemExit("unknown ow source " + ow[0])
        png_to_jasc(img, os.path.join(ow_dir, s + ".pal"))
        if front is not None:
            froot, stem = front
            if froot == "frlg":
                fp = Image.open(os.path.join(DONOR_FR, "graphics/trainers/front_pics",
                                             stem + "_front_pic.png"))
                pal_src = os.path.join(DONOR_FR, "graphics/trainers/palettes", stem + ".pal")
                shutil.copyfile(pal_src, os.path.join(tp_dir, s + ".pal"))  # CRLF
            else:  # plat/hns: palette comes from the png itself
                froot_dir = DONOR_PT if froot == "plat" else DONOR_HNS
                fp = normalize_indexed(Image.open(os.path.join(
                    froot_dir, "graphics/trainers/front_pics", stem + ".png")))
                png_to_jasc(fp, os.path.join(tp_dir, s + ".pal"))
            assert fp.size == (64, 64), stem
            fp.save(os.path.join(fp_dir, s + ".png"))

    # --- battle back sprites (64x256, 4 frames)
    bp_dir = os.path.join(TARGET, "graphics/trainers/back_pics")
    for name, root, rel in BACK_MANIFEST:
        src = os.path.join({"hns": DONOR_HNS, "plat": DONOR_PT}[root], rel)
        img = normalize_indexed(Image.open(src))
        assert img.size == (64, 256), (rel, img.size)
        s = snake(name)
        img.save(os.path.join(bp_dir, s + "_back_pic.png"))
        png_to_jasc(img, os.path.join(tp_dir, s + "_back.pal"))

    names = [n for n, _, _ in MANIFEST]
    front_names = [n for n, _, f in MANIFEST if f is not None]
    back_names = [n for n, _, _ in BACK_MANIFEST]

    # --- constants: OBJ_EVENT_GFX ids + NUM extension
    lines = ["#define OBJ_EVENT_GFX_CM_%s%s(OBJ_EVENT_GFX_POKEMON_904 + %d)"
             % (n, " " * max(1, 20 - len(n)), i + 1) for i, n in enumerate(names)]
    lines.append("#define OBJ_EVENT_GFX_CHARMODE_LAST     OBJ_EVENT_GFX_CM_%s" % names[-1])
    path = os.path.join(TARGET, "include/constants/event_objects.h")
    replace_block(path, "gfx-ids", "\n".join(lines),
                  r"^#define NUM_OBJ_EVENT_GFX", before=True)
    text = read(path)
    text = text.replace("#define NUM_OBJ_EVENT_GFX               (OBJ_EVENT_GFX_POKEMON_904 + 1)",
                        "#define NUM_OBJ_EVENT_GFX               (OBJ_EVENT_GFX_CHARMODE_LAST + 1)")
    write(path, text)

    # --- OW INCBINs (pics + palettes)
    block = "".join(
        'const u32 gObjectEventPic_Cm%s[] = INCBIN_U32("graphics/object_events/pics/people/%s.4bpp");\n'
        'const u16 gObjectEventPalette_Cm%s[] = INCBIN_U16("graphics/object_events/pics/people/%s.gbapal");\n'
        % (camel(n), snake(n), camel(n), snake(n)) for n in names)
    replace_block(os.path.join(TARGET, "src/data/object_events/object_event_graphics.h"),
                  "ow-incbins", block, r"\Z", before=True)

    # --- pic tables
    block = "".join(
        "static const struct SpriteFrameImage gObjectEventPicTable_Cm%s[] = {\n%s};\n"
        % (camel(n), "".join("    overworld_frame(gObjectEventPic_Cm%s, %d, 4, %d),\n"
                             % (camel(n), FRAME_W.get(n, 16) // 8, i)
                             for i in range(NUM_PLAYER_FRAMES)))
        for n in names)
    replace_block(os.path.join(TARGET, "src/data/object_events/object_event_pic_tables.h"),
                  "ow-pics", block, r"\Z", before=True)

    # --- graphics info structs (frame size varies by donor)
    def _info(n):
        fw = FRAME_W.get(n, 16)
        size = fw * 32 // 2
        return ("const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_Cm%s = "
                "{0xFFFF, OBJ_EVENT_PAL_CM_%s, OBJ_EVENT_PAL_TAG_NONE, %d, %d, 32, 5, "
                "SHADOW_SIZE_M, FALSE, FALSE, TRACKS_FOOT, &gObjectEventBaseOam_%dx32, "
                "gObjectEventSpriteOamTables_%dx32, gObjectEventImageAnimTable_BrendanMayNormal, "
                "gObjectEventPicTable_Cm%s, gDummySpriteAffineAnimTable};\n"
                % (camel(n), n, size, fw, fw, fw, camel(n)))
    block = "".join(_info(n) for n in names)
    replace_block(os.path.join(TARGET, "src/data/object_events/object_event_graphics_info.h"),
                  "ow-info", block, r"\Z", before=True)

    # --- pointers (must land inside gObjectEventGraphicsInfoPointers, NOT the
    # gMauvilleOldManGraphicsInfoPointers array that follows it - a bare `^};`
    # anchor picks the file's last brace and silently drops the entries, so the
    # lookup returns NULL and the player avatar crashes).
    block = "".join("    [OBJ_EVENT_GFX_CM_%s] = &gObjectEventGraphicsInfo_Cm%s,\n"
                    % (n, camel(n)) for n in names)
    path = os.path.join(TARGET, "src/data/object_events/object_event_graphics_info_pointers.h")
    text = read(path)
    text = re.sub(re.escape(MS.format(tag="ow-ptrs")) + r".*?"
                  + re.escape(ME.format(tag="ow-ptrs")) + r"\n?", "", text, flags=re.S)
    m = re.search(r"gObjectEventGraphicsInfoPointers\[[^\]]*\]\s*=\s*\{", text)
    close = text.index("\n};", m.end())
    wrapped = "%s\n%s\n%s\n" % (MS.format(tag="ow-ptrs"), block.rstrip("\n"),
                               ME.format(tag="ow-ptrs"))
    write(path, text[:close + 1] + wrapped + text[close + 1:])

    # --- palette tags + registration
    tag_defs = "".join("#define OBJ_EVENT_PAL_CM_%s%s0x%04X\n"
                       % (n, " " * max(1, 18 - len(n)), PAL_TAG_BASE + i)
                       for i, n in enumerate(names))
    path = os.path.join(TARGET, "src/event_object_movement.c")
    replace_block(path, "pal-tags", tag_defs,
                  r"^#define OBJ_EVENT_PAL_HILBERT.*$", before=False)
    entries = "".join("    {gObjectEventPalette_Cm%s, OBJ_EVENT_PAL_CM_%s},\n"
                      % (camel(n), n) for n in names)
    replace_block(path, "pal-entries", entries,
                  r"^\s*\{gObjectEventPalette_Steven,", before=True)

    # --- OW pic/pal externs are needed by event_object_movement.c's palette
    # table; the info/pic tables live in the same TU as the INCBINs.
    externs = "".join(
        "extern const u32 gObjectEventPic_Cm%s[];\n"
        "extern const u16 gObjectEventPalette_Cm%s[];\n"
        % (camel(n), camel(n)) for n in names) + "".join(
        "extern const u32 gTrainerFrontPic_Cm%s[];\n"
        "extern const u16 gTrainerPalette_Cm%s[];\n"
        % (camel(n), camel(n)) for n in front_names)
    path = os.path.join(TARGET, "include/graphics.h")
    text = read(path)
    start, end = MS.format(tag="externs"), ME.format(tag="externs")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    pos = text.rfind("#endif")
    text = text[:pos] + "%s\n%s%s\n" % (start, externs, end) + text[pos:]
    write(path, text)

    # --- TRAINER_PIC ids
    trainers_h = read(os.path.join(TARGET, "include/constants/trainers.h"))
    maxpic = max(int(m) for m in re.findall(r"#define TRAINER_PIC_\w+\s+(\d+)", trainers_h))
    lines = ["#define TRAINER_PIC_%s%s%d" % (n, " " * max(1, 20 - len(n)), maxpic + 1 + i)
             for i, n in enumerate(front_names)]
    replace_block(os.path.join(TARGET, "include/constants/trainers.h"), "pic-ids",
                  "\n".join(lines), r"^#define TRAINER_BACK_PIC_BRENDAN", before=True)

    # --- front pic INCBINs
    block = "".join(
        'const u32 gTrainerFrontPic_Cm%s[] = INCBIN_U32("graphics/trainers/front_pics/%s.4bpp.lz");\n'
        'const u16 gTrainerPalette_Cm%s[] = INCBIN_U16("graphics/trainers/palettes/%s.gbapal");\n'
        % (camel(n), snake(n), camel(n), snake(n)) for n in front_names)
    replace_block(os.path.join(TARGET, "src/data/graphics/trainers.h"),
                  "front-incbins", block, r"\Z", before=True)

    # --- front pic tables (coords, sprites, palettes, anims)
    path = os.path.join(TARGET, "src/data/trainer_graphics/front_pic_tables.h")
    text = read(path)
    coords_block = "".join("\t[TRAINER_PIC_%s] = {.size = 8, .y_offset = 1},\n" % n
                           for n in front_names)
    start, end = MS.format(tag="front-coords"), ME.format(tag="front-coords")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    anchor = text.index("[TRAINER_PIC_HILBERT] = {.size")
    line_end = text.index("\n", anchor) + 1
    text = text[:line_end] + "%s\n%s%s\n" % (start, coords_block, end) + text[line_end:]
    write(path, text)
    text = read(path)
    sprite_block = "".join("\tTRAINER_SPRITE(%s, gTrainerFrontPic_Cm%s, 0x800),\n"
                           % (n, camel(n)) for n in front_names)
    pal_block = "".join("\tTRAINER_PAL(%s, gTrainerPalette_Cm%s),\n"
                        % (n, camel(n)) for n in front_names)
    start, end = MS.format(tag="front-sprites"), ME.format(tag="front-sprites")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    anchor = text.index("TRAINER_SPRITE(HILBERT")
    line_end = text.index("\n", anchor) + 1
    text = text[:line_end] + "%s\n%s%s\n" % (start, sprite_block, end) + text[line_end:]
    start, end = MS.format(tag="front-pals"), ME.format(tag="front-pals")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    anchor = text.index("TRAINER_PAL(HILBERT")
    line_end = text.index("\n", anchor) + 1
    text = text[:line_end] + "%s\n%s%s\n" % (start, pal_block, end) + text[line_end:]
    write(path, text)

    replace_block(os.path.join(TARGET, "src/data/trainer_graphics/front_pic_anims.h"),
                  "front-anims",
                  "".join("\t[TRAINER_PIC_%s] = sAnims_RubySapphireMay,\n" % n
                          for n in front_names),
                  r"^};", before=True)

    # --- TRAINER_BACK_PIC ids (sequential after the last stock id)
    trainers_h = read(os.path.join(TARGET, "include/constants/trainers.h"))
    stock = [int(m) for m in re.findall(r"#define TRAINER_BACK_PIC_(?!CM_)\w+\s+(\d+)", trainers_h)]
    maxback = max(stock)
    lines = ["#define TRAINER_BACK_PIC_CM_%s%s%d" % (n, " " * max(1, 17 - len(n)), maxback + 1 + i)
             for i, n in enumerate(back_names)]
    replace_block(os.path.join(TARGET, "include/constants/trainers.h"), "back-ids",
                  "\n".join(lines), r"^#define TRAINER_BACK_PIC_HILBERT.*$", before=False)

    # --- back pic INCBINs
    block = "".join(
        'const u8 gTrainerBackPic_Cm%s[] = INCBIN_U8("graphics/trainers/back_pics/%s_back_pic.4bpp");\n'
        'const u16 gTrainerBackPicPalette_Cm%s[] = INCBIN_U16("graphics/trainers/palettes/%s_back.gbapal");\n'
        % (camel(n), snake(n), camel(n), snake(n)) for n in back_names)
    replace_block(os.path.join(TARGET, "src/data/graphics/trainers.h"),
                  "back-incbins", block, r"\Z", before=True)

    # --- externs (graphics.h for data.c; data.h for pokemon.c)
    externs = "".join(
        "extern const u8 gTrainerBackPic_Cm%s[];\n"
        "extern const u16 gTrainerBackPicPalette_Cm%s[];\n"
        % (camel(n), camel(n)) for n in back_names)
    path = os.path.join(TARGET, "include/graphics.h")
    text = read(path)
    start, end = MS.format(tag="back-externs"), ME.format(tag="back-externs")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    pos = text.rfind("#endif")
    text = text[:pos] + "%s\n%s%s\n" % (start, externs, end) + text[pos:]
    write(path, text)
    replace_block(os.path.join(TARGET, "include/data.h"), "back-frame-externs",
                  "".join("extern const struct SpriteFrameImage gTrainerBackPicTable_Cm%s[];\n"
                          % camel(n) for n in back_names),
                  r"^extern const struct SpriteFrameImage gTrainerBackPicTable_Hilbert\[\];.*$",
                  before=False)

    # --- back_pic_tables.h: coords, palettes, sheets (three separate arrays;
    # insert right after each array's HILBERT line, like the front tables)
    path = os.path.join(TARGET, "src/data/trainer_graphics/back_pic_tables.h")
    text = read(path)
    for tag, anchor, block in (
        ("back-coords", "[TRAINER_BACK_PIC_HILBERT]",
         "".join("    [TRAINER_BACK_PIC_CM_%s] = {.size = 8, .y_offset = 4},\n" % n
                 for n in back_names)),
        ("back-pals", "TRAINER_BACK_PAL(HILBERT,",
         "".join("    TRAINER_BACK_PAL(CM_%s, gTrainerBackPicPalette_Cm%s),\n"
                 % (n, camel(n)) for n in back_names)),
        ("back-sheets", "gTrainerBackPic_Hilbert,",
         "".join("    (const u32 *)gTrainerBackPic_Cm%s, 0x2000, TRAINER_BACK_PIC_CM_%s,\n"
                 % (camel(n), n) for n in back_names)),
    ):
        start, end = MS.format(tag=tag), ME.format(tag=tag)
        text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
        line_end = text.index("\n", text.index(anchor)) + 1
        text = text[:line_end] + "%s\n%s%s\n" % (start, block, end) + text[line_end:]
    write(path, text)

    # --- back_pic_anims.h: anim ptr arrays + dispatch table entries
    replace_block(os.path.join(TARGET, "src/data/trainer_graphics/back_pic_anims.h"),
                  "back-anims",
                  "".join("static const union AnimCmd *const sBackAnims_Cm%s[] =\n{\n"
                          "    sAnim_GeneralFrame3,\n    gAnimCmd_May_Steven_1,\n};\n"
                          % camel(n) for n in back_names),
                  r"^const union AnimCmd \*const \*const gTrainerBackAnimsPtrTable",
                  before=True)
    replace_block(os.path.join(TARGET, "src/data/trainer_graphics/back_pic_anims.h"),
                  "back-anim-ptrs",
                  "".join("    [TRAINER_BACK_PIC_CM_%s] = sBackAnims_Cm%s,\n"
                          % (n, camel(n)) for n in back_names),
                  r"^\};", before=True)

    # --- data.c: SpriteFrameImage tables (4 frames of 0x800)
    replace_block(os.path.join(TARGET, "src/data.c"), "back-frameimgs",
                  "".join("const struct SpriteFrameImage gTrainerBackPicTable_Cm%s[] =\n{\n"
                          "    gTrainerBackPic_Cm%s, 0x0800,\n"
                          "    gTrainerBackPic_Cm%s + 0x0800, 0x0800,\n"
                          "    gTrainerBackPic_Cm%s + 0x1000, 0x0800,\n"
                          "    gTrainerBackPic_Cm%s + 0x1800, 0x0800,\n};\n"
                          % ((camel(n),) * 5) for n in back_names),
                  r"^static const union AnimCmd sAnim_GeneralFrame0", before=True)

    # --- pokemon.c: sprite template per back pic id (table is indexed by id,
    # so entries must land inside gSpriteTemplateTable_TrainerBackSprites)
    path = os.path.join(TARGET, "src/pokemon.c")
    text = read(path)
    start, end = MS.format(tag="back-templates"), ME.format(tag="back-templates")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    m = re.search(r"gSpriteTemplateTable_TrainerBackSprites\[\]\s*=\s*\{", text)
    close = text.index("\n};", m.end())
    block = "".join("    {\n        .tileTag = 0xFFFF,\n        .paletteTag = 0,\n"
                    "        .oam = &gOamData_831ACB0,\n        .anims = NULL,\n"
                    "        .images = gTrainerBackPicTable_Cm%s,\n"
                    "        .affineAnims = gUnknown_082FF618,\n"
                    "        .callback = sub_8039BB4,\n    },\n" % camel(n)
                    for n in back_names)
    wrapped = "%s\n%s%s\n" % (start, block, end)
    write(path, text[:close + 1] + wrapped + text[close + 1:])

    with open(os.path.join(HERE, "imported_ow.txt"), "w") as f:
        f.write("\n".join("OBJ_EVENT_GFX_CM_" + n for n in names) + "\n")
    print("imported %d characters' sprites (%d back pics); now run emit_characters.py and make"
          % (len(names), len(back_names)))


if __name__ == "__main__":
    main()
