#!/usr/bin/env python3
"""Import character sprites from donor decomps (pokefirered etc.) into ROWE.

For each manifest entry this script:
  - builds a 9-frame 16x32 overworld sheet (16px wide, frames stacked
    vertically so gbagfx's tile order is frame-major) from the donor's
    people sprite; 3-frame standing sprites get their facing frames
    duplicated into the walk slots (character glides instead of striding)
  - copies the donor trainer front pic (64x64) and its palette
  - generates all C wiring inside CHARMODE-SPRITES marker blocks:
    OBJ_EVENT_GFX id, graphics info, pic table, INCBINs, palette tag,
    TRAINER_PIC id, front pic tables/anims, graphics.h externs

Idempotent: re-running replaces the marker blocks.
Run AFTER editing MANIFEST; then re-run emit_characters.py and make.
"""
import os
import re
import shutil
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR_FR = os.environ.get(
    "FRLG_DONOR",
    "/tmp/claude-1000/-home-jbfish00-Documents-Pokemon-Rowe-Alteration/"
    "d861755c-2ee7-4188-8126-ad647883e68d/scratchpad/pokefirered")

MS = "// CHARMODE-SPRITES-START {tag} (generated by tools/character_mode/import_sprites.py)"
ME = "// CHARMODE-SPRITES-END {tag}"

# (Name, donor OW png (people/), donor front pic stem (front_pics/<stem>_front_pic.png
#  + palettes/<stem>.pal)) - donor paths relative to the pokefirered clone.
MANIFEST = [
    ("BLUE",     "blue.png",     "champion_rival"),
    ("LANCE",    "lance.png",    "elite_four_lance"),
    ("LORELEI",  "lorelei.png",  "elite_four_lorelei"),
    ("BRUNO",    "bruno.png",    "elite_four_bruno"),
    ("AGATHA",   "agatha.png",   "elite_four_agatha"),
    ("KOGA",     "koga.png",     "leader_koga"),
    ("BROCK",    "brock.png",    "leader_brock"),
    ("MISTY",    "misty.png",    "leader_misty"),
    ("LT_SURGE", "lt_surge.png", "leader_lt_surge"),
    ("ERIKA",    "erika.png",    "leader_erika"),
    ("SABRINA",  "sabrina.png",  "leader_sabrina"),
    ("BLAINE",   "blaine.png",   "leader_blaine"),
    ("GIOVANNI", "giovanni.png", "leader_giovanni"),
]

PAL_TAG_BASE = 0x1180  # after ROWE's last used tag (0x1161 Hilbert)


def camel(name):
    return "".join(p.title() for p in name.split("_"))


def snake(name):
    return "cm_" + name.lower()


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def write(p, s):
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


def replace_block(path, tag, block, anchor_re, before=True):
    text = read(path)
    start, end = MS.format(tag=tag), ME.format(tag=tag)
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    wrapped = "%s\n%s\n%s\n" % (start, block.rstrip("\n"), end)
    m = list(re.finditer(anchor_re, text, re.M))
    assert m, (path, anchor_re)
    pos = m[-1].start() if before else m[-1].end()
    if not before:
        wrapped = "\n" + wrapped
    write(path, text[:pos] + wrapped + text[pos:])


def png_to_jasc(img, path):
    pal = img.getpalette()[:48]
    lines = ["JASC-PAL", "0100", "16"]
    for i in range(16):
        lines.append("%d %d %d" % tuple(pal[i*3:i*3+3]))
    write(path, "\r\n".join(lines) + "\r\n")


# The player avatar drives the full BrendanMayNormal (24-entry) animation
# table, whose walk/run anims reference frames 0-17. ROWE's auto-run in
# particular seeks the Run anims (frames 9-17); an NPC-style sprite that
# only supplies 9 frames indexes past its pic table and crashes. So build
# an 18-frame pic table where every walk/run frame maps back to one of the
# three facing frames (S=0, N=1, side=2) - the character glides, but never
# reads out of bounds. This mirrors ROWE's own Hilbert player costume.
NUM_PLAYER_FRAMES = 18
_S, _N, _E = 0, 1, 2  # source facing frames
PLAYER_FRAME_MAP = [
    _S, _N, _E,          # 0-2  face south/north/side
    _S, _S, _N, _N, _E, _E,   # 3-8  walk step frames
    _S, _N, _E,          # 9-11 run base
    _S, _S, _N, _N, _E, _E,   # 12-17 run step frames
]
assert len(PLAYER_FRAME_MAP) == NUM_PLAYER_FRAMES


def build_ow_sheet(src_png, dst_png):
    img = Image.open(src_png)
    assert img.mode == "P", src_png
    fw, fh = 16, img.height
    assert fh == 32, (src_png, img.size)
    n = img.width // fw
    frames = [img.crop((i*fw, 0, (i+1)*fw, fh)) for i in range(n)]
    if n >= 3:
        src = [0, 1, 2]  # first three frames are the facings
    else:
        raise SystemExit("unexpected frame count %d in %s" % (n, src_png))
    sheet = Image.new("P", (fw, fh*NUM_PLAYER_FRAMES))
    sheet.putpalette(img.getpalette())
    for i, m in enumerate(PLAYER_FRAME_MAP):
        sheet.paste(frames[src[m]], (0, i*fh))
    if "transparency" in img.info:
        sheet.save(dst_png, transparency=img.info["transparency"])
    else:
        sheet.save(dst_png)
    return img


def main():
    ow_dir = os.path.join(TARGET, "graphics/object_events/pics/people")
    fp_dir = os.path.join(TARGET, "graphics/trainers/front_pics")
    tp_dir = os.path.join(TARGET, "graphics/trainers/palettes")

    for name, ow, front in MANIFEST:
        s = snake(name)
        img = build_ow_sheet(os.path.join(DONOR_FR, "graphics/object_events/pics/people", ow),
                             os.path.join(ow_dir, s + ".png"))
        png_to_jasc(img, os.path.join(ow_dir, s + ".pal"))
        fp = Image.open(os.path.join(DONOR_FR, "graphics/trainers/front_pics",
                                     front + "_front_pic.png"))
        assert fp.size == (64, 64), front
        fp.save(os.path.join(fp_dir, s + ".png"))
        pal_src = os.path.join(DONOR_FR, "graphics/trainers/palettes", front + ".pal")
        shutil.copyfile(pal_src, os.path.join(tp_dir, s + ".pal"))  # keep CRLF for gbagfx

    names = [n for n, _, _ in MANIFEST]

    # --- constants: OBJ_EVENT_GFX ids + NUM extension
    lines = ["#define OBJ_EVENT_GFX_%s%s(OBJ_EVENT_GFX_POKEMON_904 + %d)"
             % (n, " " * max(1, 20 - len(n)), i + 1) for i, n in enumerate(names)]
    lines.append("#define OBJ_EVENT_GFX_CHARMODE_LAST     OBJ_EVENT_GFX_%s" % names[-1])
    path = os.path.join(TARGET, "include/constants/event_objects.h")
    replace_block(path, "gfx-ids", "\n".join(lines),
                  r"^#define NUM_OBJ_EVENT_GFX", before=True)
    text = read(path)
    text = text.replace("#define NUM_OBJ_EVENT_GFX               (OBJ_EVENT_GFX_POKEMON_904 + 1)",
                        "#define NUM_OBJ_EVENT_GFX               (OBJ_EVENT_GFX_CHARMODE_LAST + 1)")
    write(path, text)

    # --- OW INCBINs (pics + palettes)
    block = "".join(
        'const u32 gObjectEventPic_Cm%s[] = INCBIN_U32("graphics/object_events/pics/people/%s.4bpp");\n'
        'const u16 gObjectEventPalette_Cm%s[] = INCBIN_U16("graphics/object_events/pics/people/%s.gbapal");\n'
        % (camel(n), snake(n), camel(n), snake(n)) for n in names)
    replace_block(os.path.join(TARGET, "src/data/object_events/object_event_graphics.h"),
                  "ow-incbins", block, r"\Z", before=True)

    # --- pic tables
    block = "".join(
        "static const struct SpriteFrameImage gObjectEventPicTable_Cm%s[] = {\n%s};\n"
        % (camel(n), "".join("    overworld_frame(gObjectEventPic_Cm%s, 2, 4, %d),\n"
                             % (camel(n), i) for i in range(NUM_PLAYER_FRAMES)))
        for n in names)
    replace_block(os.path.join(TARGET, "src/data/object_events/object_event_pic_tables.h"),
                  "ow-pics", block, r"\Z", before=True)

    # --- graphics info structs
    block = "".join(
        "const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_Cm%s = "
        "{0xFFFF, OBJ_EVENT_PAL_CM_%s, OBJ_EVENT_PAL_TAG_NONE, 256, 16, 32, 5, "
        "SHADOW_SIZE_M, FALSE, FALSE, TRACKS_FOOT, &gObjectEventBaseOam_16x32, "
        "gObjectEventSpriteOamTables_16x32, gObjectEventImageAnimTable_BrendanMayNormal, "
        "gObjectEventPicTable_Cm%s, gDummySpriteAffineAnimTable};\n"
        % (camel(n), n, camel(n)) for n in names)
    replace_block(os.path.join(TARGET, "src/data/object_events/object_event_graphics_info.h"),
                  "ow-info", block, r"\Z", before=True)

    # --- pointers (must land inside gObjectEventGraphicsInfoPointers, NOT the
    # gMauvilleOldManGraphicsInfoPointers array that follows it - a bare `^};`
    # anchor picks the file's last brace and silently drops the entries, so the
    # lookup returns NULL and the player avatar crashes).
    block = "".join("    [OBJ_EVENT_GFX_%s] = &gObjectEventGraphicsInfo_Cm%s,\n"
                    % (n, camel(n)) for n in names)
    path = os.path.join(TARGET, "src/data/object_events/object_event_graphics_info_pointers.h")
    text = read(path)
    text = re.sub(re.escape(MS.format(tag="ow-ptrs")) + r".*?"
                  + re.escape(ME.format(tag="ow-ptrs")) + r"\n?", "", text, flags=re.S)
    m = re.search(r"gObjectEventGraphicsInfoPointers\[[^\]]*\]\s*=\s*\{", text)
    close = text.index("\n};", m.end())
    wrapped = "%s\n%s\n%s\n" % (MS.format(tag="ow-ptrs"), block.rstrip("\n"),
                               ME.format(tag="ow-ptrs"))
    write(path, text[:close + 1] + wrapped + text[close + 1:])

    # --- palette tags + registration
    tag_defs = "".join("#define OBJ_EVENT_PAL_CM_%s%s0x%04X\n"
                       % (n, " " * max(1, 18 - len(n)), PAL_TAG_BASE + i)
                       for i, n in enumerate(names))
    path = os.path.join(TARGET, "src/event_object_movement.c")
    replace_block(path, "pal-tags", tag_defs,
                  r"^#define OBJ_EVENT_PAL_HILBERT.*$", before=False)
    entries = "".join("    {gObjectEventPalette_Cm%s, OBJ_EVENT_PAL_CM_%s},\n"
                      % (camel(n), n) for n in names)
    replace_block(path, "pal-entries", entries,
                  r"^\s*\{gObjectEventPalette_Steven,", before=True)

    # --- OW pic/pal externs are needed by event_object_movement.c's palette
    # table; the info/pic tables live in the same TU as the INCBINs.
    externs = "".join(
        "extern const u32 gObjectEventPic_Cm%s[];\n"
        "extern const u16 gObjectEventPalette_Cm%s[];\n"
        "extern const u32 gTrainerFrontPic_Cm%s[];\n"
        "extern const u16 gTrainerPalette_Cm%s[];\n"
        % (camel(n), camel(n), camel(n), camel(n)) for n in names)
    path = os.path.join(TARGET, "include/graphics.h")
    text = read(path)
    start, end = MS.format(tag="externs"), ME.format(tag="externs")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    pos = text.rfind("#endif")
    text = text[:pos] + "%s\n%s%s\n" % (start, externs, end) + text[pos:]
    write(path, text)

    # --- TRAINER_PIC ids
    trainers_h = read(os.path.join(TARGET, "include/constants/trainers.h"))
    maxpic = max(int(m) for m in re.findall(r"#define TRAINER_PIC_\w+\s+(\d+)", trainers_h))
    lines = ["#define TRAINER_PIC_%s%s%d" % (n, " " * max(1, 20 - len(n)), maxpic + 1 + i)
             for i, n in enumerate(names)]
    replace_block(os.path.join(TARGET, "include/constants/trainers.h"), "pic-ids",
                  "\n".join(lines), r"^#define TRAINER_BACK_PIC_BRENDAN", before=True)

    # --- front pic INCBINs
    block = "".join(
        'const u32 gTrainerFrontPic_Cm%s[] = INCBIN_U32("graphics/trainers/front_pics/%s.4bpp.lz");\n'
        'const u16 gTrainerPalette_Cm%s[] = INCBIN_U16("graphics/trainers/palettes/%s.gbapal");\n'
        % (camel(n), snake(n), camel(n), snake(n)) for n in names)
    replace_block(os.path.join(TARGET, "src/data/graphics/trainers.h"),
                  "front-incbins", block, r"\Z", before=True)

    # --- front pic tables (coords, sprites, palettes, anims)
    path = os.path.join(TARGET, "src/data/trainer_graphics/front_pic_tables.h")
    text = read(path)
    coords_block = "".join("\t[TRAINER_PIC_%s] = {.size = 8, .y_offset = 1},\n" % n
                           for n in names)
    start, end = MS.format(tag="front-coords"), ME.format(tag="front-coords")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    anchor = text.index("[TRAINER_PIC_HILBERT] = {.size")
    line_end = text.index("\n", anchor) + 1
    text = text[:line_end] + "%s\n%s%s\n" % (start, coords_block, end) + text[line_end:]
    write(path, text)
    text = read(path)
    sprite_block = "".join("\tTRAINER_SPRITE(%s, gTrainerFrontPic_Cm%s, 0x800),\n"
                           % (n, camel(n)) for n in names)
    pal_block = "".join("\tTRAINER_PAL(%s, gTrainerPalette_Cm%s),\n"
                        % (n, camel(n)) for n in names)
    start, end = MS.format(tag="front-sprites"), ME.format(tag="front-sprites")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    anchor = text.index("TRAINER_SPRITE(HILBERT")
    line_end = text.index("\n", anchor) + 1
    text = text[:line_end] + "%s\n%s%s\n" % (start, sprite_block, end) + text[line_end:]
    start, end = MS.format(tag="front-pals"), ME.format(tag="front-pals")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    anchor = text.index("TRAINER_PAL(HILBERT")
    line_end = text.index("\n", anchor) + 1
    text = text[:line_end] + "%s\n%s%s\n" % (start, pal_block, end) + text[line_end:]
    write(path, text)

    replace_block(os.path.join(TARGET, "src/data/trainer_graphics/front_pic_anims.h"),
                  "front-anims",
                  "".join("\t[TRAINER_PIC_%s] = sAnims_RubySapphireMay,\n" % n
                          for n in names),
                  r"^};", before=True)

    with open(os.path.join(HERE, "imported_ow.txt"), "w") as f:
        f.write("\n".join("OBJ_EVENT_GFX_" + n for n in names) + "\n")
    print("imported %d characters' sprites; now run emit_characters.py and make" % len(names))


if __name__ == "__main__":
    main()
