#!/usr/bin/env python3
"""Import character sprites from donor decomps (pokefirered etc.) into ROWE.

For each manifest entry this script:
  - builds a 9-frame 16x32 overworld sheet (16px wide, frames stacked
    vertically so gbagfx's tile order is frame-major) from the donor's
    people sprite; 3-frame standing sprites get their facing frames
    duplicated into the walk slots (character glides instead of striding)
  - copies the donor trainer front pic (64x64) and its palette
  - generates all C wiring inside CHARMODE-SPRITES marker blocks:
    OBJ_EVENT_GFX id, graphics info, pic table, INCBINs, palette tag,
    TRAINER_PIC id, front pic tables/anims, graphics.h externs

Idempotent: re-running replaces the marker blocks.
Run AFTER editing MANIFEST; then re-run emit_characters.py and make.
"""
import os
import re
import shutil
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR_FR = os.environ.get(
    "FRLG_DONOR",
    "/tmp/claude-1000/-home-jbfish00-Documents-Pokemon-Rowe-Alteration/"
    "d861755c-2ee7-4188-8126-ad647883e68d/scratchpad/pokefirered")
DONOR_PT = os.environ.get(
    "PLAT_DONOR",
    "/tmp/claude-1000/-home-jbfish00-Documents-Pokemon-Rowe-Alteration/"
    "d861755c-2ee7-4188-8126-ad647883e68d/scratchpad/platinum")

MS = "// CHARMODE-SPRITES-START {tag} (generated by tools/character_mode/import_sprites.py)"
ME = "// CHARMODE-SPRITES-END {tag}"

# Manifest entries: (NAME, ow_source, front_source)
#   ow_source:    ("frlg", "people-relative.png") or ("rowe", "repo-relative.png") or None
#   front_source: ("frlg", "front_pic_stem") or None (None = ROWE already has a
#                 TRAINER_PIC for this character; no import needed)
MANIFEST = [
    # --- Gen I from pokefirered (3-frame standing sets; glide walk) ---
    ("BLUE",     ("frlg", "blue.png"),     ("frlg", "champion_rival")),
    ("LANCE",    ("frlg", "lance.png"),    ("frlg", "elite_four_lance")),
    ("LORELEI",  ("frlg", "lorelei.png"),  ("frlg", "elite_four_lorelei")),
    ("BRUNO",    ("frlg", "bruno.png"),    ("frlg", "elite_four_bruno")),
    ("AGATHA",   ("frlg", "agatha.png"),   ("frlg", "elite_four_agatha")),
    ("KOGA",     ("frlg", "koga.png"),     ("frlg", "leader_koga")),
    ("BROCK",    ("frlg", "brock.png"),    ("frlg", "leader_brock")),
    ("MISTY",    ("frlg", "misty.png"),    ("frlg", "leader_misty")),
    ("LT_SURGE", ("frlg", "lt_surge.png"), ("frlg", "leader_lt_surge")),
    ("ERIKA",    ("frlg", "erika.png"),    ("frlg", "leader_erika")),
    ("SABRINA",  ("frlg", "sabrina.png"),  ("frlg", "leader_sabrina")),
    ("BLAINE",   ("frlg", "blaine.png"),   ("frlg", "leader_blaine")),
    ("GIOVANNI", ("frlg", "giovanni.png"), ("frlg", "leader_giovanni")),
    # --- Gen III from ROWE's own NPC sheets (9-frame real walking) ---
    ("STEVEN",   ("rowe", "graphics/object_events/pics/people/steven.png"), None),
    ("WALLACE",  ("rowe", "graphics/object_events/pics/people/wallace.png"), None),
    ("WALLY",    ("rowe", "graphics/object_events/pics/people/wally.png"), None),
    ("ROXANNE",  ("rowe", "graphics/object_events/pics/people/gym_leaders/roxanne.png"), None),
    ("BRAWLY",   ("rowe", "graphics/object_events/pics/people/gym_leaders/brawly.png"), None),
    ("WATTSON",  ("rowe", "graphics/object_events/pics/people/gym_leaders/wattson.png"), None),
    ("FLANNERY", ("rowe", "graphics/object_events/pics/people/gym_leaders/flannery.png"), None),
    ("NORMAN",   ("rowe", "graphics/object_events/pics/people/gym_leaders/norman.png"), None),
    ("WINONA",   ("rowe", "graphics/object_events/pics/people/gym_leaders/winona.png"), None),
    ("TATE",     ("rowe", "graphics/object_events/pics/people/gym_leaders/tate.png"), None),
    ("LIZA",     ("rowe", "graphics/object_events/pics/people/gym_leaders/liza.png"), None),
    ("JUAN",     ("rowe", "graphics/object_events/pics/people/gym_leaders/juan.png"), None),
    ("SIDNEY",   ("rowe", "graphics/object_events/pics/people/elite_four/sidney.png"), None),
    ("PHOEBE",   ("rowe", "graphics/object_events/pics/people/elite_four/phoebe.png"), None),
    ("GLACIA",   ("rowe", "graphics/object_events/pics/people/elite_four/glacia.png"), None),
    ("DRAKE",    ("rowe", "graphics/object_events/pics/people/elite_four/drake.png"), None),
    ("MAXIE",    ("rowe", "graphics/object_events/pics/people/team_magma/maxie.png"), None),
    ("ARCHIE",   ("rowe", "graphics/object_events/pics/people/team_aqua/archie.png"), None),
    # --- Gen IV from sinnoh-remakes/pokeemerald-platinum ---
    # OWs are 9-frame 32x32 sheets; Lucas/Dawn have real walk+run pairs.
    ("LUCAS",    ("platrun", "graphics/object_events/pics/people/lucas/walking.png",
                             "graphics/object_events/pics/people/lucas/running.png"),
                 ("plat", "lucas_dp")),
    ("DAWN",     ("platrun", "graphics/object_events/pics/people/dawn/walking.png",
                             "graphics/object_events/pics/people/dawn/running.png"),
                 ("plat", "dawn_dp")),
    ("BARRY",    ("plat", "graphics/object_events/pics/people/barry_pt.png"), ("plat", "barry_dp")),
    ("CYNTHIA",  ("plat", "graphics/object_events/pics/people/cynthia_pt.png"), ("plat", "cynthia_dp")),
    ("ROARK",    ("plat", "graphics/object_events/pics/people/roark_pt.png"), ("plat", "roark_dp")),
    ("GARDENIA", ("plat", "graphics/object_events/pics/people/gardenia_pt.png"), ("plat", "gardenia_dp")),
    ("MAYLENE",  ("plat", "graphics/object_events/pics/people/maylene_pt.png"), ("plat", "maylene_dp")),
    ("CRASHER_WAKE", ("plat", "graphics/object_events/pics/people/crasher_wake_pt.png"), ("plat", "crasher_wake_dp")),
    ("FANTINA",  ("plat", "graphics/object_events/pics/people/fantina_pt.png"), ("plat", "fantina_dp")),
    ("BYRON",    ("plat", "graphics/object_events/pics/people/byron_pt.png"), ("plat", "byron_dp")),
    ("CANDICE",  ("plat", "graphics/object_events/pics/people/candice_pt.png"), ("plat", "candice_dp")),
    ("VOLKNER",  ("plat", "graphics/object_events/pics/people/volkner_pt.png"), ("plat", "volkner_dp")),
    ("AARON",    ("plat", "graphics/object_events/pics/people/aaron_pt.png"), None),
    ("BERTHA",   ("plat", "graphics/object_events/pics/people/bertha_pt.png"), ("plat", "bertha_dp")),
    ("FLINT",    ("plat", "graphics/object_events/pics/people/flint_pt.png"), None),
    ("LUCIAN",   ("plat", "graphics/object_events/pics/people/lucian_pt.png"), ("plat", "lucian_dp")),
    ("CYRUS",    ("plat", "graphics/object_events/pics/people/cyrus_pt.png"), ("plat", "cyrus_dp")),
    ("MARS",     ("plat", "graphics/object_events/pics/people/mars_pt.png"), ("plat", "mars_dp")),
    ("JUPITER",  ("plat", "graphics/object_events/pics/people/jupiter_pt.png"), ("plat", "jupiter_dp")),
    ("SATURN",   ("plat", "graphics/object_events/pics/people/saturn_pt.png"), ("plat", "saturn_dp")),
]

# frame width per character (pixels); default 16. Platinum sheets are 32.
FRAME_W = {n: 32 for n in ("LUCAS","DAWN","BARRY","CYNTHIA","ROARK","GARDENIA",
    "MAYLENE","CRASHER_WAKE","FANTINA","BYRON","CANDICE","VOLKNER","AARON",
    "BERTHA","FLINT","LUCIAN","CYRUS","MARS","JUPITER","SATURN")}

PAL_TAG_BASE = 0x1180  # after ROWE's last used tag (0x1161 Hilbert)


def camel(name):
    return "".join(p.title() for p in name.split("_"))


def snake(name):
    return "cm_" + name.lower()


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def write(p, s):
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


def replace_block(path, tag, block, anchor_re, before=True):
    text = read(path)
    start, end = MS.format(tag=tag), ME.format(tag=tag)
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    wrapped = "%s\n%s\n%s\n" % (start, block.rstrip("\n"), end)
    m = list(re.finditer(anchor_re, text, re.M))
    assert m, (path, anchor_re)
    pos = m[-1].start() if before else m[-1].end()
    if not before:
        wrapped = "\n" + wrapped
    write(path, text[:pos] + wrapped + text[pos:])


def png_to_jasc(img, path):
    pal = (img.getpalette() or [])[:48]
    pal = pal + [0] * (48 - len(pal))  # pad short palettes to 16 colors
    lines = ["JASC-PAL", "0100", "16"]
    for i in range(16):
        lines.append("%d %d %d" % tuple(pal[i*3:i*3+3]))
    write(path, "\r\n".join(lines) + "\r\n")


# The player avatar drives the full BrendanMayNormal (24-entry) animation
# table, whose walk/run anims reference frames 0-17. ROWE's auto-run in
# particular seeks the Run anims (frames 9-17); an NPC-style sprite that
# only supplies 9 frames indexes past its pic table and crashes. So build
# an 18-frame pic table where every walk/run frame maps back to one of the
# three facing frames (S=0, N=1, side=2) - the character glides, but never
# reads out of bounds. This mirrors ROWE's own Hilbert player costume.
NUM_PLAYER_FRAMES = 18
# 3-frame standing donors: everything maps to the facing frames (glide).
GLIDE_MAP = [0, 1, 2, 0, 0, 1, 1, 2, 2, 0, 1, 2, 0, 0, 1, 1, 2, 2]
# 9-frame walking donors: real walk frames; run block reuses walk frames.
WALK_MAP = [0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8]
assert len(GLIDE_MAP) == len(WALK_MAP) == NUM_PLAYER_FRAMES


def normalize_indexed(img):
    """Compact a P-mode png to <=16 palette slots, background at index 0.

    Some donors store 8-bit colormaps with sparse high indexes even though
    they use few colors. gbagfx needs 4bpp (16 slots, index 0 transparent)."""
    data = list(img.getdata())
    if max(data) < 16:
        return img
    used = []
    for px in data:
        if px not in used:
            used.append(px)
    bg = img.info.get("transparency", data[0])  # corner pixel fallback
    if len(used) > 16:
        # genuinely more than 16 colors: quantize, then rotate bg to slot 0
        rgb = img.convert("RGB")
        q = rgb.quantize(colors=16, method=Image.FASTOCTREE)
        qdata = list(q.getdata())
        qbg = qdata[0] if img.info.get("transparency") is None else \
            q.getpixel((0, 0))
        qpal = q.getpalette()[:48]
        order = [qbg] + [i for i in range(16) if i != qbg]
        remap = {old: new for new, old in enumerate(order)}
        newpal = []
        for old in order:
            newpal += qpal[old*3:old*3+3]
        out = Image.new("P", img.size)
        out.putpalette(newpal)
        out.putdata([remap[px] for px in qdata])
        out.info["transparency"] = 0
        return out
    if bg in used:
        used.remove(bg)
    used.insert(0, bg)
    remap = {old: new for new, old in enumerate(used)}
    pal = img.getpalette()
    newpal = []
    for old in used:
        newpal += pal[old*3:old*3+3]
    out = Image.new("P", img.size)
    out.putpalette(newpal + [0] * (48 - len(newpal)))
    out.putdata([remap[px] for px in data])
    out.info["transparency"] = 0
    return out


def slice_frames(img, fw):
    fh = img.height
    assert fh == 32, (img.size,)
    assert max(img.getdata()) < 16, "png uses >16 palette slots"
    return [img.crop((i*fw, 0, (i+1)*fw, fh)) for i in range(img.width // fw)]


def save_sheet(frames, fmap, palette, transparency, fw, dst_png):
    fh = 32
    sheet = Image.new("P", (fw, fh*NUM_PLAYER_FRAMES))
    sheet.putpalette(palette)
    for i, m in enumerate(fmap):
        sheet.paste(frames[m], (0, i*fh))
    if transparency is not None:
        sheet.save(dst_png, transparency=transparency)
    else:
        sheet.save(dst_png)


def build_ow_sheet(src_png, dst_png, fw=16):
    img = normalize_indexed(Image.open(src_png))
    assert img.mode == "P", src_png
    frames = slice_frames(img, fw)
    n = len(frames)
    if n >= 9:
        fmap = WALK_MAP
    elif n >= 3:
        fmap = GLIDE_MAP
    else:
        raise SystemExit("unexpected frame count %d in %s" % (n, src_png))
    save_sheet(frames, fmap, img.getpalette(), img.info.get("transparency"),
               fw, dst_png)
    return img


def build_ow_sheet_walkrun(walk_png, run_png, dst_png, fw=16):
    walk = normalize_indexed(Image.open(walk_png))
    run = normalize_indexed(Image.open(run_png))
    assert walk.mode == "P" and run.mode == "P"
    wf = slice_frames(walk, fw)
    rf = slice_frames(run, fw)
    assert len(wf) >= 9 and len(rf) >= 9, (walk_png, run_png)
    frames = wf[:9] + rf[:9]
    fmap = list(range(18))  # real walk 0-8 + real run 9-17
    save_sheet(frames, fmap, walk.getpalette(), walk.info.get("transparency"),
               fw, dst_png)
    return walk


def main():
    ow_dir = os.path.join(TARGET, "graphics/object_events/pics/people")
    fp_dir = os.path.join(TARGET, "graphics/trainers/front_pics")
    tp_dir = os.path.join(TARGET, "graphics/trainers/palettes")

    for name, ow, front in MANIFEST:
        s = snake(name)
        fw = FRAME_W.get(name, 16)
        if ow[0] == "frlg":
            src = os.path.join(DONOR_FR, "graphics/object_events/pics/people", ow[1])
            img = build_ow_sheet(src, os.path.join(ow_dir, s + ".png"), fw)
        elif ow[0] == "rowe":
            img = build_ow_sheet(os.path.join(TARGET, ow[1]),
                                 os.path.join(ow_dir, s + ".png"), fw)
        elif ow[0] == "plat":
            img = build_ow_sheet(os.path.join(DONOR_PT, ow[1]),
                                 os.path.join(ow_dir, s + ".png"), fw)
        elif ow[0] == "platrun":
            img = build_ow_sheet_walkrun(os.path.join(DONOR_PT, ow[1]),
                                         os.path.join(DONOR_PT, ow[2]),
                                         os.path.join(ow_dir, s + ".png"), fw)
        else:
            raise SystemExit("unknown ow source " + ow[0])
        png_to_jasc(img, os.path.join(ow_dir, s + ".pal"))
        if front is not None:
            froot, stem = front
            if froot == "frlg":
                fp = Image.open(os.path.join(DONOR_FR, "graphics/trainers/front_pics",
                                             stem + "_front_pic.png"))
                pal_src = os.path.join(DONOR_FR, "graphics/trainers/palettes", stem + ".pal")
                shutil.copyfile(pal_src, os.path.join(tp_dir, s + ".pal"))  # CRLF
            else:  # plat: palette comes from the png itself
                fp = normalize_indexed(Image.open(os.path.join(
                    DONOR_PT, "graphics/trainers/front_pics", stem + ".png")))
                png_to_jasc(fp, os.path.join(tp_dir, s + ".pal"))
            assert fp.size == (64, 64), stem
            fp.save(os.path.join(fp_dir, s + ".png"))

    names = [n for n, _, _ in MANIFEST]
    front_names = [n for n, _, f in MANIFEST if f is not None]

    # --- constants: OBJ_EVENT_GFX ids + NUM extension
    lines = ["#define OBJ_EVENT_GFX_CM_%s%s(OBJ_EVENT_GFX_POKEMON_904 + %d)"
             % (n, " " * max(1, 20 - len(n)), i + 1) for i, n in enumerate(names)]
    lines.append("#define OBJ_EVENT_GFX_CHARMODE_LAST     OBJ_EVENT_GFX_CM_%s" % names[-1])
    path = os.path.join(TARGET, "include/constants/event_objects.h")
    replace_block(path, "gfx-ids", "\n".join(lines),
                  r"^#define NUM_OBJ_EVENT_GFX", before=True)
    text = read(path)
    text = text.replace("#define NUM_OBJ_EVENT_GFX               (OBJ_EVENT_GFX_POKEMON_904 + 1)",
                        "#define NUM_OBJ_EVENT_GFX               (OBJ_EVENT_GFX_CHARMODE_LAST + 1)")
    write(path, text)

    # --- OW INCBINs (pics + palettes)
    block = "".join(
        'const u32 gObjectEventPic_Cm%s[] = INCBIN_U32("graphics/object_events/pics/people/%s.4bpp");\n'
        'const u16 gObjectEventPalette_Cm%s[] = INCBIN_U16("graphics/object_events/pics/people/%s.gbapal");\n'
        % (camel(n), snake(n), camel(n), snake(n)) for n in names)
    replace_block(os.path.join(TARGET, "src/data/object_events/object_event_graphics.h"),
                  "ow-incbins", block, r"\Z", before=True)

    # --- pic tables
    block = "".join(
        "static const struct SpriteFrameImage gObjectEventPicTable_Cm%s[] = {\n%s};\n"
        % (camel(n), "".join("    overworld_frame(gObjectEventPic_Cm%s, %d, 4, %d),\n"
                             % (camel(n), FRAME_W.get(n, 16) // 8, i)
                             for i in range(NUM_PLAYER_FRAMES)))
        for n in names)
    replace_block(os.path.join(TARGET, "src/data/object_events/object_event_pic_tables.h"),
                  "ow-pics", block, r"\Z", before=True)

    # --- graphics info structs (frame size varies by donor)
    def _info(n):
        fw = FRAME_W.get(n, 16)
        size = fw * 32 // 2
        return ("const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_Cm%s = "
                "{0xFFFF, OBJ_EVENT_PAL_CM_%s, OBJ_EVENT_PAL_TAG_NONE, %d, %d, 32, 5, "
                "SHADOW_SIZE_M, FALSE, FALSE, TRACKS_FOOT, &gObjectEventBaseOam_%dx32, "
                "gObjectEventSpriteOamTables_%dx32, gObjectEventImageAnimTable_BrendanMayNormal, "
                "gObjectEventPicTable_Cm%s, gDummySpriteAffineAnimTable};\n"
                % (camel(n), n, size, fw, fw, fw, camel(n)))
    block = "".join(_info(n) for n in names)
    replace_block(os.path.join(TARGET, "src/data/object_events/object_event_graphics_info.h"),
                  "ow-info", block, r"\Z", before=True)

    # --- pointers (must land inside gObjectEventGraphicsInfoPointers, NOT the
    # gMauvilleOldManGraphicsInfoPointers array that follows it - a bare `^};`
    # anchor picks the file's last brace and silently drops the entries, so the
    # lookup returns NULL and the player avatar crashes).
    block = "".join("    [OBJ_EVENT_GFX_CM_%s] = &gObjectEventGraphicsInfo_Cm%s,\n"
                    % (n, camel(n)) for n in names)
    path = os.path.join(TARGET, "src/data/object_events/object_event_graphics_info_pointers.h")
    text = read(path)
    text = re.sub(re.escape(MS.format(tag="ow-ptrs")) + r".*?"
                  + re.escape(ME.format(tag="ow-ptrs")) + r"\n?", "", text, flags=re.S)
    m = re.search(r"gObjectEventGraphicsInfoPointers\[[^\]]*\]\s*=\s*\{", text)
    close = text.index("\n};", m.end())
    wrapped = "%s\n%s\n%s\n" % (MS.format(tag="ow-ptrs"), block.rstrip("\n"),
                               ME.format(tag="ow-ptrs"))
    write(path, text[:close + 1] + wrapped + text[close + 1:])

    # --- palette tags + registration
    tag_defs = "".join("#define OBJ_EVENT_PAL_CM_%s%s0x%04X\n"
                       % (n, " " * max(1, 18 - len(n)), PAL_TAG_BASE + i)
                       for i, n in enumerate(names))
    path = os.path.join(TARGET, "src/event_object_movement.c")
    replace_block(path, "pal-tags", tag_defs,
                  r"^#define OBJ_EVENT_PAL_HILBERT.*$", before=False)
    entries = "".join("    {gObjectEventPalette_Cm%s, OBJ_EVENT_PAL_CM_%s},\n"
                      % (camel(n), n) for n in names)
    replace_block(path, "pal-entries", entries,
                  r"^\s*\{gObjectEventPalette_Steven,", before=True)

    # --- OW pic/pal externs are needed by event_object_movement.c's palette
    # table; the info/pic tables live in the same TU as the INCBINs.
    externs = "".join(
        "extern const u32 gObjectEventPic_Cm%s[];\n"
        "extern const u16 gObjectEventPalette_Cm%s[];\n"
        % (camel(n), camel(n)) for n in names) + "".join(
        "extern const u32 gTrainerFrontPic_Cm%s[];\n"
        "extern const u16 gTrainerPalette_Cm%s[];\n"
        % (camel(n), camel(n)) for n in front_names)
    path = os.path.join(TARGET, "include/graphics.h")
    text = read(path)
    start, end = MS.format(tag="externs"), ME.format(tag="externs")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    pos = text.rfind("#endif")
    text = text[:pos] + "%s\n%s%s\n" % (start, externs, end) + text[pos:]
    write(path, text)

    # --- TRAINER_PIC ids
    trainers_h = read(os.path.join(TARGET, "include/constants/trainers.h"))
    maxpic = max(int(m) for m in re.findall(r"#define TRAINER_PIC_\w+\s+(\d+)", trainers_h))
    lines = ["#define TRAINER_PIC_%s%s%d" % (n, " " * max(1, 20 - len(n)), maxpic + 1 + i)
             for i, n in enumerate(front_names)]
    replace_block(os.path.join(TARGET, "include/constants/trainers.h"), "pic-ids",
                  "\n".join(lines), r"^#define TRAINER_BACK_PIC_BRENDAN", before=True)

    # --- front pic INCBINs
    block = "".join(
        'const u32 gTrainerFrontPic_Cm%s[] = INCBIN_U32("graphics/trainers/front_pics/%s.4bpp.lz");\n'
        'const u16 gTrainerPalette_Cm%s[] = INCBIN_U16("graphics/trainers/palettes/%s.gbapal");\n'
        % (camel(n), snake(n), camel(n), snake(n)) for n in front_names)
    replace_block(os.path.join(TARGET, "src/data/graphics/trainers.h"),
                  "front-incbins", block, r"\Z", before=True)

    # --- front pic tables (coords, sprites, palettes, anims)
    path = os.path.join(TARGET, "src/data/trainer_graphics/front_pic_tables.h")
    text = read(path)
    coords_block = "".join("\t[TRAINER_PIC_%s] = {.size = 8, .y_offset = 1},\n" % n
                           for n in front_names)
    start, end = MS.format(tag="front-coords"), ME.format(tag="front-coords")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    anchor = text.index("[TRAINER_PIC_HILBERT] = {.size")
    line_end = text.index("\n", anchor) + 1
    text = text[:line_end] + "%s\n%s%s\n" % (start, coords_block, end) + text[line_end:]
    write(path, text)
    text = read(path)
    sprite_block = "".join("\tTRAINER_SPRITE(%s, gTrainerFrontPic_Cm%s, 0x800),\n"
                           % (n, camel(n)) for n in front_names)
    pal_block = "".join("\tTRAINER_PAL(%s, gTrainerPalette_Cm%s),\n"
                        % (n, camel(n)) for n in front_names)
    start, end = MS.format(tag="front-sprites"), ME.format(tag="front-sprites")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    anchor = text.index("TRAINER_SPRITE(HILBERT")
    line_end = text.index("\n", anchor) + 1
    text = text[:line_end] + "%s\n%s%s\n" % (start, sprite_block, end) + text[line_end:]
    start, end = MS.format(tag="front-pals"), ME.format(tag="front-pals")
    text = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S)
    anchor = text.index("TRAINER_PAL(HILBERT")
    line_end = text.index("\n", anchor) + 1
    text = text[:line_end] + "%s\n%s%s\n" % (start, pal_block, end) + text[line_end:]
    write(path, text)

    replace_block(os.path.join(TARGET, "src/data/trainer_graphics/front_pic_anims.h"),
                  "front-anims",
                  "".join("\t[TRAINER_PIC_%s] = sAnims_RubySapphireMay,\n" % n
                          for n in front_names),
                  r"^};", before=True)

    with open(os.path.join(HERE, "imported_ow.txt"), "w") as f:
        f.write("\n".join("OBJ_EVENT_GFX_CM_" + n for n in names) + "\n")
    print("imported %d characters' sprites; now run emit_characters.py and make" % len(names))


if __name__ == "__main__":
    main()
