#!/usr/bin/env python3
"""Import staged donor OVERWORLD sheets and BATTLE BACK PICS for Character Mode.

The counterpart to `import_donor_front_pics.py`, for the other two asset slots.
Until this existed, `sprites/donors/` was readable by exactly one tool and that
tool did front pics alone -- so 27 overworld sheets and 6 back pics sat staged
and unreachable while PLAN.md called the slots "art-blocked". They were not.

`import_sprites.py` built the first 95 overworld sheets, but it resolves its
donors from a scratchpad checkout that no longer exists, so it cannot be re-run.
This script reads `sprites/donors/` instead and writes into its OWN marker
blocks (`donor-ow-*`, `donor-back-*`), a separate namespace from
import_sprites.py's, so the two never fight over the same text.

⚠️ THE OVERWORLD SLOT IS NOT A ONE-LINE ALIAS FIX. `emit_characters.py` accepts
an `OBJ_EVENT_GFX_*` id for the player avatar only if it is listed in
`imported_ow.txt` / `imported_ow_donor.txt` or ends in `_NORMAL`. That gate is
deliberate: the player avatar drives the 24-entry `BrendanMayNormal` animation
table, whose walk/run anims reference frames 0-17, while a plain NPC id ships a
SHORT pic table and reads past its end -- a crash, not a glitch. Birch, Anabel,
Brandon, Greta, Lucy, Noland, Spenser and Tucker all already have an
`OBJ_EVENT_GFX_*` constant and wiring it would look like a free win; it ships a
crash. Every id this script emits is a real 18-frame player-grade sheet built by
`import_sprites.build_ow_sheet()`, and only those ids are added to the allowlist.

IDEMPOTENCY, and why it is load-bearing (see `import_donor_front_pics.mine()`):
every marker block is REWRITTEN WHOLESALE, so a character absent from this run's
picks is not "left alone", it is DELETED. The front-pic importer shipped that
bug for months and destroyed 99 imports the first time it ran with real work to
do. So this script re-derives its WHOLE output on every run: previously-imported
characters are re-picked from staged art, their ids are HELD FIXED, and it
REFUSES TO RUN (exit 1, nothing written) if any previously-imported character
stops resolving to staged art.

Emits, per overworld character:
    graphics/object_events/pics/people/<snake>.png   18-frame 16x576 sheet
    graphics/object_events/pics/people/<snake>.pal   JASC palette (CRLF)
    include/constants/event_objects.h                OBJ_EVENT_GFX_CM_<KEY>
    src/data/object_events/object_event_graphics.h   INCBINs
    .../object_event_pic_tables.h                    18-entry pic table
    .../object_event_graphics_info.h                 graphics info struct
    .../object_event_graphics_info_pointers.h        pointer row
    src/event_object_movement.c                      palette tag + registration
    include/graphics.h                               externs
    tools/character_mode/imported_ow_donor.txt       the player-safe allowlist

and per back-pic character:
    graphics/trainers/back_pics/<snake>_back_pic.png 4- or 5-frame 64xN
    graphics/trainers/palettes/<snake>_back.pal      JASC palette (CRLF)
    include/constants/trainers.h                     TRAINER_BACK_PIC_CM_<KEY>
    src/data/graphics/trainers.h                     INCBINs
    include/graphics.h, include/data.h               externs
    src/data/trainer_graphics/back_pic_tables.h      coords + pal + sheet rows
    src/data/trainer_graphics/back_pic_anims.h       anim arrays + ptr rows
    src/data.c                                       SpriteFrameImage tables
    src/pokemon.c                                    sprite template

⚠️ TWO OF THOSE ARRAYS ARE POSITIONAL, NOT DESIGNATED:
`gTrainerBackPicTable` (back_pic_tables.h) and
`gSpriteTemplateTable_TrainerBackSprites` (pokemon.c) are indexed by back-pic id
with no `[id] =` on the rows, so entries MUST be appended in id order at the end
of the array. Both blocks are emitted sorted by id for exactly that reason.

Usage:  python3 tools/character_mode/import_donor_ow_backs.py [--dry-run]
Then:   python3 tools/character_mode/emit_characters.py && make -j
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from PIL import Image
from import_sprites import (TARGET, camel, read, write, png_to_jasc,
                            normalize_indexed, slice_frames, save_sheet,
                            WALK_MAP, NUM_PLAYER_FRAMES)
from emit_characters import const_candidates

HERE = os.path.dirname(os.path.abspath(__file__))
DONORS = os.path.join(TARGET, "sprites", "donors")

# Our own marker namespace. import_sprites.py's blocks say "generated by
# tools/character_mode/import_sprites.py" in the START line, so the two never
# match each other's delete regex even where the tag names rhyme.
MS = "// CHARMODE-SPRITES-START {tag} (generated by tools/character_mode/import_donor_ow_backs.py)"
ME = "// CHARMODE-SPRITES-END {tag}"

# Best source first -- the same order and the same reasoning as
# `import_donor_front_pics.PREFERENCE`, extended with the three sets that only
# hold overworld/back art. Ordering below `hns` is by STRENGTH OF ATTRIBUTION,
# weakest last.
#
# ⚠️ A DIRECTORY NOT NAMED HERE IS SILENTLY IGNORED -- `candidates()` iterates
# this list, not `os.listdir(DONORS)`, so staging art into a new set without
# adding it here looks exactly like "there is no art for that character".
#
#   ashgray      front pics only, kept for order parity with the front importer
#   rogue        largest coherent set, one consistent style
#   taar         per-author attribution recoverable, explicit free-to-use grant
#   taar_gap     same repo, the 2026-07-28 gap-fill pass; per-file ARTIST named
#                in its CREDITS.txt, which is stronger than plain `taar/`
#   hns          project-level credit, no per-file artist
#   kalarie      named author, explicit grant; the only anime OW art anywhere
#   greenphx     named author, explicit (if optional) grant
#   pokesho      archived, permission inferred
#   dollsteak    thread-wide grant from the thread owner, not the contributor
#   loulilie     named author
#   platinum     no per-sprite credit at all, but one coherent project
#   unattributed NO licence, NO artist, NO project identity -- deliberately last
PREFERENCE = ["ashgray", "rogue", "taar", "taar_gap", "hns", "kalarie",
              "greenphx", "pokesho", "pokesho_field", "dollsteak", "loulilie",
              "platinum", "unattributed"]

# Display name -> donor filename stem, when they differ. Deliberately NOT
# shared with the front importer's ALIAS: there, James resolves to the Ash Gray
# `jessie_james` DUO portrait; here he has a solo overworld sheet of his own.
ALIAS = {}

# Back-pic donors that are not already 4 or 5 frames of 64x64. The value is the
# frame indices to take, in order, and the reason -- a judgement call about
# somebody's animation, so it is written down rather than guessed at.
BACK_FRAME_PICK = {
    # yoshord's Lance is a six-frame sheet with one extra intermediate raise
    # (frame 3) between "hand up" and "throw". Dropping it yields exactly the
    # FRLG five-frame pattern gAnimCmd_Red_1 plays: idle, hand low, hand up,
    # throw, turned. His README ships a matching six-frame sAnimCmd_Lance_Back[]
    # upstream, which was NOT harvested with the art -- if it is ever fetched,
    # a six-frame path is the better answer than this crop.
    "lance_back": ([0, 1, 2, 4, 5],
                   "6-frame yoshord sheet -> the 5-frame FRLG pattern; "
                   "frame 3 is a second arm-raise the Red anim has no slot for"),
}

# Back-pic donors that ship truecolour and need MORE than a lossless index.
# Keyed by file stem, so a NEW file can never be quantised by accident: the
# default path asserts the colour count and stops. Silently dropping colours to
# fit 4bpp produces plausible-looking corrupt art that is only caught by eye,
# which is the failure mode this project keeps re-learning.
QUANTISE = {
    # kwenio's Noland back pic (TAAR, staged 2026-07-29 from the 07-28 harvest).
    # Correct 64x256 geometry, but RGBA with 56 distinct opaque colours against
    # 4bpp's 16 -- and fully opaque, so the mint backdrop has to be masked to
    # index 0 by colour rather than by alpha or it renders as a solid green box
    # behind the player in battle. Chosen: mask everything within 8/255 per
    # channel of the corner pixel to index 0, MEDIANCUT the remaining 54 colours
    # to 15 with dithering OFF (a dither on a 64px sprite reads as noise).
    # Compared against the original as a decoded contact sheet before shipping:
    # hat, glove, vest and skin ramps all survive; the loss is one step of
    # shading on the forearm.
    "noland_back": "56-colour RGBA, opaque backdrop; mask bg by colour, "
                   "MEDIANCUT the rest to 15, no dither",
}

BG_TOLERANCE = 8  # per-channel, for masking a truecolour backdrop to index 0
PAL_TAG_BASE = 0x1200  # import_sprites used 0x1180..0x11DE; next tag up is 0x1800

slug = lambda s: re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


def key_of(disp):
    base = disp[:-len(" (anime)")] if disp.endswith(" (anime)") else disp
    return re.sub(r"[^A-Za-z0-9]+", "_", base).strip("_").upper()


def stem_of(disp):
    base = disp[:-len(" (anime)")] if disp.endswith(" (anime)") else disp
    return ALIAS.get(base, slug(base))


def display_names():
    """Character display names, in characters.txt order."""
    out = []
    with open(os.path.join(HERE, "characters.txt")) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                out.append(line.split("|")[0].strip())
    return out


# --------------------------------------------------------------------------
# donor discovery
# --------------------------------------------------------------------------
# A donor strip's FRAME WIDTH is not in its filename or its dimensions. 288x32
# is either 18 frames of 16 px or 9 frames of 32, and every 288-wide sheet in
# `sprites/donors/` is the latter -- so guessing 16 slices every sprite down the
# middle and pairs the halves as separate frames. THAT BUILDS, LINKS AND BOOTS;
# it was caught only by decoding the built .4bpp back out and looking at it.
#
# So the width is MEASURED. At a real frame boundary neither adjacent column
# carries much sprite, because frames are separated by the donor's own gutters.
# Measured over all 108 candidate strips in this tree: every 144-wide sheet
# scores 0-8 at fw=16, and every 288-wide sheet scores 19-21 at fw=16 and 0 at
# fw=32. The two clusters do not overlap and the threshold sits between them.
FRAME_BOUNDARY_MAX = 12


def _boundary_score(img, fw):
    """Worst internal frame boundary: min sprite pixels in the two columns."""
    w, h = img.size
    data = list(img.getdata())
    col = [sum(1 for y in range(h) if data[y * w + x]) for x in range(w)]
    return max(min(col[k * fw - 1], col[k * fw]) for k in range(1, w // fw))


def _checked_ow(path):
    """Open an overworld donor strip as (image, frame_width), or None.

    Matching is by EXACT filename, never a prefix, so `noland_ow_2.png` and
    `calem_ow_riding.png` (which has three blank frames where the walk cycle
    should be) can never be picked up as the walk sheet.
    """
    if not os.path.isfile(path):
        return None
    img = Image.open(path)
    if img.mode != "P" or img.height != 32:
        return None
    img = bg_to_slot0(normalize_indexed(img), path)
    for fw in (16, 32):
        if img.width % fw or img.width // fw not in (9, 18):
            continue
        if _boundary_score(img, fw) <= FRAME_BOUNDARY_MAX:
            return img, fw
    return None


def ow_candidates(disp):
    """[(src, [png, ...], fw, frames)] for this character, best source first.

    Two donor shapes are accepted, and nothing else:
      <stem>_ow_walking.png (+ <stem>_ow_running.png)  a real walk+run pair
      <stem>_ow.png                                    a 9- or 18-frame strip
    """
    stem = stem_of(disp)
    if not stem:
        return []
    out = []
    for src in PREFERENCE:
        d = os.path.join(DONORS, src)
        wpath = os.path.join(d, stem + "_ow_walking.png")
        walk = _checked_ow(wpath)
        if walk is not None and walk[0].width // walk[1] == 9:
            rpath = os.path.join(d, stem + "_ow_running.png")
            run = _checked_ow(rpath)
            if run is not None and run[1] == walk[1] and run[0].width // run[1] == 9:
                out.append((src, [wpath, rpath], walk[1], 18))
            else:
                out.append((src, [wpath], walk[1], 9))
            continue
        opath = os.path.join(d, stem + "_ow.png")
        one = _checked_ow(opath)
        if one is not None:
            out.append((src, [opath], one[1], one[0].width // one[1]))
    return out


def back_candidates(disp):
    """[(src, png, frames)] for this character, best source first."""
    stem = stem_of(disp)
    if not stem:
        return []
    out = []
    for src in PREFERENCE:
        p = os.path.join(DONORS, src, stem + "_back.png")
        if not os.path.isfile(p):
            continue
        img = Image.open(p)
        if img.width != 64 or img.height % 64:
            continue
        n = img.height // 64
        base = os.path.basename(p)[:-len(".png")]
        if n not in (4, 5) and base not in BACK_FRAME_PICK:
            continue
        out.append((src, p, len(BACK_FRAME_PICK[base][0])
                    if base in BACK_FRAME_PICK else n))
    return out


# --------------------------------------------------------------------------
# art conversion
# --------------------------------------------------------------------------
def bg_to_slot0(img, who):
    """Rotate the backdrop index to palette slot 0. Lossless, colours kept.

    ⚠️ `import_sprites.normalize_indexed()` only does this when a donor uses
    MORE than 16 slots; a donor that already fits 4bpp is returned untouched,
    backdrop wherever it happened to sit. The GBA renders sprite palette slot 0
    transparent whatever its colour value, so a donor whose backdrop sits at,
    say, slot 6 ships an opaque box round the sprite AND makes slot 6's real
    colour transparent instead. `taar/phoebe_back.png` is exactly that case, and
    it builds and links perfectly either way -- only an eye on the pixels tells
    the difference.
    """
    data = list(img.getdata())
    assert max(data) < 16, "%s: uses %d palette slots" % (who, max(data) + 1)
    bg = data[0]
    if bg == 0:
        img.info["transparency"] = 0
        return img
    pal = (img.getpalette() or [])[:48]
    pal += [0] * (48 - len(pal))
    order = [bg] + [i for i in range(16) if i != bg]
    remap = {old: new for new, old in enumerate(order)}
    newpal = []
    for old in order:
        newpal += pal[old * 3:old * 3 + 3]
    out = Image.new("P", img.size)
    out.putpalette(newpal + [0] * (768 - len(newpal)))
    out.putdata([remap[d] for d in data])
    out.info["transparency"] = 0
    return out


def build_player_sheet(pngs, fw, dst_png):
    """Write the (fw)x576 18-frame player-grade sheet the avatar animation needs.

    Donor strips are fw-wide frames on a 32px row in pokeemerald's own order:
    0 face S, 1 face N, 2 face W, 3/4 walk S, 5/6 walk N, 7/8 walk W. The player
    table wants 18: walk 0-8 then run 9-17.
    """
    imgs = []
    for p in pngs:
        im = normalize_indexed(Image.open(p))
        assert im.mode == "P", p
        imgs.append(bg_to_slot0(im, p))
    if len(imgs) == 2:                       # walk + run pair
        # ONE palette is written for the whole sheet, so a run strip indexed
        # against a different palette would come out recoloured -- and it would
        # still build, and still look like a sprite. Assert instead.
        assert imgs[0].getpalette()[:48] == imgs[1].getpalette()[:48], (
            "%s and %s do not share a palette; the run frames would be "
            "recoloured. Drop the run strip or re-index them together."
            % (pngs[0], pngs[1]))
        frames = slice_frames(imgs[0], fw)[:9] + slice_frames(imgs[1], fw)[:9]
        fmap = list(range(18))
    else:
        frames = slice_frames(imgs[0], fw)
        # 18 frames -> real walk+run; 9 -> the run block reuses the walk frames
        fmap = list(range(18)) if len(frames) >= 18 else WALK_MAP
    assert len(fmap) == NUM_PLAYER_FRAMES
    save_sheet(frames, fmap, imgs[0].getpalette(), 0, fw, dst_png)
    return imgs[0]


def build_back_pic(path, dst_png):
    """Write a 64x(64*n) back pic, backdrop at index 0. Returns (image, frames)."""
    base = os.path.basename(path)[:-len(".png")]
    img = Image.open(path)
    if img.mode == "P":
        img = bg_to_slot0(normalize_indexed(img), path)
    else:
        img = _quantise_truecolour(img, base, path)
    n = img.height // 64
    if base in BACK_FRAME_PICK:
        pick = BACK_FRAME_PICK[base][0]
        assert max(pick) < n, (path, n, pick)
    else:
        pick = list(range(n))
    assert len(pick) in (4, 5), (path, len(pick))
    out = Image.new("P", (64, 64 * len(pick)))
    out.putpalette(img.getpalette())
    for i, f in enumerate(pick):
        out.paste(img.crop((0, f * 64, 64, (f + 1) * 64)), (0, i * 64))
    out.info["transparency"] = 0
    out.save(dst_png, transparency=0)
    return out, len(pick)


def _quantise_truecolour(img, base, path):
    """Index a truecolour back pic, backdrop -> slot 0. Opt-in only."""
    rgb = img.convert("RGB")
    bg = rgb.getpixel((0, 0))
    fg = [max(abs(p[i] - bg[i]) for i in range(3)) > BG_TOLERANCE
          for p in rgb.getdata()]
    distinct = len({p for p, m in zip(rgb.getdata(), fg) if m})
    if distinct > 15 and base not in QUANTISE:
        raise SystemExit(
            "REFUSING TO GUESS -- %s has %d distinct non-backdrop colours and "
            "4bpp holds 15 (plus the backdrop at slot 0). Quantise it "
            "deliberately: add a QUANTISE entry naming the file and the choice "
            "made, after comparing the result against the original by eye."
            % (path, distinct))
    q = rgb.quantize(colors=15, method=Image.MEDIANCUT, dither=Image.Dither.NONE)
    pal = list(bg) + q.getpalette()[:45]
    out = Image.new("P", rgb.size)
    out.putpalette(pal + [0] * (768 - len(pal)))
    out.putdata([d + 1 if m else 0 for d, m in zip(q.getdata(), fg)])
    out.info["transparency"] = 0
    return out


# --------------------------------------------------------------------------
# text emission
# --------------------------------------------------------------------------
def _strip(text, tag):
    return re.sub(re.escape(MS.format(tag=tag)) + r".*?"
                  + re.escape(ME.format(tag=tag)) + r"\n?", "", text, flags=re.S)


def _block(path, tag, block, anchor_re, before=True):
    """Insert/replace a marker block at a WHOLE-LINE boundary.

    ⚠️ `import_sprites._block` prepends a "\\n" for the after-anchor case and
    strips only `MS…ME\\n?`, so every re-run leaves one more blank line behind
    and the file is not byte-stable. Anchoring past the anchor line's own
    newline instead makes a re-run reproduce the file exactly -- which is what
    lets "run it twice and diff" be a real idempotency test rather than a
    hopeful one.
    """
    text = _strip(read(path), tag)
    wrapped = "%s\n%s\n%s\n" % (MS.format(tag=tag), block.rstrip("\n"),
                                ME.format(tag=tag))
    m = list(re.finditer(anchor_re, text, re.M))
    assert m, (path, anchor_re)
    if before:
        pos = m[-1].start()
    else:
        nl = text.find("\n", m[-1].end())
        pos = len(text) if nl < 0 else nl + 1
    write(path, text[:pos] + wrapped + text[pos:])


def _block_in_array(path, tag, block, array_re):
    """Append inside a named array's braces (before its closing `};`).

    Needed wherever a bare `^};` anchor would pick the file's LAST array --
    import_sprites.py records losing entries into `gMauvilleOldManGraphicsInfo
    Pointers` that way, which made the lookup return NULL and crashed the player
    avatar.
    """
    text = _strip(read(path), tag)
    m = re.search(array_re, text)
    assert m, (path, array_re)
    close = text.index("\n};", m.end()) + 1
    write(path, text[:close] + "%s\n%s%s\n"
          % (MS.format(tag=tag), block, ME.format(tag=tag)) + text[close:])


def previous_report():
    """{(kind, display name): (source, files)} from the last run's report.

    ⚠️ "Refuses to run when a character stops resolving" does NOT cover the case
    where a character stops resolving TO THE SAME ART. Hiding
    `rogue/oak_ow.png` leaves `taar/oak_ow.png` standing, so the refusal never
    fires, the run reports "0 new" -- and Oak's overworld sprite has silently
    become a different artist's drawing. That was found by negative control, not
    by reasoning. A source change is legitimate (re-preferencing, a better
    sprite staged) so it is not fatal, but it is never silent.
    """
    path = os.path.join(HERE, "donor_ow_backs.txt")
    if not os.path.isfile(path):
        return {}
    out, rows = {}, 0
    for line in read(path).splitlines():
        if line.startswith("#") or not line.strip():
            continue
        rows += 1
        m = re.match(r"(ow|back)\s+(.+?)\s{2,}(\S+)\s{2,}(\S.*?)\s{2,}", line)
        if m:
            out[(m.group(1), m.group(2).strip())] = (m.group(3), m.group(4).strip())
    # ⚠️ A parser that quietly matches nothing is a check that cannot fail, and
    # this one already was one: the first regex wanted exactly three spaces after
    # the kind, which "ow   " has and "back " does not -- so drift detection was
    # blind to every back pic and said so by staying silent.
    assert len(out) == rows, (
        "donor_ow_backs.txt: parsed %d of %d rows -- the report format and this "
        "parser have drifted, and drift detection is now partly blind"
        % (len(out), rows))
    return out


def mine_ow(header):
    """{KEY: offset} for the OW ids THIS script emitted on a previous run."""
    m = re.search(re.escape(MS.format(tag="donor-ow-ids")) + r"(.*?)"
                  + re.escape(ME.format(tag="donor-ow-ids")), header, re.S)
    if not m:
        return {}
    return {k: int(v) for k, v in re.findall(
        r"#define OBJ_EVENT_GFX_CM_(\w+)\s+\(OBJ_EVENT_GFX_CHARMODE_LAST \+ (\d+)\)",
        m.group(1))}


def mine_back(header):
    """{KEY: id} for the back-pic ids THIS script emitted on a previous run."""
    m = re.search(re.escape(MS.format(tag="donor-back-ids")) + r"(.*?)"
                  + re.escape(ME.format(tag="donor-back-ids")), header, re.S)
    if not m:
        return {}
    return {k: int(v) for k, v in
            re.findall(r"#define TRAINER_BACK_PIC_CM_(\w+)\s+(\d+)", m.group(1))}


def main():
    dry = "--dry-run" in sys.argv
    ev_path = os.path.join(TARGET, "include/constants/event_objects.h")
    tr_path = os.path.join(TARGET, "include/constants/trainers.h")
    ev_h, tr_h = read(ev_path), read(tr_path)

    obj_gfx = set(re.findall(r"#define (OBJ_EVENT_GFX_\w+)", ev_h))
    back_pics = set(re.findall(r"#define (TRAINER_BACK_PIC_\w+)", tr_h))
    ours_ow, ours_back = mine_ow(ev_h), mine_back(tr_h)

    # Player-safe overworld ids from the OTHER importer, plus ROWE's own player
    # costumes (the `_NORMAL` ids, handled in the loop below).
    #
    # ⚠️ `imported_ow_donor.txt` is deliberately NOT read here. It is THIS
    # script's own output, and treating your own previous output as "somebody
    # else already covered this character" is the exact conflation that made the
    # front-pic importer delete 99 imports. Subtracting only what the marker
    # block still lists is not enough either: if the block and the txt ever
    # disagree, the txt silently wins and the character is skipped instead of
    # re-emitted. So the txt is informational only, and the block is the record.
    p = os.path.join(HERE, "imported_ow.txt")
    safe_ow = ({t for t in read(p).split() if t.startswith("OBJ_EVENT_GFX_")}
               if os.path.isfile(p) else set())
    safe_ow -= {"OBJ_EVENT_GFX_CM_" + k for k in ours_ow}
    back_pics -= {"TRAINER_BACK_PIC_CM_" + k for k in ours_back}

    ow_picks, back_picks = [], []
    ow_skip = ow_missing = back_skip = back_missing = 0
    lost = []
    for disp in display_names():
        key = key_of(disp)
        # --- overworld
        if any(c in obj_gfx and (c in safe_ow or c.endswith("_NORMAL"))
               for c in const_candidates(disp, "OBJ_EVENT_GFX_")):
            ow_skip += 1
        else:
            c = ow_candidates(disp)
            if c:
                src, pngs, fw, n = c[0]
                ow_picks.append(dict(disp=disp, key=key, src=src, pngs=pngs,
                                     fw=fw, frames=n,
                                     snake="cm_donor_" + slug(disp)))
            elif key in ours_ow:
                lost.append("overworld: " + disp)
            else:
                ow_missing += 1
        # --- back pic
        if any(c in back_pics for c in const_candidates(disp, "TRAINER_BACK_PIC_")):
            back_skip += 1
            continue
        c = back_candidates(disp)
        if c:
            src, png, n = c[0]
            back_picks.append(dict(disp=disp, key=key, src=src, png=png,
                                   frames=n,
                                   snake="cm_donor_" + slug(disp)))
        elif key in ours_back:
            lost.append("back pic: " + disp)
        else:
            back_missing += 1

    if lost:
        sys.exit("REFUSING TO RUN -- %d asset(s) imported by a previous run no "
                 "longer resolve to any staged donor art:\n  %s\n"
                 "Every marker block is rewritten wholesale, so re-running now "
                 "would DELETE their defines, INCBINs and table rows while "
                 "leaving the ROM referencing them. Restore the staged art (or "
                 "remove them from the donor-* blocks deliberately) first."
                 % (len(lost), "\n  ".join(lost)))

    for p in ow_picks:
        c = "OBJ_EVENT_GFX_CM_" + p["key"]
        if c in obj_gfx and p["key"] not in ours_ow:
            sys.exit("id collision: %s already exists (character %s)" % (c, p["disp"]))

    prev = previous_report()
    drift = []
    for kind, picks in (("ow", ow_picks), ("back", back_picks)):
        for p in picks:
            was = prev.get((kind, p["disp"]))
            now = (p["src"], " + ".join(os.path.basename(x) for x in
                                        (p["pngs"] if kind == "ow" else [p["png"]])))
            if was and was != now:
                drift.append("%-5s %-24s %s/%s  ->  %s/%s"
                             % (kind, p["disp"], was[0], was[1], now[0], now[1]))

    fresh_ow = [p for p in ow_picks if p["key"] not in ours_ow]
    fresh_back = [p for p in back_picks if p["key"] not in ours_back]
    print("overworld: %d already covered, %d to emit (%d new), %d have no staged art"
          % (ow_skip, len(ow_picks), len(fresh_ow), ow_missing))
    print("back pics: %d already covered, %d to emit (%d new), %d have no staged art"
          % (back_skip, len(back_picks), len(fresh_back), back_missing))
    for label, picks in (("overworld", fresh_ow), ("back", fresh_back)):
        by_src = {}
        for p in picks:
            by_src[p["src"]] = by_src.get(p["src"], 0) + 1
        for s in PREFERENCE:
            if by_src.get(s):
                print("   new %-9s from %-12s %d" % (label, s, by_src[s]))
    if drift:
        print("\n⚠️  %d already-imported asset(s) now resolve to DIFFERENT art "
              "(the id is held, the picture is not):" % len(drift))
        for d in drift:
            print("   " + d)
    if dry:
        return 0
    if not ow_picks and not back_picks:
        print("nothing to do")
        return 0

    # --- ids: held fixed for anything we issued before, appended after the max
    nxt = max(list(ours_ow.values()) + [0]) + 1
    for p in ow_picks:
        if p["key"] in ours_ow:
            p["off"] = ours_ow[p["key"]]
        else:
            p["off"] = nxt
            nxt += 1
    stock_back = [int(m) for m in re.findall(
        r"#define TRAINER_BACK_PIC_\w+\s+(\d+)", tr_h)]
    nxt = max(stock_back + list(ours_back.values())) + 1
    for p in back_picks:
        if p["key"] in ours_back:
            p["id"] = ours_back[p["key"]]
        else:
            p["id"] = nxt
            nxt += 1
    back_by_id = sorted(back_picks, key=lambda p: p["id"])

    # --- art ---------------------------------------------------------------
    ow_dir = os.path.join(TARGET, "graphics/object_events/pics/people")
    bp_dir = os.path.join(TARGET, "graphics/trainers/back_pics")
    pal_dir = os.path.join(TARGET, "graphics/trainers/palettes")
    for p in ow_picks:
        img = build_player_sheet(p["pngs"], p["fw"],
                                 os.path.join(ow_dir, p["snake"] + ".png"))
        png_to_jasc(img, os.path.join(ow_dir, p["snake"] + ".pal"))
    for p in back_picks:
        img, n = build_back_pic(p["png"],
                                os.path.join(bp_dir, p["snake"] + "_back_pic.png"))
        assert n == p["frames"], (p["disp"], n, p["frames"])
        png_to_jasc(img, os.path.join(pal_dir, p["snake"] + "_back.pal"))

    if ow_picks:
        emit_ow(ow_picks, ev_path)
    if back_picks:
        emit_back(back_picks, back_by_id, tr_path)

    write(os.path.join(HERE, "imported_ow_donor.txt"),
          "# Player-grade 18-frame overworld sheets emitted by\n"
          "# tools/character_mode/import_donor_ow_backs.py. emit_characters.py\n"
          "# only accepts an OBJ_EVENT_GFX id as the player avatar if it is\n"
          "# listed here (or in imported_ow.txt, or ends in _NORMAL).\n"
          + "".join("OBJ_EVENT_GFX_CM_%s\n" % p["key"] for p in ow_picks))
    write(os.path.join(HERE, "donor_ow_backs.txt"),
          "# Overworld sheets and back pics imported from sprites/donors/ by\n"
          "# tools/character_mode/import_donor_ow_backs.py -- regenerate, do not edit.\n"
          + "".join("ow   %-24s %-10s %-42s %2d frames of %dx32\n"
                    % (p["disp"], p["src"],
                       " + ".join(os.path.basename(x) for x in p["pngs"]),
                       p["frames"], p["fw"])
                    for p in ow_picks)
          + "".join("back %-24s %-10s %-32s %2d frames\n"
                    % (p["disp"], p["src"], os.path.basename(p["png"]), p["frames"])
                    for p in back_by_id))
    print("emitted %d overworld sheets (%d new) and %d back pics (%d new)"
          % (len(ow_picks), len(fresh_ow), len(back_picks), len(fresh_back)))
    print("next: python3 tools/character_mode/emit_characters.py && make -j")
    return 0


def emit_ow(picks, ev_path):
    # --- ids. Expressed relative to OBJ_EVENT_GFX_CHARMODE_LAST so that
    # import_sprites.py's block stays the sole owner of the base, and
    # NUM_OBJ_EVENT_GFX is repointed at ours (it sizes
    # gObjectEventGraphicsInfoPointers and bounds the lookup in
    # event_object_movement.c:3765 -- leaving it at CHARMODE_LAST would make
    # every id below refuse to load).
    lines = ["#define OBJ_EVENT_GFX_CM_%s%s(OBJ_EVENT_GFX_CHARMODE_LAST + %d)"
             % (p["key"], " " * max(1, 20 - len(p["key"])), p["off"]) for p in picks]
    lines.append("#define OBJ_EVENT_GFX_CHARMODE_DONOR_LAST OBJ_EVENT_GFX_CM_%s"
                 % max(picks, key=lambda p: p["off"])["key"])
    _block(ev_path, "donor-ow-ids", "\n".join(lines),
           r"^#define NUM_OBJ_EVENT_GFX", before=True)
    text = read(ev_path)
    text, n = re.subn(r"^#define NUM_OBJ_EVENT_GFX(\s+)\(OBJ_EVENT_GFX_\w+ \+ 1\)",
                      r"#define NUM_OBJ_EVENT_GFX\1(OBJ_EVENT_GFX_CHARMODE_DONOR_LAST + 1)",
                      text, flags=re.M)
    assert n == 1, "NUM_OBJ_EVENT_GFX not found exactly once (%d)" % n
    write(ev_path, text)

    _block(os.path.join(TARGET, "src/data/object_events/object_event_graphics.h"),
           "donor-ow-incbins", "".join(
               'const u32 gObjectEventPic_Cm%s[] = INCBIN_U32("graphics/object_events/pics/people/%s.4bpp");\n'
               'const u16 gObjectEventPalette_Cm%s[] = INCBIN_U16("graphics/object_events/pics/people/%s.gbapal");\n'
               % (camel(p["key"]), p["snake"], camel(p["key"]), p["snake"])
               for p in picks), r"\Z", before=True)

    _block(os.path.join(TARGET, "src/data/object_events/object_event_pic_tables.h"),
           "donor-ow-pics", "".join(
               "static const struct SpriteFrameImage gObjectEventPicTable_Cm%s[] = {\n%s};\n"
               % (camel(p["key"]),
                  "".join("    overworld_frame(gObjectEventPic_Cm%s, %d, 4, %d),\n"
                          % (camel(p["key"]), p["fw"] // 8, i)
                          for i in range(NUM_PLAYER_FRAMES)))
               for p in picks), r"\Z", before=True)

    # .size is the BYTE size of one frame (fw * 32 / 2 at 4bpp) and the OAM
    # tables are per frame width -- a 32px sheet described as 16px reads half a
    # frame per slot and walks off the end of the pic table.
    _block(os.path.join(TARGET, "src/data/object_events/object_event_graphics_info.h"),
           "donor-ow-info", "".join(
               "const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_Cm%s = "
               "{0xFFFF, OBJ_EVENT_PAL_CM_%s, OBJ_EVENT_PAL_TAG_NONE, %d, %d, 32, 5, "
               "SHADOW_SIZE_M, FALSE, FALSE, TRACKS_FOOT, &gObjectEventBaseOam_%dx32, "
               "gObjectEventSpriteOamTables_%dx32, gObjectEventImageAnimTable_BrendanMayNormal, "
               "gObjectEventPicTable_Cm%s, gDummySpriteAffineAnimTable};\n"
               % (camel(p["key"]), p["key"], p["fw"] * 32 // 2, p["fw"],
                  p["fw"], p["fw"], camel(p["key"])) for p in picks),
           r"\Z", before=True)

    _block_in_array(
        os.path.join(TARGET, "src/data/object_events/object_event_graphics_info_pointers.h"),
        "donor-ow-ptrs",
        "".join("    [OBJ_EVENT_GFX_CM_%s] = &gObjectEventGraphicsInfo_Cm%s,\n"
                % (p["key"], camel(p["key"])) for p in picks),
        r"gObjectEventGraphicsInfoPointers\[[^\]]*\]\s*=\s*\{")

    mv = os.path.join(TARGET, "src/event_object_movement.c")
    _block(mv, "donor-ow-paltags", "".join(
        "#define OBJ_EVENT_PAL_CM_%s%s0x%04X\n"
        % (p["key"], " " * max(1, 18 - len(p["key"])), PAL_TAG_BASE + p["off"] - 1)
        for p in picks), r"^// CHARMODE-SPRITES-END pal-tags$", before=False)
    _block(mv, "donor-ow-palentries", "".join(
        "    {gObjectEventPalette_Cm%s, OBJ_EVENT_PAL_CM_%s},\n"
        % (camel(p["key"]), p["key"]) for p in picks),
        r"^\s*\{gObjectEventPalette_Steven,", before=True)

    _block(os.path.join(TARGET, "include/graphics.h"), "donor-ow-externs",
           "".join("extern const u32 gObjectEventPic_Cm%s[];\n"
                   "extern const u16 gObjectEventPalette_Cm%s[];\n"
                   % (camel(p["key"]), camel(p["key"])) for p in picks),
           r"^#endif", before=True)


def emit_back(picks, by_id, tr_path):
    _block(tr_path, "donor-back-ids", "\n".join(
        "#define TRAINER_BACK_PIC_CM_%s%s%d"
        % (p["key"], " " * max(1, 17 - len(p["key"])), p["id"]) for p in by_id),
        r"^// CHARMODE-SPRITES-END back-ids$", before=False)

    _block(os.path.join(TARGET, "src/data/graphics/trainers.h"), "donor-back-incbins",
           "".join(
               'const u8 gTrainerBackPic_Cm%s[] = INCBIN_U8("graphics/trainers/back_pics/%s_back_pic.4bpp");\n'
               'const u16 gTrainerBackPicPalette_Cm%s[] = INCBIN_U16("graphics/trainers/palettes/%s_back.gbapal");\n'
               % (camel(p["key"]), p["snake"], camel(p["key"]), p["snake"])
               for p in picks), r"\Z", before=True)

    _block(os.path.join(TARGET, "include/graphics.h"), "donor-back-externs",
           "".join("extern const u8 gTrainerBackPic_Cm%s[];\n"
                   "extern const u16 gTrainerBackPicPalette_Cm%s[];\n"
                   % (camel(p["key"]), camel(p["key"])) for p in picks),
           r"^#endif", before=True)
    _block(os.path.join(TARGET, "include/data.h"), "donor-back-frame-externs",
           "".join("extern const struct SpriteFrameImage gTrainerBackPicTable_Cm%s[];\n"
                   % camel(p["key"]) for p in picks),
           r"^// CHARMODE-SPRITES-END back-frame-externs$", before=False)

    bt = os.path.join(TARGET, "src/data/trainer_graphics/back_pic_tables.h")
    # coords + palettes are designated-initializer arrays, so row order is free;
    # gTrainerBackPicTable is NOT, so it is appended in id order at the end.
    _block(bt, "donor-back-coords", "".join(
        "    [TRAINER_BACK_PIC_CM_%s] = {.size = 8, .y_offset = %d},\n"
        % (p["key"], 5 if p["frames"] == 5 else 4) for p in picks),
        r"^// CHARMODE-SPRITES-END back-coords$", before=False)
    _block(bt, "donor-back-pals", "".join(
        "    TRAINER_BACK_PAL(CM_%s, gTrainerBackPicPalette_Cm%s),\n"
        % (p["key"], camel(p["key"])) for p in picks),
        r"^// CHARMODE-SPRITES-END back-pals$", before=False)
    _block_in_array(bt, "donor-back-sheets", "".join(
        "    (const u32 *)gTrainerBackPic_Cm%s, 0x%04X, TRAINER_BACK_PIC_CM_%s,\n"
        % (camel(p["key"]), p["frames"] * 0x800, p["key"]) for p in by_id),
        r"gTrainerBackPicTable\[\]\s*=\s*\{")

    # 4-frame donors play the Emerald throw (gAnimCmd_May_Steven_1, frames
    # 0,1,2,0,3); 5-frame donors play the FRLG one (gAnimCmd_Red_1, frames
    # 1,2,3,4,0). Both are static in this same file, defined above the block.
    ba = os.path.join(TARGET, "src/data/trainer_graphics/back_pic_anims.h")
    _block(ba, "donor-back-anims", "".join(
        "static const union AnimCmd *const sBackAnims_Cm%s[] =\n{\n"
        "    %s,\n    %s,\n};\n"
        % (camel(p["key"]),
           "sAnim_GeneralFrame0" if p["frames"] == 5 else "sAnim_GeneralFrame3",
           "gAnimCmd_Red_1" if p["frames"] == 5 else "gAnimCmd_May_Steven_1")
        for p in picks),
        r"^const union AnimCmd \*const \*const gTrainerBackAnimsPtrTable", before=True)
    _block(ba, "donor-back-anim-ptrs", "".join(
        "    [TRAINER_BACK_PIC_CM_%s] = sBackAnims_Cm%s,\n"
        % (p["key"], camel(p["key"])) for p in picks),
        r"^// CHARMODE-SPRITES-END back-anim-ptrs$", before=False)

    _block(os.path.join(TARGET, "src/data.c"), "donor-back-frameimgs", "".join(
        "const struct SpriteFrameImage gTrainerBackPicTable_Cm%s[] =\n{\n%s};\n"
        % (camel(p["key"]),
           "".join("    gTrainerBackPic_Cm%s%s, 0x0800,\n"
                   % (camel(p["key"]), "" if i == 0 else " + 0x%04X" % (i * 0x800))
                   for i in range(p["frames"])))
        for p in picks),
        r"^// CHARMODE-SPRITES-END back-frameimgs$", before=False)

    # gSpriteTemplateTable_TrainerBackSprites is indexed by back-pic id with no
    # designators, so these rows MUST be last and in id order.
    _block_in_array(os.path.join(TARGET, "src/pokemon.c"), "donor-back-templates",
                    "".join("    {\n        .tileTag = 0xFFFF,\n        .paletteTag = 0,\n"
                            "        .oam = &gOamData_831ACB0,\n        .anims = NULL,\n"
                            "        .images = gTrainerBackPicTable_Cm%s,\n"
                            "        .affineAnims = gUnknown_082FF618,\n"
                            "        .callback = sub_8039BB4,\n    },\n" % camel(p["key"])
                            for p in by_id),
                    r"gSpriteTemplateTable_TrainerBackSprites\[\]\s*=\s*\{")


if __name__ == "__main__":
    sys.exit(main())
