#!/usr/bin/env python3
"""Port battle animations for the 188 ported 2.X moves.

Root cause of the Trick-o-nome crash: gBattleAnims_Moves (in
data/battle_anim_scripts.s, assembly -- invisible to the C-side
MOVES_COUNT sweep) still had 756 entries while MOVES_COUNT grew to 943.
Any new move that animated indexed past the table and jumped through a
garbage pointer. Trainer battles with rebalanced parties would have hit
this constantly.

The donor ships a complete 943-entry table. Its new-move animations are
mostly aliases (a `goto Move_X`, or a fall-through label stacked on the
next move's block). Strategy per move id 755..942:
  1. Resolve the donor's EFFECTIVE animation block (follow stacked labels).
  2. If the block is or reduces to a target label that exists in OUR file,
     emit `Move_NEW::  goto Move_TARGET`.
  3. If the donor block has real content whose referenced symbols all exist
     in our file (or come with it), copy the block verbatim.
  4. Anything unresolvable falls back to `goto Move_TACKLE` and is reported.

Table entries are inserted before the trailing Move_COUNT sentinel so ids
stay aligned. Idempotent via ROWEANIM markers.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR = os.environ.get(
    "ROWEREPO_DONOR", "/home/jbfish00/Documents/RoweRepo-donor")

MS = "@ ROWEANIM-PORT-START {tag} (generated by tools/character_mode/port_2x_move_anims.py)"
ME = "@ ROWEANIM-PORT-END {tag}"

FALLBACK = "Move_TACKLE"


def read(p):
    with open(p, encoding="utf-8", errors="ignore") as f:
        return f.read()


def strip_block(text, tag):
    return re.sub(re.escape(MS.format(tag=tag)) + r".*?" +
                  re.escape(ME.format(tag=tag)) + r"\n?", "", text, flags=re.S)


def wrap(tag, block):
    return "%s\n%s%s\n" % (MS.format(tag=tag), block, ME.format(tag=tag))


def main():
    dry = "--dry-run" in sys.argv
    ours_path = os.path.join(TARGET, "data", "battle_anim_scripts.s")
    ours = strip_block(strip_block(read(ours_path), "table"), "scripts")
    donor = read(os.path.join(DONOR, "data", "battle_anim_scripts.s"))

    dm = re.search(r"gBattleAnims_Moves::(.*?)(?=\n\w+::)", donor, re.S)
    donor_entries = re.findall(r"\.4byte\s+(\w+)", dm.group(1))
    om = re.search(r"gBattleAnims_Moves::(.*?)(?=\n\w+::)", ours, re.S)
    our_entries = re.findall(r"\.4byte\s+(\w+)", om.group(1))
    assert our_entries[-1] == "Move_COUNT", "expected Move_COUNT sentinel"
    n_ours = len(our_entries) - 1          # real entries (ids 0..754)
    new_labels = donor_entries[n_ours:]    # ids 755..942
    print("porting %d anim entries (ids %d..%d)"
          % (len(new_labels), n_ours, len(donor_entries) - 1))

    our_labels = set(re.findall(r"^(\w+):", ours, re.M))

    # donor label -> (block_text, next_label) for resolution
    donor_blocks = {}
    for m in re.finditer(r"^(\w+)::?\n(.*?)(?=^\w+::?$|\Z)", donor, re.S | re.M):
        donor_blocks[m.group(1)] = m.group(2)
    # ordered label list for fall-through resolution
    donor_label_seq = re.findall(r"^(\w+)::?$", donor, re.M)
    next_of = {donor_label_seq[i]: donor_label_seq[i + 1]
               for i in range(len(donor_label_seq) - 1)}

    def effective_target(label, depth=0):
        """Follow empty fall-throughs and lone gotos to a concrete label."""
        if depth > 60:
            return None
        body = donor_blocks.get(label, "")
        stripped = "\n".join(l for l in body.splitlines()
                             if l.strip() and not l.strip().startswith("@"))
        if not stripped.strip():
            nxt = next_of.get(label)
            return effective_target(nxt, depth + 1) if nxt else None
        g = re.match(r"\s*goto\s+(\w+)\s*$", stripped.strip())
        if g:
            return effective_target(g.group(1), depth + 1) or g.group(1)
        return label   # has real content

    table_rows, script_out, report = [], [], []
    emitted = set()
    for i, label in enumerate(new_labels):
        mv = label
        tgt = effective_target(label)
        if tgt and tgt in our_labels:
            # donor's anim reduces to something we already have
            table_rows.append("\t.4byte %s\n" % tgt)
            report.append("ALIAS  %-34s -> %s" % (mv, tgt))
            continue
        if tgt and tgt not in our_labels and tgt in donor_blocks:
            # real donor content: copy iff every referenced symbol resolves
            body = donor_blocks[tgt]
            refs = set(re.findall(r"\b(Move_\w+|General_\w+|Special_\w+)\b", body))
            unresolved = [r for r in refs
                          if r not in our_labels and r != tgt and r not in emitted]
            # non-label symbol deps (sprite templates, tags) are resolved by
            # cpp/linker; a missing one fails the build loudly, so only label
            # deps are pre-checked here
            if not unresolved:
                sym = tgt if tgt == mv else mv
                if sym not in emitted:
                    script_out.append("%s::\n%s" % (sym, body.rstrip() + "\n"))
                    emitted.add(sym)
                table_rows.append("\t.4byte %s\n" % sym)
                report.append("COPY   %-34s (block %s, %d lines)"
                              % (mv, tgt, body.count("\n")))
                continue
        table_rows.append("\t.4byte %s\n" % FALLBACK)
        report.append("FALLBK %-34s -> %s (unresolvable: %s)"
                      % (mv, FALLBACK, tgt))

    if dry:
        for r in report:
            print("  ", r)
        return

    # insert table rows before the Move_COUNT sentinel
    text = ours
    m = re.search(r"(\t\.4byte\s+Move_COUNT\b)", text)
    text = (text[:m.start(1)] + wrap("table", "".join(table_rows))
            + text[m.start(1):])
    # append copied scripts after the sentinel'd table (before first label)
    if script_out:
        anchor = re.search(r"\n(\w+)::?\n", text[m.end(1):])
        pos = m.end(1) + anchor.start() + 1 + len(wrap("table", "".join(table_rows)))
        # simpler: append scripts at end of file
        text = text.rstrip("\n") + "\n\n" + wrap("scripts", "".join(script_out))
    with open(ours_path, "w", encoding="utf-8") as f:
        f.write(text)
    with open(os.path.join(HERE, "rowe_anim_port_report.txt"), "w") as f:
        f.write("\n".join(report) + "\n")
    print("wrote %d table rows, %d copied scripts -> run make"
          % (len(table_rows), len(script_out)))


if __name__ == "__main__":
    main()
