#!/usr/bin/env python3
"""Adopt ROWE 2.X ability constants + names + descriptions from RoweRepo.

Ports every ABILITY_* define with id > our current max (303, BUGGED_OUT)
from the donor's include/constants/abilities.h, plus per-language names and
descriptions from the donor's src/data/text/abilities.h (donor keeps
descriptions inline via FORMAT_ABILITY_DESCRIPTION; we convert to our
static-array + pointer style). Battle effects are NOT ported — the new
abilities are inert until implemented (plan Phase 2.3).

Also aliases ABILITY_POWER_SURGE (2.X name for id 275) to our
ABILITY_EARLY_EVOLVER so donor data referencing it compiles.

Idempotent via ROWEABIL-PORT marker blocks.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR = os.environ.get(
    "ROWEREPO_DONOR", "/home/jbfish00/Documents/RoweRepo-donor")

MS = "// ROWEABIL-PORT-START {tag} (generated by tools/character_mode/port_2x_abilities.py)"
ME = "// ROWEABIL-PORT-END {tag}"

OUR_MAX_ID = 303  # ABILITY_BUGGED_OUT


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def write(p, s):
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


def strip_block(text, tag):
    return re.sub(re.escape(MS.format(tag=tag)) + r".*?" +
                  re.escape(ME.format(tag=tag)) + r"\n?", "", text, flags=re.S)


def wrap(tag, block):
    return "%s\n%s%s\n" % (MS.format(tag=tag), block, ME.format(tag=tag))


def parse_designated(block, value_re):
    """[ABILITY_X] = <value_re-captured>  ->  dict"""
    return dict(re.findall(r"\[(ABILITY_\w+)\]\s*=\s*" + value_re, block))


def main():
    dry = "--dry-run" in sys.argv
    tgt = lambda *p: os.path.join(TARGET, *p)
    dn = lambda *p: os.path.join(DONOR, *p)

    # ---- 1. donor constants with id > OUR_MAX_ID
    dtext = read(dn("include", "constants", "abilities.h"))
    seen, new_defs = {}, []
    for m in re.finditer(r"#define (ABILITY_\w+)\s+(\d+)(.*)", dtext):
        name, num, comment = m.group(1), int(m.group(2)), m.group(3).rstrip()
        if num > OUR_MAX_ID and name not in seen:
            seen[name] = num
            new_defs.append((num, name, comment))
    new_defs.sort()
    last_name = new_defs[-1][1]
    names_new = [n for _, n, _ in new_defs]
    print("adopting %d abilities (%d..%d), last=%s" %
          (len(new_defs), new_defs[0][0], new_defs[-1][0], last_name))

    # ---- 2. donor names + descriptions per language
    dta = read(dn("src", "data", "text", "abilities.h"))
    m = re.search(r"const u8 gAbilityNames.*?\{(.*?)\n\};", dta, re.S)
    names_body = m.group(1)
    es_names_body, en_names_body = re.split(r"\n#else\n", names_body, 1)
    d_es_names = parse_designated(es_names_body, r'_\("(.*?)"\)')
    d_en_names = parse_designated(en_names_body, r'_\("(.*?)"\)')

    descs = re.findall(
        r"const u8 \*const gAbilityDescriptionPointers.*?\{(.*?)\n\};", dta, re.S)
    assert len(descs) == 2, "expected ES+EN description arrays in donor"
    d_es_descs = parse_designated(descs[0], r'FORMAT_ABILITY_DESCRIPTION\("(.*?)"\)')
    d_en_descs = parse_designated(descs[1], r'FORMAT_ABILITY_DESCRIPTION\("(.*?)"\)')

    missing = [n for n in names_new if n not in d_en_names]
    for n in missing:
        print("WARN no donor EN name for %s" % n)
    for n in names_new:
        en = d_en_names.get(n, "")
        assert len(en) <= 20, (n, en)

    if dry:
        for num, n, c in new_defs:
            print(" %s = %d  EN='%s'" % (n, num, d_en_names.get(n, "?")))
        return

    # ---- 3. our constants header
    path = tgt("include", "constants", "abilities.h")
    text = strip_block(read(path), "consts")
    # drop the pre-existing count line; the marker block re-defines it
    text = re.sub(r"#define ABILITIES_COUNT_GEN8\s+ABILITY_\w+ \+ 1\n", "", text)
    lines = []
    for num, name, comment in new_defs:
        lines.append("#define %-35s %d%s\n" % (name, num, comment))
    lines.append("\n// 2.X renamed id 275; our engine still runs the 1.9.4 "
                 "Early Evolver effect (revisit in ability-effects phase)\n")
    lines.append("#define ABILITY_POWER_SURGE                 "
                 "ABILITY_EARLY_EVOLVER\n")
    lines.append("\n#define ABILITIES_COUNT_GEN8    %s + 1\n" % last_name)
    anchor = "\n#define ABILITIES_COUNT ABILITIES_COUNT_GEN8"
    assert anchor in text
    # No leading "\n": it falls outside the span strip_block removes, so it
    # survives every strip and a new one is added on top. wrap() already ends
    # with a newline, and `anchor` starts its own line, so the spacing is right
    # without it.
    text = text.replace(anchor, wrap("consts", "".join(lines)) + anchor)
    write(path, text)

    # ---- 4. our text file: description statics (ES + EN), names (ES + EN),
    #         pointer entries
    path = tgt("src", "data", "text", "abilities.h")
    text = read(path)
    for tag in ("desc-es", "desc-en", "names-es", "names-en", "ptrs"):
        text = strip_block(text, tag)

    def static_sym(name):
        return "s%sDescription2X" % name[len("ABILITY_"):].title().replace("_", "")

    def desc_block(dmap, fallback):
        out = []
        for n in names_new:
            s = dmap.get(n) or fallback.get(n) or "No data."
            out.append("static const u8 %s[] = _(\"%s\");\n" % (static_sym(n), s))
        return "".join(out)

    def names_block(nmap, fallback):
        out = []
        for n in names_new:
            s = nmap.get(n) or fallback.get(n) or "?????"
            out.append("    [%s] = _(\"%s\"),\n" % (n, s))
        return "".join(out)

    # statics section = first #if/#else/#endif; names array has the second
    # #if/#else pair; single pointer array at the end.
    parts = re.split(r"(?m)^(#if GAME_LANGUAGE == LANGUAGE_SPANISH|#else|#endif)$",
                     text)
    # parts: [pre, '#if', es_desc, '#else', en_desc, '#endif', mid(names decl),
    #         '#if', es_names, '#else', en_names, '#endif', tail(ptr array)]
    assert len(parts) == 13, "unexpected text/abilities.h layout (%d)" % len(parts)
    parts[2] = parts[2].rstrip("\n") + "\n" + wrap("desc-es", desc_block(d_es_descs, d_en_descs))
    parts[4] = parts[4].rstrip("\n") + "\n" + wrap("desc-en", desc_block(d_en_descs, d_es_descs))
    parts[8] = parts[8].rstrip("\n") + "\n" + wrap("names-es", names_block(d_es_names, d_en_names))
    parts[10] = parts[10].rstrip("\n") + "\n" + wrap("names-en", names_block(d_en_names, d_es_names))
    ptr_block = "".join("    [%s] = %s,\n" % (n, static_sym(n)) for n in names_new)
    tail = parts[12]
    close = tail.rfind("};")
    assert close != -1
    parts[12] = tail[:close] + wrap("ptrs", ptr_block) + tail[close:]
    write(path, "".join(parts))
    print("wrote %d ability texts" % len(names_new))


if __name__ == "__main__":
    main()
