#!/usr/bin/env python3
"""Port the ROWE 2.X moves our tree lacks (Gen 9 + Z-moves + ROWE customs).

The donor's move ids agree with ours exactly (0 mismatches on the 754 shared
moves), so these simply append: MOVES_COUNT 755 -> 943.

Each move needs an entry in every MOVES_COUNT-sized array or the tables go
ragged: gBattleMoves, gMoveNames, gMoveDescriptionPointers, gContestMoves,
sBattleStyleMovePoints, sForbiddenMoves.

Move EFFECTS are indices into gBattleScriptsForMoveEffects, so a move whose
donor effect we don't implement would jump into a table we never grew. The 7
such effects are remapped to a close existing effect (see EFFECT_FALLBACK) --
those moves work and hit for the right power/type, but their special behaviour
is approximated until the battle-effects phase implements them properly.

Idempotent via ROWEMOVE marker blocks.
"""
import os
import re
import sys
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR = os.environ.get(
    "ROWEREPO_DONOR", "/home/jbfish00/Documents/RoweRepo-donor")

MS = "// ROWEMOVE-PORT-START {tag} (generated by tools/character_mode/port_2x_moves.py)"
ME = "// ROWEMOVE-PORT-END {tag}"

# donor effects we don't implement -> nearest effect we do (approximation;
# revisit when the battle-effects phase lands)
EFFECT_FALLBACK = {
    "EFFECT_CHILLY_RECEPTION": "EFFECT_HIT",
    "EFFECT_DRACO_METEOR": "EFFECT_OVERHEAT",       # same -2 SpA self-drop
    "EFFECT_GIGATON_HAMMER": "EFFECT_HIT",
    "EFFECT_INVERSE_ROOM": "EFFECT_WONDER_ROOM",
    "EFFECT_MISC_HIT": "EFFECT_HIT",
    "EFFECT_SHED_TAIL": "EFFECT_SUBSTITUTE",
    "EFFECT_TOXIC_WASTE": "EFFECT_TOXIC_SPIKES",
}


def read(p):
    with open(p, encoding="utf-8", errors="ignore") as f:
        return f.read()


def write(p, s):
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


def strip_block(text, tag):
    return re.sub(re.escape(MS.format(tag=tag)) + r".*?" +
                  re.escape(ME.format(tag=tag)) + r"\n?", "", text, flags=re.S)


def wrap(tag, block):
    return "%s\n%s%s\n" % (MS.format(tag=tag), block, ME.format(tag=tag))


def defines(text, prefix):
    text = re.sub(r"//.*", "", text)
    vals = {}
    for m in re.finditer(r"#define (\w+)\s+([^\n]+)", text):
        n, e = m.group(1), m.group(2).strip()
        e2 = re.sub(r"\b([A-Za-z_]\w*)\b",
                    lambda x: str(vals[x.group(1)])
                    if x.group(1) in vals else x.group(1), e)
        try:
            vals[n] = eval(e2)
        except Exception:
            pass
    return {n: v for n, v in vals.items() if n.startswith(prefix)}


def desc_sym(move):
    return "s%s2XDesc" % "".join(
        w.title() for w in move[len("MOVE_"):].split("_"))


def main():
    dry = "--dry-run" in sys.argv
    tgt = lambda *p: os.path.join(TARGET, *p)
    dn = lambda *p: os.path.join(DONOR, *p)

    moves_h = tgt("include/constants/moves.h")
    our_text = strip_block(read(moves_h), "consts")
    ours = defines(our_text, "MOVE_")
    theirs = defines(read(dn("include/constants/moves.h")), "MOVE_")

    conflicts = [n for n in set(ours) & set(theirs) if ours[n] != theirs[n]]
    assert not conflicts, "donor move ids diverge: %s" % conflicts[:5]

    missing = sorted((theirs[n], n) for n in set(theirs) - set(ours))
    if not missing:
        print("nothing to port")
        return
    # ids must be contiguous from our current count, or the arrays go ragged
    start = max(ours.values()) + 1
    ids = [i for i, _ in missing]
    assert ids == list(range(start, start + len(ids))), \
        "donor move ids are not contiguous after ours (%s..)" % ids[:3]

    our_effects = set(re.findall(
        r"#define (EFFECT_\w+)",
        read(tgt("include/constants/battle_move_effects.h"))))
    dmoves = read(dn("src/data/battle_moves.h"))
    dnames = read(dn("src/data/text/move_names.h")) if os.path.isfile(
        dn("src/data/text/move_names.h")) else ""
    ddesc = read(dn("src/data/text/move_descriptions.h"))
    dcontest = read(dn("src/data/contest_moves.h"))

    ports, remapped = [], []
    for _id, mv in missing:
        m = re.search(r"\[%s\] =\s*\{(.*?)\n[ \t]*\},"
                      % re.escape(mv), dmoves, re.S)
        if not m:
            print("SKIP %s: no donor battle_moves entry" % mv)
            continue
        body = m.group(1)
        eff = re.search(r"\.effect = (\w+)", body)
        eff = eff.group(1) if eff else "EFFECT_HIT"
        if eff not in our_effects:
            new_eff = EFFECT_FALLBACK.get(eff, "EFFECT_HIT")
            remapped.append((mv, eff, new_eff))
            body = re.sub(r"(\.effect = )%s\b" % re.escape(eff),
                          r"\g<1>%s" % new_eff, body)
            # .argument is interpreted by the ORIGINAL effect's handler
            # (EFFECT_MISC_HIT reads MISC_EFFECT_* selectors we don't have),
            # so it means nothing once the effect is remapped
            body = re.sub(r"(\.argument = )[^,\n]+", r"\g<1>0", body)

        nm = re.search(r"\[%s\] = _\(\"([^\"]*)\"\)" % mv, dnames)
        name = nm.group(1) if nm else mv[len("MOVE_"):].replace("_", " ").title()

        dm = re.search(r"\[%s(?:\s*-\s*1)?\] = (\w+)," % mv, ddesc)
        dtext = ""
        if dm:
            sm = re.search(r"static const u8 %s\[\] = _\((.*?)\);"
                           % dm.group(1), ddesc, re.S)
            if sm:
                dtext = " ".join(re.findall(r'"([^"]*)"', sm.group(1)))
                dtext = dtext.replace("\\n", " ").replace("\\p", " ")
        if not dtext:
            dtext = "A move used by Pokemon."

        cm = re.search(r"\[%s\] =\s*\{(.*?)\n[ \t]*\},"
                       % re.escape(mv), dcontest, re.S)

        ports.append({
            "move": mv, "id": _id, "body": body.rstrip(),
            "name": name[:16],
            "desc": " ".join(dtext.split()),
            "contest": cm.group(1).rstrip() if cm else None,
        })

    print("porting %d moves (%d effects remapped)" % (len(ports), len(remapped)))
    for mv, old, new in remapped:
        print("   remap %-26s %s -> %s" % (mv, old, new))
    if dry:
        return

    new_count = ports[-1]["id"] + 1

    # ---- 1. constants
    lines = ["#define %-38s %d\n" % (p["move"], p["id"]) for p in ports]
    lines.append("\n#undef MOVES_COUNT\n#define MOVES_COUNT %d\n" % new_count)
    text = strip_block(read(moves_h), "consts")
    m = re.search(r"^#endif", text, re.M)
    write(moves_h, text[:m.start()] + wrap("consts", "".join(lines)) + text[m.start():])

    # ---- 2. gBattleMoves (this file also holds gSignatureMoveList; append to
    # gBattleMoves specifically, not to whatever array happens to be last)
    path = tgt("src/data/battle_moves.h")
    text = strip_block(read(path), "moves")
    m = re.search(r"gBattleMoves\[MOVES_COUNT\] =\s*\{", text)
    last = text.find("\n};", m.end()) + 1
    block = "".join("    [%s] =\n    {%s\n    },\n" % (p["move"], p["body"])
                    for p in ports)
    write(path, text[:last] + wrap("moves", block) + text[last:])

    # ---- 3. names
    path = tgt("src/data/text/move_names.h")
    text = strip_block(read(path), "names")
    last = text.rfind("};")
    block = "".join('    [%s] = _("%s"),\n' % (p["move"], p["name"])
                    for p in ports)
    write(path, text[:last] + wrap("names", block) + text[last:])

    # ---- 4. descriptions: statics + pointer rows
    path = tgt("src/data/text/move_descriptions.h")
    text = strip_block(strip_block(read(path), "descs"), "descptrs")

    def wrap_desc(t):
        lines = textwrap.wrap(t, width=18)[:3]
        return "\n".join('    "%s%s"' % (l, "\\n" if i < len(lines) - 1 else "")
                         for i, l in enumerate(lines))

    statics = "".join("static const u8 %s[] = _(\n%s);\n\n"
                      % (desc_sym(p["move"]), wrap_desc(p["desc"])) for p in ports)
    m = re.search(r"const u8 \*const gMoveDescriptionPointers\[", text)
    text = text[:m.start()] + wrap("descs", statics) + text[m.start():]
    last = text.rfind("};")
    rows = "".join("    [%s - 1] = %s,\n" % (p["move"], desc_sym(p["move"]))
                   for p in ports)
    write(path, text[:last] + wrap("descptrs", rows) + text[last:])

    # ---- 5. contest moves (array is MOVES_COUNT-sized). NB this file also
    # holds gContestEffectFuncs -- append to gContestMoves, not the last array.
    path = tgt("src/data/contest_moves.h")
    text = strip_block(read(path), "contest")
    m = re.search(r"gContestMoves\[MOVES_COUNT\] =\s*\{", text)
    last = text.find("\n};", m.end()) + 1
    block = "".join(
        "    [%s] =\n    {%s\n    },\n" % (
            p["move"],
            p["contest"] if p["contest"] else
            "\n        .effect = CONTEST_EFFECT_HIGHLY_APPEALING,"
            "\n        .contestCategory = CONTEST_CATEGORY_COOL,"
            "\n        .comboStarterId = 0,"
            "\n        .comboMoves = {0},")
        for p in ports)
    write(path, text[:last] + wrap("contest", block) + text[last:])

    # ---- 6. the two MOVES_COUNT-sized arrays inside .c files
    path = tgt("src/battle_script_commands.c")
    text = strip_block(read(path), "forbidden")
    m = re.search(r"sForbiddenMoves\[MOVES_COUNT\] =\s*\{", text)
    close = text.find("\n};", m.end())
    block = "".join("    [%s] = FALSE,\n" % p["move"] for p in ports)
    write(path, text[:close + 1] + wrap("forbidden", block) + text[close + 1:])

    path = tgt("src/battle_dome.c")
    text = strip_block(read(path), "dome")
    m = re.search(r"sBattleStyleMovePoints\[MOVES_COUNT\]\[NUM_MOVE_POINT_TYPES\] =\s*\{",
                  text)
    close = text.find("\n};", m.end())
    block = "".join("    [%s] = {0},\n" % p["move"] for p in ports)
    write(path, text[:close + 1] + wrap("dome", block) + text[close + 1:])

    with open(os.path.join(HERE, "rowe_move_port_report.txt"), "w") as f:
        f.write("Ported %d moves (MOVES_COUNT -> %d)\n\n" % (len(ports), new_count))
        f.write("".join("  %-30s id %d\n" % (p["move"], p["id"]) for p in ports))
        f.write("\nEffects remapped (%d) -- behaviour approximated:\n" % len(remapped))
        f.write("".join("  %-28s %s -> %s\n" % r for r in remapped))
    print("ported %d moves -> run make" % len(ports))


if __name__ == "__main__":
    main()
