#!/usr/bin/env python3
"""Port the ROWE 2.X species our tree genuinely lacks (regional/alt forms).

Complements port_2x_species_aliases.py: whatever is left after aliasing is a
real content gap (Paldean Tauros/Wooper, Ogerpon masks, Squawkabilly colours,
Tatsugiri forms, origin formes, ...). Mirrors port_rowe_megas.py's approach --
append-only species ids, idempotent marker blocks, donor graphics copied and
INCBIN paths reused verbatim -- but discovers its port list by diffing the
donor's species set against ours rather than by scanning for mega evolutions.

Per species: constant, base stats (both tables), display name, natdex mapping
(from the donor's own species->dex table), level-up learnset pointer (reuses
our family base's), evolution rows (only those whose target we have), form
species table membership, base-form id, graphics (front/back/pals/icon), pic
coordinates, single-frame anims, icon palette.

Run after port_2x_species_aliases.py. Idempotent via ROWESPEC marker blocks.
"""
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR = os.environ.get(
    "ROWEREPO_DONOR", "/home/jbfish00/Documents/RoweRepo-donor")

MS = "// ROWESPEC-PORT-START {tag} (generated by tools/character_mode/port_2x_species.py)"
ME = "// ROWESPEC-PORT-END {tag}"


def read(p):
    with open(p, encoding="utf-8", errors="ignore") as f:
        return f.read()


def write(p, s):
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


def strip_block(text, tag):
    return re.sub(re.escape(MS.format(tag=tag)) + r".*?" +
                  re.escape(ME.format(tag=tag)) + r"\n?", "", text, flags=re.S)


def wrap(tag, block):
    return "%s\n%s%s\n" % (MS.format(tag=tag), block, ME.format(tag=tag))


def insert_before_close(path, tag, block, decl_re):
    text = strip_block(read(path), tag)
    m = re.search(decl_re, text, re.M)
    assert m, (path, decl_re)
    close = text.find("\n};", m.end())
    assert close != -1
    write(path, text[:close + 1] + wrap(tag, block) + text[close + 1:])


def main():
    dry = "--dry-run" in sys.argv
    tgt = lambda *p: os.path.join(TARGET, *p)
    dn = lambda *p: os.path.join(DONOR, *p)

    sp_text = strip_block(read(tgt("include/constants/species.h")), "consts")
    our_species = set(re.findall(r"#define (SPECIES_\w+)", sp_text))
    our_natdex = set(re.findall(r"#define (NATIONAL_DEX_\w+)", sp_text))
    donor_species = set(re.findall(
        r"#define (SPECIES_\w+)", read(dn("include/constants/species.h"))))

    # aliases already map donor names onto ours; whatever is left is a real gap
    missing = sorted(s for s in donor_species - our_species
                     if s not in ("SPECIES_EGG", "SPECIES_NONE"))

    dstats = read(dn("src/data/pokemon/base_stats.h"))
    dvs = dn("src/data/pokemon/base_stats_vanilla.h")
    dvstats = read(dvs) if os.path.isfile(dvs) else dstats
    dnames = read(dn("src/data/text/species_names.h"))
    dfcoords = read(dn("src/data/pokemon_graphics/front_pic_coordinates.h"))
    dbcoords = read(dn("src/data/pokemon_graphics/back_pic_coordinates.h"))
    devo = re.sub(r"//.*", "", read(dn("src/data/pokemon/evolution.h")))

    # our alias map, so donor names resolve to our constants where they exist
    alias = dict(re.findall(r"#define (SPECIES_\w+)\s+(SPECIES_\w+)", sp_text))
    canon = lambda s: alias.get(s, s)

    # The donor ships no engine .c and no gBaseFormID, so derive each form's
    # family base from its donor form table (member 0 is the base), falling
    # back to stripping form suffixes until a species we know appears.
    dformtable = read(dn("src/data/pokemon/form_species_table.h"))
    donor_baseform = {}
    for tm in re.finditer(r"static const u16 s\w+FormSpeciesIdTable\[\] = \{(.*?)\};",
                          dformtable, re.S):
        members = re.findall(r"(SPECIES_\w+)", tm.group(1))
        for mem in members[1:]:
            donor_baseform.setdefault(mem, members[0])

    def family_base(sp):
        b = canon(donor_baseform.get(sp, ""))
        if b in our_species:
            return b
        parts = sp.split("_")
        while len(parts) > 2:
            parts = parts[:-1]
            cand = canon("_".join(parts))
            if cand in our_species:
                return cand
        return None

    # Symbol names don't track species names (TAUROS_PALDEA_COMBAT ->
    # gMonFrontPic_Tauros_Paldean_Combat_Breed), so read the donor's own pic
    # tables rather than guessing, then map symbol -> INCBIN path.
    donor_gfx = read(dn("src/data/graphics/pokemon.h"))
    sym_path = dict(re.findall(
        r"(gMon(?:FrontPic|BackPic|Palette|ShinyPalette|Icon)_\w+)\[\]"
        r" = INCBIN_U(?:32|8)\(\"([^\"]+)\"\)", donor_gfx))
    # strip our own generated block first: on a re-run its symbols would look
    # pre-existing, and the script would emit no INCBINs for them at all
    our_gfx = strip_block(read(tgt("src/data/graphics/pokemon.h")), "incbins")
    our_syms = set(re.findall(
        r"(gMon(?:FrontPic|BackPic|Palette|ShinyPalette|Icon)_\w+)\[\]", our_gfx))

    def table_syms(relpath, macro):
        return dict(re.findall(
            r"%s\((\w+),\s*(gMon\w+)\)" % macro, read(dn(relpath))))

    dfront = table_syms("src/data/pokemon_graphics/front_pic_table.h", "SPECIES_SPRITE")
    dback = table_syms("src/data/pokemon_graphics/back_pic_table.h", "SPECIES_SPRITE")
    dpal = table_syms("src/data/pokemon_graphics/palette_table.h", "SPECIES_PAL")
    dshiny = table_syms("src/data/pokemon_graphics/shiny_palette_table.h", "SPECIES_PAL")

    def our_table_syms(relpath, macro, tag):
        return dict(re.findall(
            r"%s\((\w+),\s*(gMon\w+)\)" % macro,
            strip_block(read(tgt(relpath)), tag)))

    # fallback when the donor's tables don't list the form at all
    ourfront = our_table_syms("src/data/pokemon_graphics/front_pic_table.h",
                              "SPECIES_SPRITE", "front")
    ourback = our_table_syms("src/data/pokemon_graphics/back_pic_table.h",
                             "SPECIES_SPRITE", "back")
    ourpal = our_table_syms("src/data/pokemon_graphics/palette_table.h",
                            "SPECIES_PAL", "pal")
    ourshiny = our_table_syms("src/data/pokemon_graphics/shiny_palette_table.h",
                              "SPECIES_SHINY_PAL", "shiny")

    def camel(const):
        return "".join(w.title() for w in const[len("SPECIES_"):].split("_"))

    lu = read(tgt("src/data/pokemon/level_up_learnset_pointers.h"))
    our_names = read(tgt("src/data/text/species_names.h"))

    report, ports = [], []
    for sp in missing:
        cam = camel(sp)
        key = sp[len("SPECIES_"):]
        # family base, resolved to our naming; a form shares its base's dex no.
        base = family_base(sp)
        if not base:
            report.append("SKIP %-34s cannot resolve family base" % sp)
            continue

        # Base stats: the donor declares some forms without a gBaseStats entry
        # (cosmetic variants like the Squawkabilly colours). Inherit our base
        # species' stats for those -- they're stat-identical by definition.
        entry_re = r"\[%s\]\s*=\s*(?://[^\n]*)?\s*\{(.*?)\n[ \t]*\}\s*," % sp
        sm = re.search(entry_re, dstats, re.S)
        inherited = False
        if not sm:
            our_stats = read(tgt("src/data/pokemon/base_stats.h"))
            sm = re.search(
                r"\[%s\]\s*=\s*(?://[^\n]*)?\s*\{(.*?)\n[ \t]*\}\s*," % base,
                our_stats, re.S)
            if not sm:
                report.append("SKIP %-34s no base stats (donor or ours)" % sp)
                continue
            inherited = True
        # the base may itself be a named form (MAGEARNA_ORIGINAL_COLOR); the dex
        # number lives on the plain species, so walk the suffix back
        suf = base[len("SPECIES_"):].split("_")
        while suf and ("NATIONAL_DEX_" + "_".join(suf)) not in our_natdex:
            suf = suf[:-1]
        if not suf:
            report.append("SKIP %-34s no natdex for base %s" % (sp, base))
            continue
        nd = "NATIONAL_DEX_" + "_".join(suf)

        # Resolve the 5 graphics symbols. The donor points some forms at a
        # placeholder (gMonFrontPic_CircledQuestionMark); for those, and for
        # anything unresolvable, fall back to the family base's own sprite.
        bkey = base[len("SPECIES_"):]
        gsyms, copies, bad = {}, [], False
        for kind, table, ourtable in (("front", dfront, ourfront),
                                      ("back", dback, ourback),
                                      ("pal", dpal, ourpal),
                                      ("shiny", dshiny, ourshiny)):
            sym = table.get(key)
            if not sym or "CircledQuestionMark" in sym:
                sym = table.get(bkey) or ourtable.get(bkey)
            if not sym:
                bad = True
                break
            if sym not in our_syms:          # new asset: copy it in, INCBIN it
                path = sym_path.get(sym)
                srcfile = dn(path.replace(".4bpp.lz", ".png")
                                 .replace(".gbapal.lz", ".pal")
                                 .replace(".4bpp", ".png")) if path else None
                if not path or not os.path.isfile(srcfile):
                    sym = table.get(bkey)    # donor lists it but ships no file
                    if not sym or sym not in our_syms:
                        bad = True
                        break
                else:
                    copies.append((srcfile, tgt(os.path.dirname(path)),
                                   os.path.basename(srcfile)))
            gsyms[kind] = sym
        if bad:
            report.append("SKIP %-34s cannot resolve graphics" % sp)
            continue
        # icon: donor ships no icon table (no .c), so match the front symbol's
        # stem, else reuse the base's icon.
        istem = gsyms["front"][len("gMonFrontPic_"):]
        isym = "gMonIcon_" + istem
        if isym not in our_syms and isym not in sym_path:
            isym = "gMonIcon_" + camel(base)
        if isym not in our_syms:
            ipath = sym_path.get(isym)
            isrc = dn(ipath.replace(".4bpp", ".png")) if ipath else None
            if isrc and os.path.isfile(isrc):
                copies.append((isrc, tgt(os.path.dirname(ipath)),
                               os.path.basename(isrc)))
            else:
                isym = "gMonIcon_" + camel(base)
        gsyms["icon"] = isym

        svm = re.search(entry_re, dvstats, re.S)
        nm = re.search(r"\[%s\] = _\(\"([^\"]+)\"\)" % sp, dnames)
        bn = re.search(r"\[%s\] = _\(\"([^\"]+)\"\)" % base, our_names)
        fc = re.search(r"\[%s\][^}]*?\.size = ([^,]+),\s*\.y_offset = ([^,}]+)" % sp,
                       dfcoords, re.S)
        bc = re.search(r"\[%s\][^}]*?\.size = ([^,]+),\s*\.y_offset = ([^,}]+)" % sp,
                       dbcoords, re.S)
        lm = re.search(r"\[%s\] = (\w+)," % base, lu)

        # evolutions FROM this species, keeping only targets we can resolve
        evos = []
        em = re.search(
            r"\[%s\]\s*=\s*((?:\{\{.*?\}\})|(?:\{\{.*?\}[,\s]*)+\})" % sp, devo, re.S)
        if em:
            for e in re.finditer(r"\{(EVO_\w+),\s*([\w()]+),\s*(SPECIES_\w+)\}",
                                 em.group(1)):
                tgt_sp = canon(e.group(3))
                if tgt_sp in our_species:
                    evos.append("{%s, %s, %s}" % (e.group(1), e.group(2), tgt_sp))

        ports.append({
            "sp": sp, "camel": cam, "base": base,
            "stats": sm.group(1),
            "vstats": svm.group(1) if svm else sm.group(1),
            "natdex": nd,
            "name": (nm.group(1) if nm else
                     (bn.group(1) if bn else cam))[:10],
            "syms": gsyms, "copies": copies,
            "fcoords": (fc.group(1).strip(), fc.group(2).strip()) if fc else ("0x88", "0"),
            "bcoords": (bc.group(1).strip(), bc.group(2).strip()) if bc else ("0x88", "0"),
            "learnset": lm.group(1) if lm else "sBulbasaurLevelUpLearnset",
            "evos": evos,
        })

    print("porting %d species; %d skipped" % (len(ports), len(report)))
    with open(os.path.join(HERE, "rowe_species_port_report.txt"), "w") as f:
        f.write("Ported (%d):\n" % len(ports))
        f.write("".join("  %-36s base %-28s dex %s%s\n"
                        % (p["sp"], p["base"], p["natdex"],
                           "  evo->" + ",".join(p["evos"]) if p["evos"] else "")
                        for p in ports))
        f.write("\nSkipped (%d):\n  " % len(report) + "\n  ".join(report) + "\n")
    if dry:
        for p in ports:
            print("  %-36s base=%-26s name=%s" % (p["sp"], p["base"], p["name"]))
        return
    if not ports:
        return

    ports.sort(key=lambda p: p["sp"])

    # ---- 1. species constants (chain off the mega block's last id)
    path = tgt("include/constants/species.h")
    text = strip_block(read(path), "consts")
    m = re.search(r"#define (SPECIES_\w+) \(ROWE_MEGA_START \+ (\d+)\)(?!.*ROWE_MEGA_START)",
                  text, re.S)
    assert m, "mega block not found -- run port_rowe_megas.py first"
    last_mega = m.group(1)
    lines = ["#define ROWE_SPECIES_START %s" % last_mega]
    new_ids = {p["sp"]: i for i, p in enumerate(ports, 1)}

    # ⚠️ IDS ARE ASSIGNED POSITIONALLY FROM AN ALPHABETICALLY SORTED LIST, so a
    # single new donor species sorting early would shift every id after it.
    # Standing rule 3: NEVER renumber existing ids -- a save stores the species
    # number, and renumbering corrupts every existing save. Nothing enforced
    # that here; the sprite importers hold their ids fixed and these porters did
    # not. Compare against what is already committed and refuse rather than
    # silently re-number.
    prev = {mm.group(1): int(mm.group(2)) for mm in
            re.finditer(r"#define (SPECIES_\w+) \(ROWE_SPECIES_START \+ (\d+)\)",
                        read(path))}
    moved = sorted((n, prev[n], new_ids[n]) for n in prev
                   if n in new_ids and prev[n] != new_ids[n])
    dropped = sorted(n for n in prev if n not in new_ids)
    if moved or dropped:
        for n, o, w in moved[:10]:
            print("  RENUMBERED %-40s %d -> %d" % (n, o, w))
        for n in dropped[:10]:
            print("  DROPPED    %s" % n)
        raise SystemExit(
            "port_2x_species: refusing to write -- %d existing species would be "
            "renumbered and %d dropped. A save stores the species NUMBER, so "
            "this corrupts every existing save (standing rule 3, append-only). "
            "Append the new entries after the existing ids instead."
            % (len(moved), len(dropped)))

    for i, p in enumerate(ports, 1):
        lines.append("#define %s (ROWE_SPECIES_START + %d)" % (p["sp"], i))
    lines += ["#undef SPECIES_EGG", "#undef NUM_SPECIES",
              "#define SPECIES_EGG (%s + 1)" % ports[-1]["sp"],
              "#define NUM_SPECIES SPECIES_EGG"]
    anchor = "// ROWEMEGA-PORT-END consts"
    # Step past the anchor's OWN newline rather than emitting one before the
    # block: strip_block only consumes START..END plus one trailing newline, so
    # a leading "\n" here survives every strip and stacks up a blank line per
    # run (11 of them had accumulated in species.h). See port_gen9.insert_block.
    pos = text.index(anchor) + len(anchor)
    if text[pos:pos + 1] == "\n":
        pos += 1
    write(path, text[:pos] + wrap("consts", "\n".join(lines) + "\n") +
          text[pos:])

    # ---- 2. base stats, both tables
    our_fields = set(re.findall(r"\.\s*(\w+)\s*=",
                     read(tgt("src/data/pokemon/base_stats.h"))[:8000]))

    def stats_entry(p, key):
        body = []
        for line in p[key].splitlines():
            fm = re.match(r"\s*\.(\w+)\s*=", line)
            if fm and fm.group(1) not in our_fields:
                continue
            if line.strip():
                body.append("        " + line.strip())
        return "    [%s] =\n    {\n%s\n    },\n" % (p["sp"], "\n".join(body))

    bs = tgt("src/data/pokemon/base_stats.h")
    text = strip_block(strip_block(read(bs), "gbasestats"), "vanillastats")
    vm = re.search(r"^const struct BaseStats gVanillaBaseStats\[\] =", text, re.M)
    close = text.rfind("};", 0, vm.start())
    text = (text[:close] + wrap("gbasestats", "".join(stats_entry(p, "stats")
                                                      for p in ports)) + text[close:])
    last = text.rfind("};")
    text = (text[:last] + wrap("vanillastats", "".join(stats_entry(p, "vstats")
                                                       for p in ports)) + text[last:])
    write(bs, text)

    # ---- 3. names / natdex / learnset pointers
    insert_before_close(tgt("src/data/text/species_names.h"), "names",
                        "".join('    [%s] = _("%s"),\n' % (p["sp"], p["name"])
                                for p in ports),
                        r"gSpeciesNames\[")
    path = tgt("src/pokemon.c")
    text = strip_block(read(path), "spec2nat")
    m = re.search(r"gSpeciesToNationalPokedexNum\[[^\]]*\][^{]*\{", text)
    close = text.find("};", m.end())
    block = "".join("    [%s - 1] = %s,\n" % (p["sp"], p["natdex"]) for p in ports)
    write(path, text[:close] + wrap("spec2nat", block) + text[close:])

    insert_before_close(tgt("src/data/pokemon/level_up_learnset_pointers.h"),
                        "learnptrs",
                        "".join("    [%s] = %s,\n" % (p["sp"], p["learnset"])
                                for p in ports),
                        r"gLevelUpLearnsets\[")

    # ---- 4. evolution rows for the new species (as evolution sources)
    path = tgt("src/data/pokemon/evolution.h")
    text = strip_block(read(path), "evolutions")
    evo_lines = []
    for p in ports:
        if p["evos"] and not re.search(r"^\s*\[%s\]\s*=" % p["sp"], text, re.M):
            evo_lines.append("    [%s] = {%s},\n"
                             % (p["sp"], ",\n                    ".join(p["evos"])))
    m = re.search(r"const struct SpeciesList gFirstStageTable", text)
    close = text.rfind("};", 0, m.start())
    write(path, text[:close] + wrap("evolutions", "".join(evo_lines)) + text[close:])

    # ---- 5. form tables: add each new form to its family's existing table
    ptr_text = read(tgt("src/data/pokemon/form_species_table_pointers.h"))
    existing_table = dict(re.findall(
        r"\[(SPECIES_\w+)\]\s*=\s*(s\w+FormSpeciesIdTable)", ptr_text))

    path = tgt("src/data/pokemon/form_species_table.h")
    text = strip_block(read(path), "formtables")
    new_tables, table_of = {}, {}
    for p in ports:
        sym = existing_table.get(p["base"])
        if not sym:
            sym = "s%sFormSpeciesIdTable" % camel(p["base"])
        table_of[p["sp"]] = sym
        tm = re.search(r"static const u16 %s\[\] = \{(.*?)\};" % sym, text, re.S)
        if tm:
            if p["sp"] not in tm.group(1):
                nb = re.sub(r"([ \t]*)0xFFFF", r"\g<1>%s,\n\g<1>0xFFFF" % p["sp"],
                            tm.group(1), count=1)
                text = text[:tm.start(1)] + nb + text[tm.end(1):]
        elif sym in new_tables:
            new_tables[sym] = new_tables[sym].replace(
                "    0xFFFF", "    %s,\n    0xFFFF" % p["sp"], 1)
        else:
            new_tables[sym] = ("static const u16 %s[] = {\n    %s,\n    %s,\n"
                               "    0xFFFF,\n};\n" % (sym, p["base"], p["sp"]))
    text += wrap("formtables", "".join(new_tables.values()))
    write(path, text)

    path = tgt("src/data/pokemon/form_species_table_pointers.h")
    text = strip_block(strip_block(read(path), "formptrs"), "baseforms")
    ptr_lines, emitted = [], set()
    for p in ports:
        ptr_lines.append("    [%s] = %s,\n" % (p["sp"], table_of[p["sp"]]))
        if (p["base"] not in emitted
                and not re.search(r"\[%s\] = s\w+FormSpeciesIdTable" % p["base"], text)):
            ptr_lines.append("    [%s] = %s,\n" % (p["base"], table_of[p["sp"]]))
            emitted.add(p["base"])
    m = re.search(r"gFormSpeciesIdTables\[[^\]]*\][^{]*\{", text)
    close = text.find("};", m.end())
    text = text[:close] + wrap("formptrs", "".join(ptr_lines)) + text[close:]
    m = re.search(r"gBaseFormID\[[^\]]*\][^{]*\{", text)
    close = text.find("};", m.end())
    block = "".join("    [%s] = %s,\n" % (p["sp"], p["base"]) for p in ports)
    write(path, text[:close] + wrap("baseforms", block) + text[close:])

    # ---- 6. graphics: copy new assets, INCBIN/extern only the new symbols,
    # and point the tables at whatever symbol we resolved (often an existing
    # one -- e.g. Squawkabilly colours all reuse the base sprite).
    for p in ports:
        for src, dstdir, fname in p["copies"]:
            os.makedirs(dstdir, exist_ok=True)
            dst = os.path.join(dstdir, fname)
            if os.path.isfile(dst):
                continue
            if fname.endswith(".pal"):
                # gbagfx rejects LF-terminated JASC palettes; some donor pals
                # are LF, so normalize to CRLF on the way in
                data = open(src, "rb").read().replace(b"\r\n", b"\n")
                open(dst, "wb").write(data.replace(b"\n", b"\r\n"))
            else:
                shutil.copyfile(src, dst)

    new_syms, incbins, externs = set(), [], []
    for p in ports:
        for kind in ("front", "back", "pal", "shiny", "icon"):
            sym = p["syms"][kind]
            if sym in our_syms or sym in new_syms:
                continue
            new_syms.add(sym)
            path = sym_path[sym]
            ctype = "u8" if kind == "icon" else "u32"
            incbins.append('const %s %s[] = INCBIN_U%s("%s");\n'
                           % (ctype, sym, ctype[1:], path))
            externs.append("extern const %s %s[];\n" % (ctype, sym))

    path = tgt("src/data/graphics/pokemon.h")
    text = strip_block(read(path), "incbins")
    write(path, text.rstrip("\n") + "\n\n" + wrap("incbins", "".join(incbins)))

    path = tgt("include/graphics.h")
    text = strip_block(read(path), "externs")
    m = re.search(r"^#endif", text, re.M)
    write(path, text[:m.start()] + wrap("externs", "".join(externs)) + text[m.start():])

    insert_before_close(tgt("src/data/pokemon_graphics/front_pic_table.h"), "front",
                        "".join("    SPECIES_SPRITE(%s, %s),\n"
                                % (p["sp"][len("SPECIES_"):], p["syms"]["front"])
                                for p in ports), r"gMonFrontPicTable\[")
    insert_before_close(tgt("src/data/pokemon_graphics/back_pic_table.h"), "back",
                        "".join("    SPECIES_SPRITE(%s, %s),\n"
                                % (p["sp"][len("SPECIES_"):], p["syms"]["back"])
                                for p in ports), r"gMonBackPicTable\[")
    insert_before_close(tgt("src/data/pokemon_graphics/palette_table.h"), "pal",
                        "".join("    SPECIES_PAL(%s, %s),\n"
                                % (p["sp"][len("SPECIES_"):], p["syms"]["pal"])
                                for p in ports), r"gMonPaletteTable\[")
    insert_before_close(tgt("src/data/pokemon_graphics/shiny_palette_table.h"), "shiny",
                        "".join("    SPECIES_SHINY_PAL(%s, %s),\n"
                                % (p["sp"][len("SPECIES_"):], p["syms"]["shiny"])
                                for p in ports), r"gMonShinyPaletteTable\[")
    insert_before_close(tgt("src/data/pokemon_graphics/front_pic_coordinates.h"),
                        "fcoords",
                        "".join("    [%s] = {.size = %s, .y_offset = %s},\n"
                                % (p["sp"], p["fcoords"][0], p["fcoords"][1])
                                for p in ports), r"gMonFrontPicCoords\[")
    insert_before_close(tgt("src/data/pokemon_graphics/back_pic_coordinates.h"),
                        "bcoords",
                        "".join("    [%s] = {.size = %s, .y_offset = %s},\n"
                                % (p["sp"], p["bcoords"][0], p["bcoords"][1])
                                for p in ports), r"gMonBackPicCoords\[")
    # single-frame anim per species + ptr table entries (same shape as the
    # mega port -- gMonFrontAnimsPtrTable needs a real array per species)
    anim_defs = "".join(
        "static const union AnimCmd sAnim_%(s)s_1[] =\n{\n"
        "    ANIMCMD_FRAME(0, 1),\n    ANIMCMD_END,\n};\n"
        "static const union AnimCmd *const sAnims_%(s)s[] ={\n"
        "    sAnim_GeneralFrame0,\n    sAnim_%(s)s_1,\n};\n"
        % {"s": p["sp"][len("SPECIES_"):]} for p in ports)
    path = tgt("src/data/pokemon_graphics/front_pic_anims.h")
    text = strip_block(strip_block(read(path), "animdefs"), "anims")
    m = re.search(r"const union AnimCmd \*const \*const gMonFrontAnimsPtrTable", text)
    text = text[:m.start()] + wrap("animdefs", anim_defs) + text[m.start():]
    m = re.search(r"gMonFrontAnimsPtrTable\[[^\]]*\][^{]*\{", text)
    close = text.find("};", m.end())
    block = "".join("    [%s] = sAnims_%s,\n" % (p["sp"], p["sp"][len("SPECIES_"):])
                    for p in ports)
    write(path, text[:close] + wrap("anims", block) + text[close:])

    # icons: table + palette index (reuse the family base's palette slot)
    path = tgt("src/pokemon_icon.c")
    text = strip_block(strip_block(read(path), "icons"), "iconpals")
    ipals = dict(re.findall(r"\[(SPECIES_\w+)\]\s*=\s*(\d+)", text))
    m = re.search(r"gMonIconTable\[[^\]]*\][^{]*\{", text)
    close = text.find("};", m.end())
    block = "".join("    [%s] = %s,\n" % (p["sp"], p["syms"]["icon"])
                    for p in ports)
    text = text[:close] + wrap("icons", block) + text[close:]
    m = re.search(r"gMonIconPaletteIndices\[[^\]]*\][^{]*\{", text)
    close = text.find("};", m.end())
    block = "".join("    [%s] = %s,\n" % (p["sp"], ipals.get(p["base"], "0"))
                    for p in ports)
    text = text[:close] + wrap("iconpals", block) + text[close:]
    write(path, text)

    print("ported %d species -> run make" % len(ports))


if __name__ == "__main__":
    main()
