#!/usr/bin/env python3
"""Port ROWE 2.X trainer parties (2.X balancing) onto our trainer structs.

The donor unified its four TrainerMon* structs into one `struct TrainerMon`.
Our engine still switches on partyFlags across four variants, so rather than
rewrite CreateNPCTrainerParty, every ported party is emitted as our superset
variant (TrainerMonItemCustomMoves) and its trainer is flagged
CUSTOM_MOVESET|HELD_ITEM. That is safe because the engine's custom-moveset
path explicitly tolerates partially-filled move arrays ("you can add custom
moves without needing to fill everything") and a zero heldItem.

Only parties whose species/moves/items all exist here are taken; a party with
an unknown species is left at our existing version rather than half-ported.
Donor `.nature` and `.style` are carried into our struct (a .style field was
added for exactly this): 2.X trainer data assigns Battle Styles per mon, so
the data lands now even though the styles engine is a later phase.

Idempotent: rewrites src/data/trainer_parties.h between ROWETRN markers and
patches the matching trainer entries in src/data/trainers.h in place.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR = os.environ.get(
    "ROWEREPO_DONOR", "/home/jbfish00/Documents/RoweRepo-donor")

MS = "// ROWETRN-PORT-START (generated by tools/character_mode/port_2x_trainers.py)"
ME = "// ROWETRN-PORT-END"

SCALARS = ("lvl", "abilityNum", "happiness", "species", "formId",
           "postgameheldItem", "heldItem", "pokeball", "isShiny",
           "exioliteBoost", "nature", "style")
ARRAYS = ("evs", "moves", "postgamemoves")


def read(p):
    with open(p, encoding="utf-8", errors="ignore") as f:
        return f.read()


def write(p, s):
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


def main():
    dry = "--dry-run" in sys.argv
    tgt = lambda *p: os.path.join(TARGET, *p)
    dn = lambda *p: os.path.join(DONOR, *p)

    known = set()
    for root, _d, files in os.walk(tgt("include")):
        for fn in files:
            if fn.endswith(".h"):
                known |= set(re.findall(r"\b[A-Z][A-Z0-9_]{2,}\b",
                                        read(os.path.join(root, fn))))

    def resolvable(expr):
        for tok in re.findall(r"\b[A-Za-z_]\w*\b", expr):
            if not tok.isdigit() and tok not in known:
                return False
        return True

    dparties = re.sub(r"//.*", "", read(dn("src/data/trainer_parties.h")))
    # expand the donor's GENERIC_MON(x) shorthand
    dparties = re.sub(
        r"GENERIC_MON\(\s*(\w+)\s*\)",
        r"{ .lvl = 1, .abilityNum = 3, .species = \1, }", dparties)

    our_parties_text = read(tgt("src/data/trainer_parties.h"))
    our_syms = set(re.findall(r"static const struct \w+ (sParty_\w+)\[\]",
                              our_parties_text))

    ported, skipped, styles = [], [], 0
    for m in re.finditer(
            r"static const struct TrainerMon (sParty_\w+)\[\] = \{(.*?)\n\};",
            dparties, re.S):
        sym, body = m.group(1), m.group(2)
        if sym not in our_syms:
            skipped.append((sym, "no such party in our tree"))
            continue

        mons, bad = [], None
        for mm in re.finditer(r"\{(.*?)\}(?=\s*,\s*(?:\{|$)|\s*$)", body, re.S):
            mb = mm.group(1)
            if not mb.strip():
                continue
            mon = {}
            for f in SCALARS:
                fm = re.search(r"\.%s\s*=\s*([^,\n{]+)" % f, mb)
                if fm:
                    mon[f] = fm.group(1).strip().rstrip(",").strip()
            for f in ARRAYS:
                # Braced normally, but a handful of donor entries are written
                # unbraced (".moves = MOVE_POUND, MOVE_LEER, ...") -- which is
                # not even valid C. Accept both and re-brace.
                am = re.search(r"\.%s\s*=\s*(\{[^}]*\})" % f, mb)
                if am:
                    mon[f] = am.group(1)
                    continue
                am = re.search(r"\.%s\s*=\s*([^\n{]+?)(?=\n\s*[.}])" % f, mb, re.S)
                if am:
                    items = [x.strip() for x in am.group(1).split(",") if x.strip()]
                    if items:
                        mon[f] = "{%s}" % ", ".join(items)
            if "species" not in mon:
                continue
            if "style" in mon:
                styles += 1
            for k, v in mon.items():
                if not resolvable(v):
                    bad = "%s=%s" % (k, v)
                    break
            if bad:
                break
            mons.append(mon)

        if bad or not mons:
            skipped.append((sym, bad or "no mons parsed"))
            continue
        ported.append((sym, mons))

    print("trainer parties: %d ported, %d skipped (%d mons carried a Battle "
          "Style, dropped)" % (len(ported), len(skipped), styles))
    if dry:
        for s, why in skipped[:15]:
            print("   SKIP %-34s %s" % (s, why))
        return

    # ---- 1. rewrite the party arrays
    out = []
    for sym, mons in ported:
        out.append("static const struct TrainerMonItemCustomMoves %s[] = {\n" % sym)
        for mon in mons:
            out.append("    {\n")
            out.append("    .iv = 0,\n")
            out.append("    .lvl = %s,\n" % mon.get("lvl", "1"))
            out.append("    .evs = %s,\n" % mon.get("evs", "{0, 0, 0, 0, 0, 0}"))
            out.append("    .abilityNum = %s,\n" % mon.get("abilityNum", "3"))
            out.append("    .happiness = %s,\n" % mon.get("happiness", "0"))
            out.append("    .species = %s,\n" % mon["species"])
            out.append("    .formId = %s,\n" % mon.get("formId", "0"))
            out.append("    .postgameheldItem = %s,\n"
                       % mon.get("postgameheldItem", "ITEM_NONE"))
            out.append("    .heldItem = %s,\n" % mon.get("heldItem", "ITEM_NONE"))
            out.append("    .postgamemoves = %s,\n"
                       % mon.get("postgamemoves", "{MOVE_NONE, MOVE_NONE, MOVE_NONE, MOVE_NONE}"))
            out.append("    .moves = %s,\n"
                       % mon.get("moves", "{MOVE_NONE, MOVE_NONE, MOVE_NONE, MOVE_NONE}"))
            out.append("    .pokeball = %s,\n" % mon.get("pokeball", "0"))
            out.append("    .isShiny = %s,\n" % mon.get("isShiny", "FALSE"))
            out.append("    .exioliteBoost = %s,\n" % mon.get("exioliteBoost", "FALSE"))
            out.append("    .hiddenNature = %s,\n" % mon.get("nature", "0"))
            out.append("    .style = %s,\n" % mon.get("style", "STYLE_BALANCED"))
            out.append("    },\n")
        out.append("};\n\n")

    text = read(tgt("src/data/trainer_parties.h"))
    text = re.sub(re.escape(MS) + r".*?" + re.escape(ME) + r"\n?", "", text, flags=re.S)
    # drop our old definitions of the parties we're replacing
    for sym, _mons in ported:
        text = re.sub(
            r"static const struct \w+ %s\[\] = \{.*?\n\};\n*" % re.escape(sym),
            "", text, flags=re.S)
    text = text.rstrip("\n") + "\n\n%s\n%s%s\n" % (MS, "".join(out), ME)
    write(tgt("src/data/trainer_parties.h"), text)

    # ---- 2. point the trainers at them with the right flags/union member
    ported_syms = {s for s, _ in ported}
    sizes = {s: len(m) for s, m in ported}
    ttext = read(tgt("src/data/trainers.h"))
    patched = 0

    def fix_entry(m):
        nonlocal patched
        entry = m.group(0)
        pm = re.search(r"\.party = \{\.(\w+) = (sParty_\w+)\}", entry)
        if not pm or pm.group(2) not in ported_syms:
            return entry
        sym = pm.group(2)
        entry = re.sub(r"\.partyFlags = [^,]*,",
                       ".partyFlags = F_TRAINER_PARTY_CUSTOM_MOVESET | F_TRAINER_PARTY_HELD_ITEM,",
                       entry, count=1)
        entry = re.sub(r"\.partySize = [^,]*,",
                       ".partySize = %d," % sizes[sym], entry, count=1)
        entry = re.sub(r"\.party = \{\.\w+ = %s\}" % sym,
                       ".party = {.ItemCustomMoves = %s}" % sym, entry, count=1)
        patched += 1
        return entry

    ttext = re.sub(r"\[TRAINER_\w+\]\s*=\s*\{.*?\n    \},", fix_entry, ttext, flags=re.S)
    write(tgt("src/data/trainers.h"), ttext)

    with open(os.path.join(HERE, "rowe_trainer_port_report.txt"), "w") as f:
        f.write("Ported %d trainer parties (%d trainer entries repointed)\n"
                % (len(ported), patched))
        f.write("%d mons carried a 2.X Battle Style (.style) -- dropped, no "
                "engine support yet\n\nSkipped (%d):\n" % (styles, len(skipped)))
        for s, why in skipped:
            f.write("  %-36s %s\n" % (s, why))
    print("ported %d parties, repointed %d trainers -> run make"
          % (len(ported), patched))


if __name__ == "__main__":
    main()
