#!/usr/bin/env python3
"""Port ROWE 2.X's signature-move table onto our engine's struct.

Our engine is the SAME system at an earlier revision: it already reads a
gSignatureMoveList and implements most SIGNATURE_MOD_* types, but with the
effect slots as flat fields (modification/variable/argument/chance x6) and
only 138 species filled in. The donor's list is the later shape -- 332
species, effects nested in a moveEffect[] array, plus an unlockedLevel -- so
this translates nested -> flat rather than replacing the engine.

Mods our engine doesn't implement are dropped per-slot (the rest of the
entry still applies) and reported, so the summary can list exactly which
moves are only partially faithful to 2.X.

unlockedLevel is not carried over: our struct has no such field and every
consumer keys off (species, move) alone, so signatures are always active --
same as our existing 138 entries behave today.

Idempotent: regenerates the whole gSignatureMoveList block in
src/data/battle_moves.h between the ROWESIG markers.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR = os.environ.get(
    "ROWEREPO_DONOR", "/home/jbfish00/Documents/RoweRepo-donor")

MS = "// ROWESIG-PORT-START (generated by tools/character_mode/port_2x_signature_moves.py)"
ME = "// ROWESIG-PORT-END"

# mods our battle code actually acts on (see include/pokemon.h + battle_util.c)
IMPLEMENTED_MODS = {
    "SIGNATURE_MOD_NONE", "SIGNATURE_MOD_OTHER", "SIGNATURE_MOD_POWER",
    "SIGNATURE_MOD_ACCURACY", "SIGNATURE_MOD_TYPE", "SIGNATURE_MOD_EFFECT_CHANCE",
    "SIGNATURE_MOD_DAMAGE_STAT", "SIGNATURE_MOD_PRIORITY", "SIGNATURE_MOD_PSS_CHANGE",
    "SIGNATURE_MOD_SE_AGAINST_TYPE", "SIGNATURE_MOD_SECOND_TYPE",
    "SIGNATURE_MOD_MODIFY_FIELD", "SIGNATURE_MOD_ATTACKER_STAT_UP",
    "SIGNATURE_MOD_TARGET_STAT_DOWN", "SIGNATURE_MOD_SECONDARY_EFFECT",
    "SIGNATURE_MOD_DEFENSE_STAT", "SIGNATURE_MOD_PENETRATING",
    # added for the 2.X port:
    "SIGNATURE_MOD_EFFECT_CHANGE", "SIGNATURE_MOD_CHANGE_TARGET",
    "SIGNATURE_MOD_NEUTRAL_AGAINST_TYPE", "SIGNATURE_MOD_MULTI_HIT_ALWAYS",
    "SIGNATURE_MOD_MULTI_HIT_MIN_TIMES", "SIGNATURE_MOD_MULTI_HIT_MAX_TIMES",
    "SIGNATURE_MOD_ADD_FLAG", "SIGNATURE_MOD_REMOVE_FLAG",
    "SIGNATURE_MOD_SPEED",
}
# secondary effects our SIGNATURE_MOD_SECONDARY_EFFECT switch handles
IMPLEMENTED_SECONDARY = {
    "SIGNATURE_SECONDARY_EFFECT_NONE", "SIGNATURE_SECONDARY_EFFECT_POISON",
    "SIGNATURE_SECONDARY_EFFECT_TOXIC", "SIGNATURE_SECONDARY_EFFECT_PARALYSIS",
    "SIGNATURE_SECONDARY_EFFECT_BURN", "SIGNATURE_SECONDARY_EFFECT_FREEZE",
    "SIGNATURE_SECONDARY_EFFECT_SLEEP", "SIGNATURE_SECONDARY_EFFECT_CONFUSION",
    "SIGNATURE_SECONDARY_EFFECT_INFATUATION", "SIGNATURE_SECONDARY_EFFECT_FLINCH",
    "SIGNATURE_SECONDARY_EFFECT_CURSE", "SIGNATURE_SECONDARY_EFFECT_LEECH_SEED",
    "SIGNATURE_SECONDARY_EFFECT_REMOVE_STAT_CHANGES",
    "SIGNATURE_SECONDARY_EFFECT_TAUNT", "SIGNATURE_SECONDARY_EFFECT_GIVE_THIRD_TYPE",
    "SIGNATURE_SECONDARY_EFFECT_RECKOIL", "SIGNATURE_SECONDARY_EFFECT_CURE",
    "SIGNATURE_SECONDARY_EFFECT_DRAIN", "SIGNATURE_SECONDARY_EFFECT_HEAL_STATUS",
    "SIGNATURE_SECONDARY_EFFECT_SET_HEAL_BLOCK",
    "SIGNATURE_SECONDARY_EFFECT_INFESTATION",
    "SIGNATURE_SECONDARY_EFFECT_STEAL_POSITIVE_STAT_CHANGES",
}
MAX_SLOTS = 6


def read(p):
    with open(p, encoding="utf-8", errors="ignore") as f:
        return f.read()


def main():
    dry = "--dry-run" in sys.argv
    tgt = lambda *p: os.path.join(TARGET, *p)
    dn = lambda *p: os.path.join(DONOR, *p)

    sp_text = read(tgt("include/constants/species.h"))
    our_species = set(re.findall(r"#define (SPECIES_\w+)", sp_text))
    our_moves = set(re.findall(r"#define (MOVE_\w+)",
                               read(tgt("include/constants/moves.h"))))

    # Every symbol our headers define. Donor slots sometimes reference
    # constants from ITS newer engine (SIGNATURE_CONDITION_*, ...); those slots
    # can't compile here, so they're dropped and reported like any other
    # unimplemented mod.
    known = set()
    for root, _dirs, files in os.walk(tgt("include")):
        for fn in files:
            if fn.endswith(".h"):
                known |= set(re.findall(r"\b[A-Z][A-Z0-9_]{2,}\b",
                                        read(os.path.join(root, fn))))

    def resolvable(expr):
        for tok in re.findall(r"\b[A-Za-z_]\w*\b", expr):
            if not tok.isdigit() and tok not in known:
                return False
        return True

    dsig = re.sub(r"//.*", "", read(dn("src/data/battle_moves_signature.h")))

    entries, skipped, partial = [], [], []
    # each species entry: [SPECIES_X] = { ... },  (top level of the array)
    for m in re.finditer(r"\[(SPECIES_\w+)\]\s*=\s*\{(.*?)\n    \},", dsig, re.S):
        sp, body = m.group(1), m.group(2)
        if sp not in our_species:
            skipped.append((sp, "species not in tree"))
            continue
        mv = re.search(r"\.move\s*=\s*(MOVE_\w+)", body)
        if not mv or mv.group(1) not in our_moves:
            skipped.append((sp, "move %s not in tree"
                            % (mv.group(1) if mv else "?")))
            continue
        move = mv.group(1)

        desc = re.search(r'DEFINE_SIGNATURE_MOVE_DESCRIPTION\(\s*"(.*?)"\s*\)',
                         body, re.S)
        # .description is a fixed char[SIGNATURE_MOVE_DESCRIPTION_TEXT_LENGTH]
        desc = " ".join(desc.group(1).split())[:118] if desc else ""

        slots, dropped = [], []
        for em in re.finditer(
                r"\[SIGNATURE_MOVE_EFFECT_\d+\]\s*=\s*\{(.*?)\}", body, re.S):
            eb = em.group(1)
            mod = re.search(r"\.modification\s*=\s*(\w+)", eb)
            if not mod:
                continue
            mod = mod.group(1)
            var = re.search(r"\.variable\s*=\s*([^,\n]+)", eb)
            arg = re.search(r"\.argument\s*=\s*([^,\n]+)", eb)
            chance = re.search(r"\.chance\s*=\s*([^,\n]+)", eb)
            var = var.group(1).strip() if var else "0"
            arg = arg.group(1).strip() if arg else "0"
            chance = chance.group(1).strip() if chance else "0"

            # donor data shorthands: enum members used directly as mods
            if mod == "SIGNATURE_STAT_STAGES_IGNORED":
                mod, var = "SIGNATURE_MOD_ADD_FLAG", "FLAG_STAT_STAGES_IGNORED"
            elif mod == "SIGNATURE_PRIORITY_IN_CONDITIONS":
                mod, chance, var = ("SIGNATURE_MOD_PRIORITY", var,
                                    "SIGNATURE_PRIORITY_IN_CONDITIONS")
            if mod not in IMPLEMENTED_MODS:
                dropped.append(mod)
                continue
            if (mod == "SIGNATURE_MOD_SECONDARY_EFFECT"
                    and var not in IMPLEMENTED_SECONDARY):
                dropped.append("%s(%s)" % (mod, var))
                continue
            if not all(resolvable(x) for x in (var, arg, chance)):
                dropped.append("%s(unknown constant)" % mod)
                continue
            slots.append((mod, var, arg, chance))

        if len(slots) > MAX_SLOTS:
            dropped += ["overflow:%s" % s[0] for s in slots[MAX_SLOTS:]]
            slots = slots[:MAX_SLOTS]
        if dropped:
            partial.append((sp, move, dropped))
        entries.append({"sp": sp, "move": move, "desc": desc, "slots": slots})

    print("signature entries: %d ported, %d skipped, %d partially applied"
          % (len(entries), len(skipped), len(partial)))
    if dry:
        for sp, mv, d in partial[:20]:
            print("   PARTIAL %-30s %-22s dropped: %s" % (sp, mv, ", ".join(d)))
        for sp, why in skipped[:10]:
            print("   SKIP    %-30s %s" % (sp, why))
        return

    # ---- emit
    out = []
    for e in entries:
        out.append("    [%s] =\n    {\n" % e["sp"])
        out.append("        .move = %s,\n" % e["move"])
        if e["desc"]:
            out.append("        .differentDescription = TRUE,\n")
            out.append('        .description = _("%s"),\n' % e["desc"])
        else:
            out.append("        .differentDescription = FALSE,\n")
            out.append('        .description = _("Default Description"),\n')
        for i, (mod, var, arg, chance) in enumerate(e["slots"], 1):
            sfx = "" if i == 1 else str(i)
            out.append("        .modification%s = %s,\n" % (sfx, mod))
            out.append("        .variable%s = %s,\n" % (sfx, var))
            if arg != "0":
                out.append("        .argument%s = %s,\n" % (sfx, arg))
            if chance != "0":
                out.append("        .chance%s = %s,\n" % (sfx, chance))
        out.append("    },\n")
    block = "%s\n%s%s\n" % (MS, "".join(out), ME)

    path = tgt("src/data/battle_moves.h")
    text = read(path)
    text = re.sub(re.escape(MS) + r".*?" + re.escape(ME) + r"\n?", "", text, flags=re.S)
    m = re.search(r"const struct SignatureMove gSignatureMoveList\[NUM_SPECIES\] = \{",
                  text)
    assert m, "gSignatureMoveList not found"
    close = text.find("\n};", m.end())
    assert close != -1
    # replace the whole body: our 138 hand-written entries are a subset of the
    # donor's 332 and would otherwise collide as duplicate initializers
    with open(os.path.join(HERE, "rowe_signature_port_report.txt"), "w") as f:
        f.write("Ported %d signature entries (replaces the previous 138)\n\n"
                % len(entries))
        f.write("PARTIALLY APPLIED (%d) -- entry ported, listed effect slots "
                "dropped because our engine has no handler:\n" % len(partial))
        for sp, mv, d in partial:
            f.write("  %-32s %-24s %s\n" % (sp, mv, ", ".join(d)))
        f.write("\nSKIPPED (%d):\n" % len(skipped))
        for sp, why in skipped:
            f.write("  %-32s %s\n" % (sp, why))
    write_text = text[:m.end()] + "\n" + block + text[close:]
    with open(path, "w", encoding="utf-8") as f:
        f.write(write_text)
    print("wrote gSignatureMoveList (%d entries) -> run make" % len(entries))


if __name__ == "__main__":
    main()
