#!/usr/bin/env python3
"""Port ROWE 2.X mega evolutions (custom megas) from BelialClover/RoweRepo.

Discovers every EVO_MEGA_EVOLUTION target in the donor that this tree lacks
and whose base species exists here, then ports: species constant, base stats
(both tables), display name, natdex mapping, evolution entry, form tables,
graphics (front/back/pals/icon copied from the donor, INCBIN paths reused
verbatim), pic coords, single-frame anims, learnset pointer, stone item.

Idempotent via ROWEMEGA-PORT marker blocks. Run with --dry-run to only print
the port list/report. After running: make, then update the Lilycove vendor
(tag vendor update runs here too) and rebuild.
"""
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR = os.environ.get(
    "ROWEREPO_DONOR", "/home/jbfish00/Documents/RoweRepo-donor")

MS = "// ROWEMEGA-PORT-START {tag} (generated by tools/character_mode/port_rowe_megas.py)"
ME = "// ROWEMEGA-PORT-END {tag}"


def read(p):
    with open(p, encoding="utf-8", errors="ignore") as f:
        return f.read()


def write(p, s):
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


def strip_block(text, tag):
    return re.sub(re.escape(MS.format(tag=tag)) + r".*?" +
                  re.escape(ME.format(tag=tag)) + r"\n?", "", text, flags=re.S)


def wrap(tag, block):
    return "%s\n%s%s\n" % (MS.format(tag=tag), block, ME.format(tag=tag))


def insert_before_close(path, tag, block, decl_re):
    """Insert a marker block just before the }; closing the array decl_re."""
    text = strip_block(read(path), tag)
    m = re.search(decl_re, text, re.M)
    assert m, (path, decl_re)
    close = text.find("\n};", m.end())
    assert close != -1
    write(path, text[:close + 1] + wrap(tag, block) + text[close + 1:])


def consts(path, prefix):
    return set(re.findall(r"#define (%s\w+)" % prefix, read(path)))


def main():
    dry = "--dry-run" in sys.argv
    tgt = lambda *p: os.path.join(TARGET, *p)
    dn = lambda *p: os.path.join(DONOR, *p)

    # exclude our own generated blocks so re-runs re-discover the same megas
    sp_text = strip_block(read(tgt("include/constants/species.h")), "consts")
    our_species = set(re.findall(r"#define (SPECIES_\w+)", sp_text))
    our_items = set(re.findall(
        r"#define (ITEM_\w+)",
        strip_block(read(tgt("include/constants/items.h")), "stone-ids")))
    our_natdex = set(re.findall(r"#define (NATIONAL_DEX_\w+)", sp_text))

    # ---- discover megas in donor evolution table
    devo = read(dn("src/data/pokemon/evolution.h"))
    devo = re.sub(r"//.*", "", devo)  # drop commented-out rows
    rows = []  # (base, item, mega)
    for m in re.finditer(r"\[(SPECIES_\w+)\]\s*=\s*((?:\{\{.*?\}\})|(?:\{\{.*?\}[,\s]*)+\})",
                         devo, re.S):
        base = m.group(1)
        for e in re.finditer(r"\{EVO_MEGA_EVOLUTION,\s*(ITEM_\w+),\s*(SPECIES_\w+)\}",
                             m.group(2)):
            rows.append((base, e.group(1), e.group(2)))

    donor_gfx = read(dn("src/data/graphics/pokemon.h"))
    gfx_paths = {}  # keyed by symbol suffix lowercased with underscores removed
    for kind, sym in (("front", "gMonFrontPic"), ("back", "gMonBackPic"),
                      ("pal", "gMonPalette"), ("shiny", "gMonShinyPalette"),
                      ("icon", "gMonIcon")):
        for mm in re.finditer(r"%s_(\w+)\[\] = INCBIN_U(?:32|8)\(\"([^\"]+)\"\)" % sym,
                              donor_gfx):
            key = mm.group(1).replace("_", "").lower()
            gfx_paths.setdefault(key, {})[kind] = mm.group(2)

    dstats = read(dn("src/data/pokemon/base_stats.h"))
    dvstats = read(dn("src/data/pokemon/base_stats_vanilla.h")) if \
        os.path.isfile(dn("src/data/pokemon/base_stats_vanilla.h")) else dstats
    dnames = read(dn("src/data/text/species_names.h"))
    dfcoords = read(dn("src/data/pokemon_graphics/front_pic_coordinates.h"))
    dbcoords = read(dn("src/data/pokemon_graphics/back_pic_coordinates.h"))
    dud = read(dn("src/data/pokemon/ud_trade_ids.h")) if \
        os.path.isfile(dn("src/data/pokemon/ud_trade_ids.h")) else ""
    ditems = read(dn("src/data/items.h"))

    def camel(const):  # SPECIES_X_MEGA_Y -> XMegaY
        return "".join(w.title() for w in const[len("SPECIES_"):].split("_"))

    FORM_TAILS = ["_GALAR", "_HISUI", "_ALOLA", "_LOW_KEY", "_RAPID_STRIKE",
                  "_SINGLE_STRIKE", "_STRETCHY", "_DROOPY", "_CURLY", "_ETERNAL",
                  "_REDUX", "_F", "_X", "_Y", "_G"]

    def natdex_for(base):
        suf = base[len("SPECIES_"):]
        while True:
            if ("NATIONAL_DEX_" + suf) in our_natdex:
                return "NATIONAL_DEX_" + suf
            for t in FORM_TAILS:
                if suf.endswith(t):
                    suf = suf[:-len(t)]
                    break
            else:
                return None

    report, ports = [], []
    seen = set()
    for base, item, mega in rows:
        if mega in seen:
            continue
        seen.add(mega)
        if mega in our_species:
            continue  # already have it (official megas, primals)
        if base not in our_species:
            report.append("SKIP %-34s base %s not in tree" % (mega, base))
            continue
        cam = camel(mega)
        g = gfx_paths.get(cam.lower())
        if not g or not all(k in g for k in ("front", "back", "pal", "shiny")):
            report.append("SKIP %-34s no donor graphics (sym %s)" % (mega, cam))
            continue
        # source files must exist (png/pal come from the same dir as the .lz path)
        srcdir = dn(os.path.dirname(g["front"]))
        need = ["front.png", "back.png", "normal.pal", "shiny.pal", "icon.png"]
        missing = [f for f in need if not os.path.isfile(os.path.join(srcdir, f))]
        if missing:
            report.append("SKIP %-34s missing files %s in %s" % (mega, missing, srcdir))
            continue
        entry_re = r"\[%s\]\s*=\s*(?://[^\n]*)?\s*\{(.*?)\n[ \t]*\}\s*," % mega
        sm = re.search(entry_re, dstats, re.S)
        if not sm:
            report.append("SKIP %-34s no donor base stats" % mega)
            continue
        svm = re.search(entry_re, dvstats, re.S)
        nd = natdex_for(base)
        if not nd:
            report.append("SKIP %-34s cannot resolve natdex for %s" % (mega, base))
            continue
        nm = re.search(r"\[%s\] = _\(\"([^\"]+)\"\)" % mega, dnames)
        fc = re.search(r"\[%s\][^}]*?\.size = ([^,]+),\s*\.y_offset = ([^,}]+)" % mega,
                       dfcoords, re.S)
        bc = re.search(r"\[%s\][^}]*?\.size = ([^,]+),\s*\.y_offset = ([^,}]+)" % mega,
                       dbcoords, re.S)
        ud = re.search(r"\[%s\] = (\d+)" % mega, dud)
        ports.append({
            "base": base, "item": item, "mega": mega, "camel": cam,
            "stats": sm.group(1),
            "vstats": svm.group(1) if svm else sm.group(1),
            "natdex": nd,
            "name": nm.group(1) if nm else
                    base[len("SPECIES_"):].split("_")[0].title(),
            "gfx": g, "srcdir": srcdir,
            "fcoords": (fc.group(1).strip(), fc.group(2).strip()) if fc else ("0x88", "0"),
            "bcoords": (bc.group(1).strip(), bc.group(2).strip()) if bc else ("0x88", "0"),
            "ud": ud.group(1) if ud else None,
        })

    print("porting %d megas; %d skipped" % (len(ports), len(report)))
    with open(os.path.join(HERE, "rowe_mega_port_report.txt"), "w") as f:
        f.write("Ported (%d):\n" % len(ports))
        f.write("".join("  %s (stone %s, base %s)\n" % (p["mega"], p["item"], p["base"])
                        for p in ports))
        f.write("\nSkipped (%d):\n  " % len(report) + "\n  ".join(report) + "\n")
    if dry:
        return

    ports.sort(key=lambda p: p["mega"])

    # ---- 1. species constants (append after the Gen 9 block)
    lines = ["#define ROWE_MEGA_START SPECIES_PECHARUNT"]
    for i, p in enumerate(ports, 1):
        lines.append("#define %s (ROWE_MEGA_START + %d)" % (p["mega"], i))
    lines += ["#undef SPECIES_EGG", "#undef NUM_SPECIES",
              "#define SPECIES_EGG (%s + 1)" % ports[-1]["mega"],
              "#define NUM_SPECIES SPECIES_EGG"]
    path = tgt("include/constants/species.h")
    text = strip_block(read(path), "consts")
    anchor = "// GEN9-PORT-END species-consts"
    pos = text.index(anchor) + len(anchor)
    line_end = text.index("\n", pos) + 1 if "\n" in text[pos:pos+2] else pos + 1
    write(path, text[:pos] + "\n" + wrap("consts", "\n".join(lines) + "\n") +
          text[pos:])

    # ---- 2. base stats into both tables (sanitize to fields our struct has)
    our_fields = set(re.findall(r"\.\s*(\w+)\s*=",
                     read(tgt("src/data/pokemon/base_stats.h"))[:8000]))
    def stats_entry(p, key):
        body = []
        for line in p[key].splitlines():
            fm = re.match(r"\s*\.(\w+)\s*=", line)
            if fm and fm.group(1) not in our_fields:
                continue
            if line.strip():
                body.append("        " + line.strip())
        return "    [%s] =\n    {\n%s\n    },\n" % (p["mega"], "\n".join(body))
    block = "".join(stats_entry(p, "stats") for p in ports)
    vblock = "".join(stats_entry(p, "vstats") for p in ports)
    bs = tgt("src/data/pokemon/base_stats.h")
    text = strip_block(strip_block(read(bs), "gbasestats"), "vanillastats")
    vm = re.search(r"^const struct BaseStats gVanillaBaseStats\[\] =", text, re.M)
    close = text.rfind("};", 0, vm.start())
    text = text[:close] + wrap("gbasestats", block) + text[close:]
    last = text.rfind("};")
    text = text[:last] + wrap("vanillastats", vblock) + text[last:]
    write(bs, text)

    # ---- 3. names / natdex / learnset ptrs / ud ids
    # Use OUR base species' name (already shortened to fit 10 chars);
    # donor mega names can exceed POKEMON_NAME_LENGTH.
    our_names = read(tgt("src/data/text/species_names.h"))
    def mega_name(p):
        mm = re.search(r"\[%s\] = _\(\"([^\"]+)\"\)" % p["base"], our_names)
        return mm.group(1) if mm else p["name"][:10]
    insert_before_close(tgt("src/data/text/species_names.h"), "names",
                        "".join('    [%s] = _("%s"),\n' % (p["mega"], mega_name(p))
                                for p in ports),
                        r"gSpeciesNames\[")
    path = tgt("src/pokemon.c")
    text = strip_block(read(path), "spec2nat")
    m = re.search(r"gSpeciesToNationalPokedexNum\[[^\]]*\][^{]*\{", text)
    close = text.find("};", m.end())
    block = "".join("    [%s - 1] = %s,\n" % (p["mega"], p["natdex"]) for p in ports)
    write(path, text[:close] + wrap("spec2nat", block) + text[close:])

    lu = read(tgt("src/data/pokemon/level_up_learnset_pointers.h"))
    def base_learnset(p):
        mm = re.search(r"\[%s\] = (\w+)," % p["base"], lu)
        return mm.group(1) if mm else "sBulbasaurLevelUpLearnset"
    insert_before_close(tgt("src/data/pokemon/level_up_learnset_pointers.h"),
                        "learnptrs",
                        "".join("    [%s] = %s,\n" % (p["mega"], base_learnset(p))
                                for p in ports),
                        r"gLevelUpLearnsets\[")
    ud_ports = [p for p in ports if p["ud"]]
    if ud_ports:
        insert_before_close(tgt("src/data/pokemon/ud_trade_ids.h"), "udids",
                            "".join("    [%s] = %s,\n" % (p["mega"], p["ud"])
                                    for p in ud_ports),
                            r"gUDTradeIds\[|const u16 \w+\[NUM_SPECIES\]")

    # ---- 4. evolution entries (only for bases with no existing entry)
    path = tgt("src/data/pokemon/evolution.h")
    text = strip_block(read(path), "evolutions")
    by_base = {}
    for p in ports:
        by_base.setdefault(p["base"], []).append(
            "{EVO_MEGA_EVOLUTION, %s, %s}" % (p["item"], p["mega"]))
    evo_lines, manual = [], []
    for base, rows_b in by_base.items():
        if re.search(r"^\s*\[%s\]\s*=" % base, text, re.M):
            manual.append((base, rows_b))
        else:
            evo_lines.append("    [%s] = {%s},\n"
                             % (base, ",\n                    ".join(rows_b)))
    m = re.search(r"const struct SpeciesList gFirstStageTable", text)
    close = text.rfind("};", 0, m.start())
    text = text[:close] + wrap("evolutions", "".join(evo_lines)) + text[close:]
    # bases that already have an entry: append rows inside it, matching the
    # entry's outer braces properly (rows nest one level).
    for base, rows_b in manual:
        for row in rows_b:
            m2 = re.search(r"\[%s\]\s*=\s*\{" % base, text)
            depth, i = 1, m2.end()
            while depth and i < len(text):
                if text[i] == "{":
                    depth += 1
                elif text[i] == "}":
                    depth -= 1
                i += 1
            entry = text[m2.end():i - 1]
            if row in entry:
                continue
            ins = i - 1  # position of the entry's closing brace
            prefix = text[:ins].rstrip()
            if prefix.endswith(","):
                prefix = prefix[:-1]
            text = prefix + ",\n\t\t\t\t\t" + row + "\n\t\t\t\t\t" + text[ins:]
    write(path, text)

    # ---- 5. form species tables + pointers + base-form map
    path = tgt("src/data/pokemon/form_species_table.h")
    text = strip_block(read(path), "formtables")
    new_tables, table_of = {}, {}
    for p in ports:
        stem = p["base"][len("SPECIES_"):].title().replace("_", "")
        sym = "s%sFormSpeciesIdTable" % stem
        table_of[p["mega"]] = sym
        tm = re.search(r"static const u16 %s\[\] = \{(.*?)\};" % sym, text, re.S)
        if tm:
            if p["mega"] not in tm.group(1):
                nb = re.sub(r"([ \t]*)0xFFFF", r"\g<1>%s,\n\g<1>0xFFFF" % p["mega"],
                            tm.group(1), count=1)
                text = text[:tm.start(1)] + nb + text[tm.end(1):]
        elif sym in new_tables:
            new_tables[sym] = new_tables[sym].replace(
                "    0xFFFF", "    %s,\n    0xFFFF" % p["mega"], 1)
        else:
            new_tables[sym] = ("static const u16 %s[] = {\n    %s,\n    %s,\n"
                               "    0xFFFF,\n};\n" % (sym, p["base"], p["mega"]))
    text += wrap("formtables", "".join(new_tables.values()))
    write(path, text)

    path = tgt("src/data/pokemon/form_species_table_pointers.h")
    text = strip_block(strip_block(read(path), "formptrs"), "baseforms")
    ptr_lines = []
    emitted_bases = set()
    for p in ports:
        ptr_lines.append("    [%s] = %s,\n" % (p["mega"], table_of[p["mega"]]))
        if (p["base"] not in emitted_bases
                and not re.search(r"\[%s\] = s\w+FormSpeciesIdTable" % p["base"], text)):
            ptr_lines.append("    [%s] = %s,\n" % (p["base"], table_of[p["mega"]]))
            emitted_bases.add(p["base"])
    m = re.search(r"gFormSpeciesIdTables\[[^\]]*\][^{]*\{", text)
    close = text.find("};", m.end())
    text = text[:close] + wrap("formptrs", "".join(ptr_lines)) + text[close:]
    m = re.search(r"gBaseFormID\[[^\]]*\][^{]*\{", text)
    close = text.find("};", m.end())
    block = "".join("    [%s] = %s,\n" % (p["mega"], p["base"]) for p in ports)
    text = text[:close] + wrap("baseforms", block) + text[close:]
    write(path, text)

    # ---- 6. graphics: copy assets, INCBINs, externs, tables, coords, anims, icons
    for p in ports:
        dstdir = tgt(os.path.dirname(p["gfx"]["front"]))
        os.makedirs(dstdir, exist_ok=True)
        for f in ("front.png", "back.png", "normal.pal", "shiny.pal", "icon.png"):
            src, dst = os.path.join(p["srcdir"], f), os.path.join(dstdir, f)
            if f.endswith(".pal"):  # gbagfx requires CRLF JASC palettes
                with open(src, "rb") as fh:
                    data = fh.read().replace(b"\r\n", b"\n").replace(b"\n", b"\r\n")
                with open(dst, "wb") as fh:
                    fh.write(data)
            else:
                shutil.copyfile(src, dst)

    block = "".join(
        'const u32 gMonFrontPic_%(c)s[] = INCBIN_U32("%(f)s");\n'
        'const u32 gMonBackPic_%(c)s[] = INCBIN_U32("%(b)s");\n'
        'const u32 gMonPalette_%(c)s[] = INCBIN_U32("%(p)s");\n'
        'const u32 gMonShinyPalette_%(c)s[] = INCBIN_U32("%(s)s");\n'
        'const u8 gMonIcon_%(c)s[] = INCBIN_U8("%(i)s");\n'
        % {"c": p["camel"], "f": p["gfx"]["front"], "b": p["gfx"]["back"],
           "p": p["gfx"]["pal"], "s": p["gfx"]["shiny"],
           "i": p["gfx"].get("icon", os.path.dirname(p["gfx"]["front"]) + "/icon.4bpp")}
        for p in ports)
    path = tgt("src/data/graphics/pokemon.h")
    text = strip_block(read(path), "incbins")
    write(path, text + "\n" + wrap("incbins", block))

    block = "".join(
        "extern const u32 gMonFrontPic_%(c)s[];\nextern const u32 gMonBackPic_%(c)s[];\n"
        "extern const u32 gMonPalette_%(c)s[];\nextern const u32 gMonShinyPalette_%(c)s[];\n"
        "extern const u8 gMonIcon_%(c)s[];\n" % {"c": p["camel"]} for p in ports)
    path = tgt("include/graphics.h")
    text = strip_block(read(path), "megaexterns")
    pos = text.rfind("#endif")
    write(path, text[:pos] + wrap("megaexterns", block) + text[pos:])

    for tag, fname, line in [
        ("fronts", "front_pic_table.h", "    SPECIES_SPRITE(%(u)s, gMonFrontPic_%(c)s),\n"),
        ("backs", "back_pic_table.h", "    SPECIES_SPRITE(%(u)s, gMonBackPic_%(c)s),\n"),
        ("pals", "palette_table.h", "    SPECIES_PAL(%(u)s, gMonPalette_%(c)s),\n"),
        ("shinypals", "shiny_palette_table.h", "    SPECIES_PAL(%(u)s, gMonShinyPalette_%(c)s),\n"),
    ]:
        block = "".join(line % {"u": p["mega"][len("SPECIES_"):], "c": p["camel"]}
                        for p in ports)
        path = tgt("src/data/pokemon_graphics", fname)
        text = strip_block(read(path), tag)
        close = text.rfind("};")
        write(path, text[:close] + wrap(tag, block) + text[close:])

    for tag, fname, key in [("frontcoords", "front_pic_coordinates.h", "fcoords"),
                            ("backcoords", "back_pic_coordinates.h", "bcoords")]:
        block = "".join(
            "    [%s] =\n    {\n        .size = %s,\n        .y_offset = %s,\n    },\n"
            % (p["mega"], p[key][0], p[key][1]) for p in ports)
        path = tgt("src/data/pokemon_graphics", fname)
        text = strip_block(read(path), tag)
        close = text.rfind("};")
        write(path, text[:close] + wrap(tag, block) + text[close:])

    # anims: single-frame anim per mega + ptr table entries
    anim_defs = "".join(
        "static const union AnimCmd sAnim_%(m)s_1[] =\n{\n"
        "    ANIMCMD_FRAME(0, 1),\n    ANIMCMD_END,\n};\n"
        "static const union AnimCmd *const sAnims_%(m)s[] ={\n"
        "    sAnim_GeneralFrame0,\n    sAnim_%(m)s_1,\n};\n"
        % {"m": p["mega"][len("SPECIES_"):]} for p in ports)
    path = tgt("src/data/pokemon_graphics/front_pic_anims.h")
    text = strip_block(strip_block(read(path), "animdefs"), "animptrs")
    m = re.search(r"const union AnimCmd \*const \*const gMonFrontAnimsPtrTable", text)
    text = text[:m.start()] + wrap("animdefs", anim_defs) + text[m.start():]
    m = re.search(r"gMonFrontAnimsPtrTable\[[^\]]*\][^{]*\{", text)
    close = text.find("};", m.end())
    block = "".join("    [%s] = sAnims_%s,\n"
                    % (p["mega"], p["mega"][len("SPECIES_"):]) for p in ports)
    text = text[:close] + wrap("animptrs", block) + text[close:]
    write(path, text)

    # icons: table + palette index (reuse the base species' index)
    path = tgt("src/pokemon_icon.c")
    text = strip_block(strip_block(read(path), "icontable"), "iconpals")
    def base_iconpal(p):
        mm = re.search(r"\[%s\] = (\d)," % p["base"], text)
        return mm.group(1) if mm else "0"
    m = re.search(r"gMonIconTable\[[^\]]*\][^{]*\{", text)
    close = text.find("};", m.end())
    block = "".join("    [%s] = gMonIcon_%s,\n" % (p["mega"], p["camel"]) for p in ports)
    text = text[:close] + wrap("icontable", block) + text[close:]
    m = re.search(r"gMonIconPaletteIndices\[[^\]]*\][^{]*\{", text)
    close = text.find("};", m.end())
    block = "".join("    [%s] = %s,\n" % (p["mega"], base_iconpal(p)) for p in ports)
    text = text[:close] + wrap("iconpals", block) + text[close:]
    write(path, text)

    # ---- 7. stone items: constants + entries + descriptions
    new_items = []
    seen_items = set()
    for p in ports:
        if p["item"] not in our_items and p["item"] not in seen_items:
            seen_items.add(p["item"])
            new_items.append(p)
    itext = read(tgt("include/constants/items.h"))
    maxid = max(int(n) for n in re.findall(r"#define ITEM_\w+\s+(\d+)", itext))
    lines = []
    for i, p in enumerate(new_items, 1):
        lines.append("#define %s%s%d" % (p["item"], " " * max(1, 26 - len(p["item"])),
                                         maxid + i))
    lines.append("#undef ITEMS_COUNT")
    lines.append("#define ITEMS_COUNT %d" % (maxid + len(new_items) + 1))
    text = strip_block(itext, "stone-ids")
    m = re.search(r"^#define ITEMS_COUNT \d+.*$", text, re.M)
    write(tgt("include/constants/items.h"),
          text[:m.end() + 1] + wrap("stone-ids", "\n".join(lines) + "\n") +
          text[m.end() + 1:])

    def stone_entry(p):
        dm = re.search(r"\[%s\] =\s*\{(.*?)\n    \}," % p["item"], ditems, re.S)
        name = re.search(r'\.name = _\("([^"]+)"\)', dm.group(1)).group(1) if dm else \
            p["item"][len("ITEM_"):].title()
        desc = ""
        if dm:
            dd = re.search(r'FORMAT_ITEM_DESCRIPTION\("([^"]*)"\)', dm.group(1))
            if dd:
                desc = dd.group(1)
        if not desc:
            desc = "A Mega Stone."
        # wrap description to 3 lines of <=18 chars for the bag UI
        words, linesd, cur = desc.split(), [], ""
        for w in words:
            if len(cur) + len(w) + 1 > 18 and cur:
                linesd.append(cur)
                cur = w
            else:
                cur = (cur + " " + w).strip()
        if cur:
            linesd.append(cur)
        desc_c = "\\n\"\n    \"".join(linesd[:3])
        return (
            'static const u8 s%(c)sDesc[] = _(\n    "%(d)s");\n' % {
                "c": p["item"][len("ITEM_"):].title().replace("_", ""), "d": desc_c},
            "    [%(i)s] =\n    {\n"
            '        .name = _("%(n)s"),\n'
            "        .itemId = %(i)s,\n        .price = 200,\n"
            "        .holdEffect = HOLD_EFFECT_MEGA_STONE,\n"
            "        .description = s%(c)sDesc,\n"
            "        .pocket = POCKET_MEGA_STONES,\n        .type = 4,\n"
            "        .fieldUseFunc = ItemUseOutOfBattle_CannotUse,\n"
            "        .secondaryId = 0,\n    },\n" % {
                "i": p["item"], "n": name,
                "c": p["item"][len("ITEM_"):].title().replace("_", "")})
    descs = "".join(stone_entry(p)[0] for p in new_items)
    entries = "".join(stone_entry(p)[1] for p in new_items)
    path = tgt("src/data/items.h")
    text = strip_block(strip_block(read(path), "stone-descs"), "stone-entries")
    m = re.search(r"const struct Item gItems\[\]", text)
    text = text[:m.start()] + wrap("stone-descs", descs) + text[m.start():]
    close = text.rfind("};")
    text = text[:close] + wrap("stone-entries", entries) + text[close:]
    write(path, text)

    # ---- 8. catch-revert switch cases in battle_script_commands.c
    path = tgt("src/battle_script_commands.c")
    text = strip_block(read(path), "catchrevert")
    anchor = "        case SPECIES_GROUDON_PRIMAL:"
    pos = text.index(anchor)
    block = "".join("        case %s:\n" % p["mega"] for p in ports)
    write(path, text[:pos] + wrap("catchrevert", block) + text[pos:])

    print("ported %d megas, %d new stone items -> run make" % (len(ports), len(new_items)))


if __name__ == "__main__":
    main()
