#!/usr/bin/env python3
"""Port the ROWE 2.X items our tree lacks (append-only, same as the species).

Adds the ~74 items RoweRepo has and we don't: the HM-replacement tools (Axe,
Lantern, Pickaxe, ...), Sevii tickets, charms, Gen 8/9 held items (Booster
Energy, Loaded Dice, Covert Cloak, ...), evolution items (apples, masks,
scrolls, teacups) and the few stones for megas we ported. Our item ids stay
put -- only new ids are appended -- so saves survive; donor scripts reference
items by name, so numbering never has to match.

Battle/field EFFECTS are not implemented here: an item's holdEffect is carried
over when we already have that HOLD_EFFECT_* constant, and the 5 hold effects
we lack are added as constants only (inert until the battle-effects phase).

Idempotent via ROWEITEM marker blocks.
"""
import os
import re
import shutil
import sys
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR = os.environ.get(
    "ROWEREPO_DONOR", "/home/jbfish00/Documents/RoweRepo-donor")

MS = "// ROWEITEM-PORT-START {tag} (generated by tools/character_mode/port_2x_items.py)"
ME = "// ROWEITEM-PORT-END {tag}"

# donor name -> our existing constant (renames, not new content)
ALIASES = {"ITEM_TM22_SOLAR_BEAM": "ITEM_TM22"}


def read(p):
    with open(p, encoding="utf-8", errors="ignore") as f:
        return f.read()


def write(p, s):
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


def strip_block(text, tag):
    return re.sub(re.escape(MS.format(tag=tag)) + r".*?" +
                  re.escape(ME.format(tag=tag)) + r"\n?", "", text, flags=re.S)


def wrap(tag, block):
    return "%s\n%s%s\n" % (MS.format(tag=tag), block, ME.format(tag=tag))


def defines(text, prefix):
    text = re.sub(r"//.*", "", text)
    vals = {}
    for m in re.finditer(r"#define (\w+)\s+([^\n]+)", text):
        n, e = m.group(1), m.group(2).strip()
        e2 = re.sub(r"\b([A-Za-z_]\w*)\b",
                    lambda x: str(vals[x.group(1)])
                    if x.group(1) in vals else x.group(1), e)
        try:
            vals[n] = eval(e2)
        except Exception:
            pass
    return {n: v for n, v in vals.items() if n.startswith(prefix)}


def desc_sym(item):
    return "s%s2XDesc" % "".join(
        w.title() for w in item[len("ITEM_"):].split("_"))


def wrap_desc(text):
    """Our item descriptions are hand-wrapped 3 lines; the donor auto-wraps."""
    lines = textwrap.wrap(" ".join(text.split()), width=18)[:3]
    return "\n".join('    "%s%s"' % (l, "\\n" if i < len(lines) - 1 else "")
                     for i, l in enumerate(lines))


def main():
    dry = "--dry-run" in sys.argv
    tgt = lambda *p: os.path.join(TARGET, *p)
    dn = lambda *p: os.path.join(DONOR, *p)

    items_h = tgt("include/constants/items.h")
    our_text = strip_block(read(items_h), "consts")
    ours = defines(our_text, "ITEM_")
    theirs = defines(read(dn("include/constants/items.h")), "ITEM_")

    missing = sorted(n for n in set(theirs) - set(ours) if n not in ALIASES)
    # donor entries carry a Spanish/English #if pair; keep the English branch
    # so we don't lift Spanish names out of the first .name we happen to match
    ditems = re.sub(
        r"#if GAME_LANGUAGE == LANGUAGE_SPANISH\n.*?#else\n(.*?)#endif\n",
        r"\1", read(dn("src/data/items.h")), flags=re.S)
    dicons = read(dn("src/data/item_icon_table.h"))
    dgfx = read(dn("src/data/graphics/items.h"))
    our_gfx = strip_block(read(tgt("src/data/graphics/items.h")), "incbins")
    our_icon_syms = set(re.findall(r"(gItemIcon(?:Palette)?_\w+)\[\]", our_gfx))
    sym_path = dict(re.findall(
        r"(gItemIcon(?:Palette)?_\w+)\[\] = INCBIN_U32\(\"([^\"]+)\"\)", dgfx))
    icon_rows = re.findall(
        r"\[(ITEM_\w+)\]\s*=\s*\{\s*(gItemIcon_\w+),\s*(gItemIconPalette_\w+)\s*\}",
        dicons)
    icon_of = {i: ic for i, ic, _ in icon_rows}
    icon_pal = {i: pl for i, _, pl in icon_rows}

    our_hold = set(re.findall(r"#define (HOLD_EFFECT_\w+)",
                              read(tgt("include/constants/hold_effects.h"))))
    their_hold_text = read(dn("include/constants/hold_effects.h"))
    their_hold = defines(their_hold_text, "HOLD_EFFECT_")
    new_hold = sorted((v, k) for k, v in their_hold.items() if k not in our_hold)

    # donor items.h defines its own price macros (EVO_ITEMS_PRICE, ...) at the
    # top of the file; resolve them to numbers rather than importing the macros
    donor_local = dict(
        (m.group(1), m.group(2)) for m in
        re.finditer(r"^#define (\w+)\s+(\d+)$", ditems, re.M))

    def resolve(v):
        return donor_local.get(v, v) if v else v

    # our field-use / battle-use function names, to avoid emitting unknown ones
    our_item_src = read(tgt("src/data/items.h"))
    known_funcs = set(re.findall(r"\.fieldUseFunc = (\w+)", our_item_src)) | \
                  set(re.findall(r"\.battleUseFunc = (\w+)", our_item_src))

    ports, report = [], []
    for item in missing:
        m = re.search(r"\[%s\] =\s*\{(.*?)\n[ \t]*\},"
                      % re.escape(item), ditems, re.S)
        if not m:
            report.append("SKIP %-28s no donor entry" % item)
            continue
        body = m.group(1)
        f = lambda key, default=None: (
            re.search(r"\.%s = ([^,\n]+)" % key, body).group(1).strip()
            if re.search(r"\.%s = ([^,\n]+)" % key, body) else default)
        name = re.search(r'\.name = _\("([^"]*)"\)', body)
        desc = re.search(r'\.description = FORMAT_ITEM_DESCRIPTION\("(.*?)"\)',
                         body, re.S)
        if not desc:
            desc = re.search(r'\.description = _\("(.*?)"\)', body, re.S)
        hold = f("holdEffect", "HOLD_EFFECT_NONE")
        if hold not in our_hold and hold not in [k for _, k in new_hold]:
            hold = "HOLD_EFFECT_NONE"
        fuse = f("fieldUseFunc", "ItemUseOutOfBattle_CannotUse")
        if fuse not in known_funcs:
            fuse = "ItemUseOutOfBattle_CannotUse"
        buse = f("battleUseFunc")
        if buse and buse not in known_funcs:
            buse = None
        ports.append({
            "item": item,
            "name": (name.group(1) if name else item[len("ITEM_"):].title())[:17],
            "desc": (desc.group(1) if desc else "A 2.X item."),
            "price": resolve(f("price", "0")),
            "hold": hold,
            "holdparam": resolve(f("holdEffectParam", "0")),
            "pocket": f("pocket", "POCKET_ITEMS"),
            "type": f("type", "4"),
            "fieldUseFunc": fuse,
            "battleUsage": f("battleUsage"),
            "battleUseFunc": buse,
            "secondaryId": resolve(f("secondaryId", "0")),
            "icon": icon_of.get(item), "iconpal": icon_pal.get(item),
        })

    print("porting %d items (%d hold effects, %d aliases); %d skipped"
          % (len(ports), len(new_hold), len(ALIASES), len(report)))
    if dry:
        for p in ports[:100]:
            print("  %-28s %-14s %-22s %s"
                  % (p["item"], p["name"], p["pocket"], p["hold"]))
        for r in report:
            print(" ", r)
        return
    if not ports:
        return

    base_id = max(ours.values())

    # ---- 1. constants + hold effects
    lines = []
    for i, p in enumerate(ports, 1):
        lines.append("#define %-34s %d\n" % (p["item"], base_id + i))
    for dn_name, our_name in sorted(ALIASES.items()):
        lines.append("#define %-34s %s\n" % (dn_name, our_name))
    lines.append("\n#undef ITEMS_COUNT\n#undef ITEM_FIELD_ARROW\n")
    lines.append("#define ITEMS_COUNT %d\n" % (base_id + len(ports) + 1))
    lines.append("#define ITEM_FIELD_ARROW ITEMS_COUNT\n")
    text = strip_block(read(items_h), "consts")
    m = re.search(r"^#endif", text, re.M)
    write(items_h, text[:m.start()] + wrap("consts", "".join(lines)) + text[m.start():])

    if new_hold:
        path = tgt("include/constants/hold_effects.h")
        text = strip_block(read(path), "holds")
        block = "".join("#define %-34s %s\n" % (k, v) for v, k in new_hold)
        m = re.search(r"^#endif", text, re.M)
        write(path, text[:m.start()] + wrap("holds", block) + text[m.start():])

    # ---- 2. descriptions (our file has an ES block then an EN block)
    path = tgt("src/data/text/item_descriptions.h")
    text = strip_block(read(path), "desc")
    block = "".join("static const u8 %s[] = _(\n%s);\n\n"
                    % (desc_sym(p["item"]), wrap_desc(p["desc"])) for p in ports)
    # one copy is enough: the statics are file-scope and both language blocks
    # are in the same file, so define them once after the #endif
    m = re.search(r"^#endif", text, re.M)
    write(path, text[:m.start()] + wrap("desc", block) + text[m.start():])

    # ---- 3. item entries
    def entry(p):
        out = ["    [%s] =\n    {\n" % p["item"]]
        out.append('        .name = _("%s"),\n' % p["name"])
        out.append("        .itemId = %s,\n" % p["item"])
        out.append("        .price = %s,\n" % p["price"])
        out.append("        .holdEffect = %s,\n" % p["hold"])
        out.append("        .holdEffectParam = %s,\n" % p["holdparam"])
        out.append("        .description = %s,\n" % desc_sym(p["item"]))
        out.append("        .pocket = %s,\n" % p["pocket"])
        out.append("        .type = %s,\n" % p["type"])
        out.append("        .fieldUseFunc = %s,\n" % p["fieldUseFunc"])
        if p["battleUsage"]:
            out.append("        .battleUsage = %s,\n" % p["battleUsage"])
        if p["battleUseFunc"]:
            out.append("        .battleUseFunc = %s,\n" % p["battleUseFunc"])
        out.append("        .secondaryId = %s,\n" % p["secondaryId"])
        out.append("    },\n")
        return "".join(out)

    path = tgt("src/data/items.h")
    text = strip_block(read(path), "entries")
    last = text.rfind("};")
    write(path, text[:last] + wrap("entries", "".join(entry(p) for p in ports))
          + text[last:])

    # ---- 4. icons: copy new pngs, INCBIN + extern + table rows
    copies, incbins, externs, new_syms = [], [], [], set()
    for p in ports:
        for sym in (p["icon"], p["iconpal"]):
            if not sym or sym in our_icon_syms or sym in new_syms:
                continue
            path_lz = sym_path.get(sym)
            if not path_lz:
                continue
            src = dn(path_lz.replace(".4bpp.lz", ".png").replace(".gbapal.lz", ".pal"))
            if not os.path.isfile(src):
                continue
            new_syms.add(sym)
            copies.append((src, tgt(os.path.dirname(path_lz)), os.path.basename(src)))
            incbins.append('const u32 %s[] = INCBIN_U32("%s");\n' % (sym, path_lz))
            externs.append("extern const u32 %s[];\n" % sym)

    for src, dstdir, fname in copies:
        os.makedirs(dstdir, exist_ok=True)
        dst = os.path.join(dstdir, fname)
        if os.path.isfile(dst):
            continue
        if fname.endswith(".pal"):
            data = open(src, "rb").read().replace(b"\r\n", b"\n")
            open(dst, "wb").write(data.replace(b"\n", b"\r\n"))
        else:
            shutil.copyfile(src, dst)

    path = tgt("src/data/graphics/items.h")
    text = strip_block(read(path), "incbins")
    write(path, text.rstrip("\n") + "\n\n" + wrap("incbins", "".join(incbins)))

    path = tgt("include/graphics.h")
    text = strip_block(read(path), "itemexterns")
    m = re.search(r"^#endif", text, re.M)
    write(path, text[:m.start()] + wrap("itemexterns", "".join(externs))
          + text[m.start():])

    path = tgt("src/data/item_icon_table.h")
    text = strip_block(read(path), "icons")
    rows = []
    for p in ports:
        icon = p["icon"] if (p["icon"] in our_icon_syms or p["icon"] in new_syms) \
            else "gItemIcon_QuestionMark"
        pal = p["iconpal"] if (p["iconpal"] in our_icon_syms or p["iconpal"] in new_syms) \
            else "gItemIconPalette_QuestionMark"
        rows.append("    [%s] = {%s, %s},\n" % (p["item"], icon, pal))
    last = text.rfind("};")
    write(path, text[:last] + wrap("icons", "".join(rows)) + text[last:])

    with open(os.path.join(HERE, "rowe_item_port_report.txt"), "w") as f:
        f.write("Ported (%d):\n" % len(ports))
        f.write("".join("  %-30s %-14s %-24s %s\n"
                        % (p["item"], p["name"], p["pocket"], p["hold"])
                        for p in ports))
        f.write("\nNew hold effects (%d, constants only -- no battle logic):\n"
                % len(new_hold))
        f.write("".join("  %s\n" % k for _, k in new_hold))
        if report:
            f.write("\nSkipped (%d):\n  " % len(report) + "\n  ".join(report) + "\n")
    print("ported %d items, %d new icons -> run make" % (len(ports), len(new_syms)))


if __name__ == "__main__":
    main()
