"""Add the ROWE 2.X trainers our tree doesn't have at all (append-only).

port_2x_trainers.py rebalances parties for trainers we ALREADY have. This
adds the ~138 the donor has and we don't (Sevii/Kanto NPCs, extra E4/gym
trainers), together with everything a new trainer needs:

  - TRAINER_* constants (donor ids start at 1000, above our max, no clashes)
  - MAX_TRAINERS_COUNT 864 -> 2000, matching 2.X. Its flag pool grows to
    suit; SaveBlock1 has room (measured ~14.1K of the 16K sector budget).
  - missing TRAINER_CLASS_* / TRAINER_PIC_* constants + class names + money
  - trainer front pics copied from the donor (frlg/) with INCBIN/extern,
    pic table, palette table, single-frame anims, pic coords
  - the trainer entries themselves, parties emitted as our superset variant
    (TrainerMonItemCustomMoves) exactly like port_2x_trainers.py

A trainer is skipped only if its party can't be resolved (unknown species).
Idempotent via ROWENEWTRN markers.
"""
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR = os.environ.get("ROWEREPO_DONOR", "/home/jbfish00/Documents/RoweRepo-donor")

M = "ROWENEWTRN"
MS = "// %s-START {tag} (generated by tools/character_mode/port_2x_new_trainers.py)" % M
ME = "// %s-END {tag}" % M

SCALARS = ("lvl", "abilityNum", "happiness", "species", "formId",
           "postgameheldItem", "heldItem", "pokeball", "isShiny",
           "exioliteBoost", "nature", "style")
ARRAYS = ("evs", "moves", "postgamemoves")


def read(p):
    with open(p, encoding="utf-8", errors="ignore") as f:
        return f.read()


def write(p, s):
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


def strip_block(text, tag):
    return re.sub(re.escape(MS.format(tag=tag)) + r".*?" +
                  re.escape(ME.format(tag=tag)) + r"\n?", "", text, flags=re.S)


def wrap(tag, block):
    return "%s\n%s%s\n" % (MS.format(tag=tag), block, ME.format(tag=tag))


def defines(text, prefix):
    text = re.sub(r"//.*", "", text)
    vals = {}
    for m in re.finditer(r"#define (\w+)\s+([^\n]+)", text):
        n, e = m.group(1), m.group(2).strip()
        e2 = re.sub(r"\b([A-Za-z_]\w*)\b",
                    lambda x: str(vals[x.group(1)]) if x.group(1) in vals else x.group(1), e)
        try:
            vals[n] = eval(e2)
        except Exception:
            pass
    return {n: v for n, v in vals.items() if n.startswith(prefix)}


def parse_party(body, resolvable):
    mons = []
    for mm in re.finditer(r"\{(.*?)\}(?=\s*,\s*(?:\{|$)|\s*$)", body, re.S):
        mb = mm.group(1)
        if not mb.strip():
            continue
        mon = {}
        for f in SCALARS:
            fm = re.search(r"\.%s\s*=\s*([^,\n{]+)" % f, mb)
            if fm:
                mon[f] = fm.group(1).strip().rstrip(",").strip()
        for f in ARRAYS:
            am = re.search(r"\.%s\s*=\s*(\{[^}]*\})" % f, mb)
            if am:
                mon[f] = am.group(1)
                continue
            am = re.search(r"\.%s\s*=\s*([^\n{]+?)(?=\n\s*[.}])" % f, mb, re.S)
            if am:
                items = [x.strip() for x in am.group(1).split(",") if x.strip()]
                if items:
                    mon[f] = "{%s}" % ", ".join(items)
        if "species" not in mon:
            continue
        for v in mon.values():
            if not resolvable(v):
                return None
        mons.append(mon)
    return mons or None


def emit_mon(mon):
    g = mon.get
    return ("    {\n"
            "    .iv = 0,\n"
            "    .lvl = %s,\n" % g("lvl", "1") +
            "    .evs = %s,\n" % g("evs", "{0, 0, 0, 0, 0, 0}") +
            "    .abilityNum = %s,\n" % g("abilityNum", "3") +
            "    .happiness = %s,\n" % g("happiness", "0") +
            "    .species = %s,\n" % mon["species"] +
            "    .formId = %s,\n" % g("formId", "0") +
            "    .postgameheldItem = %s,\n" % g("postgameheldItem", "ITEM_NONE") +
            "    .heldItem = %s,\n" % g("heldItem", "ITEM_NONE") +
            "    .postgamemoves = %s,\n" % g("postgamemoves", "{MOVE_NONE, MOVE_NONE, MOVE_NONE, MOVE_NONE}") +
            "    .moves = %s,\n" % g("moves", "{MOVE_NONE, MOVE_NONE, MOVE_NONE, MOVE_NONE}") +
            "    .pokeball = %s,\n" % g("pokeball", "0") +
            "    .isShiny = %s,\n" % g("isShiny", "FALSE") +
            "    .exioliteBoost = %s,\n" % g("exioliteBoost", "FALSE") +
            "    .hiddenNature = %s,\n" % g("nature", "0") +
            "    .style = %s,\n" % g("style", "STYLE_BALANCED") +
            "    },\n")


def main():
    dry = "--dry-run" in sys.argv
    tgt = lambda *p: os.path.join(TARGET, *p)
    dn = lambda *p: os.path.join(DONOR, *p)

    known = set()
    for root, _d, files in os.walk(tgt("include")):
        for fn in files:
            if fn.endswith(".h"):
                known |= set(re.findall(r"\b[A-Z][A-Z0-9_]{2,}\b",
                                        read(os.path.join(root, fn))))
    # classes/pics we're about to add count as known
    dop = read(dn("include/constants/opponents.h"))
    dtr = read(dn("include/constants/trainers.h"))
    # strip our own generated blocks or a re-run sees its previous output as
    # pre-existing and ports nothing
    our_op = strip_block(read(tgt("include/constants/opponents.h")), "consts")
    our_tr = strip_block(strip_block(read(tgt("include/constants/trainers.h")),
                                     "classes"), "pics")

    our_trainers = defines(our_op, "TRAINER_")
    donor_trainers = defines(dop, "TRAINER_")
    # Donor ids collide with ours in places (its 852-854 are different
    # trainers than our 852-854), so new trainers get OUR next free ids --
    # scripts and data link by name, never by number.
    next_id = max(v for v in our_trainers.values() if isinstance(v, int)) + 1
    missing_names = sorted(set(donor_trainers) - set(our_trainers),
                           key=lambda n: donor_trainers[n])
    missing_trainers = [(next_id + i, n) for i, n in enumerate(missing_names)]

    our_class = set(re.findall(r"#define (TRAINER_CLASS_\w+)", our_tr))
    our_pic = set(re.findall(r"#define (TRAINER_PIC_\w+)", our_tr))
    donor_class = dict(re.findall(r"#define (TRAINER_CLASS_\w+)\s+(\w+)", re.sub(r"//.*", "", dtr)))
    donor_pic = dict(re.findall(r"#define (TRAINER_PIC_\w+)\s+(\w+)", re.sub(r"//.*", "", dtr)))
    new_classes = [c for c in donor_class if c not in our_class]
    new_pics = [p for p in donor_pic if p not in our_pic]

    for c in new_classes:
        known.add(c)
    for p in new_pics:
        known.add(p)
    for _id, n in missing_trainers:
        known.add(n)

    def resolvable(expr):
        for tok in re.findall(r"\b[A-Za-z_]\w*\b", expr):
            if not tok.isdigit() and tok not in known:
                return False
        return True

    dparties = re.sub(r"//.*", "", read(dn("src/data/trainer_parties.h")))
    dparties = re.sub(r"GENERIC_MON\(\s*(\w+)\s*\)",
                      r"{ .lvl = 1, .abilityNum = 3, .species = \1, }", dparties)
    donor_party = dict(
        (m.group(1), m.group(2)) for m in re.finditer(
            r"static const struct TrainerMon (sParty_\w+)\[\] = \{(.*?)\n\};",
            dparties, re.S))

    dtrainers = read(dn("src/data/trainers.h"))
    trainer_entry = {}
    for m in re.finditer(r"\[(TRAINER_\w+)\]\s*=\s*\{(.*?)\n    \},", dtrainers, re.S):
        trainer_entry[m.group(1)] = m.group(2)

    ported, skipped = [], []
    for _id, name in missing_trainers:
        body = trainer_entry.get(name)
        if body is None:
            skipped.append((name, "no donor trainer entry"))
            continue
        # The donor writes `.party = TRAINER_PARTY(sParty_X)`; older trees write
        # `.party = {.Field = sParty_X}`. Accept both -- matching only the second is what
        # left all 91 new trainers with no Pokemon at all.
        pm = re.search(r"\.party\s*=\s*(?:TRAINER_PARTY\(\s*(sParty_\w+)\s*\)"
                       r"|\{\s*\.\w+\s*=\s*(sParty_\w+)\s*\})", body)
        party_sym = (pm.group(1) or pm.group(2)) if pm else None
        # NEVER emit a trainer with an empty party: a battle against nobody is worse than
        # a missing trainer, and it used to happen without even a skip line in the report.
        if not party_sym:
            skipped.append((name, "no party symbol in the donor entry"))
            continue
        if party_sym not in donor_party:
            skipped.append((name, "party %s absent from donor trainer_parties.h" % party_sym))
            continue
        mons = parse_party(donor_party[party_sym], resolvable)
        if not mons:
            skipped.append((name, "party %s unresolved" % party_sym))
            continue
        # pull the scalar header fields
        def field(key, default):
            fm = re.search(r"\.%s = ([^,\n]+)" % key, body)
            return fm.group(1).strip() if fm else default
        cls = field("trainerClass", "TRAINER_CLASS_PKMN_TRAINER_1")
        pic = field("trainerPic", "TRAINER_PIC_HIKER")
        music = field("encounterMusic_gender", "TRAINER_ENCOUNTER_MUSIC_MALE")
        tname = re.search(r'\.trainerName = _\("([^"]*)"\)', body)
        dbl = field("doubleBattle", "FALSE")
        ai = field("aiFlags", "0")
        items = re.search(r"\.items = (\{[^}]*\})", body)
        if not resolvable(cls) or not resolvable(pic) or not resolvable(music):
            skipped.append((name, "unresolved class/pic/music"))
            continue
        # .lvl is a SENTINEL in battle_main.c, not a literal level: 1 = scale to the badge-
        # appropriate trainer level, 3 = LeaderMinLevel, 2/5/6 = various random modes.
        # OVERRIDE the donor's raw .lvl -- 2.X scales its trainers via .partyLevel and its
        # per-mon .lvl means something else there. Carried through raw, a donor `.lvl = 2`
        # lands in a branch of battle_main.c that has no case for 2 and becomes a LITERAL
        # level 2, so a Rocket grunt at 16 badges led with a level-2 Pokemon.
        plevel = field("partyLevel", "TRAINER_LEVEL_DYNAMIC_NORMAL")
        lvl = "3" if "GYM_LEADER" in plevel else "1"
        for _m in mons:
            _m["lvl"] = lvl
        ported.append({
            "name": name, "id": _id, "class": cls, "pic": pic, "music": music,
            "tname": tname.group(1) if tname else "",
            "double": dbl, "ai": ai,
            "items": items.group(1) if items else "{}",
            "party_sym": party_sym, "mons": mons,
        })

    print("new trainers: %d ported, %d skipped; +%d classes, +%d pics"
          % (len(ported), len(skipped), len(new_classes), len(new_pics)))
    if dry:
        for n, why in skipped[:20]:
            print("   SKIP %-32s %s" % (n, why))
        return
    if not ported:
        return

    # ---- 1. MAX_TRAINERS_COUNT + trainer constants
    # Constants for EVERY missing trainer, not just ported ones: 2.X reserves
    # ids (e.g. 45 Sevii Rocket grunts with no entries yet) and its map
    # scripts reference them by name; Phase 4 needs those to assemble.
    path = tgt("include/constants/opponents.h")
    text = strip_block(read(path), "consts")
    text = re.sub(r"#define MAX_TRAINERS_COUNT\s+\d+",
                  "#define MAX_TRAINERS_COUNT                  2000", text)
    new_count = max(i for i, _ in missing_trainers) + 1
    text = re.sub(r"#define TRAINERS_COUNT\s+\d+",
                  "#define TRAINERS_COUNT                      %d" % new_count,
                  text)
    lines = ["#define %-34s %d\n" % (n, i) for i, n in missing_trainers]
    m = re.search(r"^#endif", text, re.M)
    write(path, text[:m.start()] + wrap("consts", "".join(lines)) + text[m.start():])

    # ---- 2. classes + pics constants
    path = tgt("include/constants/trainers.h")
    text = strip_block(strip_block(read(path), "classes"), "pics")
    if new_classes:
        blk = "".join("#define %-40s %s\n" % (c, donor_class[c]) for c in new_classes)
        m = re.search(r"^#endif", text, re.M)
        text = text[:m.start()] + wrap("classes", blk) + text[m.start():]
    if new_pics:
        blk = "".join("#define %-40s %s\n" % (p, donor_pic[p]) for p in new_pics)
        m = re.search(r"^#endif", text, re.M)
        text = text[:m.start()] + wrap("pics", blk) + text[m.start():]
    write(path, text)

    # ---- 3. class names + money for new classes
    dclassnames = read(dn("src/data/text/trainer_class_names.h"))
    path = tgt("src/data/text/trainer_class_names.h")
    text = strip_block(read(path), "classnames")
    rows = []
    for c in new_classes:
        nm = re.search(r"\[%s\]\s*=\s*_\(\"([^\"]*)\"\)" % c, dclassnames)
        fallback = c[len("TRAINER_CLASS_"):].replace("_", " ").title()[:12]
        rows.append('    [%s] = _("%s"),\n' % (c, nm.group(1) if nm else fallback))
    if rows:
        last = text.rfind("};")
        text = text[:last] + wrap("classnames", "".join(rows)) + text[last:]
    write(path, text)

    # The donor ships no battle_main.c, so its money values are unavailable;
    # use the FRLG-canonical payouts for these classes (they're all FRLG
    # classes: Crush Girl 24, Juggler 32, Painter 16, Scientist 48, Tamer 36,
    # Cool Couple 24) with 20 as fallback.
    FRLG_MONEY = {"TRAINER_CLASS_CRUSH_GIRL": "24", "TRAINER_CLASS_JUGGLER": "32",
                  "TRAINER_CLASS_PAINTER": "16", "TRAINER_CLASS_SCIENTIST": "48",
                  "TRAINER_CLASS_TAMER": "36", "TRAINER_CLASS_COOL_COUPLE": "24"}
    path = tgt("src/battle_main.c")
    text = strip_block(read(path), "money")
    rows = []
    for c in new_classes:
        rows.append("    {%s, %s},\n" % (c, FRLG_MONEY.get(c, "20")))
    if rows:
        m = re.search(r"gTrainerMoneyTable\[\] =\s*\{", text)
        # insert before the terminating {0xFF, ...} sentinel
        sentinel = re.search(r"\n(\s*\{\s*0xFF)", text[m.end():])
        pos = m.end() + sentinel.start(1)
        text = text[:pos] + wrap("money", "".join(rows)) + text[pos:]
    write(path, text)

    # ---- 4. trainer front pics for the new pic constants
    dgfx = read(dn("src/data/graphics/trainers.h"))
    cost = dn("src/data/player_costumes/trainer_costumes_gfx_data.h")
    if os.path.isfile(cost):
        dgfx += read(cost)   # 2.X keeps costume-derived trainer pics here
    pic_sym = {}   # TRAINER_PIC_X -> (frontSym, palSym, path_front, path_pal)
    for pm in re.finditer(
            r"const u32 (gTrainerFrontPic_\w+)\[\] = INCBIN_U32\(\"([^\"]+)\"\);",
            dgfx):
        pic_sym.setdefault(pm.group(1), {})["front"] = (pm.group(1), pm.group(2))
    palpath = dict(re.findall(
        r"const u16 (gTrainerPalette_\w+)\[\] = INCBIN_U16\(\"([^\"]+)\"\);", dgfx))

    dfront_rows = re.findall(
        r"TRAINER_SPRITE\((\w+),\s*(gTrainerFrontPic_\w+),\s*(0x[0-9A-Fa-f]+)\)",
        read(dn("src/data/trainer_graphics/front_pic_tables.h")))
    dfront_tbl = {k: sym for k, sym, _sz in dfront_rows}
    dfront_size = {k: sz for k, _sym, sz in dfront_rows}
    dpal_tbl = dict(re.findall(r"TRAINER_PAL\((\w+),\s*(gTrainerPalette_\w+)\)", read(dn("src/data/trainer_graphics/front_pic_tables.h"))))
    dcoords = read(dn("src/data/trainer_graphics/front_pic_anims.h")) if os.path.isfile(dn("src/data/trainer_graphics/front_pic_anims.h")) else ""
    dpiccoords = read(dn("src/data/trainer_graphics/front_pic_tables.h"))

    our_gfx = strip_block(read(tgt("src/data/graphics/trainers.h")), "incbins")
    our_syms = set(re.findall(r"(gTrainer(?:FrontPic|Palette)_\w+)\[\]", our_gfx))

    incbins, externs, front_rows, pal_rows, anim_defs, anim_rows, coord_rows = \
        [], [], [], [], [], [], []
    copies = []
    donor_gfx_all = dgfx
    for pic in new_pics:
        key = pic[len("TRAINER_PIC_"):]
        fsym = dfront_tbl.get(key)
        psym = dpal_tbl.get(key)
        if not fsym or not psym:
            continue
        # incbin paths
        fpath = dict(re.findall(r"(gTrainerFrontPic_\w+)\[\]\s*=\s*INCBIN_U32\(\"([^\"]+)\"\)", donor_gfx_all)).get(fsym)
        ppath = dict(re.findall(r"(gTrainerPalette_\w+)\[\]\s*=\s*INCBIN_U16\(\"([^\"]+)\"\)", donor_gfx_all)).get(psym)
        if (fsym not in our_syms and not fpath) or (psym not in our_syms and not ppath):
            continue   # cannot wire this sprite; leave the pic unrowed
        size = dfront_size.get(key, "0x800")
        if fsym not in our_syms and fpath:
            src = dn(fpath.replace(".4bpp.lz", ".png"))
            if os.path.isfile(src):
                copies.append((src, tgt(os.path.dirname(fpath)), os.path.basename(src)))
            incbins.append('const u32 %s[] = INCBIN_U32("%s");\n' % (fsym, fpath))
            externs.append("extern const u32 %s[];\n" % fsym)
        if psym not in our_syms and ppath:
            src = dn(ppath.replace(".gbapal", ".pal"))
            if os.path.isfile(src):
                copies.append((src, tgt(os.path.dirname(ppath)), os.path.basename(src)))
            incbins.append('const u16 %s[] = INCBIN_U16("%s");\n' % (psym, ppath))
            externs.append("extern const u16 %s[];\n" % psym)
        front_rows.append("    TRAINER_SPRITE(%s, %s, %s),\n" % (key, fsym, size))
        pal_rows.append("    TRAINER_PAL(%s, %s),\n" % (key, psym))
        anim_rows.append("    [%s] = sAnims_%s,\n" % (pic, key.title().replace("_", "")))
        anim_defs.append("static const union AnimCmd *const sAnims_%s[] ={\n    sAnim_GeneralFrame0,\n};\n" % key.title().replace("_", ""))
        cm = re.search(r"\[%s\]\s*=\s*\{\.size = ([^,]+),\s*\.y_offset = ([^,}]+)" % pic, dpiccoords)
        coord_rows.append("    [%s] = {.size = %s, .y_offset = %s},\n"
                          % (pic, cm.group(1).strip() if cm else "8", cm.group(2).strip() if cm else "1"))

    for src, dstdir, fn in copies:
        os.makedirs(dstdir, exist_ok=True)
        dst = os.path.join(dstdir, fn)
        if os.path.isfile(dst):
            continue
        if fn.endswith(".pal"):
            data = open(src, "rb").read().replace(b"\r\n", b"\n")
            open(dst, "wb").write(data.replace(b"\n", b"\r\n"))
        else:
            shutil.copyfile(src, dst)

    if incbins:
        path = tgt("src/data/graphics/trainers.h")
        text = strip_block(read(path), "incbins")
        write(path, text.rstrip("\n") + "\n\n" + wrap("incbins", "".join(incbins)))
        path = tgt("include/graphics.h")
        text = strip_block(read(path), "trainerexterns")
        m = re.search(r"^#endif", text, re.M)
        write(path, text[:m.start()] + wrap("trainerexterns", "".join(externs)) + text[m.start():])
    if front_rows:
        for relpath, tag, rows, decl in (
                ("src/data/trainer_graphics/front_pic_tables.h", "fronttbl", front_rows, r"gTrainerFrontPicTable\[\]"),
                ("src/data/trainer_graphics/front_pic_tables.h", "paltbl", pal_rows, r"gTrainerFrontPicPaletteTable\[\]"),
                ("src/data/trainer_graphics/front_pic_anims.h", "animptr", anim_rows, r"gTrainerFrontAnimsPtrTable\[\]"),
                ("src/data/trainer_graphics/front_pic_tables.h", "coords", coord_rows, r"gTrainerFrontPicCoords\[\]")):
            path = tgt(relpath)
            text = strip_block(read(path), tag)
            m = re.search(decl + r"[^{]*\{", text)
            if not m:
                print("   !! %s not found in %s -- %d rows DROPPED"
                      % (decl, relpath, len(rows)))
                continue
            close = text.find("\n};", m.end())
            text = text[:close + 1] + wrap(tag, "".join(rows)) + text[close + 1:]
            write(path, text)
        # anim defs go before the ptr table
        path = tgt("src/data/trainer_graphics/front_pic_anims.h")
        text = strip_block(read(path), "animdefs")
        m = re.search(r"const union AnimCmd \*const \*const gTrainerFrontAnimsPtrTable", text)
        if m:
            text = text[:m.start()] + wrap("animdefs", "".join(anim_defs)) + text[m.start():]
            write(path, text)

    # ---- 5. parties + trainer entries
    party_out = []
    emitted = set()
    for p in ported:
        # Several donor trainers point at the SAME party symbol (sParty_Dynamic is shared by
        # dozens). Emit each symbol once, or the C file gets duplicate definitions.
        if p["mons"] and p["party_sym"] not in emitted:
            emitted.add(p["party_sym"])
            party_out.append("static const struct TrainerMonItemCustomMoves %s[] = {\n" % p["party_sym"])
            for mon in p["mons"]:
                party_out.append(emit_mon(mon))
            party_out.append("};\n\n")
    path = tgt("src/data/trainer_parties.h")
    text = strip_block(read(path), "parties")
    # avoid redefining a party symbol we already emitted elsewhere
    existing = set(re.findall(r"(sParty_\w+)\[\]", text))
    party_out2 = []
    skip_sym = set()
    for chunk in "".join(party_out).split("static const struct TrainerMonItemCustomMoves ")[1:]:
        sym = chunk.split("[")[0]
        if sym in existing:
            skip_sym.add(sym)
            continue
        existing.add(sym)
        party_out2.append("static const struct TrainerMonItemCustomMoves " + chunk)
    text = text.rstrip("\n") + "\n\n" + wrap("parties", "".join(party_out2))
    write(path, text)

    entry_out = []
    for p in ported:
        party = ".party = {.ItemCustomMoves = %s}" % p["party_sym"] if p["mons"] else ".party = {.NoItemDefaultMoves = NULL}"
        flags = "F_TRAINER_PARTY_CUSTOM_MOVESET | F_TRAINER_PARTY_HELD_ITEM" if p["mons"] else "0"
        size = len(p["mons"]) if p["mons"] else 0
        entry_out.append(
            "    [%s] =\n    {\n"
            "        .partyFlags = %s,\n"
            "        .trainerClass = %s,\n"
            "        .encounterMusic_gender = %s,\n"
            "        .trainerPic = %s,\n"
            '        .trainerName = _("%s"),\n'
            "        .items = %s,\n"
            "        .doubleBattle = %s,\n"
            "        .aiFlags = %s,\n"
            "        .partySize = %d,\n"
            "        %s,\n"
            "    },\n" % (p["name"], flags, p["class"], p["music"], p["pic"],
                         p["tname"], p["items"], p["double"], p["ai"], size, party))
    path = tgt("src/data/trainers.h")
    text = strip_block(read(path), "entries")
    last = text.rfind("};")
    write(path, text[:last] + wrap("entries", "".join(entry_out)) + text[last:])

    with open(os.path.join(HERE, "rowe_new_trainer_report.txt"), "w") as f:
        f.write("Added %d new trainers, +%d classes, +%d pics; MAX_TRAINERS_COUNT -> 2000\n\n"
                % (len(ported), len(new_classes), len(new_pics)))
        f.write("Skipped (%d):\n" % len(skipped))
        for n, why in skipped:
            f.write("  %-34s %s\n" % (n, why))
    print("added %d trainers -> run make" % len(ported))


if __name__ == "__main__":
    main()
