#!/usr/bin/env python3
"""Alias ROWE 2.X species names onto our equivalent constants.

Our tree (1.9.4 + Gen 9 port) and RoweRepo name the same regional/alternate
forms differently (SPECIES_ARCANINE_HUSIAN vs SPECIES_ARCANINE_HISUI,
SPECIES_PIKACHU_ALOLA_CAP vs SPECIES_PIKACHU_ALOLA, ...). Rather than adopt
the donor's numbering -- which would renumber ~435 species and invalidate
every existing save -- we keep our ids and add #define aliases so that donor
data (trainer parties, encounters, signature moves) links by name as-is.

Aliases are plain #defines to our constant, so they cost no ROM and never
appear as separate array entries.

Idempotent via ROWEALIAS marker block. Prints the species that are genuinely
absent from our tree (those need a real port, not an alias).
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR = os.environ.get(
    "ROWEREPO_DONOR", "/home/jbfish00/Documents/RoweRepo-donor")

MS = "// ROWEALIAS-START (generated by tools/character_mode/port_2x_species_aliases.py)"
ME = "// ROWEALIAS-END"

# Donor-suffix -> our-suffix synonyms, applied to normalize both sides.
SYN = [
    ("HUSIAN", "HISUI"), ("GALARIAN", "GALAR"), ("ALOLAN", "ALOLA"),
    ("_FLOWER", ""), ("_TRIM", ""), ("_CLOAK", ""), ("_DRIVE", ""),
    ("_SEA", ""), ("_MODE", ""), ("_FACE", ""), ("_STYLE", ""),
    ("_RIDER", ""), ("_COLOR", ""), ("_CAP", ""), ("_BREED", ""),
    ("FEMALE", "F"), ("MIMEJR", "MIME_JR"), ("PH_D", "PHD"),
    ("CROWNED_SWORD", "CROWNED"), ("CROWNED_SHIELD", "CROWNED"),
    ("MINIOR_CORE_RED", "MINIOR_CORE"), ("PA_U", "PAU"),
    ("UNOWN_EMARK", "UNOWN_EXCLAMATION"), ("UNOWN_QMARK", "UNOWN_QUESTION"),
    ("POKE_BALL", "POKEBALL"),
]


def norm(name):
    s = name
    for a, b in SYN:
        s = s.replace(a, b)
    while "__" in s:
        s = s.replace("__", "_")
    return s.rstrip("_")


def species_defines(path, drop_block=True):
    text = open(path, encoding="utf-8").read()
    if drop_block:
        text = re.sub(re.escape(MS) + r".*?" + re.escape(ME) + r"\n?", "",
                      text, flags=re.S)
    text = re.sub(r"//.*", "", text)
    vals = {}
    for m in re.finditer(r"#define (\w+)\s+([^\n]+)", text):
        name, expr = m.group(1), m.group(2).strip()
        e2 = re.sub(r"\b([A-Za-z_]\w*)\b",
                    lambda x: str(vals[x.group(1)])
                    if x.group(1) in vals else x.group(1), expr)
        try:
            vals[name] = eval(e2)
        except Exception:
            pass
    return {n: v for n, v in vals.items() if n.startswith("SPECIES_")}, text


def main():
    dry = "--dry-run" in sys.argv
    ours_path = os.path.join(TARGET, "include", "constants", "species.h")
    ours, ours_text = species_defines(ours_path)
    theirs, _ = species_defines(
        os.path.join(DONOR, "include", "constants", "species.h"), False)

    by_norm = {}
    for n in ours:
        by_norm.setdefault(norm(n), n)

    aliases, missing = [], []
    for dn in sorted(theirs):
        if dn in ours:
            continue                      # same name already
        target = by_norm.get(norm(dn))
        if target:
            aliases.append((dn, target))
        else:
            missing.append(dn)

    print("aliases: %d" % len(aliases))
    print("genuinely missing (need a real port): %d" % len(missing))
    for m in missing:
        print("   ", m)
    if dry:
        return

    block = ["// 2.X names for forms we already have under different names.\n"
             "// Lets donor data (trainers/encounters/moves) link without\n"
             "// renumbering our species -- which would break every save.\n"]
    for dn, target in aliases:
        block.append("#define %-38s %s\n" % (dn, target))
    body = "%s\n%s%s\n" % (MS, "".join(block), ME)

    text = open(ours_path, encoding="utf-8").read()
    text = re.sub(re.escape(MS) + r".*?" + re.escape(ME) + r"\n?", "",
                  text, flags=re.S)
    m = re.search(r"^#endif.*$", text, re.M)   # closing include guard
    assert m, "no #endif in species.h"
    text = text[:m.start()] + body + "\n" + text[m.start():]
    open(ours_path, "w", encoding="utf-8").write(text)
    print("wrote %d aliases into include/constants/species.h" % len(aliases))


if __name__ == "__main__":
    main()
