#!/usr/bin/env python3
"""Port Gen 9 species data from pokeemerald-expansion into ROWE 1.9.4.

Parses gSpeciesInfo entries (gen_9_families.h) from the donor and fans them out
into ROWE's split tables: species constants, national dex, base stats (both
gBaseStats and gVanillaBaseStats), names, dex text/entries/orders, level-up
learnsets, egg moves, evolutions, first-stage tables, and graphics wiring.
Graphics PNG/pal files are copied; the ROM build converts them via gbagfx.

Idempotent: every insertion is wrapped in GEN9-PORT markers and replaced on
re-run. Run from anywhere:  python3 tools/character_mode/port_gen9.py
"""
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
DONOR = os.environ.get(
    "GEN9_DONOR",
    "/tmp/claude-1000/-home-jbfish00-Documents-Pokemon-Rowe-Alteration/"
    "d861755c-2ee7-4188-8126-ad647883e68d/scratchpad/pokeemerald-expansion",
)

MARK_START = "// GEN9-PORT-START {tag} (generated by tools/character_mode/port_gen9.py)"
MARK_END = "// GEN9-PORT-END {tag}"

FIRST_NATDEX = 906   # Sprigatito
LAST_NATDEX = 1025   # Pecharunt

# ROWE caps names at POKEMON_NAME_LENGTH = 10.
SHORT_NAMES = {
    "Meowscarada": "Meowscrada",
    "Oinkologne": "Oinkolgne",
    "Squawkabilly": "Squawkbily",
    "Kilowattrel": "Kilowattrl",
    "Brambleghast": "Brmbleghst",
    "Dudunsparce": "Dudnsparce",
    "Poltchageist": "Poltchagst",
    "Fezandipiti": "Fezandipti",
    "Great Tusk": "Great Tusk",
    "Scream Tail": "ScreamTail",
    "Brute Bonnet": "BruteBonet",
    "Flutter Mane": "FluttrMane",
    "Slither Wing": "SlithrWing",
    "Sandy Shocks": "SandyShock",
    "Iron Treads": "IronTreads",
    "Iron Bundle": "IronBundle",
    "Iron Jugulis": "IronJuglis",
    "Iron Thorns": "IronThorns",
    "Iron Valiant": "IrnValiant",
    "Roaring Moon": "RoarngMoon",
    "Walking Wake": "WalkngWake",
    "Iron Leaves": "IronLeaves",
    "Gouging Fire": "GougngFire",
    "Raging Bolt": "RagingBolt",
    "Iron Boulder": "IronBouldr",
    "Iron Crown": "Iron Crown",
}

# Cross-gen evolutions into Gen 9 whose donor methods don't exist in ROWE.
# (old_species, method, param, target_gen9_species)
CROSS_GEN_EVOS = [
    ("SPECIES_PRIMEAPE", "EVO_LEVEL", 35, "SPECIES_ANNIHILAPE"),
    ("SPECIES_DUNSPARCE", "EVO_LEVEL", 32, "SPECIES_DUDUNSPARCE"),
    ("SPECIES_GIRAFARIG", "EVO_LEVEL", 32, "SPECIES_FARIGIRAF"),
    ("SPECIES_BISHARP", "EVO_LEVEL", 52, "SPECIES_KINGAMBIT"),
]
# Donor entries keyed by a form constant that IS the species default.
# donor suffix -> plain suffix used for the ROWE constant and graphics dir.
DEFAULT_FORMS = {
    "OINKOLOGNE_M": "OINKOLOGNE",
    "MAUSHOLD_THREE": "MAUSHOLD",
    "SQUAWKABILLY_GREEN": "SQUAWKABILLY",
    "PALAFIN_ZERO": "PALAFIN",
    "TATSUGIRI_CURLY": "TATSUGIRI",
    "DUDUNSPARCE_TWO_SEGMENT": "DUDUNSPARCE",
    "GIMMIGHOUL_CHEST": "GIMMIGHOUL",
    "OGERPON_TEAL": "OGERPON",
    "TERAPAGOS_NORMAL": "TERAPAGOS",
    "POLTCHAGEIST_COUNTERFEIT": "POLTCHAGEIST",
    "SINISTCHA_UNREMARKABLE": "SINISTCHA",
}

# Gen 9 species whose evolution family starts at an OLD species.
CROSS_GEN_BASES = {
    "SPECIES_ANNIHILAPE": "SPECIES_MANKEY",
    "SPECIES_DUDUNSPARCE": "SPECIES_DUNSPARCE",
    "SPECIES_FARIGIRAF": "SPECIES_GIRAFARIG",
    "SPECIES_KINGAMBIT": "SPECIES_PAWNIARD",
    "SPECIES_DIPPLIN": "SPECIES_APPLIN",
    "SPECIES_HYDRAPPLE": "SPECIES_APPLIN",
    "SPECIES_ARCHALUDON": "SPECIES_DURALUDON",
    "SPECIES_SINISTCHA": "SPECIES_POLTCHAGEIST",
}


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def write(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def normalize_text(s):
    return (s.replace("’", "'").replace("‘", "'")
            .replace("“", '"').replace("”", '"')
            .replace("—", "-").replace("–", "-"))


def strip_marker_block(text, tag):
    start = MARK_START.format(tag=tag)
    end = MARK_END.format(tag=tag)
    pat = re.compile(re.escape(start) + r".*?" + re.escape(end) + r"\n?", re.S)
    return pat.sub("", text)


def insert_block(path, tag, block, anchor_re, before=True, count=1):
    """Insert marker-wrapped block before/after the `count`-th anchor match."""
    text = strip_marker_block(read(path), tag)
    wrapped = "%s%s\n%s\n%s\n" % ("" if before else "\n",
                                  MARK_START.format(tag=tag), block.rstrip("\n"),
                                  MARK_END.format(tag=tag))
    matches = list(re.finditer(anchor_re, text, re.M))
    if len(matches) < count:
        raise SystemExit("anchor %r x%d not found in %s" % (anchor_re, count, path))
    m = matches[count - 1]
    pos = m.start() if before else m.end()
    write(path, text[:pos] + wrapped + text[pos:])


# ---------------------------------------------------------------- donor parse

def split_entries(text):
    """Yield (species_const, body) for each [SPECIES_X] = { ... } block."""
    for m in re.finditer(r"\[(SPECIES_\w+)\]\s*=\s*\{", text):
        depth, i = 1, m.end()
        while depth:
            c = text[i]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
            i += 1
        yield m.group(1), text[m.end():i - 1]


def field(body, name, default=None):
    m = re.search(r"\.%s\s*=\s*([^,\n]+)" % name, body)
    return m.group(1).strip() if m else default


def parse_string(body, name):
    m = re.search(r'\.%s\s*=\s*_\("([^"]*)"\)' % name, body)
    return m.group(1) if m else None


def parse_description(body):
    m = re.search(r"\.description\s*=\s*COMPOUND_STRING\(", body)
    if not m:
        return None
    depth, i = 1, m.end()
    while depth:
        c = body[i]
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        i += 1
    raw = body[m.end():i - 1]
    return "".join(re.findall(r'"((?:[^"\\]|\\.)*)"', raw))


def parse_evolutions(body):
    m = re.search(r"\.evolutions\s*=\s*EVOLUTION\(", body)
    if not m:
        return []
    depth, i = 1, m.end()
    while depth:
        c = body[i]
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        i += 1
    raw = body[m.end():i - 1]
    evos = []
    for em in re.finditer(r"\{([^}]*)\}", raw):
        parts = [p.strip() for p in em.group(1).split(",")]
        if len(parts) >= 3:
            evos.append((parts[0], parts[1], parts[2]))
    return evos


def parse_coords(body, name):
    m = re.search(r"\.%s\s*=\s*MON_COORDS_SIZE\((\d+),\s*(\d+)\)" % name, body)
    if not m:
        return 0x88
    w, h = int(m.group(1)), int(m.group(2))
    return ((w // 8) << 4) | (h // 8)


def parse_learnset_arrays(path, wanted_symbols):
    """Extract `static const struct LevelUpMove sXLevelUpLearnset[] = {...};`"""
    text = read(path)
    out = {}
    for sym in wanted_symbols:
        m = re.search(
            r"static const struct LevelUpMove %s\[\] = \{(.*?)\};" % re.escape(sym),
            text, re.S)
        if m:
            out[sym] = m.group(1)
    return out


def parse_egg_move_arrays(path, wanted_symbols):
    text = read(path)
    out = {}
    for sym in wanted_symbols:
        m = re.search(r"const u16 %s\[\] = \{(.*?)\};" % re.escape(sym), text, re.S)
        if m:
            moves = re.findall(r"(MOVE_\w+)", m.group(1))
            out[sym] = [mv for mv in moves if mv != "MOVE_UNAVAILABLE"]
    return out


# ------------------------------------------------------------- target consts

def defined_constants(path, prefix):
    return set(re.findall(r"#define (%s\w+)" % prefix, read(path)))


def valid_moves(path):
    """Move constants with value < MOVES_COUNT (755)."""
    text = read(path)
    count = int(re.search(r"#define MOVES_COUNT_GEN8\s+(\d+)", text).group(1))
    ok = set()
    for m in re.finditer(r"#define (MOVE_\w+)\s+(\d+)", text):
        if int(m.group(2)) < count:
            ok.add(m.group(1))
    return ok


def main():
    donor_info = os.path.join(DONOR, "src/data/pokemon/species_info/gen_9_families.h")
    if not os.path.isfile(donor_info):
        raise SystemExit("donor not found: " + donor_info)

    tgt = lambda *p: os.path.join(TARGET, *p)

    moves_ok = valid_moves(tgt("include/constants/moves.h"))
    abilities_ok = defined_constants(tgt("include/constants/abilities.h"), "ABILITY_")
    items_ok = defined_constants(tgt("include/constants/items.h"), "ITEM_")
    evo_ok = defined_constants(tgt("include/constants/pokemon.h"), "EVO_")

    # ---- collect base Gen 9 species from donor
    natdex_names = {}   # e.g. "SPRIGATITO" -> 906
    dex_h = read(os.path.join(DONOR, "include/constants/pokedex.h"))
    m = re.search(r"enum NationalDexOrder\s*\{(.*?)\};", dex_h, re.S)
    counter = None
    for tok in re.finditer(r"NATIONAL_DEX_(\w+)\s*(?:=\s*(\w+))?\s*,", m.group(1)):
        name, val = tok.group(1), tok.group(2)
        if val is not None:
            counter = int(val) if val.isdigit() else 0
        else:
            counter = 0 if counter is None else counter + 1
        natdex_names[name] = counter

    import glob
    family_files = sorted(glob.glob(
        os.path.join(DONOR, "src/data/pokemon/species_info/gen_*_families.h")))

    species = []       # list of dicts, in natdex order
    report = []        # human-readable notes for review
    entries = []
    for ff in family_files:
        entries.extend(split_entries(read(ff)))
    for const, body in entries:
        suffix = const[len("SPECIES_"):]
        suffix = DEFAULT_FORMS.get(suffix, suffix)
        nat = field(body, "natDexNum")
        if not nat or not nat.startswith("NATIONAL_DEX_"):
            continue
        nat_suffix = nat[len("NATIONAL_DEX_"):]
        if suffix != nat_suffix:
            continue  # alternate form -> skip in v1
        const = "SPECIES_" + suffix  # normalized ROWE constant
        num = natdex_names.get(nat_suffix)
        if num is None or not (FIRST_NATDEX <= num <= LAST_NATDEX):
            continue

        name = parse_string(body, "speciesName")
        disp = SHORT_NAMES.get(name, name)
        if len(disp) > 10:
            raise SystemExit("name too long and not in SHORT_NAMES: " + name)
        if disp != name:
            report.append("name shortened: %s -> %s" % (name, disp))

        types = re.findall(r"TYPE_\w+", field(body, "types", ""))
        t1 = types[0] if types else "TYPE_NORMAL"
        t2 = types[1] if len(types) > 1 else t1

        raw_abils = re.findall(r"ABILITY_\w+", field(body, "abilities", "") or
                               body[body.find(".abilities"):body.find("}", body.find(".abilities"))]
                               if ".abilities" in body else "")
        # abilities = { a0, a1, hidden }
        while len(raw_abils) < 3:
            raw_abils.append("ABILITY_NONE")
        abils = []
        for a in raw_abils[:3]:
            if a in abilities_ok:
                abils.append(a)
            else:
                report.append("%s: ability %s missing in ROWE -> ABILITY_NONE" % (const, a))
                abils.append("ABILITY_NONE")
        if abils[0] == "ABILITY_NONE" and abils[2] != "ABILITY_NONE":
            abils[0], abils[2] = abils[2], "ABILITY_NONE"
        if abils[0] == "ABILITY_NONE" and abils[1] != "ABILITY_NONE":
            abils[0], abils[1] = abils[1], "ABILITY_NONE"

        items = {}
        for k in ("itemCommon", "itemRare"):
            v = field(body, k)
            if v and v in items_ok:
                items[k] = v
            elif v:
                report.append("%s: item %s missing in ROWE -> dropped" % (const, v))

        eggs = re.findall(r"EGG_GROUP_\w+", field(body, "eggGroups", "") or "")
        eg1 = eggs[0] if eggs else "EGG_GROUP_NO_EGGS_DISCOVERED"
        eg2 = eggs[1] if len(eggs) > 1 else eg1

        evs = {k: v for k, v in re.findall(r"\.(evYield_\w+)\s*=\s*(\d+)", body)}

        friendship = field(body, "friendship", "70")
        if friendship == "STANDARD_FRIENDSHIP":
            friendship = "70"

        evos = []
        for method, param, target_sp in parse_evolutions(body):
            tsuf = target_sp[len("SPECIES_"):]
            target_sp = "SPECIES_" + DEFAULT_FORMS.get(tsuf, tsuf)
            if method in evo_ok:
                evos.append((method, param, target_sp))
            else:
                repl = None
                if "LEVEL" in method:
                    repl = ("EVO_LEVEL", param if param.isdigit() and param != "0" else "36")
                if repl:
                    evos.append((repl[0], repl[1], target_sp))
                    report.append("%s: evo method %s -> %s %s" % (const, method, repl[0], repl[1]))
                else:
                    evos.append(("EVO_LEVEL", "36", target_sp))
                    report.append("%s: evo method %s unsupported -> EVO_LEVEL 36" % (const, method))

        species.append({
            "const": const, "suffix": suffix, "natdex": num,
            "name": disp,
            "body": body,
            "type1": t1, "type2": t2,
            "abilities": abils, "items": items,
            "egg1": eg1, "egg2": eg2, "evs": evs,
            "friendship": friendship,
            "genderRatio": field(body, "genderRatio", "MON_GENDERLESS"),
            "catchRate": field(body, "catchRate", "45"),
            "expYield": field(body, "expYield", "100"),
            "eggCycles": field(body, "eggCycles", "20"),
            "growthRate": field(body, "growthRate", "GROWTH_MEDIUM_FAST"),
            "bodyColor": field(body, "bodyColor", "BODY_COLOR_GRAY"),
            "noFlip": field(body, "noFlip", "FALSE"),
            "category": parse_string(body, "categoryName") or "???",
            "height": field(body, "height", "0"),
            "weight": field(body, "weight", "0"),
            "description": normalize_text(parse_description(body) or "No data."),
            "pokemonScale": field(body, "pokemonScale", "256"),
            "pokemonOffset": field(body, "pokemonOffset", "0"),
            "trainerScale": field(body, "trainerScale", "256"),
            "trainerOffset": field(body, "trainerOffset", "0"),
            "frontCoords": parse_coords(body, "frontPicSize"),
            "frontYOff": field(body, "frontPicYOffset", "0"),
            "backCoords": parse_coords(body, "backPicSize"),
            "backYOff": field(body, "backPicYOffset", "0"),
            "iconPalIndex": field(body, "iconPalIndex", "0"),
            "levelUpSym": field(body, "levelUpLearnset"),
            "eggMoveSym": field(body, "eggMoveLearnset"),
            "evolutions": evos,
        })

    # Ogerpon is macro-generated in the donor; hardcode its Teal Mask base form.
    if not any(s["natdex"] == 1017 for s in species):
        species.append({
            "const": "SPECIES_OGERPON", "suffix": "OGERPON", "natdex": 1017,
            "name": "Ogerpon", "body": "",
            "type1": "TYPE_GRASS", "type2": "TYPE_GRASS",
            "abilities": ["ABILITY_DEFIANT", "ABILITY_NONE", "ABILITY_NONE"],
            "items": {}, "egg1": "EGG_GROUP_NO_EGGS_DISCOVERED",
            "egg2": "EGG_GROUP_NO_EGGS_DISCOVERED",
            "evs": {"evYield_Attack": "3"}, "friendship": "70",
            "genderRatio": "MON_FEMALE", "catchRate": "5", "expYield": "275",
            "eggCycles": "10", "growthRate": "GROWTH_SLOW",
            "bodyColor": "BODY_COLOR_GREEN", "noFlip": "FALSE",
            "category": "Mask", "height": "12", "weight": "398",
            "description": ("This Pokémon's type changes based on\n"
                            "which mask it's wearing. It confounds\n"
                            "its enemies with nimble movements\nand kicks."),
            "pokemonScale": "356", "pokemonOffset": "17",
            "trainerScale": "256", "trainerOffset": "0",
            "frontCoords": 0x88, "frontYOff": "2",
            "backCoords": 0x88, "backYOff": "0",
            "iconPalIndex": "1",
            "levelUpSym": "sOgerponLevelUpLearnset", "eggMoveSym": None,
            "evolutions": [],
        })
        stats = {"baseHP": "80", "baseAttack": "120", "baseDefense": "84",
                 "baseSpeed": "110", "baseSpAttack": "60", "baseSpDefense": "96"}
        species[-1]["body"] = "".join(".%s = %s,\n" % kv for kv in stats.items())

    species.sort(key=lambda s: s["natdex"])
    if len(species) != LAST_NATDEX - FIRST_NATDEX + 1:
        got = {s["natdex"] for s in species}
        missing = [n for n in range(FIRST_NATDEX, LAST_NATDEX + 1) if n not in got]
        raise SystemExit("expected %d species, got %d; missing natdex: %s" %
                         (LAST_NATDEX - FIRST_NATDEX + 1, len(species), missing))

    # ---- learnsets / egg moves from donor
    lu_syms = [s["levelUpSym"] for s in species if s["levelUpSym"]]
    lu = parse_learnset_arrays(
        os.path.join(DONOR, "src/data/pokemon/level_up_learnsets/gen_9.h"), lu_syms)
    egg_syms = [s["eggMoveSym"] for s in species if s["eggMoveSym"]]
    eggm = parse_egg_move_arrays(
        os.path.join(DONOR, "src/data/pokemon/egg_moves.h"), egg_syms)

    # ---------------------------------------------------------------- emit
    C = lambda s: s  # cosmetic alias

    # 1. species constants + national dex
    lines = ["// Generation 9 (ported from pokeemerald-expansion)",
             "#define GEN_9_START SPECIES_DECIDUEYE_HUSIAN"]
    for i, s in enumerate(species, 1):
        lines.append("#define %s GEN_9_START + %d" % (s["const"], i))
    lines.append("")
    lines.append("#undef SPECIES_EGG")
    lines.append("#undef NUM_SPECIES")
    lines.append("#define SPECIES_EGG (%s + 1)" % species[-1]["const"])
    lines.append("#define NUM_SPECIES SPECIES_EGG")
    insert_block(tgt("include/constants/species.h"), "species-consts",
                 "\n".join(lines),
                 r"^(?://GEN9 moved: )?#define SPECIES_EGG SPECIES_DECIDUEYE_HUSIAN \+ 1",
                 before=False)
    # The original SPECIES_EGG/NUM_SPECIES defines remain; the block above
    # #undefs and redefines them, and the original NUM_SPECIES re-definition
    # after the block is identical, which C allows.

    lines = ["#define NATIONAL_DEX_%s %d" % (s["suffix"], s["natdex"]) for s in species]
    lines.append("#undef NATIONAL_DEX_COUNT")
    lines.append("#define NATIONAL_DEX_COUNT NATIONAL_DEX_%s" % species[-1]["suffix"])
    insert_block(tgt("include/constants/species.h"), "natdex-consts",
                 "\n".join(lines),
                 r"^(?://GEN9 moved: )?#define NATIONAL_DEX_COUNT NATIONAL_DEX_ENAMORUS",
                 before=False)

    # 2. base stats (same block for both tables)
    def stats_entry(s):
        ev = "".join("        .%s = %s,\n" % (k, v) for k, v in sorted(s["evs"].items()))
        it = "".join("        .%s = %s,\n" % ("item1" if k == "itemCommon" else "item2", v)
                     for k, v in sorted(s["items"].items()))
        return (
            "    [%(const)s] =\n    {\n"
            "        .baseHP = %(hp)s, .baseAttack = %(atk)s, .baseDefense = %(dfn)s,\n"
            "        .baseSpeed = %(spe)s, .baseSpAttack = %(spa)s, .baseSpDefense = %(spd)s,\n"
            "        .type1 = %(t1)s,\n        .type2 = %(t2)s,\n"
            "        .catchRate = %(catch)s,\n        .expYield = %(exp)s,\n"
            "%(ev)s%(it)s"
            "        .genderRatio = %(gender)s,\n        .eggCycles = %(cycles)s,\n"
            "        .friendship = %(friend)s,\n        .growthRate = %(growth)s,\n"
            "        .eggGroup1 = %(eg1)s,\n        .eggGroup2 = %(eg2)s,\n"
            "        .abilities = {%(a0)s, %(a1)s},\n        .abilityHidden = %(ah)s,\n"
            "        .safariZoneFleeRate = 0,\n"
            "        .bodyColor = %(color)s,\n        .noFlip = %(noflip)s,\n    },\n"
        ) % {
            "const": s["const"],
            "hp": field(s["body"], "baseHP"), "atk": field(s["body"], "baseAttack"),
            "dfn": field(s["body"], "baseDefense"), "spe": field(s["body"], "baseSpeed"),
            "spa": field(s["body"], "baseSpAttack"), "spd": field(s["body"], "baseSpDefense"),
            "t1": s["type1"], "t2": s["type2"], "catch": s["catchRate"], "exp": s["expYield"],
            "ev": ev, "it": it, "gender": s["genderRatio"], "cycles": s["eggCycles"],
            "friend": s["friendship"], "growth": s["growthRate"],
            "eg1": s["egg1"], "eg2": s["egg2"],
            "a0": s["abilities"][0], "a1": s["abilities"][1], "ah": s["abilities"][2],
            "color": s["bodyColor"], "noflip": s["noFlip"],
        }

    stats_block = "".join(stats_entry(s) for s in species)
    bs = tgt("src/data/pokemon/base_stats.h")
    # gBaseStats: insert before the }; that precedes gVanillaBaseStats
    text = strip_marker_block(strip_marker_block(read(bs), "gbasestats"), "vanillastats")
    write(bs, text)
    vanilla_decl = r"^const struct BaseStats gVanillaBaseStats\[\] ="
    text = read(bs)
    vm = re.search(vanilla_decl, text, re.M)
    close_before_vanilla = text.rfind("};", 0, vm.start())
    text = (text[:close_before_vanilla] +
            "%s\n%s%s\n" % (MARK_START.format(tag="gbasestats"), stats_block,
                            MARK_END.format(tag="gbasestats")) +
            text[close_before_vanilla:])
    last_close = text.rfind("};")
    text = (text[:last_close] +
            "%s\n%s%s\n" % (MARK_START.format(tag="vanillastats"), stats_block,
                            MARK_END.format(tag="vanillastats")) +
            text[last_close:])
    write(bs, text)

    # 3. names
    block = "".join('    [%s] = _("%s"),\n' % (s["const"], s["name"]) for s in species)
    insert_block(tgt("src/data/text/species_names.h"), "names", block, r"^};", count=1)

    # 4. dex text + entries
    def textsym(s):
        return "g%sPokedexTextGen9" % s["suffix"].title().replace("_", "")
    block = "".join(
        'const u8 %s[] = _(\n    "%s");\n\n' % (
            textsym(s), s["description"].replace("\n", "\\n\"\n    \""))
        for s in species)
    path = tgt("src/data/pokemon/pokedex_text.h")
    text = strip_marker_block(read(path), "dextext")
    write(path, text + "\n%s\n%s%s\n" % (MARK_START.format(tag="dextext"), block,
                                         MARK_END.format(tag="dextext")))

    block = "".join(
        "    [NATIONAL_DEX_%s] =\n    {\n"
        "        .categoryName = _(\"%s\"),\n        .height = %s,\n        .weight = %s,\n"
        "        .description = %s,\n        .unused = 0,\n"
        "        .pokemonScale = %s,\n        .pokemonOffset = %s,\n"
        "        .trainerScale = %s,\n        .trainerOffset = %s,\n    },\n" % (
            s["suffix"], s["category"][:11], s["height"], s["weight"], textsym(s),
            s["pokemonScale"], s["pokemonOffset"], s["trainerScale"], s["trainerOffset"])
        for s in species)
    insert_block(tgt("src/data/pokemon/pokedex_entries.h"), "dexentries", block, r"^};", count=1)

    # 5. species -> natdex map (designated entries after positional block)
    block = "".join("    [%s] = NATIONAL_DEX_%s,\n" % (s["const"], s["suffix"])
                    for s in species)
    path = tgt("src/pokemon.c")
    text = strip_marker_block(read(path), "spec2nat")
    m = re.search(r"const u16 gSpeciesToNationalPokedexNum\[NUM_SPECIES\][^{]*\{", text)
    close = text.find("};", m.end())
    text = (text[:close] + "%s\n%s%s\n" % (MARK_START.format(tag="spec2nat"), block,
                                           MARK_END.format(tag="spec2nat")) + text[close:])
    write(path, text)

    # 6. level-up learnsets + pointers
    filtered = dropped_moves = 0
    blocks = []
    for s in species:
        sym = s["levelUpSym"]
        raw = lu.get(sym)
        entries = []
        if raw:
            for lm in re.finditer(r"LEVEL_UP_MOVE\(\s*(\d+)\s*,\s*(MOVE_\w+)\s*\)", raw):
                if lm.group(2) in moves_ok:
                    entries.append("    LEVEL_UP_MOVE(%2s, %s)," % (lm.group(1), lm.group(2)))
                else:
                    dropped_moves += 1
        if not entries:
            entries = ["    LEVEL_UP_MOVE( 1, MOVE_TACKLE),"]
            report.append("%s: empty learnset, gave Tackle" % s["const"])
        filtered += len(entries)
        blocks.append("static const struct LevelUpMove %s[] = {\n%s\n    LEVEL_UP_END\n};\n"
                      % (sym, "\n".join(entries)))
    path = tgt("src/data/pokemon/level_up_learnsets.h")
    text = strip_marker_block(read(path), "learnsets")
    write(path, text + "\n%s\n%s%s\n" % (MARK_START.format(tag="learnsets"),
                                         "\n".join(blocks), MARK_END.format(tag="learnsets")))
    block = "".join("    [%s] = %s,\n" % (s["const"], s["levelUpSym"]) for s in species)
    insert_block(tgt("src/data/pokemon/level_up_learnset_pointers.h"), "learnptrs",
                 block, r"^};", count=1)

    # 7. egg moves
    egg_blocks = []
    for s in species:
        mv = [m for m in eggm.get(s["eggMoveSym"] or "", []) if m in moves_ok]
        if mv:
            egg_blocks.append("\tegg_moves(%s,\n\t\t%s),\n" % (s["suffix"], ",\n\t\t".join(mv)))
    insert_block(tgt("src/data/pokemon/egg_moves.h"), "eggmoves", "".join(egg_blocks),
                 r"^\s*EGG_MOVES_TERMINATOR")

    # 8. evolutions + first stages + families
    ported_consts = {s["const"] for s in species}
    target_species = defined_constants(tgt("include/constants/species.h"), "SPECIES_")
    evo_lines = []
    for s in species:
        rows_list, seen_targets = [], set()
        for e in s["evolutions"]:
            if e[2] in seen_targets:
                continue
            if e[2] not in ported_consts and e[2] not in target_species:
                report.append("%s: evo target %s not in ROWE -> dropped" % (s["const"], e[2]))
                continue
            seen_targets.add(e[2])
            rows_list.append(e)
        s["evolutions"] = rows_list
        if rows_list:
            rows = ", ".join("{%s, %s, %s}" % e for e in rows_list)
            evo_lines.append("    [%s] = {%s},\n" % (s["const"], rows))
    for old, method, param, target_sp in CROSS_GEN_EVOS:
        evo_lines.append("    [%s] = {{%s, %d, %s}},\n" % (old, method, param, target_sp))
    path = tgt("src/data/pokemon/evolution.h")
    text = strip_marker_block(strip_marker_block(read(path), "evolutions"), "families")
    m = re.search(r"const struct SpeciesList gFirstStageTable\[POKEMON_FAMILIES\]", text)
    close = text.rfind("};", 0, m.start())
    text = (text[:close] + "%s\n%s%s\n" % (MARK_START.format(tag="evolutions"),
                                           "".join(evo_lines),
                                           MARK_END.format(tag="evolutions")) + text[close:])
    write(path, text)

    # families: base-stage Gen 9 species not evolving FROM anything
    evolve_targets = set()
    for s in species:
        for _, _, t in s["evolutions"]:
            evolve_targets.add(t)
    for t in CROSS_GEN_BASES:
        evolve_targets.add(t)
    new_families = [s["const"] for s in species if s["const"] not in evolve_targets]
    block = "".join("    {%s},\n" % c for c in new_families)
    path = tgt("src/data/pokemon/evolution.h")
    text = read(path)
    last_close = text.rfind("};")
    text = (text[:last_close] + "%s\n%s%s\n" % (MARK_START.format(tag="families"), block,
                                                MARK_END.format(tag="families")) +
            text[last_close:])
    write(path, text)
    pk = tgt("include/constants/pokemon.h")
    text = read(pk)
    text = re.sub(r"#define POKEMON_FAMILIES \d+( //GEN9 was \d+)?",
                  lambda m0: "#define POKEMON_FAMILIES %d //GEN9 was 384"
                             % (384 + len(new_families)), text)
    write(pk, text)

    # first_stage.h: species -> base species of its family
    base_of = dict(CROSS_GEN_BASES)
    chain_parent = {}
    for s in species:
        for _, _, t in s["evolutions"]:
            chain_parent[t] = s["const"]
    def find_base(c):
        seen = set()
        while c in chain_parent and c not in seen:
            seen.add(c)
            c = chain_parent[c]
        return base_of.get(c, c)
    block = "".join("    [%s] = {%s},\n" % (s["const"], find_base(s["const"]))
                    for s in species)
    insert_block(tgt("src/data/pokemon/first_stage.h"), "firststage", block, r"^};", count=1)

    # 9. graphics: copy assets + INCBINs + tables
    def gfx_dir(s):
        return s["suffix"].lower()
    def camel(s):
        return s["suffix"].title().replace("_", "")
    missing_gfx = []
    for s in species:
        src = os.path.join(DONOR, "graphics/pokemon", gfx_dir(s))
        dst = tgt("graphics/pokemon", gfx_dir(s))
        if not os.path.isdir(src):
            missing_gfx.append(s["const"])
            continue
        os.makedirs(dst, exist_ok=True)
        for f in ("front.png", "back.png", "normal.pal", "shiny.pal", "icon.png"):
            fsrc = os.path.join(src, f)
            if os.path.isfile(fsrc):
                shutil.copy(fsrc, os.path.join(dst, f))
            elif f == "front.png" and os.path.isfile(os.path.join(src, "anim_front.png")):
                from PIL import Image
                img = Image.open(os.path.join(src, "anim_front.png"))
                img.crop((0, 0, img.width, img.height // 2)).save(os.path.join(dst, f))
            else:
                missing_gfx.append(s["const"] + ":" + f)
    if missing_gfx:
        raise SystemExit("missing donor graphics: %s" % missing_gfx[:10])

    block = "".join(
        'const u32 gMonFrontPic_%(c)s[] = INCBIN_U32("graphics/pokemon/%(d)s/front.4bpp.lz");\n'
        'const u32 gMonBackPic_%(c)s[] = INCBIN_U32("graphics/pokemon/%(d)s/back.4bpp.lz");\n'
        'const u32 gMonPalette_%(c)s[] = INCBIN_U32("graphics/pokemon/%(d)s/normal.gbapal.lz");\n'
        'const u32 gMonShinyPalette_%(c)s[] = INCBIN_U32("graphics/pokemon/%(d)s/shiny.gbapal.lz");\n'
        'const u8 gMonIcon_%(c)s[] = INCBIN_U8("graphics/pokemon/%(d)s/icon.4bpp");\n'
        % {"c": camel(s), "d": gfx_dir(s)} for s in species)
    path = tgt("src/data/graphics/pokemon.h")
    text = strip_marker_block(read(path), "incbins")
    write(path, text + "\n%s\n%s%s\n" % (MARK_START.format(tag="incbins"), block,
                                         MARK_END.format(tag="incbins")))

    # extern declarations so tables in data.c/pokemon_icon.c can reference them
    block = "".join(
        "extern const u32 gMonFrontPic_%(c)s[];\n"
        "extern const u32 gMonBackPic_%(c)s[];\n"
        "extern const u32 gMonPalette_%(c)s[];\n"
        "extern const u32 gMonShinyPalette_%(c)s[];\n"
        "extern const u8 gMonIcon_%(c)s[];\n" % {"c": camel(s)} for s in species)
    path = tgt("include/graphics.h")
    text = strip_marker_block(read(path), "externs")
    m = re.search(r"^#endif", text[::-1])  # append before trailing #endif if present
    if "#endif" in text:
        pos = text.rfind("#endif")
        text = (text[:pos] + "%s\n%s%s\n" % (MARK_START.format(tag="externs"), block,
                                             MARK_END.format(tag="externs")) + text[pos:])
    else:
        text += "%s\n%s%s\n" % (MARK_START.format(tag="externs"), block,
                                MARK_END.format(tag="externs"))
    write(path, text)

    for tag, fname, line in [
        ("fronts", "front_pic_table.h",
         "    SPECIES_SPRITE(%(u)s, gMonFrontPic_%(c)s),\n"),
        ("backs", "back_pic_table.h",
         "    SPECIES_SPRITE(%(u)s, gMonBackPic_%(c)s),\n"),
        ("pals", "palette_table.h",
         "    SPECIES_PAL(%(u)s, gMonPalette_%(c)s),\n"),
        ("shinypals", "shiny_palette_table.h",
         "    SPECIES_PAL(%(u)s, gMonShinyPalette_%(c)s),\n"),
    ]:
        block = "".join(line % {"u": s["suffix"], "c": camel(s)} for s in species)
        insert_block(tgt("src/data/pokemon_graphics", fname), tag, block, r"^};", count=1)

    block = "".join(
        "    [%s] =\n    {\n        .size = 0x%02x,\n        .y_offset = %s,\n    },\n"
        % (s["const"], s["frontCoords"], s["frontYOff"]) for s in species)
    insert_block(tgt("src/data/pokemon_graphics/front_pic_coordinates.h"),
                 "frontcoords", block, r"^};", count=1)
    block = "".join(
        "    [%s] =\n    {\n        .size = 0x%02x,\n        .y_offset = %s,\n    },\n"
        % (s["const"], s["backCoords"], s["backYOff"]) for s in species)
    insert_block(tgt("src/data/pokemon_graphics/back_pic_coordinates.h"),
                 "backcoords", block, r"^};", count=1)

    # icons: two tables in src/pokemon_icon.c
    path = tgt("src/pokemon_icon.c")
    text = strip_marker_block(strip_marker_block(read(path), "icontable"), "iconpals")
    m = re.search(r"gMonIconTable\[\][^{]*\{", text)
    close = text.find("};", m.end())
    block = "".join("    [%s] = gMonIcon_%s,\n" % (s["const"], camel(s)) for s in species)
    text = (text[:close] + "%s\n%s%s\n" % (MARK_START.format(tag="icontable"), block,
                                           MARK_END.format(tag="icontable")) + text[close:])
    m = re.search(r"gMonIconPaletteIndices\[\][^{]*\{", text)
    close = text.find("};", m.end())
    block = "".join("    [%s] = %s,\n" % (s["const"], s["iconPalIndex"]) for s in species)
    text = (text[:close] + "%s\n%s%s\n" % (MARK_START.format(tag="iconpals"), block,
                                           MARK_END.format(tag="iconpals")) + text[close:])
    write(path, text)

    # 10. pokedex order arrays: insert sorted
    path = tgt("src/data/pokemon/pokedex_orders.h")
    text = read(path)
    entries = read(tgt("src/data/pokemon/pokedex_entries.h"))
    hw = {}  # natdex suffix -> (height, weight)
    for m in re.finditer(r"\[NATIONAL_DEX_(\w+)\][^}]*?\.height = (\d+),\s*\.weight = (\d+)",
                         entries, re.S):
        hw[m.group(1)] = (int(m.group(2)), int(m.group(3)))
    for s in species:
        hw[s["suffix"]] = (int(s["height"]), int(s["weight"]))
    names = {s["suffix"]: s["name"] for s in species}

    def insert_sorted(array_name, key):
        nonlocal text
        m = re.search(r"const u16 %s\[\] =\s*\{(.*?)\};" % array_name, text, re.S)
        body = m.group(1)
        existing = re.findall(r"NATIONAL_DEX_(\w+)", body)
        existing = [e for e in existing if e not in names]  # strip prior gen9 on re-run
        items = [(key(e), i, e) for i, e in enumerate(existing)]
        for s in species:
            k = key(s["suffix"])
            pos = len(items)
            for idx, (ik, _, _) in enumerate(items):
                if ik > k:
                    pos = idx
                    break
            items.insert(pos, (k, -1, s["suffix"]))
        new_body = "\n" + "".join("    NATIONAL_DEX_%s,\n" % e for _, _, e in items)
        text = text[:m.start(1)] + new_body + text[m.end(1):]

    display = lambda e: names.get(e, e.replace("_", " ").title())
    insert_sorted("gPokedexOrder_Alphabetical", lambda e: display(e).upper())
    insert_sorted("gPokedexOrder_Weight", lambda e: hw.get(e, (0, 0))[1])
    insert_sorted("gPokedexOrder_Height", lambda e: hw.get(e, (0, 0))[0])
    write(path, text)

    # ---- report
    rep_path = os.path.join(HERE, "gen9_port_report.txt")
    with open(rep_path, "w") as f:
        f.write("Ported %d Gen 9 species (natdex %d-%d)\n" %
                (len(species), FIRST_NATDEX, LAST_NATDEX))
        f.write("Level-up moves kept: %d, dropped (not in ROWE): %d\n" %
                (filtered, dropped_moves))
        f.write("New evolution families: %d (POKEMON_FAMILIES now %d)\n" %
                (len(new_families), 384 + len(new_families)))
        f.write("\n".join(report) + "\n")
    print("OK: %d species ported. Report: %s" % (len(species), rep_path))


if __name__ == "__main__":
    main()
