const struct MonCoords gTrainerBackPicCoords[] =
{
    [TRAINER_BACK_PIC_BRENDAN]               = {.size = 8, .y_offset = 4},
    [TRAINER_BACK_PIC_MAY]                   = {.size = 8, .y_offset = 4},
    [TRAINER_BACK_PIC_RED]                   = {.size = 8, .y_offset = 5},
    [TRAINER_BACK_PIC_LEAF]                  = {.size = 8, .y_offset = 5},
    [TRAINER_BACK_PIC_RUBY_SAPPHIRE_BRENDAN] = {.size = 8, .y_offset = 4},
    [TRAINER_BACK_PIC_RUBY_SAPPHIRE_MAY]     = {.size = 8, .y_offset = 4},
    [TRAINER_BACK_PIC_WALLY]                 = {.size = 8, .y_offset = 4},
    [TRAINER_BACK_PIC_STEVEN]                = {.size = 8, .y_offset = 4},
    [TRAINER_BACK_PIC_HILBERT]               = {.size = 8, .y_offset = 4},
// CHARMODE-SPRITES-START back-coords (generated by tools/character_mode/import_sprites.py)
    [TRAINER_BACK_PIC_CM_ETHAN] = {.size = 8, .y_offset = 4},
    [TRAINER_BACK_PIC_CM_KRIS] = {.size = 8, .y_offset = 4},
    [TRAINER_BACK_PIC_CM_LUCAS] = {.size = 8, .y_offset = 4},
    [TRAINER_BACK_PIC_CM_DAWN] = {.size = 8, .y_offset = 4},
    [TRAINER_BACK_PIC_CM_BARRY] = {.size = 8, .y_offset = 4},
// CHARMODE-SPRITES-END back-coords
// CHARMODE-SPRITES-START donor-back-coords (generated by tools/character_mode/import_donor_ow_backs.py)
    [TRAINER_BACK_PIC_CM_BLUE] = {.size = 8, .y_offset = 5},
    [TRAINER_BACK_PIC_CM_LANCE] = {.size = 8, .y_offset = 5},
    [TRAINER_BACK_PIC_CM_LYRA] = {.size = 8, .y_offset = 5},
    [TRAINER_BACK_PIC_CM_PHOEBE] = {.size = 8, .y_offset = 4},
    [TRAINER_BACK_PIC_CM_CALEM] = {.size = 8, .y_offset = 5},
    [TRAINER_BACK_PIC_CM_SERENA] = {.size = 8, .y_offset = 5},
    [TRAINER_BACK_PIC_CM_NOLAND] = {.size = 8, .y_offset = 4},
// CHARMODE-SPRITES-END donor-back-coords
};

const struct SpritePalette gTrainerBackPicPaletteTable[] =
{
    TRAINER_BACK_PAL(BRENDAN,               gTrainerPalette_Brendan),
    TRAINER_BACK_PAL(MAY,                   gTrainerPalette_May),
    TRAINER_BACK_PAL(RED,                   gTrainerBackPicPalette_Red),
    TRAINER_BACK_PAL(LEAF,                  gTrainerBackPicPalette_Leaf),
    TRAINER_BACK_PAL(RUBY_SAPPHIRE_BRENDAN, gTrainerPalette_RubySapphireBrendan),
    TRAINER_BACK_PAL(RUBY_SAPPHIRE_MAY,     gTrainerPalette_RubySapphireMay),
    TRAINER_BACK_PAL(WALLY,                 gTrainerPalette_Wally),
    TRAINER_BACK_PAL(STEVEN,                gTrainerPalette_Steven),
    TRAINER_BACK_PAL(HILBERT,               gTrainerPalette_Hilbert),
// CHARMODE-SPRITES-START back-pals (generated by tools/character_mode/import_sprites.py)
    TRAINER_BACK_PAL(CM_ETHAN, gTrainerBackPicPalette_CmEthan),
    TRAINER_BACK_PAL(CM_KRIS, gTrainerBackPicPalette_CmKris),
    TRAINER_BACK_PAL(CM_LUCAS, gTrainerBackPicPalette_CmLucas),
    TRAINER_BACK_PAL(CM_DAWN, gTrainerBackPicPalette_CmDawn),
    TRAINER_BACK_PAL(CM_BARRY, gTrainerBackPicPalette_CmBarry),
// CHARMODE-SPRITES-END back-pals
// CHARMODE-SPRITES-START donor-back-pals (generated by tools/character_mode/import_donor_ow_backs.py)
    TRAINER_BACK_PAL(CM_BLUE, gTrainerBackPicPalette_CmBlue),
    TRAINER_BACK_PAL(CM_LANCE, gTrainerBackPicPalette_CmLance),
    TRAINER_BACK_PAL(CM_LYRA, gTrainerBackPicPalette_CmLyra),
    TRAINER_BACK_PAL(CM_PHOEBE, gTrainerBackPicPalette_CmPhoebe),
    TRAINER_BACK_PAL(CM_CALEM, gTrainerBackPicPalette_CmCalem),
    TRAINER_BACK_PAL(CM_SERENA, gTrainerBackPicPalette_CmSerena),
    TRAINER_BACK_PAL(CM_NOLAND, gTrainerBackPicPalette_CmNoland),
// CHARMODE-SPRITES-END donor-back-pals
};

// this table goes functionally unused, since none of these pics are compressed
// and the place they would get extracted to gets overwritten later anyway
// the casts are so they'll play nice with the strict struct definition
const struct CompressedSpriteSheet gTrainerBackPicTable[] =
{
    (const u32 *)gTrainerBackPic_Brendan,             0x2000, TRAINER_BACK_PIC_BRENDAN,
    (const u32 *)gTrainerBackPic_May,                 0x2000, TRAINER_BACK_PIC_MAY,
    (const u32 *)gTrainerBackPic_Red,                 0x2800, TRAINER_BACK_PIC_RED,
    (const u32 *)gTrainerBackPic_Leaf,                0x2800, TRAINER_BACK_PIC_LEAF,
    (const u32 *)gTrainerBackPic_RubySapphireBrendan, 0x2000, TRAINER_BACK_PIC_RUBY_SAPPHIRE_BRENDAN,
    (const u32 *)gTrainerBackPic_RubySapphireMay,     0x2000, TRAINER_BACK_PIC_RUBY_SAPPHIRE_MAY,
    (const u32 *)gTrainerBackPic_Wally,               0x2000, TRAINER_BACK_PIC_WALLY,
    (const u32 *)gTrainerBackPic_Steven,              0x2000, TRAINER_BACK_PIC_STEVEN,
    (const u32 *)gTrainerBackPic_Hilbert,             0x2000, TRAINER_BACK_PIC_HILBERT,
// CHARMODE-SPRITES-START back-sheets (generated by tools/character_mode/import_sprites.py)
    (const u32 *)gTrainerBackPic_CmEthan, 0x2000, TRAINER_BACK_PIC_CM_ETHAN,
    (const u32 *)gTrainerBackPic_CmKris, 0x2000, TRAINER_BACK_PIC_CM_KRIS,
    (const u32 *)gTrainerBackPic_CmLucas, 0x2000, TRAINER_BACK_PIC_CM_LUCAS,
    (const u32 *)gTrainerBackPic_CmDawn, 0x2000, TRAINER_BACK_PIC_CM_DAWN,
    (const u32 *)gTrainerBackPic_CmBarry, 0x2000, TRAINER_BACK_PIC_CM_BARRY,
// CHARMODE-SPRITES-END back-sheets
// CHARMODE-SPRITES-START donor-back-sheets (generated by tools/character_mode/import_donor_ow_backs.py)
    (const u32 *)gTrainerBackPic_CmBlue, 0x2800, TRAINER_BACK_PIC_CM_BLUE,
    (const u32 *)gTrainerBackPic_CmLance, 0x2800, TRAINER_BACK_PIC_CM_LANCE,
    (const u32 *)gTrainerBackPic_CmLyra, 0x2800, TRAINER_BACK_PIC_CM_LYRA,
    (const u32 *)gTrainerBackPic_CmPhoebe, 0x2000, TRAINER_BACK_PIC_CM_PHOEBE,
    (const u32 *)gTrainerBackPic_CmCalem, 0x2800, TRAINER_BACK_PIC_CM_CALEM,
    (const u32 *)gTrainerBackPic_CmSerena, 0x2800, TRAINER_BACK_PIC_CM_SERENA,
    (const u32 *)gTrainerBackPic_CmNoland, 0x2000, TRAINER_BACK_PIC_CM_NOLAND,
// CHARMODE-SPRITES-END donor-back-sheets
};
