static const union AnimCmd gAnimCmd_Brendan_1[] =
{
    ANIMCMD_FRAME(0, 24),
    ANIMCMD_FRAME(1, 9),
    ANIMCMD_FRAME(2, 24),
    ANIMCMD_FRAME(0, 9),
    ANIMCMD_FRAME(3, 50),
    ANIMCMD_END,
};

static const union AnimCmd gAnimCmd_May_Steven_1[] =
{
    ANIMCMD_FRAME(0, 24),
    ANIMCMD_FRAME(1, 9),
    ANIMCMD_FRAME(2, 24),
    ANIMCMD_FRAME(0, 9),
    ANIMCMD_FRAME(3, 50),
    ANIMCMD_END,
};

static const union AnimCmd gAnimCmd_Wally_1[] =
{
    ANIMCMD_FRAME(0, 24),
    ANIMCMD_FRAME(1, 9),
    ANIMCMD_FRAME(2, 24),
    ANIMCMD_FRAME(0, 9),
    ANIMCMD_FRAME(3, 50),
    ANIMCMD_END,
};

static const union AnimCmd gAnimCmd_Red_1[] =
{
    ANIMCMD_FRAME(1, 20),
    ANIMCMD_FRAME(2, 6),
    ANIMCMD_FRAME(3, 6),
    ANIMCMD_FRAME(4, 24),
    ANIMCMD_FRAME(0, 1),
    ANIMCMD_END,
};

static const union AnimCmd gAnimCmd_Leaf_1[] =
{
    ANIMCMD_FRAME(1, 20),
    ANIMCMD_FRAME(2, 6),
    ANIMCMD_FRAME(3, 6),
    ANIMCMD_FRAME(4, 24),
    ANIMCMD_FRAME(0, 1),
    ANIMCMD_END,
};

static const union AnimCmd gAnimCmd_RubySapphireBrendan_1[] =
{
    ANIMCMD_FRAME(0, 24),
    ANIMCMD_FRAME(1, 9),
    ANIMCMD_FRAME(2, 24),
    ANIMCMD_FRAME(0, 9),
    ANIMCMD_FRAME(3, 50),
    ANIMCMD_END,
};

static const union AnimCmd gAnimCmd_RubySapphireMay_1[] =
{
    ANIMCMD_FRAME(0, 24),
    ANIMCMD_FRAME(1, 9),
    ANIMCMD_FRAME(2, 24),
    ANIMCMD_FRAME(0, 9),
    ANIMCMD_FRAME(3, 50),
    ANIMCMD_END,
};

static const union AnimCmd *const sBackAnims_Brendan[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_Brendan_1,
};

static const union AnimCmd *const sBackAnims_May[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_May_Steven_1,
};

static const union AnimCmd *const sBackAnims_Red[] =
{
    sAnim_GeneralFrame0,
    gAnimCmd_Red_1,
};

static const union AnimCmd *const sBackAnims_Leaf[] =
{
    sAnim_GeneralFrame0,
    gAnimCmd_Leaf_1,
};

static const union AnimCmd *const sBackAnims_RubySapphireBrendan[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_RubySapphireBrendan_1,
};

static const union AnimCmd *const sBackAnims_RubySapphireMay[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_RubySapphireMay_1,
};

static const union AnimCmd *const sBackAnims_Wally[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_Wally_1,
};

static const union AnimCmd *const sBackAnims_Steven[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_May_Steven_1,
};

static const union AnimCmd *const sBackAnims_Hilbert[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_May_Steven_1,
};

// CHARMODE-SPRITES-START back-anims (generated by tools/character_mode/import_sprites.py)
static const union AnimCmd *const sBackAnims_CmEthan[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_May_Steven_1,
};
static const union AnimCmd *const sBackAnims_CmKris[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_May_Steven_1,
};
static const union AnimCmd *const sBackAnims_CmLucas[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_May_Steven_1,
};
static const union AnimCmd *const sBackAnims_CmDawn[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_May_Steven_1,
};
static const union AnimCmd *const sBackAnims_CmBarry[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_May_Steven_1,
};
// CHARMODE-SPRITES-END back-anims
// CHARMODE-SPRITES-START donor-back-anims (generated by tools/character_mode/import_donor_ow_backs.py)
static const union AnimCmd *const sBackAnims_CmBlue[] =
{
    sAnim_GeneralFrame0,
    gAnimCmd_Red_1,
};
static const union AnimCmd *const sBackAnims_CmLance[] =
{
    sAnim_GeneralFrame0,
    gAnimCmd_Red_1,
};
static const union AnimCmd *const sBackAnims_CmLyra[] =
{
    sAnim_GeneralFrame0,
    gAnimCmd_Red_1,
};
static const union AnimCmd *const sBackAnims_CmPhoebe[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_May_Steven_1,
};
static const union AnimCmd *const sBackAnims_CmCalem[] =
{
    sAnim_GeneralFrame0,
    gAnimCmd_Red_1,
};
static const union AnimCmd *const sBackAnims_CmSerena[] =
{
    sAnim_GeneralFrame0,
    gAnimCmd_Red_1,
};
static const union AnimCmd *const sBackAnims_CmNoland[] =
{
    sAnim_GeneralFrame3,
    gAnimCmd_May_Steven_1,
};
// CHARMODE-SPRITES-END donor-back-anims
const union AnimCmd *const *const gTrainerBackAnimsPtrTable[] =
{
    [TRAINER_BACK_PIC_BRENDAN]               = sBackAnims_Brendan,
    [TRAINER_BACK_PIC_MAY]                   = sBackAnims_May,
    [TRAINER_BACK_PIC_RED]                   = sBackAnims_Red,
    [TRAINER_BACK_PIC_LEAF]                  = sBackAnims_Leaf,
    [TRAINER_BACK_PIC_RUBY_SAPPHIRE_BRENDAN] = sBackAnims_RubySapphireBrendan,
    [TRAINER_BACK_PIC_RUBY_SAPPHIRE_MAY]     = sBackAnims_RubySapphireMay,
    [TRAINER_BACK_PIC_WALLY]                 = sBackAnims_Wally,
    [TRAINER_BACK_PIC_STEVEN]                = sBackAnims_Steven,
    [TRAINER_BACK_PIC_HILBERT]               = sBackAnims_Hilbert,
// CHARMODE-SPRITES-START back-anim-ptrs (generated by tools/character_mode/import_sprites.py)
    [TRAINER_BACK_PIC_CM_ETHAN] = sBackAnims_CmEthan,
    [TRAINER_BACK_PIC_CM_KRIS] = sBackAnims_CmKris,
    [TRAINER_BACK_PIC_CM_LUCAS] = sBackAnims_CmLucas,
    [TRAINER_BACK_PIC_CM_DAWN] = sBackAnims_CmDawn,
    [TRAINER_BACK_PIC_CM_BARRY] = sBackAnims_CmBarry,
// CHARMODE-SPRITES-END back-anim-ptrs
// CHARMODE-SPRITES-START donor-back-anim-ptrs (generated by tools/character_mode/import_donor_ow_backs.py)
    [TRAINER_BACK_PIC_CM_BLUE] = sBackAnims_CmBlue,
    [TRAINER_BACK_PIC_CM_LANCE] = sBackAnims_CmLance,
    [TRAINER_BACK_PIC_CM_LYRA] = sBackAnims_CmLyra,
    [TRAINER_BACK_PIC_CM_PHOEBE] = sBackAnims_CmPhoebe,
    [TRAINER_BACK_PIC_CM_CALEM] = sBackAnims_CmCalem,
    [TRAINER_BACK_PIC_CM_SERENA] = sBackAnims_CmSerena,
    [TRAINER_BACK_PIC_CM_NOLAND] = sBackAnims_CmNoland,
// CHARMODE-SPRITES-END donor-back-anim-ptrs
};
