gText_FlyingTaxi_Intro::
    .string "Hello. I pilot one of the\n"
    .string "Flying Taxis.\p"
    .string "Do you need a lift?$"

gText_FlyingTaxi_WhereDoYouWantToGo::
    .string "Where do you want to go?$"

gText_FlyingTaxi_Goodbye::
    .string "Keep us in mind the next time\n"
    .string "you need a ride!$"
	
//Gym Items
	Special_Gym_Text_Explain_Amulet_Coin:
	.string "This item is an Amulet Coin\p"
	.string "Its an Item that must be\n"
	.string "held by your First Pokémon.\p"
	.string "It doubles the money you get\n"
	.string "from a Fight with a Trainer.$"
	
	Special_Gym_Text_Explain_Item_Finder:
	.string "This item is the Item Finder.\p"
	.string "This will help you find Hidden\n"
	.string "Items while you travel.$"
	
	Special_Gym_Text_Explain_Good_Rod:
	.string "This item is the Good Rod.\n"
	.string "You can use it to find stronger\l"
	.string "Pokémon than the Old Rod.$"
	
	Special_Gym_Text_Explain_Oval_Charm:
	.string "This item is an Oval Charm.\p"
	.string "Its an item that doubles the\n"
	.string "possibilites of getting an Baby\l"
	.string "Pokémon from the Daycare.$"

	Special_Gym_Text_Explain_Catching_Charm:
	.string "This item is a Catching Charm.\p"
	.string "It increase the chance of getting a\n"
	.string "critical catch.$"
	
	Special_Gym_Text_Explain_Super_Rod:
	.string "This item is the Super Rod.\p"
	.string "Its the ultimate Rod you can find,\n"
	.string "its used by the pros for catching\l"
	.string "the strongest water Pokémon.$"
	
	Special_Gym_Text_Explain_Lucky_Egg:
	.string "This item is a Lucky Egg.\p"
	.string "Make your Pokémon Hold it\n"
	.string "and it will gain double the Exp.$"
	
	Special_Gym_Text_Explain_Mega_Bracelet:
	.string "This item is the Mega Bracelet.\p"
	.string "This item will make you able\n"
	.string "to Mega Evolve your Pokémon\p"
	.string "Pressing Start with a Pokémon\n"
	.string "that can Mega Evolve in Battle.$"
	
	Special_Gym_Text_Explain_Shiny_Charm:
	.string "This item is the Shiny Charm.\p"
	.string "Its an item that doubles the\n"
	.string "possibilites of getting a shiny\l"
	.string "Pokémon.$"

	Special_Gym_Text_Explain_Exp_Charm:
	.string "This item is the Exp Charm.\p"
	.string "Carry it and every Pokémon in\n"
	.string "your party will earn more Exp.$"

	Special_Gym_Text_Explain_Fly_Charm:
	.string "This item is the Fly Charm.\p"
	.string "Carry it and you can take to the\n"
	.string "skies from anywhere you please.$"

	Special_Gym_Text_Explain_Fly_Tool:
	.string "This item is the Fly Tool.\p"
	.string "With it you no longer need a\n"
	.string "Pokémon that knows how to Fly.$"

	Special_Gym_Text_Explain_Effort_Tool:
	.string "This item is the Effort Tool.\p"
	.string "Use it to control how your\n"
	.string "Pokémon spend their effort.$"

	Special_Gym_Text_Explain_Alpha_Charm:
	.string "This item is the Alpha Charm.\p"
	.string "Its an item that raises the\n"
	.string "chance of meeting an Alpha\l"
	.string "Pokémon in the wild.$"

	Special_Gym_Text_Explain_Wonder_Charm:
	.string "This item is the Wonder Charm.\p"
	.string "Its an item that improves what\n"
	.string "you receive from Wonder Trades.$"

	Special_Gym_Text_Explain_Master_Ball:
	.string "This is a Master Ball.\p"
	.string "It will catch any Pokémon\n"
	.string "without fail. Use it wisely!$"

	Special_Gym_Text_Explain_Old_Save:
	.string "It looks like you are using\n"
	.string "an old Save File.\p"
	.string "I need to update your Items and\n"
	.string "some other things before you can\l"
	.string "continue.$"
