# 1 "data/scripts/abnormal_weather.pory"

# 2 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute114North::
# 3 "data/scripts/abnormal_weather.pory"
	setmetatile 7, 3, METATILE_Fallarbor_RedCaveEntrance_Top, 1
# 4 "data/scripts/abnormal_weather.pory"
	setmetatile 7, 4, METATILE_Fallarbor_RedCaveEntrance_Bottom, 0
# 5 "data/scripts/abnormal_weather.pory"
	return
# 6 "data/scripts/abnormal_weather.pory"

# 7 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute114South::
# 8 "data/scripts/abnormal_weather.pory"
	setmetatile 6, 45, METATILE_Fallarbor_BrownCaveEntrance_Top, 1
# 9 "data/scripts/abnormal_weather.pory"
	setmetatile 6, 46, METATILE_Fallarbor_BrownCaveEntrance_Bottom, 0
# 10 "data/scripts/abnormal_weather.pory"
	return
# 11 "data/scripts/abnormal_weather.pory"

# 12 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute115West::
# 13 "data/scripts/abnormal_weather.pory"
	setmetatile 21, 5, METATILE_Fallarbor_BrownCaveEntrance_Top, 1
# 14 "data/scripts/abnormal_weather.pory"
	setmetatile 21, 6, METATILE_Fallarbor_BrownCaveEntrance_Bottom, 0
# 15 "data/scripts/abnormal_weather.pory"
	return
# 16 "data/scripts/abnormal_weather.pory"

# 17 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute115East::
# 18 "data/scripts/abnormal_weather.pory"
	setmetatile 36, 9, METATILE_Fallarbor_BrownCaveEntrance_Top, 1
# 19 "data/scripts/abnormal_weather.pory"
	setmetatile 36, 10, METATILE_Fallarbor_BrownCaveEntrance_Bottom, 0
# 20 "data/scripts/abnormal_weather.pory"
	return
# 21 "data/scripts/abnormal_weather.pory"

# 22 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute116North::
# 23 "data/scripts/abnormal_weather.pory"
	setmetatile 59, 12, METATILE_General_CaveEntrance_Top, 1
# 24 "data/scripts/abnormal_weather.pory"
	setmetatile 59, 13, METATILE_General_CaveEntrance_Bottom, 0
# 25 "data/scripts/abnormal_weather.pory"
	return
# 26 "data/scripts/abnormal_weather.pory"

# 27 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute116South::
# 28 "data/scripts/abnormal_weather.pory"
	setmetatile 79, 5, METATILE_General_CaveEntrance_Top, 1
# 29 "data/scripts/abnormal_weather.pory"
	setmetatile 79, 6, METATILE_General_CaveEntrance_Bottom, 0
# 30 "data/scripts/abnormal_weather.pory"
	return
# 31 "data/scripts/abnormal_weather.pory"

# 32 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute118East::
# 33 "data/scripts/abnormal_weather.pory"
	setmetatile 42, 5, METATILE_General_CaveEntrance_Top, 1
# 34 "data/scripts/abnormal_weather.pory"
	setmetatile 42, 6, METATILE_General_CaveEntrance_Bottom, 0
# 35 "data/scripts/abnormal_weather.pory"
	return
# 36 "data/scripts/abnormal_weather.pory"

# 37 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute118West::
# 38 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 5, METATILE_General_CaveEntrance_Top, 1
# 39 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 6, METATILE_General_CaveEntrance_Bottom, 0
# 40 "data/scripts/abnormal_weather.pory"
	return
# 41 "data/scripts/abnormal_weather.pory"

# 42 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute105North::
# 43 "data/scripts/abnormal_weather.pory"
	setmetatile 10, 28, METATILE_General_RoughWater, 0
# 44 "data/scripts/abnormal_weather.pory"
	setmetatile 11, 28, METATILE_General_RoughWater, 0
# 45 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 29, METATILE_General_RoughWater, 0
# 46 "data/scripts/abnormal_weather.pory"
	setmetatile 10, 29, METATILE_General_RoughDeepWater, 0
# 47 "data/scripts/abnormal_weather.pory"
	setmetatile 11, 29, METATILE_General_RoughDeepWater, 0
# 48 "data/scripts/abnormal_weather.pory"
	setmetatile 12, 29, METATILE_General_RoughWater, 0
# 49 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 30, METATILE_General_RoughWater, 0
# 50 "data/scripts/abnormal_weather.pory"
	setmetatile 10, 30, METATILE_General_RoughDeepWater, 0
# 51 "data/scripts/abnormal_weather.pory"
	setmetatile 11, 30, METATILE_General_RoughDeepWater, 0
# 52 "data/scripts/abnormal_weather.pory"
	setmetatile 12, 30, METATILE_General_RoughWater, 0
# 53 "data/scripts/abnormal_weather.pory"
	setmetatile 10, 31, METATILE_General_RoughWater, 0
# 54 "data/scripts/abnormal_weather.pory"
	setmetatile 11, 31, METATILE_General_RoughWater, 0
# 55 "data/scripts/abnormal_weather.pory"
	return
# 56 "data/scripts/abnormal_weather.pory"

# 57 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute105South::
# 58 "data/scripts/abnormal_weather.pory"
	setmetatile 20, 53, METATILE_General_RoughWater, 0
# 59 "data/scripts/abnormal_weather.pory"
	setmetatile 21, 53, METATILE_General_RoughWater, 0
# 60 "data/scripts/abnormal_weather.pory"
	setmetatile 19, 54, METATILE_General_RoughWater, 0
# 61 "data/scripts/abnormal_weather.pory"
	setmetatile 20, 54, METATILE_General_RoughDeepWater, 0
# 62 "data/scripts/abnormal_weather.pory"
	setmetatile 21, 54, METATILE_General_RoughDeepWater, 0
# 63 "data/scripts/abnormal_weather.pory"
	setmetatile 22, 54, METATILE_General_RoughWater, 0
# 64 "data/scripts/abnormal_weather.pory"
	setmetatile 19, 55, METATILE_General_RoughWater, 0
# 65 "data/scripts/abnormal_weather.pory"
	setmetatile 20, 55, METATILE_General_RoughDeepWater, 0
# 66 "data/scripts/abnormal_weather.pory"
	setmetatile 21, 55, METATILE_General_RoughDeepWater, 0
# 67 "data/scripts/abnormal_weather.pory"
	setmetatile 22, 55, METATILE_General_RoughWater, 0
# 68 "data/scripts/abnormal_weather.pory"
	setmetatile 20, 56, METATILE_General_RoughWater, 0
# 69 "data/scripts/abnormal_weather.pory"
	setmetatile 21, 56, METATILE_General_RoughWater, 0
# 70 "data/scripts/abnormal_weather.pory"
	return
# 71 "data/scripts/abnormal_weather.pory"

# 72 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute125West::
# 73 "data/scripts/abnormal_weather.pory"
	setmetatile 8, 16, METATILE_General_RoughWater, 0
# 74 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 16, METATILE_General_RoughWater, 0
# 75 "data/scripts/abnormal_weather.pory"
	setmetatile 7, 17, METATILE_General_RoughWater, 0
# 76 "data/scripts/abnormal_weather.pory"
	setmetatile 8, 17, METATILE_General_RoughDeepWater, 0
# 77 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 17, METATILE_General_RoughDeepWater, 0
# 78 "data/scripts/abnormal_weather.pory"
	setmetatile 10, 17, METATILE_General_RoughWater, 0
# 79 "data/scripts/abnormal_weather.pory"
	setmetatile 7, 18, METATILE_General_RoughWater, 0
# 80 "data/scripts/abnormal_weather.pory"
	setmetatile 8, 18, METATILE_General_RoughDeepWater, 0
# 81 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 18, METATILE_General_RoughDeepWater, 0
# 82 "data/scripts/abnormal_weather.pory"
	setmetatile 10, 18, METATILE_General_RoughWater, 0
# 83 "data/scripts/abnormal_weather.pory"
	setmetatile 8, 19, METATILE_General_RoughWater, 0
# 84 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 19, METATILE_General_RoughWater, 0
# 85 "data/scripts/abnormal_weather.pory"
	return
# 86 "data/scripts/abnormal_weather.pory"

# 87 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute125East::
# 88 "data/scripts/abnormal_weather.pory"
	setmetatile 53, 18, METATILE_General_RoughWater, 0
# 89 "data/scripts/abnormal_weather.pory"
	setmetatile 54, 18, METATILE_General_RoughWater, 0
# 90 "data/scripts/abnormal_weather.pory"
	setmetatile 52, 19, METATILE_General_RoughWater, 0
# 91 "data/scripts/abnormal_weather.pory"
	setmetatile 53, 19, METATILE_General_RoughDeepWater, 0
# 92 "data/scripts/abnormal_weather.pory"
	setmetatile 54, 19, METATILE_General_RoughDeepWater, 0
# 93 "data/scripts/abnormal_weather.pory"
	setmetatile 55, 19, METATILE_General_RoughWater, 0
# 94 "data/scripts/abnormal_weather.pory"
	setmetatile 52, 20, METATILE_General_RoughWater, 0
# 95 "data/scripts/abnormal_weather.pory"
	setmetatile 53, 20, METATILE_General_RoughDeepWater, 0
# 96 "data/scripts/abnormal_weather.pory"
	setmetatile 54, 20, METATILE_General_RoughDeepWater, 0
# 97 "data/scripts/abnormal_weather.pory"
	setmetatile 55, 20, METATILE_General_RoughWater, 0
# 98 "data/scripts/abnormal_weather.pory"
	setmetatile 53, 21, METATILE_General_RoughWater, 0
# 99 "data/scripts/abnormal_weather.pory"
	setmetatile 54, 21, METATILE_General_RoughWater, 0
# 100 "data/scripts/abnormal_weather.pory"
	return
# 101 "data/scripts/abnormal_weather.pory"

# 102 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute127North::
# 103 "data/scripts/abnormal_weather.pory"
	setmetatile 57, 9, METATILE_General_RoughWater, 0
# 104 "data/scripts/abnormal_weather.pory"
	setmetatile 58, 9, METATILE_General_RoughWater, 0
# 105 "data/scripts/abnormal_weather.pory"
	setmetatile 56, 10, METATILE_General_RoughWater, 0
# 106 "data/scripts/abnormal_weather.pory"
	setmetatile 57, 10, METATILE_General_RoughDeepWater, 0
# 107 "data/scripts/abnormal_weather.pory"
	setmetatile 58, 10, METATILE_General_RoughDeepWater, 0
# 108 "data/scripts/abnormal_weather.pory"
	setmetatile 59, 10, METATILE_General_RoughWater, 0
# 109 "data/scripts/abnormal_weather.pory"
	setmetatile 56, 11, METATILE_General_RoughWater, 0
# 110 "data/scripts/abnormal_weather.pory"
	setmetatile 57, 11, METATILE_General_RoughDeepWater, 0
# 111 "data/scripts/abnormal_weather.pory"
	setmetatile 58, 11, METATILE_General_RoughDeepWater, 0
# 112 "data/scripts/abnormal_weather.pory"
	setmetatile 59, 11, METATILE_General_RoughWater, 0
# 113 "data/scripts/abnormal_weather.pory"
	setmetatile 57, 12, METATILE_General_RoughWater, 0
# 114 "data/scripts/abnormal_weather.pory"
	setmetatile 58, 12, METATILE_General_RoughWater, 0
# 115 "data/scripts/abnormal_weather.pory"
	return
# 116 "data/scripts/abnormal_weather.pory"

# 117 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute127South::
# 118 "data/scripts/abnormal_weather.pory"
	setmetatile 61, 30, METATILE_General_RoughWater, 0
# 119 "data/scripts/abnormal_weather.pory"
	setmetatile 62, 30, METATILE_General_RoughWater, 0
# 120 "data/scripts/abnormal_weather.pory"
	setmetatile 60, 31, METATILE_General_RoughWater, 0
# 121 "data/scripts/abnormal_weather.pory"
	setmetatile 61, 31, METATILE_General_RoughDeepWater, 0
# 122 "data/scripts/abnormal_weather.pory"
	setmetatile 62, 31, METATILE_General_RoughDeepWater, 0
# 123 "data/scripts/abnormal_weather.pory"
	setmetatile 63, 31, METATILE_General_RoughWater, 0
# 124 "data/scripts/abnormal_weather.pory"
	setmetatile 60, 32, METATILE_General_RoughWater, 0
# 125 "data/scripts/abnormal_weather.pory"
	setmetatile 61, 32, METATILE_General_RoughDeepWater, 0
# 126 "data/scripts/abnormal_weather.pory"
	setmetatile 62, 32, METATILE_General_RoughDeepWater, 0
# 127 "data/scripts/abnormal_weather.pory"
	setmetatile 63, 32, METATILE_General_RoughWater, 0
# 128 "data/scripts/abnormal_weather.pory"
	setmetatile 61, 33, METATILE_General_RoughWater, 0
# 129 "data/scripts/abnormal_weather.pory"
	setmetatile 62, 33, METATILE_General_RoughWater, 0
# 130 "data/scripts/abnormal_weather.pory"
	return
# 131 "data/scripts/abnormal_weather.pory"

# 132 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute129West::
# 133 "data/scripts/abnormal_weather.pory"
	setmetatile 16, 14, METATILE_General_RoughWater, 0
# 134 "data/scripts/abnormal_weather.pory"
	setmetatile 17, 14, METATILE_General_RoughWater, 0
# 135 "data/scripts/abnormal_weather.pory"
	setmetatile 15, 15, METATILE_General_RoughWater, 0
# 136 "data/scripts/abnormal_weather.pory"
	setmetatile 16, 15, METATILE_General_RoughDeepWater, 0
# 137 "data/scripts/abnormal_weather.pory"
	setmetatile 17, 15, METATILE_General_RoughDeepWater, 0
# 138 "data/scripts/abnormal_weather.pory"
	setmetatile 18, 15, METATILE_General_RoughWater, 0
# 139 "data/scripts/abnormal_weather.pory"
	setmetatile 15, 16, METATILE_General_RoughWater, 0
# 140 "data/scripts/abnormal_weather.pory"
	setmetatile 16, 16, METATILE_General_RoughDeepWater, 0
# 141 "data/scripts/abnormal_weather.pory"
	setmetatile 17, 16, METATILE_General_RoughDeepWater, 0
# 142 "data/scripts/abnormal_weather.pory"
	setmetatile 18, 16, METATILE_General_RoughWater, 0
# 143 "data/scripts/abnormal_weather.pory"
	setmetatile 16, 17, METATILE_General_RoughWater, 0
# 144 "data/scripts/abnormal_weather.pory"
	setmetatile 17, 17, METATILE_General_RoughWater, 0
# 145 "data/scripts/abnormal_weather.pory"
	return
# 146 "data/scripts/abnormal_weather.pory"

# 147 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_PlaceTilesRoute129East::
# 148 "data/scripts/abnormal_weather.pory"
	setmetatile 42, 19, METATILE_General_RoughWater, 0
# 149 "data/scripts/abnormal_weather.pory"
	setmetatile 43, 19, METATILE_General_RoughWater, 0
# 150 "data/scripts/abnormal_weather.pory"
	setmetatile 41, 20, METATILE_General_RoughWater, 0
# 151 "data/scripts/abnormal_weather.pory"
	setmetatile 42, 20, METATILE_General_RoughDeepWater, 0
# 152 "data/scripts/abnormal_weather.pory"
	setmetatile 43, 20, METATILE_General_RoughDeepWater, 0
# 153 "data/scripts/abnormal_weather.pory"
	setmetatile 44, 20, METATILE_General_RoughWater, 0
# 154 "data/scripts/abnormal_weather.pory"
	setmetatile 41, 21, METATILE_General_RoughWater, 0
# 155 "data/scripts/abnormal_weather.pory"
	setmetatile 42, 21, METATILE_General_RoughDeepWater, 0
# 156 "data/scripts/abnormal_weather.pory"
	setmetatile 43, 21, METATILE_General_RoughDeepWater, 0
# 157 "data/scripts/abnormal_weather.pory"
	setmetatile 44, 21, METATILE_General_RoughWater, 0
# 158 "data/scripts/abnormal_weather.pory"
	setmetatile 42, 22, METATILE_General_RoughWater, 0
# 159 "data/scripts/abnormal_weather.pory"
	setmetatile 43, 22, METATILE_General_RoughWater, 0
# 160 "data/scripts/abnormal_weather.pory"
	return
# 161 "data/scripts/abnormal_weather.pory"

# 162 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_HideMapNamePopup::
# 163 "data/scripts/abnormal_weather.pory"
	setflag FLAG_HIDE_MAP_NAME_POPUP
# 164 "data/scripts/abnormal_weather.pory"
	return
# 165 "data/scripts/abnormal_weather.pory"

# 166 "data/scripts/abnormal_weather.pory"
AbnormalWeather_StartKyogreWeather::
# 167 "data/scripts/abnormal_weather.pory"
	setweather WEATHER_DOWNPOUR
# 168 "data/scripts/abnormal_weather.pory"
	return
# 169 "data/scripts/abnormal_weather.pory"

# 170 "data/scripts/abnormal_weather.pory"
AbnormalWeather_StartGroudonWeather::
# 171 "data/scripts/abnormal_weather.pory"
	setweather WEATHER_DROUGHT
# 172 "data/scripts/abnormal_weather.pory"
	return
# 173 "data/scripts/abnormal_weather.pory"

# 174 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_EndEventAndCleanup_1::
# 175 "data/scripts/abnormal_weather.pory"
	lockall
# 176 "data/scripts/abnormal_weather.pory"
	compare VAR_ABNORMAL_WEATHER_LOCATION, MARINE_CAVE_LOCATIONS_START
# 177 "data/scripts/abnormal_weather.pory"
	goto_if_ge AbnormalWeather_EventScript_ShowRainEndedMessage
# 178 "data/scripts/abnormal_weather.pory"
	goto AbnormalWeather_EventScript_ShowSunEndedMessage
# 179 "data/scripts/abnormal_weather.pory"
	end
# 180 "data/scripts/abnormal_weather.pory"

# 181 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_EndEventAndCleanup_2::
# 182 "data/scripts/abnormal_weather.pory"
	closemessage
# 183 "data/scripts/abnormal_weather.pory"
	fadescreenswapbuffers FADE_TO_BLACK
# 184 "data/scripts/abnormal_weather.pory"
	setweather WEATHER_SUNNY
# 185 "data/scripts/abnormal_weather.pory"
	doweather
# 186 "data/scripts/abnormal_weather.pory"
	call AbnormalWeather_EventScript_CleanupMapTiles
# 187 "data/scripts/abnormal_weather.pory"
	special DrawWholeMapView
# 188 "data/scripts/abnormal_weather.pory"
	setvar VAR_ABNORMAL_WEATHER_LOCATION, ABNORMAL_WEATHER_NONE
# 189 "data/scripts/abnormal_weather.pory"
	setvar VAR_SHOULD_END_ABNORMAL_WEATHER, 0
# 190 "data/scripts/abnormal_weather.pory"
	clearflag FLAG_HIDE_MAP_NAME_POPUP
# 191 "data/scripts/abnormal_weather.pory"
	fadescreenswapbuffers FADE_FROM_BLACK
# 192 "data/scripts/abnormal_weather.pory"
	releaseall
# 193 "data/scripts/abnormal_weather.pory"
	end
# 194 "data/scripts/abnormal_weather.pory"

# 195 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_ShowRainEndedMessage::
# 196 "data/scripts/abnormal_weather.pory"
	msgbox gText_AbnormalWeatherEnded_Rain, MSGBOX_DEFAULT
# 197 "data/scripts/abnormal_weather.pory"
	goto AbnormalWeather_EventScript_EndEventAndCleanup_2
# 198 "data/scripts/abnormal_weather.pory"
	end
# 199 "data/scripts/abnormal_weather.pory"

# 200 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_ShowSunEndedMessage::
# 201 "data/scripts/abnormal_weather.pory"
	msgbox gText_AbnormalWeatherEnded_Sun, MSGBOX_DEFAULT
# 202 "data/scripts/abnormal_weather.pory"
	goto AbnormalWeather_EventScript_EndEventAndCleanup_2
# 203 "data/scripts/abnormal_weather.pory"
	end
# 204 "data/scripts/abnormal_weather.pory"

# 205 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupMapTiles::
# 206 "data/scripts/abnormal_weather.pory"
	switch VAR_ABNORMAL_WEATHER_LOCATION
# 207 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_114_NORTH, AbnormalWeather_EventScript_CleanupRoute114North
# 208 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_114_SOUTH, AbnormalWeather_EventScript_CleanupRoute114South
# 209 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_115_WEST, AbnormalWeather_EventScript_CleanupRoute115West
# 210 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_115_EAST, AbnormalWeather_EventScript_CleanupRoute115East
# 211 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_116_NORTH, AbnormalWeather_EventScript_CleanupRoute116North
# 212 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_116_SOUTH, AbnormalWeather_EventScript_CleanupRoute116South
# 213 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_118_EAST, AbnormalWeather_EventScript_CleanupRoute118East
# 214 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_118_WEST, AbnormalWeather_EventScript_CleanupRoute118West
# 215 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_105_NORTH, AbnormalWeather_EventScript_CleanupRoute105North
# 216 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_105_SOUTH, AbnormalWeather_EventScript_CleanupRoute105South
# 217 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_125_WEST, AbnormalWeather_EventScript_CleanupRoute125West
# 218 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_125_EAST, AbnormalWeather_EventScript_CleanupRoute125East
# 219 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_127_NORTH, AbnormalWeather_EventScript_CleanupRoute127North
# 220 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_127_SOUTH, AbnormalWeather_EventScript_CleanupRoute127South
# 221 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_129_WEST, AbnormalWeather_EventScript_CleanupRoute129West
# 222 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_129_EAST, AbnormalWeather_EventScript_CleanupRoute129East
# 223 "data/scripts/abnormal_weather.pory"
	return
# 224 "data/scripts/abnormal_weather.pory"

# 225 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute114North::
# 226 "data/scripts/abnormal_weather.pory"
	setmetatile 7, 3, METATILE_Fallarbor_RedRockWall, 1
# 227 "data/scripts/abnormal_weather.pory"
	setmetatile 7, 4, METATILE_Fallarbor_RedRockWall, 1
# 228 "data/scripts/abnormal_weather.pory"
	return
# 229 "data/scripts/abnormal_weather.pory"

# 230 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute114South::
# 231 "data/scripts/abnormal_weather.pory"
	setmetatile 6, 45, METATILE_Fallarbor_BrownRockWall, 1
# 232 "data/scripts/abnormal_weather.pory"
	setmetatile 6, 46, METATILE_Fallarbor_BrownRockWall, 1
# 233 "data/scripts/abnormal_weather.pory"
	return
# 234 "data/scripts/abnormal_weather.pory"

# 235 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute115West::
# 236 "data/scripts/abnormal_weather.pory"
	setmetatile 21, 5, METATILE_Fallarbor_BrownRockWall, 1
# 237 "data/scripts/abnormal_weather.pory"
	setmetatile 21, 6, METATILE_Fallarbor_BrownRockWall, 1
# 238 "data/scripts/abnormal_weather.pory"
	return
# 239 "data/scripts/abnormal_weather.pory"

# 240 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute115East::
# 241 "data/scripts/abnormal_weather.pory"
	setmetatile 36, 9, METATILE_Fallarbor_BrownRockWall, 1
# 242 "data/scripts/abnormal_weather.pory"
	setmetatile 36, 10, METATILE_Fallarbor_BrownRockWall, 1
# 243 "data/scripts/abnormal_weather.pory"
	return
# 244 "data/scripts/abnormal_weather.pory"

# 245 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute116North::
# 246 "data/scripts/abnormal_weather.pory"
	setmetatile 59, 12, METATILE_General_RockWall_RockBase, 1
# 247 "data/scripts/abnormal_weather.pory"
	setmetatile 59, 13, METATILE_General_RockWall_RockBase, 1
# 248 "data/scripts/abnormal_weather.pory"
	return
# 249 "data/scripts/abnormal_weather.pory"

# 250 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute116South::
# 251 "data/scripts/abnormal_weather.pory"
	setmetatile 79, 5, METATILE_General_RockWall_RockBase, 1
# 252 "data/scripts/abnormal_weather.pory"
	setmetatile 79, 6, METATILE_General_RockWall_RockBase, 1
# 253 "data/scripts/abnormal_weather.pory"
	return
# 254 "data/scripts/abnormal_weather.pory"

# 255 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute118East::
# 256 "data/scripts/abnormal_weather.pory"
	setmetatile 42, 5, METATILE_General_RockWall_RockBase, 1
# 257 "data/scripts/abnormal_weather.pory"
	setmetatile 42, 6, METATILE_General_RockWall_GrassBase, 1
# 258 "data/scripts/abnormal_weather.pory"
	return
# 259 "data/scripts/abnormal_weather.pory"

# 260 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute118West::
# 261 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 5, METATILE_General_RockWall_RockBase, 1
# 262 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 6, METATILE_General_RockWall_GrassBase, 1
# 263 "data/scripts/abnormal_weather.pory"
	return
# 264 "data/scripts/abnormal_weather.pory"

# 265 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute105North::
# 266 "data/scripts/abnormal_weather.pory"
	setmetatile 10, 28, METATILE_General_CalmWater, 0
# 267 "data/scripts/abnormal_weather.pory"
	setmetatile 11, 28, METATILE_General_CalmWater, 0
# 268 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 29, METATILE_General_CalmWater, 0
# 269 "data/scripts/abnormal_weather.pory"
	setmetatile 10, 29, METATILE_General_CalmWater, 0
# 270 "data/scripts/abnormal_weather.pory"
	setmetatile 11, 29, METATILE_General_CalmWater, 0
# 271 "data/scripts/abnormal_weather.pory"
	setmetatile 12, 29, METATILE_General_CalmWater, 0
# 272 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 30, METATILE_General_CalmWater, 0
# 273 "data/scripts/abnormal_weather.pory"
	setmetatile 10, 30, METATILE_General_CalmWater, 0
# 274 "data/scripts/abnormal_weather.pory"
	setmetatile 11, 30, METATILE_General_CalmWater, 0
# 275 "data/scripts/abnormal_weather.pory"
	setmetatile 12, 30, METATILE_General_CalmWater, 0
# 276 "data/scripts/abnormal_weather.pory"
	setmetatile 10, 31, METATILE_General_CalmWater, 0
# 277 "data/scripts/abnormal_weather.pory"
	setmetatile 11, 31, METATILE_General_CalmWater, 0
# 278 "data/scripts/abnormal_weather.pory"
	return
# 279 "data/scripts/abnormal_weather.pory"

# 280 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute105South::
# 281 "data/scripts/abnormal_weather.pory"
	setmetatile 20, 53, METATILE_General_CalmWater, 0
# 282 "data/scripts/abnormal_weather.pory"
	setmetatile 21, 53, METATILE_General_CalmWater, 0
# 283 "data/scripts/abnormal_weather.pory"
	setmetatile 19, 54, METATILE_General_CalmWater, 0
# 284 "data/scripts/abnormal_weather.pory"
	setmetatile 20, 54, METATILE_General_CalmWater, 0
# 285 "data/scripts/abnormal_weather.pory"
	setmetatile 21, 54, METATILE_General_CalmWater, 0
# 286 "data/scripts/abnormal_weather.pory"
	setmetatile 22, 54, METATILE_General_CalmWater, 0
# 287 "data/scripts/abnormal_weather.pory"
	setmetatile 19, 55, METATILE_General_CalmWater, 0
# 288 "data/scripts/abnormal_weather.pory"
	setmetatile 20, 55, METATILE_General_CalmWater, 0
# 289 "data/scripts/abnormal_weather.pory"
	setmetatile 21, 55, METATILE_General_CalmWater, 0
# 290 "data/scripts/abnormal_weather.pory"
	setmetatile 22, 55, METATILE_General_CalmWater, 0
# 291 "data/scripts/abnormal_weather.pory"
	setmetatile 20, 56, METATILE_General_CalmWater, 0
# 292 "data/scripts/abnormal_weather.pory"
	setmetatile 21, 56, METATILE_General_CalmWater, 0
# 293 "data/scripts/abnormal_weather.pory"
	return
# 294 "data/scripts/abnormal_weather.pory"

# 295 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute125West::
# 296 "data/scripts/abnormal_weather.pory"
	setmetatile 8, 16, METATILE_General_CalmWater, 0
# 297 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 16, METATILE_General_CalmWater, 0
# 298 "data/scripts/abnormal_weather.pory"
	setmetatile 7, 17, METATILE_General_CalmWater, 0
# 299 "data/scripts/abnormal_weather.pory"
	setmetatile 8, 17, METATILE_General_CalmWater, 0
# 300 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 17, METATILE_General_CalmWater, 0
# 301 "data/scripts/abnormal_weather.pory"
	setmetatile 10, 17, METATILE_General_CalmWater, 0
# 302 "data/scripts/abnormal_weather.pory"
	setmetatile 7, 18, METATILE_General_CalmWater, 0
# 303 "data/scripts/abnormal_weather.pory"
	setmetatile 8, 18, METATILE_General_CalmWater, 0
# 304 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 18, METATILE_General_CalmWater, 0
# 305 "data/scripts/abnormal_weather.pory"
	setmetatile 10, 18, METATILE_General_CalmWater, 0
# 306 "data/scripts/abnormal_weather.pory"
	setmetatile 8, 19, METATILE_General_CalmWater, 0
# 307 "data/scripts/abnormal_weather.pory"
	setmetatile 9, 19, METATILE_General_CalmWater, 0
# 308 "data/scripts/abnormal_weather.pory"
	return
# 309 "data/scripts/abnormal_weather.pory"

# 310 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute125East::
# 311 "data/scripts/abnormal_weather.pory"
	setmetatile 53, 18, METATILE_General_CalmWater, 0
# 312 "data/scripts/abnormal_weather.pory"
	setmetatile 54, 18, METATILE_General_CalmWater, 0
# 313 "data/scripts/abnormal_weather.pory"
	setmetatile 52, 19, METATILE_General_CalmWater, 0
# 314 "data/scripts/abnormal_weather.pory"
	setmetatile 53, 19, METATILE_General_CalmWater, 0
# 315 "data/scripts/abnormal_weather.pory"
	setmetatile 54, 19, METATILE_General_CalmWater, 0
# 316 "data/scripts/abnormal_weather.pory"
	setmetatile 55, 19, METATILE_General_CalmWater, 0
# 317 "data/scripts/abnormal_weather.pory"
	setmetatile 52, 20, METATILE_General_CalmWater, 0
# 318 "data/scripts/abnormal_weather.pory"
	setmetatile 53, 20, METATILE_General_CalmWater, 0
# 319 "data/scripts/abnormal_weather.pory"
	setmetatile 54, 20, METATILE_General_CalmWater, 0
# 320 "data/scripts/abnormal_weather.pory"
	setmetatile 55, 20, METATILE_General_CalmWater, 0
# 321 "data/scripts/abnormal_weather.pory"
	setmetatile 53, 21, METATILE_General_CalmWater, 0
# 322 "data/scripts/abnormal_weather.pory"
	setmetatile 54, 21, METATILE_General_CalmWater, 0
# 323 "data/scripts/abnormal_weather.pory"
	return
# 324 "data/scripts/abnormal_weather.pory"

# 325 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute127North::
# 326 "data/scripts/abnormal_weather.pory"
	setmetatile 57, 9, METATILE_General_CalmWater, 0
# 327 "data/scripts/abnormal_weather.pory"
	setmetatile 58, 9, METATILE_General_CalmWater, 0
# 328 "data/scripts/abnormal_weather.pory"
	setmetatile 56, 10, METATILE_General_CalmWater, 0
# 329 "data/scripts/abnormal_weather.pory"
	setmetatile 57, 10, METATILE_General_CalmWater, 0
# 330 "data/scripts/abnormal_weather.pory"
	setmetatile 58, 10, METATILE_General_CalmWater, 0
# 331 "data/scripts/abnormal_weather.pory"
	setmetatile 59, 10, METATILE_General_CalmWater, 0
# 332 "data/scripts/abnormal_weather.pory"
	setmetatile 56, 11, METATILE_General_CalmWater, 0
# 333 "data/scripts/abnormal_weather.pory"
	setmetatile 57, 11, METATILE_General_CalmWater, 0
# 334 "data/scripts/abnormal_weather.pory"
	setmetatile 58, 11, METATILE_General_CalmWater, 0
# 335 "data/scripts/abnormal_weather.pory"
	setmetatile 59, 11, METATILE_General_CalmWater, 0
# 336 "data/scripts/abnormal_weather.pory"
	setmetatile 57, 12, METATILE_General_CalmWater, 0
# 337 "data/scripts/abnormal_weather.pory"
	setmetatile 58, 12, METATILE_General_CalmWater, 0
# 338 "data/scripts/abnormal_weather.pory"
	return
# 339 "data/scripts/abnormal_weather.pory"

# 340 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute127South::
# 341 "data/scripts/abnormal_weather.pory"
	setmetatile 61, 30, METATILE_General_CalmWater, 0
# 342 "data/scripts/abnormal_weather.pory"
	setmetatile 62, 30, METATILE_General_CalmWater, 0
# 343 "data/scripts/abnormal_weather.pory"
	setmetatile 60, 31, METATILE_General_CalmWater, 0
# 344 "data/scripts/abnormal_weather.pory"
	setmetatile 61, 31, METATILE_General_CalmWater, 0
# 345 "data/scripts/abnormal_weather.pory"
	setmetatile 62, 31, METATILE_General_CalmWater, 0
# 346 "data/scripts/abnormal_weather.pory"
	setmetatile 63, 31, METATILE_General_CalmWater, 0
# 347 "data/scripts/abnormal_weather.pory"
	setmetatile 60, 32, METATILE_General_CalmWater, 0
# 348 "data/scripts/abnormal_weather.pory"
	setmetatile 61, 32, METATILE_General_CalmWater, 0
# 349 "data/scripts/abnormal_weather.pory"
	setmetatile 62, 32, METATILE_General_CalmWater, 0
# 350 "data/scripts/abnormal_weather.pory"
	setmetatile 63, 32, METATILE_General_CalmWater, 0
# 351 "data/scripts/abnormal_weather.pory"
	setmetatile 61, 33, METATILE_General_CalmWater, 0
# 352 "data/scripts/abnormal_weather.pory"
	setmetatile 62, 33, METATILE_General_CalmWater, 0
# 353 "data/scripts/abnormal_weather.pory"
	return
# 354 "data/scripts/abnormal_weather.pory"

# 355 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute129West::
# 356 "data/scripts/abnormal_weather.pory"
	setmetatile 16, 14, METATILE_General_CalmWater, 0
# 357 "data/scripts/abnormal_weather.pory"
	setmetatile 17, 14, METATILE_General_CalmWater, 0
# 358 "data/scripts/abnormal_weather.pory"
	setmetatile 15, 15, METATILE_General_CalmWater, 0
# 359 "data/scripts/abnormal_weather.pory"
	setmetatile 16, 15, METATILE_General_CalmWater, 0
# 360 "data/scripts/abnormal_weather.pory"
	setmetatile 17, 15, METATILE_General_CalmWater, 0
# 361 "data/scripts/abnormal_weather.pory"
	setmetatile 18, 15, METATILE_General_CalmWater, 0
# 362 "data/scripts/abnormal_weather.pory"
	setmetatile 15, 16, METATILE_General_CalmWater, 0
# 363 "data/scripts/abnormal_weather.pory"
	setmetatile 16, 16, METATILE_General_CalmWater, 0
# 364 "data/scripts/abnormal_weather.pory"
	setmetatile 17, 16, METATILE_General_CalmWater, 0
# 365 "data/scripts/abnormal_weather.pory"
	setmetatile 18, 16, METATILE_General_CalmWater, 0
# 366 "data/scripts/abnormal_weather.pory"
	setmetatile 16, 17, METATILE_General_CalmWater, 0
# 367 "data/scripts/abnormal_weather.pory"
	setmetatile 17, 17, METATILE_General_CalmWater, 0
# 368 "data/scripts/abnormal_weather.pory"
	return
# 369 "data/scripts/abnormal_weather.pory"

# 370 "data/scripts/abnormal_weather.pory"
AbnormalWeather_EventScript_CleanupRoute129East::
# 371 "data/scripts/abnormal_weather.pory"
	setmetatile 42, 19, METATILE_General_CalmWater, 0
# 372 "data/scripts/abnormal_weather.pory"
	setmetatile 43, 19, METATILE_General_CalmWater, 0
# 373 "data/scripts/abnormal_weather.pory"
	setmetatile 41, 20, METATILE_General_CalmWater, 0
# 374 "data/scripts/abnormal_weather.pory"
	setmetatile 42, 20, METATILE_General_CalmWater, 0
# 375 "data/scripts/abnormal_weather.pory"
	setmetatile 43, 20, METATILE_General_CalmWater, 0
# 376 "data/scripts/abnormal_weather.pory"
	setmetatile 44, 20, METATILE_General_CalmWater, 0
# 377 "data/scripts/abnormal_weather.pory"
	setmetatile 41, 21, METATILE_General_CalmWater, 0
# 378 "data/scripts/abnormal_weather.pory"
	setmetatile 42, 21, METATILE_General_CalmWater, 0
# 379 "data/scripts/abnormal_weather.pory"
	setmetatile 43, 21, METATILE_General_CalmWater, 0
# 380 "data/scripts/abnormal_weather.pory"
	setmetatile 44, 21, METATILE_General_CalmWater, 0
# 381 "data/scripts/abnormal_weather.pory"
	setmetatile 42, 22, METATILE_General_CalmWater, 0
# 382 "data/scripts/abnormal_weather.pory"
	setmetatile 43, 22, METATILE_General_CalmWater, 0
# 383 "data/scripts/abnormal_weather.pory"
	return
# 384 "data/scripts/abnormal_weather.pory"

# 385 "data/scripts/abnormal_weather.pory"
AbnormalWeather_Underwater_SetupEscapeWarp::
# 386 "data/scripts/abnormal_weather.pory"
	switch VAR_ABNORMAL_WEATHER_LOCATION
# 387 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_105_NORTH, AbnormalWeather_Underwater_SetupEscapeWarpRoute105North
# 388 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_105_SOUTH, AbnormalWeather_Underwater_SetupEscapeWarpRoute105South
# 389 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_125_WEST, AbnormalWeather_Underwater_SetupEscapeWarpRoute125West
# 390 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_125_EAST, AbnormalWeather_Underwater_SetupEscapeWarpRoute125East
# 391 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_127_NORTH, AbnormalWeather_Underwater_SetupEscapeWarpRoute127North
# 392 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_127_SOUTH, AbnormalWeather_Underwater_SetupEscapeWarpRoute127South
# 393 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_129_WEST, AbnormalWeather_Underwater_SetupEscapeWarpRoute129West
# 394 "data/scripts/abnormal_weather.pory"
	case ABNORMAL_WEATHER_ROUTE_129_EAST, AbnormalWeather_Underwater_SetupEscapeWarpRoute129East
# 395 "data/scripts/abnormal_weather.pory"
	return
# 396 "data/scripts/abnormal_weather.pory"

# 397 "data/scripts/abnormal_weather.pory"
AbnormalWeather_Underwater_SetupEscapeWarpRoute105North::
# 398 "data/scripts/abnormal_weather.pory"
	setescapewarp MAP_ROUTE105, 255, 11, 29
# 399 "data/scripts/abnormal_weather.pory"
	return
# 400 "data/scripts/abnormal_weather.pory"

# 401 "data/scripts/abnormal_weather.pory"
AbnormalWeather_Underwater_SetupEscapeWarpRoute105South::
# 402 "data/scripts/abnormal_weather.pory"
	setescapewarp MAP_ROUTE105, 255, 21, 54
# 403 "data/scripts/abnormal_weather.pory"
	return
# 404 "data/scripts/abnormal_weather.pory"

# 405 "data/scripts/abnormal_weather.pory"
AbnormalWeather_Underwater_SetupEscapeWarpRoute125West::
# 406 "data/scripts/abnormal_weather.pory"
	setescapewarp MAP_ROUTE125, 255, 9, 17
# 407 "data/scripts/abnormal_weather.pory"
	return
# 408 "data/scripts/abnormal_weather.pory"

# 409 "data/scripts/abnormal_weather.pory"
AbnormalWeather_Underwater_SetupEscapeWarpRoute125East::
# 410 "data/scripts/abnormal_weather.pory"
	setescapewarp MAP_ROUTE125, 255, 54, 19
# 411 "data/scripts/abnormal_weather.pory"
	return
# 412 "data/scripts/abnormal_weather.pory"

# 413 "data/scripts/abnormal_weather.pory"
AbnormalWeather_Underwater_SetupEscapeWarpRoute127North::
# 414 "data/scripts/abnormal_weather.pory"
	setescapewarp MAP_ROUTE127, 255, 58, 10
# 415 "data/scripts/abnormal_weather.pory"
	return
# 416 "data/scripts/abnormal_weather.pory"

# 417 "data/scripts/abnormal_weather.pory"
AbnormalWeather_Underwater_SetupEscapeWarpRoute127South::
# 418 "data/scripts/abnormal_weather.pory"
	setescapewarp MAP_ROUTE127, 255, 62, 31
# 419 "data/scripts/abnormal_weather.pory"
	return
# 420 "data/scripts/abnormal_weather.pory"

# 421 "data/scripts/abnormal_weather.pory"
AbnormalWeather_Underwater_SetupEscapeWarpRoute129West::
# 422 "data/scripts/abnormal_weather.pory"
	setescapewarp MAP_ROUTE129, 255, 17, 15
# 423 "data/scripts/abnormal_weather.pory"
	return
# 424 "data/scripts/abnormal_weather.pory"

# 425 "data/scripts/abnormal_weather.pory"
AbnormalWeather_Underwater_SetupEscapeWarpRoute129East::
# 426 "data/scripts/abnormal_weather.pory"
	setescapewarp MAP_ROUTE129, 255, 43, 20
# 427 "data/scripts/abnormal_weather.pory"
	return
