# 1 "data/scripts/berry_blender.pory"

# 2 "data/scripts/berry_blender.pory"
@ Note: local IDs shared with scripts.inc for LilycoveCity_ContestLobby
# 3 "data/scripts/berry_blender.pory"
.set LOCALID_MAN, 3
# 4 "data/scripts/berry_blender.pory"
.set LOCALID_BOY, 9
# 5 "data/scripts/berry_blender.pory"
.set LOCALID_TWIN, 10
# 6 "data/scripts/berry_blender.pory"
.set LOCALID_POKEFAN_F, 15
# 7 "data/scripts/berry_blender.pory"
.set LOCALID_EXPERT_M, 16
# 8 "data/scripts/berry_blender.pory"
.set LOCALID_GIRL, 17
# 9 "data/scripts/berry_blender.pory"

# 10 "data/scripts/berry_blender.pory"
.set NUM_OPPONENTS, VAR_0x8009
# 11 "data/scripts/berry_blender.pory"

# 12 "data/scripts/berry_blender.pory"
BerryBlender_Text_WantToMakePokeblocks:
# 13 "data/scripts/berry_blender.pory"
	.string "Oh? Did you want to make some {POKEBLOCK}S\n"
# 14 "data/scripts/berry_blender.pory"
	.string "with this old-timer?$"
# 15 "data/scripts/berry_blender.pory"

# 16 "data/scripts/berry_blender.pory"
BerryBlender_Text_Excellent:
# 17 "data/scripts/berry_blender.pory"
	.string "Excellent!$"
# 18 "data/scripts/berry_blender.pory"

# 19 "data/scripts/berry_blender.pory"
BerryBlender_Text_MadeOldTimerSad:
# 20 "data/scripts/berry_blender.pory"
	.string "Oh…\n"
# 21 "data/scripts/berry_blender.pory"
	.string "You've made this old-timer sad…$"
# 22 "data/scripts/berry_blender.pory"

# 23 "data/scripts/berry_blender.pory"
BerryBlender_Text_KnowHowToMakePokeblocks:
# 24 "data/scripts/berry_blender.pory"
	.string "Do you know how to make a {POKEBLOCK}?$"
# 25 "data/scripts/berry_blender.pory"

# 26 "data/scripts/berry_blender.pory"
BerryBlender_Text_LetsBerryBlender:
# 27 "data/scripts/berry_blender.pory"
	.string "Let's get started, then!\p"
# 28 "data/scripts/berry_blender.pory"
	.string "Let's Berry Blender!$"
# 29 "data/scripts/berry_blender.pory"

# 30 "data/scripts/berry_blender.pory"
BerryBlender_Text_ExplainBerryBlending:
# 31 "data/scripts/berry_blender.pory"
	.string "Okay, a little explanation, then.\p"
# 32 "data/scripts/berry_blender.pory"
	.string "Oh, don't worry, it's quite simple.\p"
# 33 "data/scripts/berry_blender.pory"
	.string "When the Blender's arrow comes to\n"
# 34 "data/scripts/berry_blender.pory"
	.string "your marker, just press the A Button.\p"
# 35 "data/scripts/berry_blender.pory"
	.string "That's all you have to do.\n"
# 36 "data/scripts/berry_blender.pory"
	.string "You'll see how easy it is when you try.$"
# 37 "data/scripts/berry_blender.pory"

# 38 "data/scripts/berry_blender.pory"
BerryBlender_Text_DontHaveAnyBerries:
# 39 "data/scripts/berry_blender.pory"
	.string "Oh?\n"
# 40 "data/scripts/berry_blender.pory"
	.string "You don't have any Berries?\p"
# 41 "data/scripts/berry_blender.pory"
	.string "If you don't have any Berries,\n"
# 42 "data/scripts/berry_blender.pory"
	.string "you can't make any {POKEBLOCK}S.$"
# 43 "data/scripts/berry_blender.pory"

# 44 "data/scripts/berry_blender.pory"
BerryBlender_Text_CanHaveOneOfMyBerries:
# 45 "data/scripts/berry_blender.pory"
	.string "Well, that won't do at all now, will it?\p"
# 46 "data/scripts/berry_blender.pory"
	.string "If you don't mind leftovers, you can\n"
# 47 "data/scripts/berry_blender.pory"
	.string "have one of my Berries.\p"
# 48 "data/scripts/berry_blender.pory"
	.string "That way, we could make some {POKEBLOCK}S\n"
# 49 "data/scripts/berry_blender.pory"
	.string "together using the Berry Blender.$"
# 50 "data/scripts/berry_blender.pory"

# 51 "data/scripts/berry_blender.pory"
BerryBlender_Text_DontHaveAnyBerriesToSpare:
# 52 "data/scripts/berry_blender.pory"
	.string "If I had some Berries left over,\n"
# 53 "data/scripts/berry_blender.pory"
	.string "I'd gladly give you one…\p"
# 54 "data/scripts/berry_blender.pory"
	.string "But, I don't have any to spare today.\n"
# 55 "data/scripts/berry_blender.pory"
	.string "We'll have to do this another time.$"
# 56 "data/scripts/berry_blender.pory"

# 57 "data/scripts/berry_blender.pory"
BerryBlender_Text_PokeblockCaseIsFull:
# 58 "data/scripts/berry_blender.pory"
	.string "But your {POKEBLOCK} Case is full.\p"
# 59 "data/scripts/berry_blender.pory"
	.string "You should use some {POKEBLOCK}S before\n"
# 60 "data/scripts/berry_blender.pory"
	.string "you come see me again.$"
# 61 "data/scripts/berry_blender.pory"

# 62 "data/scripts/berry_blender.pory"
BerryBlender_Text_DontHavePokeblockCase:
# 63 "data/scripts/berry_blender.pory"
	.string "But you don't have a {POKEBLOCK} Case.\p"
# 64 "data/scripts/berry_blender.pory"
	.string "You should get a {POKEBLOCK} Case and then\n"
# 65 "data/scripts/berry_blender.pory"
	.string "come see me.$"
# 66 "data/scripts/berry_blender.pory"

# 67 "data/scripts/berry_blender.pory"
BerryBlender_Text_LetsGetBlendingAlready:
# 68 "data/scripts/berry_blender.pory"
	.string "Let's get blending already!$"
# 69 "data/scripts/berry_blender.pory"

# 70 "data/scripts/berry_blender.pory"
BerryBlender_Text_WhatKindOfPokeblockWillIGet:
# 71 "data/scripts/berry_blender.pory"
	.string "I wonder what kind of {POKEBLOCK} I'll get?\n"
# 72 "data/scripts/berry_blender.pory"
	.string "This is so exciting!$"
# 73 "data/scripts/berry_blender.pory"

# 74 "data/scripts/berry_blender.pory"
BerryBlender_Text_WantToBlendPokeblocksWithUs:
# 75 "data/scripts/berry_blender.pory"
	.string "Hi, there! Did you want to blend some\n"
# 76 "data/scripts/berry_blender.pory"
	.string "{POKEBLOCK}S with us?$"
# 77 "data/scripts/berry_blender.pory"

# 78 "data/scripts/berry_blender.pory"
BerryBlender_Text_Okay:
# 79 "data/scripts/berry_blender.pory"
	.string "Okay!$"
# 80 "data/scripts/berry_blender.pory"

# 81 "data/scripts/berry_blender.pory"
BerryBlender_Text_ThatsTooBad:
# 82 "data/scripts/berry_blender.pory"
	.string "That's too bad…\p"
# 83 "data/scripts/berry_blender.pory"
	.string "But we'll always be around whenever\n"
# 84 "data/scripts/berry_blender.pory"
	.string "you get the urge to blend!$"
# 85 "data/scripts/berry_blender.pory"

# 86 "data/scripts/berry_blender.pory"
BerryBlender_Text_KnowHowToMakePokeblocks2:
# 87 "data/scripts/berry_blender.pory"
	.string "Of course, you do know how to\n"
# 88 "data/scripts/berry_blender.pory"
	.string "blend {POKEBLOCK}S, don't you?$"
# 89 "data/scripts/berry_blender.pory"

# 90 "data/scripts/berry_blender.pory"
BerryBlender_Text_LetsBerryBlender2:
# 91 "data/scripts/berry_blender.pory"
	.string "Let's get started, then!\p"
# 92 "data/scripts/berry_blender.pory"
	.string "Let's Berry Blender!$"
# 93 "data/scripts/berry_blender.pory"

# 94 "data/scripts/berry_blender.pory"
BerryBlender_Text_ExplainBerryBlending2:
# 95 "data/scripts/berry_blender.pory"
	.string "Okay!\n"
# 96 "data/scripts/berry_blender.pory"
	.string "Let me explain it to you!\p"
# 97 "data/scripts/berry_blender.pory"
	.string "When the spinning Blender's arrow\n"
# 98 "data/scripts/berry_blender.pory"
	.string "reaches your marker, just press\l"
# 99 "data/scripts/berry_blender.pory"
	.string "the A Button.\p"
# 100 "data/scripts/berry_blender.pory"
	.string "That's all it takes.\n"
# 101 "data/scripts/berry_blender.pory"
	.string "Pretty easy, don't you think?$"
# 102 "data/scripts/berry_blender.pory"

# 103 "data/scripts/berry_blender.pory"
BerryBlender_Text_DontHaveAnyBerries2:
# 104 "data/scripts/berry_blender.pory"
	.string "Oh, but wait a second here…\n"
# 105 "data/scripts/berry_blender.pory"
	.string "You don't have any Berries.\p"
# 106 "data/scripts/berry_blender.pory"
	.string "You can't make any {POKEBLOCK}S without\n"
# 107 "data/scripts/berry_blender.pory"
	.string "Berries…\p"
# 108 "data/scripts/berry_blender.pory"
	.string "We'll always be around whenever you\n"
# 109 "data/scripts/berry_blender.pory"
	.string "get hold of some Berries to blend.$"
# 110 "data/scripts/berry_blender.pory"

# 111 "data/scripts/berry_blender.pory"
BerryBlender_Text_PokeblockCaseIsFull2:
# 112 "data/scripts/berry_blender.pory"
	.string "Oh, but wait a second here…\n"
# 113 "data/scripts/berry_blender.pory"
	.string "Your {POKEBLOCK} Case is full.\p"
# 114 "data/scripts/berry_blender.pory"
	.string "You should use some {POKEBLOCK}S and\n"
# 115 "data/scripts/berry_blender.pory"
	.string "then come back.$"
# 116 "data/scripts/berry_blender.pory"

# 117 "data/scripts/berry_blender.pory"
BerryBlender_Text_DontHavePokeblockCase2:
# 118 "data/scripts/berry_blender.pory"
	.string "Oh, but wait a second here…\n"
# 119 "data/scripts/berry_blender.pory"
	.string "You don't have a {POKEBLOCK} Case.\p"
# 120 "data/scripts/berry_blender.pory"
	.string "You should get a {POKEBLOCK} Case and\n"
# 121 "data/scripts/berry_blender.pory"
	.string "then come back.$"
# 122 "data/scripts/berry_blender.pory"

# 123 "data/scripts/berry_blender.pory"
@ Unused
# 124 "data/scripts/berry_blender.pory"
BerryBlender_Text_MakePokeblocksWithOurGroup:
# 125 "data/scripts/berry_blender.pory"
	.string "Oh, hello! Did you want to make some\n"
# 126 "data/scripts/berry_blender.pory"
	.string "{POKEBLOCK}S with our little group?$"
# 127 "data/scripts/berry_blender.pory"

# 128 "data/scripts/berry_blender.pory"
BerryBlender_Text_OhDear:
# 129 "data/scripts/berry_blender.pory"
	.string "Oh, dear!$"
# 130 "data/scripts/berry_blender.pory"

# 131 "data/scripts/berry_blender.pory"
BerryBlender_Text_LeftUsInShock:
# 132 "data/scripts/berry_blender.pory"
	.string "Oh, dear me…\p"
# 133 "data/scripts/berry_blender.pory"
	.string "You've left us in shock!$"
# 134 "data/scripts/berry_blender.pory"

# 135 "data/scripts/berry_blender.pory"
BerryBlender_Text_KnowHowToMakePokeblocks3:
# 136 "data/scripts/berry_blender.pory"
	.string "Naturally, you know how to make\n"
# 137 "data/scripts/berry_blender.pory"
	.string "{POKEBLOCK}S, don't you?$"
# 138 "data/scripts/berry_blender.pory"

# 139 "data/scripts/berry_blender.pory"
BerryBlender_Text_LetsBerryBlender3:
# 140 "data/scripts/berry_blender.pory"
	.string "Okay, dear!\n"
# 141 "data/scripts/berry_blender.pory"
	.string "Let's get started!\p"
# 142 "data/scripts/berry_blender.pory"
	.string "Let's Berry Blender!$"
# 143 "data/scripts/berry_blender.pory"

# 144 "data/scripts/berry_blender.pory"
BerryBlender_Text_ExplainBerryBlending3:
# 145 "data/scripts/berry_blender.pory"
	.string "Oh, dear!\p"
# 146 "data/scripts/berry_blender.pory"
	.string "Then, I'll explain it to you nicely.\p"
# 147 "data/scripts/berry_blender.pory"
	.string "When the Blender's arrow spins to\n"
# 148 "data/scripts/berry_blender.pory"
	.string "your marker, press the A Button.\p"
# 149 "data/scripts/berry_blender.pory"
	.string "That's all it takes.\n"
# 150 "data/scripts/berry_blender.pory"
	.string "Isn't it simple?$"
# 151 "data/scripts/berry_blender.pory"

# 152 "data/scripts/berry_blender.pory"
BerryBlender_Text_DontHaveAnyBerries3:
# 153 "data/scripts/berry_blender.pory"
	.string "You don't have any Berries,\n"
# 154 "data/scripts/berry_blender.pory"
	.string "do you?\p"
# 155 "data/scripts/berry_blender.pory"
	.string "If you don't have any Berries,\n"
# 156 "data/scripts/berry_blender.pory"
	.string "you can't make any {POKEBLOCK}S.\p"
# 157 "data/scripts/berry_blender.pory"
	.string "We'll always be making {POKEBLOCK}S here,\n"
# 158 "data/scripts/berry_blender.pory"
	.string "so let's make some together when\l"
# 159 "data/scripts/berry_blender.pory"
	.string "you get a Berry or two.$"
# 160 "data/scripts/berry_blender.pory"

# 161 "data/scripts/berry_blender.pory"
BerryBlender_Text_PokeblockCaseIsFull3:
# 162 "data/scripts/berry_blender.pory"
	.string "Your {POKEBLOCK} Case is full,\n"
# 163 "data/scripts/berry_blender.pory"
	.string "it looks like.\p"
# 164 "data/scripts/berry_blender.pory"
	.string "You should use some {POKEBLOCK}S up\n"
# 165 "data/scripts/berry_blender.pory"
	.string "and then come back.$"
# 166 "data/scripts/berry_blender.pory"

# 167 "data/scripts/berry_blender.pory"
BerryBlender_Text_DontHavePokeblockCase3:
# 168 "data/scripts/berry_blender.pory"
	.string "You haven't gotten a {POKEBLOCK} Case\n"
# 169 "data/scripts/berry_blender.pory"
	.string "yet, it looks like.\p"
# 170 "data/scripts/berry_blender.pory"
	.string "You need to get a {POKEBLOCK} Case before\n"
# 171 "data/scripts/berry_blender.pory"
	.string "you come back.$"
# 172 "data/scripts/berry_blender.pory"

# 173 "data/scripts/berry_blender.pory"
BerryBlender_Text_SetNewBlenderRecord:
# 174 "data/scripts/berry_blender.pory"
	.string "Okay! Today's going to be the day that\n"
# 175 "data/scripts/berry_blender.pory"
	.string "I set a new Blender speed record!$"
# 176 "data/scripts/berry_blender.pory"

# 177 "data/scripts/berry_blender.pory"
BerryBlender_Text_LookGoodAtBlendingJoinUs:
# 178 "data/scripts/berry_blender.pory"
	.string "Oh, dear!\n"
# 179 "data/scripts/berry_blender.pory"
	.string "You look as if you're good at blending.\l"
# 180 "data/scripts/berry_blender.pory"
	.string "Would you like to join us?$"
# 181 "data/scripts/berry_blender.pory"

# 182 "data/scripts/berry_blender.pory"
BerryBlender_Text_MakeDeliciousPokeblocks:
# 183 "data/scripts/berry_blender.pory"
	.string "I'm going to make delicious {POKEBLOCK}S\n"
# 184 "data/scripts/berry_blender.pory"
	.string "and make my Pokémon cuter.$"
# 185 "data/scripts/berry_blender.pory"

# 186 "data/scripts/berry_blender.pory"
BerryBlender_Text_SaveGameBeforeBerryBlenderLink:
# 187 "data/scripts/berry_blender.pory"
	.string "{POKEBLOCK}S will be made with your friends \n"
# 188 "data/scripts/berry_blender.pory"
	.string "from Berries in the Berry Blender.\p"
# 189 "data/scripts/berry_blender.pory"
	.string "Is it okay to save the game before\n"
# 190 "data/scripts/berry_blender.pory"
	.string "linking with your friends?$"
# 191 "data/scripts/berry_blender.pory"

# 192 "data/scripts/berry_blender.pory"
BerryBlender_Text_SearchingForFriends:
# 193 "data/scripts/berry_blender.pory"
	.string "Searching for your friends…\n"
# 194 "data/scripts/berry_blender.pory"
	.string "… … B Button: Cancel$"
# 195 "data/scripts/berry_blender.pory"

# 196 "data/scripts/berry_blender.pory"
BerryBlender_Text_Player1Arrived:
# 197 "data/scripts/berry_blender.pory"
	.string "{STR_VAR_1} arrived.$"
# 198 "data/scripts/berry_blender.pory"

# 199 "data/scripts/berry_blender.pory"
BerryBlender_Text_Player1And2Arrived:
# 200 "data/scripts/berry_blender.pory"
	.string "{STR_VAR_1} and {STR_VAR_2} arrived.$"
# 201 "data/scripts/berry_blender.pory"

# 202 "data/scripts/berry_blender.pory"
BerryBlender_Text_AllPlayersArrived:
# 203 "data/scripts/berry_blender.pory"
	.string "{STR_VAR_1}, {STR_VAR_2}, and\n"
# 204 "data/scripts/berry_blender.pory"
	.string "{STR_VAR_3} arrived.$"
# 205 "data/scripts/berry_blender.pory"

# 206 "data/scripts/berry_blender.pory"
BerryBlender_Text_NoBerriesLink:
# 207 "data/scripts/berry_blender.pory"
	.string "You have no Berries.\n"
# 208 "data/scripts/berry_blender.pory"
	.string "The Berry Blender can't be used.$"
# 209 "data/scripts/berry_blender.pory"

# 210 "data/scripts/berry_blender.pory"
BerryBlender_Text_PokeblockCaseIsFullLink:
# 211 "data/scripts/berry_blender.pory"
	.string "Your {POKEBLOCK} Case is full.\n"
# 212 "data/scripts/berry_blender.pory"
	.string "The Berry Blender can't be used.$"
# 213 "data/scripts/berry_blender.pory"

# 214 "data/scripts/berry_blender.pory"
BerryBlender_Text_DontHavePokeblockCaseLink:
# 215 "data/scripts/berry_blender.pory"
	.string "You don't have a {POKEBLOCK} Case.\n"
# 216 "data/scripts/berry_blender.pory"
	.string "The Berry Blender can't be used.$"
# 217 "data/scripts/berry_blender.pory"

# 218 "data/scripts/berry_blender.pory"
BerryBlender_Text_LoveMakingPokeblocks:
# 219 "data/scripts/berry_blender.pory"
	.string "I love making {POKEBLOCK}S.\p"
# 220 "data/scripts/berry_blender.pory"
	.string "I always have some Berries with me.$"
# 221 "data/scripts/berry_blender.pory"

# 222 "data/scripts/berry_blender.pory"
BerryBlender_Text_MakePokeblocksUsingBerryBlender:
# 223 "data/scripts/berry_blender.pory"
	.string "If you'd like, we could make some\n"
# 224 "data/scripts/berry_blender.pory"
	.string "{POKEBLOCK}S together using the\l"
# 225 "data/scripts/berry_blender.pory"
	.string "Berry Blender.$"
# 226 "data/scripts/berry_blender.pory"

# 227 "data/scripts/berry_blender.pory"
BerryBlender_Text_DontHaveAnyBerriesHaveOne:
# 228 "data/scripts/berry_blender.pory"
	.string "Oh?\n"
# 229 "data/scripts/berry_blender.pory"
	.string "You don't have any Berries?\p"
# 230 "data/scripts/berry_blender.pory"
	.string "Well, that won't do at all now, will it?\p"
# 231 "data/scripts/berry_blender.pory"
	.string "If you don't mind leftovers, you can\n"
# 232 "data/scripts/berry_blender.pory"
	.string "have one of my Berries.$"
# 233 "data/scripts/berry_blender.pory"

# 234 "data/scripts/berry_blender.pory"
BerryBlender_Text_UseItToMakePokeblocksTogether:
# 235 "data/scripts/berry_blender.pory"
	.string "We'll use it to make {POKEBLOCK}S together\n"
# 236 "data/scripts/berry_blender.pory"
	.string "using the Berry Blender.$"
# 237 "data/scripts/berry_blender.pory"

# 238 "data/scripts/berry_blender.pory"
BerryBlender_Text_DontHaveAnyBerriesNoneToSpare:
# 239 "data/scripts/berry_blender.pory"
	.string "Oh?\n"
# 240 "data/scripts/berry_blender.pory"
	.string "You don't have any Berries?\p"
# 241 "data/scripts/berry_blender.pory"
	.string "If I had some left over, I'd gladly\n"
# 242 "data/scripts/berry_blender.pory"
	.string "give you one…\p"
# 243 "data/scripts/berry_blender.pory"
	.string "But, I don't have any to spare today.\n"
# 244 "data/scripts/berry_blender.pory"
	.string "Sorry about that.$"
# 245 "data/scripts/berry_blender.pory"

# 246 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_BerryBlender1::
# 247 "data/scripts/berry_blender.pory"
	lockall
# 248 "data/scripts/berry_blender.pory"
	goto_if_unset FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER, BerryBlender_EventScript_BlendMasterPresent
# 249 "data/scripts/berry_blender.pory"
	setvar NUM_OPPONENTS, 1
# 250 "data/scripts/berry_blender.pory"
	applymovement LOCALID_EXPERT_M, BerryBlender_Movement_BlendLeaderWalkInPlace
# 251 "data/scripts/berry_blender.pory"
	waitmovement 0
# 252 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_WantToMakePokeblocks, MSGBOX_YESNO
# 253 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, YES
# 254 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_TryUseBerryBlender1
# 255 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_DeclineBlender1
# 256 "data/scripts/berry_blender.pory"
	end
# 257 "data/scripts/berry_blender.pory"

# 258 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_DeclineBlender1:
# 259 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_MadeOldTimerSad, MSGBOX_DEFAULT
# 260 "data/scripts/berry_blender.pory"
	releaseall
# 261 "data/scripts/berry_blender.pory"
	end
# 262 "data/scripts/berry_blender.pory"

# 263 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender1NoBerries:
# 264 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_DontHaveAnyBerries, MSGBOX_DEFAULT
# 265 "data/scripts/berry_blender.pory"
	dotimebasedevents
# 266 "data/scripts/berry_blender.pory"
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_Blender1NoSpareBerries
# 267 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_Blender1GiveSpareBerry
# 268 "data/scripts/berry_blender.pory"
	end
# 269 "data/scripts/berry_blender.pory"

# 270 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender1NoSpareBerries:
# 271 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_DontHaveAnyBerriesToSpare, MSGBOX_DEFAULT
# 272 "data/scripts/berry_blender.pory"
	releaseall
# 273 "data/scripts/berry_blender.pory"
	end
# 274 "data/scripts/berry_blender.pory"

# 275 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender1GiveSpareBerry:
# 276 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_CanHaveOneOfMyBerries, MSGBOX_DEFAULT
# 277 "data/scripts/berry_blender.pory"
	giveitem ITEM_PECHA_BERRY
# 278 "data/scripts/berry_blender.pory"
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
# 279 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_UseBerryBlender1
# 280 "data/scripts/berry_blender.pory"
	end
# 281 "data/scripts/berry_blender.pory"

# 282 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_UseBerryBlender1:
# 283 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks, MSGBOX_YESNO
# 284 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, YES
# 285 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_StartBlender1
# 286 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_ExplainBlending1
# 287 "data/scripts/berry_blender.pory"
	end
# 288 "data/scripts/berry_blender.pory"

# 289 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_StartBlender1:
# 290 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_LetsBerryBlender, MSGBOX_DEFAULT
# 291 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_DoBerryBlending
# 292 "data/scripts/berry_blender.pory"
	end
# 293 "data/scripts/berry_blender.pory"

# 294 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_ExplainBlending1:
# 295 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_ExplainBerryBlending, MSGBOX_DEFAULT
# 296 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_StartBlender1
# 297 "data/scripts/berry_blender.pory"
	end
# 298 "data/scripts/berry_blender.pory"

# 299 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_TryUseBerryBlender1:
# 300 "data/scripts/berry_blender.pory"
	checkitem ITEM_POKEBLOCK_CASE, 1
# 301 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, FALSE
# 302 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_Blender1NoCase
# 303 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
# 304 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, 65535
# 305 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_Blender1CaseFull
# 306 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, PlayerHasBerries
# 307 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, FALSE
# 308 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_Blender1NoBerries
# 309 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_Excellent, MSGBOX_DEFAULT
# 310 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_UseBerryBlender1
# 311 "data/scripts/berry_blender.pory"
	end
# 312 "data/scripts/berry_blender.pory"

# 313 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_DoBerryBlending:
# 314 "data/scripts/berry_blender.pory"
	copyvar VAR_0x8004, NUM_OPPONENTS
# 315 "data/scripts/berry_blender.pory"
	fadescreen FADE_TO_BLACK
# 316 "data/scripts/berry_blender.pory"
	special DoBerryBlending
# 317 "data/scripts/berry_blender.pory"
	waitstate
# 318 "data/scripts/berry_blender.pory"
	releaseall
# 319 "data/scripts/berry_blender.pory"
	end
# 320 "data/scripts/berry_blender.pory"

# 321 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender1CaseFull:
# 322 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_PokeblockCaseIsFull, MSGBOX_DEFAULT
# 323 "data/scripts/berry_blender.pory"
	releaseall
# 324 "data/scripts/berry_blender.pory"
	end
# 325 "data/scripts/berry_blender.pory"

# 326 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender1NoCase:
# 327 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_DontHavePokeblockCase, MSGBOX_DEFAULT
# 328 "data/scripts/berry_blender.pory"
	releaseall
# 329 "data/scripts/berry_blender.pory"
	end
# 330 "data/scripts/berry_blender.pory"

# 331 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_BerryBlender2::
# 332 "data/scripts/berry_blender.pory"
	lockall
# 333 "data/scripts/berry_blender.pory"
	setvar NUM_OPPONENTS, 2
# 334 "data/scripts/berry_blender.pory"
	applymovement LOCALID_TWIN, Common_Movement_FaceOriginalDirection
# 335 "data/scripts/berry_blender.pory"
	applymovement LOCALID_MAN, BerryBlender_Movement_BlendLeaderWalkInPlace
# 336 "data/scripts/berry_blender.pory"
	waitmovement 0
# 337 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_WantToBlendPokeblocksWithUs, MSGBOX_YESNO
# 338 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, YES
# 339 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_TryUseBerryBlender2
# 340 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_DeclineBlender2
# 341 "data/scripts/berry_blender.pory"
	end
# 342 "data/scripts/berry_blender.pory"

# 343 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_DeclineBlender2:
# 344 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_ThatsTooBad, MSGBOX_DEFAULT
# 345 "data/scripts/berry_blender.pory"
	releaseall
# 346 "data/scripts/berry_blender.pory"
	end
# 347 "data/scripts/berry_blender.pory"

# 348 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender2NoBerries:
# 349 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_DontHaveAnyBerries2, MSGBOX_DEFAULT
# 350 "data/scripts/berry_blender.pory"
	release
# 351 "data/scripts/berry_blender.pory"
	end
# 352 "data/scripts/berry_blender.pory"

# 353 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_UseBerryBlender2:
# 354 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks2, MSGBOX_YESNO
# 355 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, YES
# 356 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_StartBlender2
# 357 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_ExplainBlending2
# 358 "data/scripts/berry_blender.pory"
	end
# 359 "data/scripts/berry_blender.pory"

# 360 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_StartBlender2:
# 361 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_LetsBerryBlender2, MSGBOX_DEFAULT
# 362 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_DoBerryBlending
# 363 "data/scripts/berry_blender.pory"
	end
# 364 "data/scripts/berry_blender.pory"

# 365 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_ExplainBlending2:
# 366 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_ExplainBerryBlending2, MSGBOX_DEFAULT
# 367 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_StartBlender2
# 368 "data/scripts/berry_blender.pory"
	end
# 369 "data/scripts/berry_blender.pory"

# 370 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_TryUseBerryBlender2:
# 371 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, PlayerHasBerries
# 372 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, FALSE
# 373 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_Blender2NoBerries
# 374 "data/scripts/berry_blender.pory"
	checkitem ITEM_POKEBLOCK_CASE, 1
# 375 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, FALSE
# 376 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_Blender2NoCase
# 377 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_Okay, MSGBOX_DEFAULT
# 378 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
# 379 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, 65535
# 380 "data/scripts/berry_blender.pory"
	goto_if_ne BerryBlender_EventScript_UseBerryBlender2
# 381 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, 65535
# 382 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_Blender2CaseFull
# 383 "data/scripts/berry_blender.pory"
	end
# 384 "data/scripts/berry_blender.pory"

# 385 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender2CaseFull:
# 386 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_PokeblockCaseIsFull2, MSGBOX_DEFAULT
# 387 "data/scripts/berry_blender.pory"
	releaseall
# 388 "data/scripts/berry_blender.pory"
	end
# 389 "data/scripts/berry_blender.pory"

# 390 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender2NoCase:
# 391 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_DontHavePokeblockCase2, MSGBOX_DEFAULT
# 392 "data/scripts/berry_blender.pory"
	releaseall
# 393 "data/scripts/berry_blender.pory"
	end
# 394 "data/scripts/berry_blender.pory"

# 395 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_BerryBlender3::
# 396 "data/scripts/berry_blender.pory"
	lockall
# 397 "data/scripts/berry_blender.pory"
	setvar VAR_0x8008, LOCALID_POKEFAN_F
# 398 "data/scripts/berry_blender.pory"
	setvar NUM_OPPONENTS, 3
# 399 "data/scripts/berry_blender.pory"
	applymovement LOCALID_BOY, Common_Movement_FaceOriginalDirection
# 400 "data/scripts/berry_blender.pory"
	applymovement LOCALID_GIRL, Common_Movement_FaceOriginalDirection
# 401 "data/scripts/berry_blender.pory"
	applymovement VAR_0x8008, BerryBlender_Movement_BlendLeaderWalkInPlace
# 402 "data/scripts/berry_blender.pory"
	waitmovement 0
# 403 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_YESNO
# 404 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, YES
# 405 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_TryUseBlender3
# 406 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_DeclineBlender3
# 407 "data/scripts/berry_blender.pory"
	end
# 408 "data/scripts/berry_blender.pory"

# 409 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_DeclineBlender3:
# 410 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_LeftUsInShock, MSGBOX_DEFAULT
# 411 "data/scripts/berry_blender.pory"
	releaseall
# 412 "data/scripts/berry_blender.pory"
	end
# 413 "data/scripts/berry_blender.pory"

# 414 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender3NoBerries:
# 415 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_DontHaveAnyBerries3, MSGBOX_DEFAULT
# 416 "data/scripts/berry_blender.pory"
	release
# 417 "data/scripts/berry_blender.pory"
	end
# 418 "data/scripts/berry_blender.pory"

# 419 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_UseBerryBlender3:
# 420 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks3, MSGBOX_YESNO
# 421 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, YES
# 422 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_StartBlender3
# 423 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_ExplainBlending3
# 424 "data/scripts/berry_blender.pory"
	end
# 425 "data/scripts/berry_blender.pory"

# 426 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_StartBlender3:
# 427 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_LetsBerryBlender3, MSGBOX_DEFAULT
# 428 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_DoBerryBlending
# 429 "data/scripts/berry_blender.pory"
	end
# 430 "data/scripts/berry_blender.pory"

# 431 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_ExplainBlending3:
# 432 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_ExplainBerryBlending3, MSGBOX_DEFAULT
# 433 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_StartBlender3
# 434 "data/scripts/berry_blender.pory"
	end
# 435 "data/scripts/berry_blender.pory"

# 436 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_TryUseBlender3:
# 437 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, PlayerHasBerries
# 438 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, FALSE
# 439 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_Blender3NoBerries
# 440 "data/scripts/berry_blender.pory"
	checkitem ITEM_POKEBLOCK_CASE, 1
# 441 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, FALSE
# 442 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_Blender3NoCase
# 443 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_OhDear, MSGBOX_DEFAULT
# 444 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
# 445 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, 65535
# 446 "data/scripts/berry_blender.pory"
	goto_if_ne BerryBlender_EventScript_UseBerryBlender3
# 447 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, 65535
# 448 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_Blender3CaseFull
# 449 "data/scripts/berry_blender.pory"
	end
# 450 "data/scripts/berry_blender.pory"

# 451 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender3CaseFull:
# 452 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_PokeblockCaseIsFull3, MSGBOX_DEFAULT
# 453 "data/scripts/berry_blender.pory"
	releaseall
# 454 "data/scripts/berry_blender.pory"
	end
# 455 "data/scripts/berry_blender.pory"

# 456 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender3NoCase:
# 457 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_DontHavePokeblockCase3, MSGBOX_DEFAULT
# 458 "data/scripts/berry_blender.pory"
	releaseall
# 459 "data/scripts/berry_blender.pory"
	end
# 460 "data/scripts/berry_blender.pory"

# 461 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_BlendMasterPresent:
# 462 "data/scripts/berry_blender.pory"
	lockall
# 463 "data/scripts/berry_blender.pory"
	setvar NUM_OPPONENTS, 1
# 464 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_SeeMyMasteryInAction, MSGBOX_YESNO
# 465 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, YES
# 466 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_TryBlendWithBlendMaster
# 467 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_TooBusyNowIsee, MSGBOX_DEFAULT
# 468 "data/scripts/berry_blender.pory"
	releaseall
# 469 "data/scripts/berry_blender.pory"
	end
# 470 "data/scripts/berry_blender.pory"

# 471 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_BlendMasterNoBerries:
# 472 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_BlendMasterNoBerries, MSGBOX_DEFAULT
# 473 "data/scripts/berry_blender.pory"
	releaseall
# 474 "data/scripts/berry_blender.pory"
	end
# 475 "data/scripts/berry_blender.pory"

# 476 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_TryBlendWithBlendMaster:
# 477 "data/scripts/berry_blender.pory"
	checkitem ITEM_POKEBLOCK_CASE, 1
# 478 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, FALSE
# 479 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_BlendMasterNoCase
# 480 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, PlayerHasBerries
# 481 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, FALSE
# 482 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_BlendMasterNoBerries
# 483 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
# 484 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, 65535
# 485 "data/scripts/berry_blender.pory"
	goto_if_ne BerryBlender_EventScript_BlendWithBlendMaster
# 486 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, 65535
# 487 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_BlendMasterCaseFull
# 488 "data/scripts/berry_blender.pory"
	end
# 489 "data/scripts/berry_blender.pory"

# 490 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_BlendWithBlendMaster:
# 491 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks, MSGBOX_YESNO
# 492 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, NO
# 493 "data/scripts/berry_blender.pory"
	call_if_eq BerryBlender_EventScript_BlendMasterExplainBlending
# 494 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_BlendMasterLetsBerryBlender, MSGBOX_DEFAULT
# 495 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_DoBerryBlending
# 496 "data/scripts/berry_blender.pory"
	end
# 497 "data/scripts/berry_blender.pory"

# 498 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_BlendMasterExplainBlending:
# 499 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_BlendMasterExplainBerryBlending, MSGBOX_DEFAULT
# 500 "data/scripts/berry_blender.pory"
	return
# 501 "data/scripts/berry_blender.pory"

# 502 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_BlendMasterNoCase:
# 503 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_BlendMasterNoPokeblockCase, MSGBOX_DEFAULT
# 504 "data/scripts/berry_blender.pory"
	releaseall
# 505 "data/scripts/berry_blender.pory"
	end
# 506 "data/scripts/berry_blender.pory"

# 507 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_BlendMasterCaseFull:
# 508 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_BlendMasterPokeblockCaseFull, MSGBOX_DEFAULT
# 509 "data/scripts/berry_blender.pory"
	releaseall
# 510 "data/scripts/berry_blender.pory"
	end
# 511 "data/scripts/berry_blender.pory"

# 512 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender2Man::
# 513 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_SetNewBlenderRecord, MSGBOX_NPC
# 514 "data/scripts/berry_blender.pory"
	end
# 515 "data/scripts/berry_blender.pory"

# 516 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender3PokefanF::
# 517 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_NPC
# 518 "data/scripts/berry_blender.pory"
	end
# 519 "data/scripts/berry_blender.pory"

# 520 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender2Twin::
# 521 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_MakeDeliciousPokeblocks, MSGBOX_NPC
# 522 "data/scripts/berry_blender.pory"
	end
# 523 "data/scripts/berry_blender.pory"

# 524 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_Blender1ExpertM::
# 525 "data/scripts/berry_blender.pory"
	setvar VAR_0x8008, 15
# 526 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_ExpertMCheckGiveBerry
# 527 "data/scripts/berry_blender.pory"
	end
# 528 "data/scripts/berry_blender.pory"

# 529 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_ExpertMCheckGiveBerry:
# 530 "data/scripts/berry_blender.pory"
	lock
# 531 "data/scripts/berry_blender.pory"
	faceplayer
# 532 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_LoveMakingPokeblocks, MSGBOX_DEFAULT
# 533 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, PlayerHasBerries
# 534 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, TRUE
# 535 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_ExpertMPlayerHasBerries
# 536 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, FALSE
# 537 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_ExpertMNoBerries
# 538 "data/scripts/berry_blender.pory"
	end
# 539 "data/scripts/berry_blender.pory"

# 540 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_ExpertMPlayerHasBerries:
# 541 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_MakePokeblocksUsingBerryBlender, MSGBOX_DEFAULT
# 542 "data/scripts/berry_blender.pory"
	release
# 543 "data/scripts/berry_blender.pory"
	end
# 544 "data/scripts/berry_blender.pory"

# 545 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_ExpertMNoBerries:
# 546 "data/scripts/berry_blender.pory"
	checkitem ITEM_POKEBLOCK_CASE, 1
# 547 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, FALSE
# 548 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_ExpertMNoSpareBerries
# 549 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
# 550 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, 65535
# 551 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_ExpertMNoSpareBerries
# 552 "data/scripts/berry_blender.pory"
	dotimebasedevents
# 553 "data/scripts/berry_blender.pory"
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_ExpertMNoSpareBerries
# 554 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_ExpertMGiveBerry
# 555 "data/scripts/berry_blender.pory"
	end
# 556 "data/scripts/berry_blender.pory"

# 557 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_ExpertMNoSpareBerries:
# 558 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_DontHaveAnyBerriesNoneToSpare, MSGBOX_DEFAULT
# 559 "data/scripts/berry_blender.pory"
	release
# 560 "data/scripts/berry_blender.pory"
	end
# 561 "data/scripts/berry_blender.pory"

# 562 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_ExpertMGiveBerry:
# 563 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_DontHaveAnyBerriesHaveOne, MSGBOX_DEFAULT
# 564 "data/scripts/berry_blender.pory"
	giveitem ITEM_PECHA_BERRY
# 565 "data/scripts/berry_blender.pory"
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
# 566 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_UseItToMakePokeblocksTogether, MSGBOX_DEFAULT
# 567 "data/scripts/berry_blender.pory"
	release
# 568 "data/scripts/berry_blender.pory"
	end
# 569 "data/scripts/berry_blender.pory"

# 570 "data/scripts/berry_blender.pory"
BerryBlender_Movement_BlendLeaderWalkInPlace:
# 571 "data/scripts/berry_blender.pory"
	walk_in_place_fastest_right
# 572 "data/scripts/berry_blender.pory"
	step_end
# 573 "data/scripts/berry_blender.pory"

# 574 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_BerryBlenderLink::
# 575 "data/scripts/berry_blender.pory"
	lockall
# 576 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, PlayerHasBerries
# 577 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, FALSE
# 578 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_LinkBlenderNoBerries
# 579 "data/scripts/berry_blender.pory"
	checkitem ITEM_POKEBLOCK_CASE, 1
# 580 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, FALSE
# 581 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_LinkBlenderNoCase
# 582 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
# 583 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, 65535
# 584 "data/scripts/berry_blender.pory"
	goto_if_ne BerryBlender_EventScript_LinkBlenderSaveGame
# 585 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, 65535
# 586 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_LinkBlenderCaseFull
# 587 "data/scripts/berry_blender.pory"
	end
# 588 "data/scripts/berry_blender.pory"

# 589 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_LinkBlenderSaveGame:
# 590 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_SaveGameBeforeBerryBlenderLink, MSGBOX_YESNO
# 591 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, YES
# 592 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_TryDoLinkBlender
# 593 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, NO
# 594 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_CancelLinkBlender
# 595 "data/scripts/berry_blender.pory"
	end
# 596 "data/scripts/berry_blender.pory"

# 597 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_LinkBlenderNoBerries:
# 598 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_NoBerriesLink, MSGBOX_DEFAULT
# 599 "data/scripts/berry_blender.pory"
	releaseall
# 600 "data/scripts/berry_blender.pory"
	end
# 601 "data/scripts/berry_blender.pory"

# 602 "data/scripts/berry_blender.pory"
Common_EventScript_Autosave::
# 603 "data/scripts/berry_blender.pory"
	special SaveGame
# 604 "data/scripts/berry_blender.pory"
	waitstate
# 605 "data/scripts/berry_blender.pory"
	closemessage
# 606 "data/scripts/berry_blender.pory"
	end
# 607 "data/scripts/berry_blender.pory"

# 608 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_TryDoLinkBlender:
# 609 "data/scripts/berry_blender.pory"
	call Common_EventScript_SaveGame
# 610 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, FALSE
# 611 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_CancelLinkBlender
# 612 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, IsWirelessAdapterConnected
# 613 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, TRUE
# 614 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_StartDecideLinkLeader
# 615 "data/scripts/berry_blender.pory"
	message BerryBlender_Text_SearchingForFriends
# 616 "data/scripts/berry_blender.pory"
	waitmessage
# 617 "data/scripts/berry_blender.pory"
	special TryBerryBlenderLinkup
# 618 "data/scripts/berry_blender.pory"
	waitstate
# 619 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, LINKUP_SUCCESS
# 620 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_SpawnLinkPartners
# 621 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, LINKUP_SOMEONE_NOT_READY
# 622 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_CloseLinkNotReady
# 623 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, LINKUP_DIFF_SELECTIONS
# 624 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_CloseLinkDifferentSelections
# 625 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, LINKUP_FAILED
# 626 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_CloseLink
# 627 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, LINKUP_CONNECTION_ERROR
# 628 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_LinkError
# 629 "data/scripts/berry_blender.pory"
	end
# 630 "data/scripts/berry_blender.pory"

# 631 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_TwoPlayerLink:
# 632 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_Player1Arrived, MSGBOX_DEFAULT
# 633 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_DoLinkBerryBlending
# 634 "data/scripts/berry_blender.pory"
	end
# 635 "data/scripts/berry_blender.pory"

# 636 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_ThreePlayerLink:
# 637 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_Player1And2Arrived, MSGBOX_DEFAULT
# 638 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_DoLinkBerryBlending
# 639 "data/scripts/berry_blender.pory"
	end
# 640 "data/scripts/berry_blender.pory"

# 641 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_FourPlayerLink:
# 642 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_AllPlayersArrived, MSGBOX_DEFAULT
# 643 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_DoLinkBerryBlending
# 644 "data/scripts/berry_blender.pory"
	end
# 645 "data/scripts/berry_blender.pory"

# 646 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_DoLinkBerryBlending:
# 647 "data/scripts/berry_blender.pory"
	setvar VAR_0x8004, 0  @ number of opponents, 0 indicates Link
# 648 "data/scripts/berry_blender.pory"
	fadescreen FADE_TO_BLACK
# 649 "data/scripts/berry_blender.pory"
	removeobject 240 @ Unclear where these local IDs come from,
# 650 "data/scripts/berry_blender.pory"
	removeobject 239 @ but presumably they'd be the 4 link players
# 651 "data/scripts/berry_blender.pory"
	removeobject 238 
# 652 "data/scripts/berry_blender.pory"
	removeobject 237
# 653 "data/scripts/berry_blender.pory"
	special DoBerryBlending
# 654 "data/scripts/berry_blender.pory"
	waitstate
# 655 "data/scripts/berry_blender.pory"
	releaseall
# 656 "data/scripts/berry_blender.pory"
	end
# 657 "data/scripts/berry_blender.pory"

# 658 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_CancelLinkBlender:
# 659 "data/scripts/berry_blender.pory"
	releaseall
# 660 "data/scripts/berry_blender.pory"
	end
# 661 "data/scripts/berry_blender.pory"

# 662 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_LinkBlenderCaseFull:
# 663 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_PokeblockCaseIsFullLink, MSGBOX_DEFAULT
# 664 "data/scripts/berry_blender.pory"
	releaseall
# 665 "data/scripts/berry_blender.pory"
	end
# 666 "data/scripts/berry_blender.pory"

# 667 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_LinkBlenderNoCase:
# 668 "data/scripts/berry_blender.pory"
	msgbox BerryBlender_Text_DontHavePokeblockCaseLink, MSGBOX_DEFAULT
# 669 "data/scripts/berry_blender.pory"
	releaseall
# 670 "data/scripts/berry_blender.pory"
	end
# 671 "data/scripts/berry_blender.pory"

# 672 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_CloseLinkNotReady:
# 673 "data/scripts/berry_blender.pory"
	special CloseLink
# 674 "data/scripts/berry_blender.pory"
	msgbox Text_SomeoneIsNotReadyToLink, MSGBOX_DEFAULT
# 675 "data/scripts/berry_blender.pory"
	releaseall
# 676 "data/scripts/berry_blender.pory"
	end
# 677 "data/scripts/berry_blender.pory"

# 678 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_CloseLinkDifferentSelections:
# 679 "data/scripts/berry_blender.pory"
	special CloseLink
# 680 "data/scripts/berry_blender.pory"
	msgbox Text_PlayersMadeDifferentSelections, MSGBOX_DEFAULT
# 681 "data/scripts/berry_blender.pory"
	releaseall
# 682 "data/scripts/berry_blender.pory"
	end
# 683 "data/scripts/berry_blender.pory"

# 684 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_CloseLink:
# 685 "data/scripts/berry_blender.pory"
	special CloseLink
# 686 "data/scripts/berry_blender.pory"
	msgbox gText_PokeblockLinkCanceled, MSGBOX_DEFAULT
# 687 "data/scripts/berry_blender.pory"
	releaseall
# 688 "data/scripts/berry_blender.pory"
	end
# 689 "data/scripts/berry_blender.pory"

# 690 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_LinkError:
# 691 "data/scripts/berry_blender.pory"
	special CloseLink
# 692 "data/scripts/berry_blender.pory"
	msgbox Text_LinkErrorPleaseReset, MSGBOX_DEFAULT
# 693 "data/scripts/berry_blender.pory"
	releaseall
# 694 "data/scripts/berry_blender.pory"
	end
# 695 "data/scripts/berry_blender.pory"

# 696 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_SpawnLinkPartners:
# 697 "data/scripts/berry_blender.pory"
	fadescreen FADE_TO_BLACK
# 698 "data/scripts/berry_blender.pory"
	specialvar VAR_RESULT, GetLinkPartnerNames
# 699 "data/scripts/berry_blender.pory"
	copyvar VAR_0x8008, VAR_RESULT
# 700 "data/scripts/berry_blender.pory"
	copyvar VAR_0x8004, VAR_0x8008
# 701 "data/scripts/berry_blender.pory"
	special SpawnLinkPartnerObjectEvent
# 702 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_LinkPlayersArrived
# 703 "data/scripts/berry_blender.pory"
	end
# 704 "data/scripts/berry_blender.pory"

# 705 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_LinkPlayersArrived:
# 706 "data/scripts/berry_blender.pory"
	fadescreen FADE_FROM_BLACK
# 707 "data/scripts/berry_blender.pory"
	switch VAR_0x8008
# 708 "data/scripts/berry_blender.pory"
	case 2, BerryBlender_EventScript_TwoPlayerLink
# 709 "data/scripts/berry_blender.pory"
	case 3, BerryBlender_EventScript_ThreePlayerLink
# 710 "data/scripts/berry_blender.pory"
	case 4, BerryBlender_EventScript_FourPlayerLink
# 711 "data/scripts/berry_blender.pory"
	end
# 712 "data/scripts/berry_blender.pory"

# 713 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_StartDecideLinkLeader:
# 714 "data/scripts/berry_blender.pory"
	setvar VAR_0x8004, LINK_GROUP_BERRY_BLENDER
# 715 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_DecideLinkLeader
# 716 "data/scripts/berry_blender.pory"
	end
# 717 "data/scripts/berry_blender.pory"

# 718 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_DecideLinkLeader:
# 719 "data/scripts/berry_blender.pory"
	message LilycoveCity_ContestLobby_Text_PleaseDecideLinkLeader
# 720 "data/scripts/berry_blender.pory"
	waitmessage
# 721 "data/scripts/berry_blender.pory"
	multichoice 16, 6, MULTI_LINK_LEADER, 0
# 722 "data/scripts/berry_blender.pory"
	switch VAR_RESULT
# 723 "data/scripts/berry_blender.pory"
	case 0, BerryBlender_EventScript_TryJoinGroup
# 724 "data/scripts/berry_blender.pory"
	case 1, BerryBlender_EventScript_TryLeadGroup
# 725 "data/scripts/berry_blender.pory"
	case 2, BerryBlender_EventScript_CloseLink
# 726 "data/scripts/berry_blender.pory"
	case MULTI_B_PRESSED, BerryBlender_EventScript_CloseLink
# 727 "data/scripts/berry_blender.pory"
	end
# 728 "data/scripts/berry_blender.pory"

# 729 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_TryLeadGroup:
# 730 "data/scripts/berry_blender.pory"
	call BerryBlender_EventScript_TryBecomeLinkLeader
# 731 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, LINKUP_SUCCESS
# 732 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_LinkLeaderDecided
# 733 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, LINKUP_FAILED
# 734 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_DecideLinkLeader
# 735 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN
# 736 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_TryLeadGroup
# 737 "data/scripts/berry_blender.pory"
	release
# 738 "data/scripts/berry_blender.pory"
	end
# 739 "data/scripts/berry_blender.pory"

# 740 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_TryJoinGroup:
# 741 "data/scripts/berry_blender.pory"
	call BerryBlender_EventScript_TryJoinLinkGroup
# 742 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, LINKUP_SUCCESS
# 743 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_LinkLeaderDecided
# 744 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, LINKUP_FAILED
# 745 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_DecideLinkLeader
# 746 "data/scripts/berry_blender.pory"
	compare VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN
# 747 "data/scripts/berry_blender.pory"
	goto_if_eq BerryBlender_EventScript_TryJoinGroup
# 748 "data/scripts/berry_blender.pory"
	release
# 749 "data/scripts/berry_blender.pory"
	end
# 750 "data/scripts/berry_blender.pory"

# 751 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_TryBecomeLinkLeader:
# 752 "data/scripts/berry_blender.pory"
	special TryBecomeLinkLeader
# 753 "data/scripts/berry_blender.pory"
	waitstate
# 754 "data/scripts/berry_blender.pory"
	return
# 755 "data/scripts/berry_blender.pory"

# 756 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_TryJoinLinkGroup:
# 757 "data/scripts/berry_blender.pory"
	special TryJoinLinkGroup
# 758 "data/scripts/berry_blender.pory"
	waitstate
# 759 "data/scripts/berry_blender.pory"
	return
# 760 "data/scripts/berry_blender.pory"

# 761 "data/scripts/berry_blender.pory"
BerryBlender_EventScript_LinkLeaderDecided:
# 762 "data/scripts/berry_blender.pory"
	goto BerryBlender_EventScript_SpawnLinkPartners
# 763 "data/scripts/berry_blender.pory"
	end
