# 1 "data/scripts/item_ball_scripts.pory"

# 2 "data/scripts/item_ball_scripts.pory"
Route102_EventScript_ItemPotion:: @ 8290CD8
# 3 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POTION
# 4 "data/scripts/item_ball_scripts.pory"
	end
# 5 "data/scripts/item_ball_scripts.pory"

# 6 "data/scripts/item_ball_scripts.pory"
Route103_EventScript_ItemGuardSpec:: @ 8290CE5
# 7 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_GUARD_SPEC
# 8 "data/scripts/item_ball_scripts.pory"
	end
# 9 "data/scripts/item_ball_scripts.pory"

# 10 "data/scripts/item_ball_scripts.pory"
Route103_EventScript_ItemPPUp:: @ 8290CF2
# 11 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POKE_BALL
# 12 "data/scripts/item_ball_scripts.pory"
	end
# 13 "data/scripts/item_ball_scripts.pory"

# 14 "data/scripts/item_ball_scripts.pory"
Route104_EventScript_ItemPPUp:: @ 8290CFF
# 15 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POKE_BALL
# 16 "data/scripts/item_ball_scripts.pory"
	end
# 17 "data/scripts/item_ball_scripts.pory"

# 18 "data/scripts/item_ball_scripts.pory"
Route104_EventScript_ItemPokeBall:: @ 8290D0C
# 19 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POKE_BALL
# 20 "data/scripts/item_ball_scripts.pory"
	end
# 21 "data/scripts/item_ball_scripts.pory"

# 22 "data/scripts/item_ball_scripts.pory"
Route104_EventScript_ItemXAccuracy:: @ 8290D19
# 23 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_X_ACCURACY
# 24 "data/scripts/item_ball_scripts.pory"
	end
# 25 "data/scripts/item_ball_scripts.pory"

# 26 "data/scripts/item_ball_scripts.pory"
Route104_EventScript_ItemPotion:: @ 8290D26
# 27 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POTION
# 28 "data/scripts/item_ball_scripts.pory"
	end
# 29 "data/scripts/item_ball_scripts.pory"

# 30 "data/scripts/item_ball_scripts.pory"
Route105_EventScript_ItemIron:: @ 8290D33
# 31 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_IRON
# 32 "data/scripts/item_ball_scripts.pory"
	end
# 33 "data/scripts/item_ball_scripts.pory"

# 34 "data/scripts/item_ball_scripts.pory"
Route106_EventScript_ItemProtein:: @ 8290D40
# 35 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_PROTEIN
# 36 "data/scripts/item_ball_scripts.pory"
	end
# 37 "data/scripts/item_ball_scripts.pory"

# 38 "data/scripts/item_ball_scripts.pory"
Route108_EventScript_ItemStarPiece:: @ 8290D4D
# 39 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_STAR_PIECE
# 40 "data/scripts/item_ball_scripts.pory"
	end
# 41 "data/scripts/item_ball_scripts.pory"

# 42 "data/scripts/item_ball_scripts.pory"
Route109_EventScript_ItemPPUp:: @ 8290D5A
# 43 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POKE_BALL
# 44 "data/scripts/item_ball_scripts.pory"
	end
# 45 "data/scripts/item_ball_scripts.pory"

# 46 "data/scripts/item_ball_scripts.pory"
Route109_EventScript_ItemPotion:: @ 8290D67
# 47 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POTION
# 48 "data/scripts/item_ball_scripts.pory"
	end
# 49 "data/scripts/item_ball_scripts.pory"

# 50 "data/scripts/item_ball_scripts.pory"
Route110_EventScript_ItemRareCandy:: @ 8290D74
# 51 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_UP_GRADE
# 52 "data/scripts/item_ball_scripts.pory"
	end
# 53 "data/scripts/item_ball_scripts.pory"

# 54 "data/scripts/item_ball_scripts.pory"
Route110_EventScript_ItemDireHit:: @ 8290D81
# 55 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_DIRE_HIT
# 56 "data/scripts/item_ball_scripts.pory"
	end
# 57 "data/scripts/item_ball_scripts.pory"

# 58 "data/scripts/item_ball_scripts.pory"
Route110_EventScript_ItemElixir:: @ 8290D8E
# 59 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ELIXIR
# 60 "data/scripts/item_ball_scripts.pory"
	end
# 61 "data/scripts/item_ball_scripts.pory"

# 62 "data/scripts/item_ball_scripts.pory"
Route111_EventScript_ItemTM37:: @ 8290D9B
# 63 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM37
# 64 "data/scripts/item_ball_scripts.pory"
	end
# 65 "data/scripts/item_ball_scripts.pory"

# 66 "data/scripts/item_ball_scripts.pory"
Route111_EventScript_ItemStardust:: @ 8290DA8
# 67 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_STARDUST
# 68 "data/scripts/item_ball_scripts.pory"
	end
# 69 "data/scripts/item_ball_scripts.pory"

# 70 "data/scripts/item_ball_scripts.pory"
Route111_EventScript_ItemHPUp:: @ 8290DB5
# 71 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_HP_UP
# 72 "data/scripts/item_ball_scripts.pory"
	end
# 73 "data/scripts/item_ball_scripts.pory"

# 74 "data/scripts/item_ball_scripts.pory"
Route111_EventScript_ItemElixir:: @ 8290DC2
# 75 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ELIXIR
# 76 "data/scripts/item_ball_scripts.pory"
	end
# 77 "data/scripts/item_ball_scripts.pory"

# 78 "data/scripts/item_ball_scripts.pory"
Route112_EventScript_ItemNugget:: @ 8290DCF
# 79 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_NUGGET
# 80 "data/scripts/item_ball_scripts.pory"
	end
# 81 "data/scripts/item_ball_scripts.pory"

# 82 "data/scripts/item_ball_scripts.pory"
Route113_EventScript_ItemMaxEther:: @ 8290DDC
# 83 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MAX_ETHER
# 84 "data/scripts/item_ball_scripts.pory"
	end
# 85 "data/scripts/item_ball_scripts.pory"

# 86 "data/scripts/item_ball_scripts.pory"
Route113_EventScript_ItemSuperRepel:: @ 8290DE9
# 87 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_SUPER_REPEL
# 88 "data/scripts/item_ball_scripts.pory"
	end
# 89 "data/scripts/item_ball_scripts.pory"

# 90 "data/scripts/item_ball_scripts.pory"
Route113_EventScript_ItemHyperPotion:: @ 8290DF6
# 91 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_HYPER_POTION
# 92 "data/scripts/item_ball_scripts.pory"
	end
# 93 "data/scripts/item_ball_scripts.pory"

# 94 "data/scripts/item_ball_scripts.pory"
Route114_EventScript_ItemRareCandy:: @ 8290E03
# 95 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_STARDUST
# 96 "data/scripts/item_ball_scripts.pory"
	end
# 97 "data/scripts/item_ball_scripts.pory"

# 98 "data/scripts/item_ball_scripts.pory"
Route114_EventScript_ItemProtein:: @ 8290E10
# 99 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_PROTEIN
# 100 "data/scripts/item_ball_scripts.pory"
	end
# 101 "data/scripts/item_ball_scripts.pory"

# 102 "data/scripts/item_ball_scripts.pory"
Route114_EventScript_ItemEnergyPowder:: @ 8290E1D
# 103 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ENERGY_POWDER
# 104 "data/scripts/item_ball_scripts.pory"
	end
# 105 "data/scripts/item_ball_scripts.pory"

# 106 "data/scripts/item_ball_scripts.pory"
Route115_EventScript_ItemSuperPotion:: @ 8290E2A
# 107 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_SUPER_POTION
# 108 "data/scripts/item_ball_scripts.pory"
	end
# 109 "data/scripts/item_ball_scripts.pory"

# 110 "data/scripts/item_ball_scripts.pory"
Route115_EventScript_ItemTM01:: @ 8290E37
# 111 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM01
# 112 "data/scripts/item_ball_scripts.pory"
	end
# 113 "data/scripts/item_ball_scripts.pory"

# 114 "data/scripts/item_ball_scripts.pory"
Route115_EventScript_ItemIron:: @ 8290E44
# 115 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_FOCUS_SASH
# 116 "data/scripts/item_ball_scripts.pory"
	end
# 117 "data/scripts/item_ball_scripts.pory"

# 118 "data/scripts/item_ball_scripts.pory"
Route115_EventScript_ItemGreatBall:: @ 8290E51
# 119 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_GREAT_BALL
# 120 "data/scripts/item_ball_scripts.pory"
	end
# 121 "data/scripts/item_ball_scripts.pory"

# 122 "data/scripts/item_ball_scripts.pory"
Route115_EventScript_ItemHealPowder:: @ 8290E5E
# 123 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_HEAL_POWDER
# 124 "data/scripts/item_ball_scripts.pory"
	end
# 125 "data/scripts/item_ball_scripts.pory"

# 126 "data/scripts/item_ball_scripts.pory"
Route115_EventScript_ItemPPUp:: @ 8290E6B
# 127 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POKE_BALL
# 128 "data/scripts/item_ball_scripts.pory"
	end
# 129 "data/scripts/item_ball_scripts.pory"

# 130 "data/scripts/item_ball_scripts.pory"
Route116_EventScript_ItemXSpecial:: @ 8290E78
# 131 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_X_SP_ATK
# 132 "data/scripts/item_ball_scripts.pory"
	end
# 133 "data/scripts/item_ball_scripts.pory"

# 134 "data/scripts/item_ball_scripts.pory"
Route116_EventScript_ItemEther:: @ 8290E85
# 135 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ETHER
# 136 "data/scripts/item_ball_scripts.pory"
	end
# 137 "data/scripts/item_ball_scripts.pory"

# 138 "data/scripts/item_ball_scripts.pory"
Route116_EventScript_ItemRepel:: @ 8290E92
# 139 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_REPEL
# 140 "data/scripts/item_ball_scripts.pory"
	end
# 141 "data/scripts/item_ball_scripts.pory"

# 142 "data/scripts/item_ball_scripts.pory"
Route116_EventScript_ItemHPUp:: @ 8290E9F
# 143 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_HP_UP
# 144 "data/scripts/item_ball_scripts.pory"
	end
# 145 "data/scripts/item_ball_scripts.pory"

# 146 "data/scripts/item_ball_scripts.pory"
Route116_EventScript_ItemPotion:: @ 8290EAC
# 147 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POTION
# 148 "data/scripts/item_ball_scripts.pory"
	end
# 149 "data/scripts/item_ball_scripts.pory"

# 150 "data/scripts/item_ball_scripts.pory"
Route117_EventScript_ItemGreatBall:: @ 8290EB9
# 151 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_GREAT_BALL
# 152 "data/scripts/item_ball_scripts.pory"
	end
# 153 "data/scripts/item_ball_scripts.pory"

# 154 "data/scripts/item_ball_scripts.pory"
Route117_EventScript_ItemRevive:: @ 8290EC6
# 155 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_REVIVE
# 156 "data/scripts/item_ball_scripts.pory"
	end
# 157 "data/scripts/item_ball_scripts.pory"

# 158 "data/scripts/item_ball_scripts.pory"
Route118_EventScript_ItemHyperPotion:: @ 8290ED3
# 159 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_HYPER_POTION
# 160 "data/scripts/item_ball_scripts.pory"
	end
# 161 "data/scripts/item_ball_scripts.pory"

# 162 "data/scripts/item_ball_scripts.pory"
Route119_EventScript_ItemSuperRepel:: @ 8290EE0
# 163 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_SUPER_REPEL
# 164 "data/scripts/item_ball_scripts.pory"
	end
# 165 "data/scripts/item_ball_scripts.pory"

# 166 "data/scripts/item_ball_scripts.pory"
Route119_EventScript_ItemZinc:: @ 8290EED
# 167 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ZINC
# 168 "data/scripts/item_ball_scripts.pory"
	end
# 169 "data/scripts/item_ball_scripts.pory"

# 170 "data/scripts/item_ball_scripts.pory"
Route119_EventScript_ItemElixir:: @ 8290EFA
# 171 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ELIXIR
# 172 "data/scripts/item_ball_scripts.pory"
	end
# 173 "data/scripts/item_ball_scripts.pory"

# 174 "data/scripts/item_ball_scripts.pory"
Route119_EventScript_ItemLeafStone:: @ 8290F07
# 175 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_LEAF_STONE
# 176 "data/scripts/item_ball_scripts.pory"
	end
# 177 "data/scripts/item_ball_scripts.pory"

# 178 "data/scripts/item_ball_scripts.pory"
Route119_EventScript_ItemRareCandy:: @ 8290F14
# 179 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_STARDUST
# 180 "data/scripts/item_ball_scripts.pory"
	end
# 181 "data/scripts/item_ball_scripts.pory"

# 182 "data/scripts/item_ball_scripts.pory"
Route119_EventScript_ItemHyperPotion:: @ 8290F21
# 183 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_HYPER_POTION
# 184 "data/scripts/item_ball_scripts.pory"
	end
# 185 "data/scripts/item_ball_scripts.pory"

# 186 "data/scripts/item_ball_scripts.pory"
Route119_EventScript_ItemHyperPotion2:: @ 8290F2E
# 187 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_HYPER_POTION
# 188 "data/scripts/item_ball_scripts.pory"
	end
# 189 "data/scripts/item_ball_scripts.pory"

# 190 "data/scripts/item_ball_scripts.pory"
Route119_EventScript_ItemElixir2:: @ 8290F3B
# 191 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ELIXIR
# 192 "data/scripts/item_ball_scripts.pory"
	end
# 193 "data/scripts/item_ball_scripts.pory"

# 194 "data/scripts/item_ball_scripts.pory"
Route120_EventScript_ItemNugget:: @ 8290F48
# 195 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_BLACK_SLUDGE
# 196 "data/scripts/item_ball_scripts.pory"
	end
# 197 "data/scripts/item_ball_scripts.pory"

# 198 "data/scripts/item_ball_scripts.pory"
Route120_EventScript_ItemFullHeal:: @ 8290F55
# 199 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_FULL_HEAL
# 200 "data/scripts/item_ball_scripts.pory"
	end
# 201 "data/scripts/item_ball_scripts.pory"

# 202 "data/scripts/item_ball_scripts.pory"
Route120_EventScript_ItemHyperPotion:: @ 8290F62
# 203 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_HYPER_POTION
# 204 "data/scripts/item_ball_scripts.pory"
	end
# 205 "data/scripts/item_ball_scripts.pory"

# 206 "data/scripts/item_ball_scripts.pory"
Route120_EventScript_ItemNestBall:: @ 8290F6F
# 207 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_NEST_BALL
# 208 "data/scripts/item_ball_scripts.pory"
	end
# 209 "data/scripts/item_ball_scripts.pory"

# 210 "data/scripts/item_ball_scripts.pory"
Route120_EventScript_ItemRevive:: @ 8290F7C
# 211 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_REVIVE
# 212 "data/scripts/item_ball_scripts.pory"
	end
# 213 "data/scripts/item_ball_scripts.pory"

# 214 "data/scripts/item_ball_scripts.pory"
Route121_EventScript_ItemCarbos:: @ 8290F89
# 215 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_CARBOS
# 216 "data/scripts/item_ball_scripts.pory"
	end
# 217 "data/scripts/item_ball_scripts.pory"

# 218 "data/scripts/item_ball_scripts.pory"
Route121_EventScript_ItemRevive:: @ 8290F96
# 219 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_REVIVE
# 220 "data/scripts/item_ball_scripts.pory"
	end
# 221 "data/scripts/item_ball_scripts.pory"

# 222 "data/scripts/item_ball_scripts.pory"
Route121_EventScript_ItemZinc:: @ 8290FA3
# 223 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ZINC
# 224 "data/scripts/item_ball_scripts.pory"
	end
# 225 "data/scripts/item_ball_scripts.pory"

# 226 "data/scripts/item_ball_scripts.pory"
Route123_EventScript_ItemCalcium:: @ 8290FB0
# 227 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_CALCIUM
# 228 "data/scripts/item_ball_scripts.pory"
	end
# 229 "data/scripts/item_ball_scripts.pory"

# 230 "data/scripts/item_ball_scripts.pory"
Route123_EventScript_ItemUltraBall:: @ 8290FBD
# 231 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ULTRA_BALL
# 232 "data/scripts/item_ball_scripts.pory"
	end
# 233 "data/scripts/item_ball_scripts.pory"

# 234 "data/scripts/item_ball_scripts.pory"
Route123_EventScript_ItemElixir:: @ 8290FCA
# 235 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ELIXIR
# 236 "data/scripts/item_ball_scripts.pory"
	end
# 237 "data/scripts/item_ball_scripts.pory"

# 238 "data/scripts/item_ball_scripts.pory"
Route123_EventScript_ItemPPUp:: @ 8290FD7
# 239 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POKE_BALL
# 240 "data/scripts/item_ball_scripts.pory"
	end
# 241 "data/scripts/item_ball_scripts.pory"

# 242 "data/scripts/item_ball_scripts.pory"
Route123_EventScript_ItemRevivalHerb:: @ 8290FE4
# 243 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_REVIVAL_HERB
# 244 "data/scripts/item_ball_scripts.pory"
	end
# 245 "data/scripts/item_ball_scripts.pory"

# 246 "data/scripts/item_ball_scripts.pory"
Route124_EventScript_ItemRedShard:: @ 8290FF1
# 247 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_RED_SHARD
# 248 "data/scripts/item_ball_scripts.pory"
	end
# 249 "data/scripts/item_ball_scripts.pory"

# 250 "data/scripts/item_ball_scripts.pory"
Route124_EventScript_ItemBlueShard:: @ 8290FFE
# 251 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_BLUE_SHARD
# 252 "data/scripts/item_ball_scripts.pory"
	end
# 253 "data/scripts/item_ball_scripts.pory"

# 254 "data/scripts/item_ball_scripts.pory"
Route124_EventScript_ItemYellowShard:: @ 829100B
# 255 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_YELLOW_SHARD
# 256 "data/scripts/item_ball_scripts.pory"
	end
# 257 "data/scripts/item_ball_scripts.pory"

# 258 "data/scripts/item_ball_scripts.pory"
Route125_EventScript_ItemBigPearl:: @ 8291018
# 259 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_BIG_PEARL
# 260 "data/scripts/item_ball_scripts.pory"
	end
# 261 "data/scripts/item_ball_scripts.pory"

# 262 "data/scripts/item_ball_scripts.pory"
Route126_EventScript_ItemGreenShard:: @ 8291025
# 263 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_GREEN_SHARD
# 264 "data/scripts/item_ball_scripts.pory"
	end
# 265 "data/scripts/item_ball_scripts.pory"

# 266 "data/scripts/item_ball_scripts.pory"
Route127_EventScript_ItemZinc:: @ 8291032
# 267 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ZINC
# 268 "data/scripts/item_ball_scripts.pory"
	end
# 269 "data/scripts/item_ball_scripts.pory"

# 270 "data/scripts/item_ball_scripts.pory"
Route127_EventScript_ItemCarbos:: @ 829103F
# 271 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_CARBOS
# 272 "data/scripts/item_ball_scripts.pory"
	end
# 273 "data/scripts/item_ball_scripts.pory"

# 274 "data/scripts/item_ball_scripts.pory"
Route127_EventScript_ItemRareCandy:: @ 829104C
# 275 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_STARDUST
# 276 "data/scripts/item_ball_scripts.pory"
	end
# 277 "data/scripts/item_ball_scripts.pory"

# 278 "data/scripts/item_ball_scripts.pory"
Route132_EventScript_ItemRareCandy:: @ 8291059
# 279 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_STARDUST
# 280 "data/scripts/item_ball_scripts.pory"
	end
# 281 "data/scripts/item_ball_scripts.pory"

# 282 "data/scripts/item_ball_scripts.pory"
Route132_EventScript_ItemProtein:: @ 8291066
# 283 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_PROTEIN
# 284 "data/scripts/item_ball_scripts.pory"
	end
# 285 "data/scripts/item_ball_scripts.pory"

# 286 "data/scripts/item_ball_scripts.pory"
Route133_EventScript_ItemBigPearl:: @ 8291073
# 287 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_BIG_PEARL
# 288 "data/scripts/item_ball_scripts.pory"
	end
# 289 "data/scripts/item_ball_scripts.pory"

# 290 "data/scripts/item_ball_scripts.pory"
Route133_EventScript_ItemStarPiece:: @ 8291080
# 291 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_STAR_PIECE
# 292 "data/scripts/item_ball_scripts.pory"
	end
# 293 "data/scripts/item_ball_scripts.pory"

# 294 "data/scripts/item_ball_scripts.pory"
Route133_EventScript_ItemMaxRevive:: @ 829108D
# 295 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MAX_REVIVE
# 296 "data/scripts/item_ball_scripts.pory"
	end
# 297 "data/scripts/item_ball_scripts.pory"

# 298 "data/scripts/item_ball_scripts.pory"
Route134_EventScript_ItemCarbos:: @ 829109A
# 299 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_CARBOS
# 300 "data/scripts/item_ball_scripts.pory"
	end
# 301 "data/scripts/item_ball_scripts.pory"

# 302 "data/scripts/item_ball_scripts.pory"
Route134_EventScript_ItemStarPiece:: @ 82910A7
# 303 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_STAR_PIECE
# 304 "data/scripts/item_ball_scripts.pory"
	end
# 305 "data/scripts/item_ball_scripts.pory"

# 306 "data/scripts/item_ball_scripts.pory"
PetalburgCity_EventScript_ItemMaxRevive:: @ 82910B4
# 307 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MAX_REVIVE
# 308 "data/scripts/item_ball_scripts.pory"
	end
# 309 "data/scripts/item_ball_scripts.pory"

# 310 "data/scripts/item_ball_scripts.pory"
PetalburgCity_EventScript_ItemEther:: @ 82910C1
# 311 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ETHER
# 312 "data/scripts/item_ball_scripts.pory"
	end
# 313 "data/scripts/item_ball_scripts.pory"

# 314 "data/scripts/item_ball_scripts.pory"
MauvilleCity_EventScript_ItemXSpeed:: @ 82910CE
# 315 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_X_SPEED
# 316 "data/scripts/item_ball_scripts.pory"
	end
# 317 "data/scripts/item_ball_scripts.pory"

# 318 "data/scripts/item_ball_scripts.pory"
RustboroCity_EventScript_ItemXDefend:: @ 82910DB
# 319 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_X_DEFENSE
# 320 "data/scripts/item_ball_scripts.pory"
	end
# 321 "data/scripts/item_ball_scripts.pory"

# 322 "data/scripts/item_ball_scripts.pory"
LilycoveCity_EventScript_ItemMaxRepel:: @ 82910E8
# 323 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MAX_REPEL
# 324 "data/scripts/item_ball_scripts.pory"
	end
# 325 "data/scripts/item_ball_scripts.pory"

# 326 "data/scripts/item_ball_scripts.pory"
MossdeepCity_EventScript_ItemNetBall:: @ 82910F5
# 327 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_NET_BALL
# 328 "data/scripts/item_ball_scripts.pory"
	end
# 329 "data/scripts/item_ball_scripts.pory"

# 330 "data/scripts/item_ball_scripts.pory"
PetalburgWoods_EventScript_ItemXAttack:: @ 8291102
# 331 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_X_ATTACK
# 332 "data/scripts/item_ball_scripts.pory"
	end
# 333 "data/scripts/item_ball_scripts.pory"

# 334 "data/scripts/item_ball_scripts.pory"
PetalburgWoods_EventScript_ItemGreatBall:: @ 829110F
# 335 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_GREAT_BALL
# 336 "data/scripts/item_ball_scripts.pory"
	end
# 337 "data/scripts/item_ball_scripts.pory"

# 338 "data/scripts/item_ball_scripts.pory"
PetalburgWoods_EventScript_ItemEther:: @ 829111C
# 339 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ETHER
# 340 "data/scripts/item_ball_scripts.pory"
	end
# 341 "data/scripts/item_ball_scripts.pory"

# 342 "data/scripts/item_ball_scripts.pory"
PetalburgWoods_EventScript_ItemParalyzeHeal:: @ 8291129
# 343 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_PARALYZE_HEAL
# 344 "data/scripts/item_ball_scripts.pory"
	end
# 345 "data/scripts/item_ball_scripts.pory"

# 346 "data/scripts/item_ball_scripts.pory"
RusturfTunnel_EventScript_ItemPokeBall:: @ 8291136
# 347 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POKE_BALL
# 348 "data/scripts/item_ball_scripts.pory"
	end
# 349 "data/scripts/item_ball_scripts.pory"

# 350 "data/scripts/item_ball_scripts.pory"
RusturfTunnel_EventScript_ItemMaxEther:: @ 8291143
# 351 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MAX_ETHER
# 352 "data/scripts/item_ball_scripts.pory"
	end
# 353 "data/scripts/item_ball_scripts.pory"

# 354 "data/scripts/item_ball_scripts.pory"
GraniteCave_1F_EventScript_ItemEscapeRope:: @ 8291150
# 355 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ESCAPE_ROPE
# 356 "data/scripts/item_ball_scripts.pory"
	end
# 357 "data/scripts/item_ball_scripts.pory"

# 358 "data/scripts/item_ball_scripts.pory"
GraniteCave_B1F_EventScript_ItemPokeBall:: @ 829115D
# 359 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POKE_BALL
# 360 "data/scripts/item_ball_scripts.pory"
	end
# 361 "data/scripts/item_ball_scripts.pory"

# 362 "data/scripts/item_ball_scripts.pory"
GraniteCave_B2F_EventScript_ItemRepel:: @ 829116A
# 363 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_REPEL
# 364 "data/scripts/item_ball_scripts.pory"
	end
# 365 "data/scripts/item_ball_scripts.pory"

# 366 "data/scripts/item_ball_scripts.pory"
GraniteCave_B2F_EventScript_ItemRareCandy:: @ 8291177
# 367 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_STARDUST
# 368 "data/scripts/item_ball_scripts.pory"
	end
# 369 "data/scripts/item_ball_scripts.pory"

# 370 "data/scripts/item_ball_scripts.pory"
JaggedPass_EventScript_ItemBurnHeal:: @ 8291184
# 371 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_BURN_HEAL
# 372 "data/scripts/item_ball_scripts.pory"
	end
# 373 "data/scripts/item_ball_scripts.pory"

# 374 "data/scripts/item_ball_scripts.pory"
FieryPath_EventScript_ItemFireStone:: @ 8291191
# 375 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_FIRE_STONE
# 376 "data/scripts/item_ball_scripts.pory"
	end
# 377 "data/scripts/item_ball_scripts.pory"

# 378 "data/scripts/item_ball_scripts.pory"
FieryPath_EventScript_ItemTM06:: @ 829119E
# 379 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM06
# 380 "data/scripts/item_ball_scripts.pory"
	end
# 381 "data/scripts/item_ball_scripts.pory"

# 382 "data/scripts/item_ball_scripts.pory"
MeteorFalls_1F_1R_EventScript_ItemTM23:: @ 82911AB
# 383 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM23
# 384 "data/scripts/item_ball_scripts.pory"
	end
# 385 "data/scripts/item_ball_scripts.pory"

# 386 "data/scripts/item_ball_scripts.pory"
MeteorFalls_1F_1R_EventScript_ItemFullHeal:: @ 82911B8
# 387 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_FULL_HEAL
# 388 "data/scripts/item_ball_scripts.pory"
	end
# 389 "data/scripts/item_ball_scripts.pory"

# 390 "data/scripts/item_ball_scripts.pory"
MeteorFalls_1F_1R_EventScript_ItemMoonStone:: @ 82911C5
# 391 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MOON_STONE
# 392 "data/scripts/item_ball_scripts.pory"
	end
# 393 "data/scripts/item_ball_scripts.pory"

# 394 "data/scripts/item_ball_scripts.pory"
MeteorFalls_1F_1R_EventScript_ItemPPUP:: @ 82911D2
# 395 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POKE_BALL
# 396 "data/scripts/item_ball_scripts.pory"
	end
# 397 "data/scripts/item_ball_scripts.pory"

# 398 "data/scripts/item_ball_scripts.pory"
MeteorFalls_B1F_2R_EventScript_ItemTM02:: @ 82911DF
# 399 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM02
# 400 "data/scripts/item_ball_scripts.pory"
	end
# 401 "data/scripts/item_ball_scripts.pory"

# 402 "data/scripts/item_ball_scripts.pory"
NewMauville_Inside_EventScript_ItemUltraBall:: @ 82911EC
# 403 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ULTRA_BALL
# 404 "data/scripts/item_ball_scripts.pory"
	end
# 405 "data/scripts/item_ball_scripts.pory"

# 406 "data/scripts/item_ball_scripts.pory"
NewMauville_Inside_EventScript_ItemEscapeRope:: @ 82911F9
# 407 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ESCAPE_ROPE
# 408 "data/scripts/item_ball_scripts.pory"
	end
# 409 "data/scripts/item_ball_scripts.pory"

# 410 "data/scripts/item_ball_scripts.pory"
NewMauville_Inside_EventScript_ItemThunderStone:: @ 8291206
# 411 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_THUNDER_STONE
# 412 "data/scripts/item_ball_scripts.pory"
	end
# 413 "data/scripts/item_ball_scripts.pory"

# 414 "data/scripts/item_ball_scripts.pory"
NewMauville_Inside_EventScript_ItemFullHeal:: @ 8291213
# 415 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_FULL_HEAL
# 416 "data/scripts/item_ball_scripts.pory"
	end
# 417 "data/scripts/item_ball_scripts.pory"

# 418 "data/scripts/item_ball_scripts.pory"
NewMauville_Inside_EventScript_ItemParalyzeHeal:: @ 8291220
# 419 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_PARALYZE_HEAL
# 420 "data/scripts/item_ball_scripts.pory"
	end
# 421 "data/scripts/item_ball_scripts.pory"

# 422 "data/scripts/item_ball_scripts.pory"
AbandonedShip_Rooms_1F_EventScript_ItemHarborMail:: @ 829122D
# 423 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_HARBOR_MAIL
# 424 "data/scripts/item_ball_scripts.pory"
	end
# 425 "data/scripts/item_ball_scripts.pory"

# 426 "data/scripts/item_ball_scripts.pory"
AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope:: @ 829123A
# 427 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ESCAPE_ROPE
# 428 "data/scripts/item_ball_scripts.pory"
	end
# 429 "data/scripts/item_ball_scripts.pory"

# 430 "data/scripts/item_ball_scripts.pory"
AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall:: @ 8291247
# 431 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_DIVE_BALL
# 432 "data/scripts/item_ball_scripts.pory"
	end
# 433 "data/scripts/item_ball_scripts.pory"

# 434 "data/scripts/item_ball_scripts.pory"
AbandonedShip_Room_B1F_EventScript_ItemTM13:: @ 8291254
# 435 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM13
# 436 "data/scripts/item_ball_scripts.pory"
	end
# 437 "data/scripts/item_ball_scripts.pory"

# 438 "data/scripts/item_ball_scripts.pory"
AbandonedShip_Rooms2_1F_EventScript_ItemRevive:: @ 8291261
# 439 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_REVIVE
# 440 "data/scripts/item_ball_scripts.pory"
	end
# 441 "data/scripts/item_ball_scripts.pory"

# 442 "data/scripts/item_ball_scripts.pory"
AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey:: @ 829126E
# 443 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_STORAGE_KEY
# 444 "data/scripts/item_ball_scripts.pory"
	end
# 445 "data/scripts/item_ball_scripts.pory"

# 446 "data/scripts/item_ball_scripts.pory"
AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall:: @ 829127B
# 447 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_LUXURY_BALL
# 448 "data/scripts/item_ball_scripts.pory"
	end
# 449 "data/scripts/item_ball_scripts.pory"

# 450 "data/scripts/item_ball_scripts.pory"
AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner:: @ 8291288
# 451 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_SCANNER
# 452 "data/scripts/item_ball_scripts.pory"
	end
# 453 "data/scripts/item_ball_scripts.pory"

# 454 "data/scripts/item_ball_scripts.pory"
AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone:: @ 8291295
# 455 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_WATER_STONE
# 456 "data/scripts/item_ball_scripts.pory"
	end
# 457 "data/scripts/item_ball_scripts.pory"

# 458 "data/scripts/item_ball_scripts.pory"
AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18:: @ 82912A2
# 459 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM18
# 460 "data/scripts/item_ball_scripts.pory"
	end
# 461 "data/scripts/item_ball_scripts.pory"

# 462 "data/scripts/item_ball_scripts.pory"
ScorchedSlab_EventScript_ItemTM11:: @ 82912AF
# 463 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM11
# 464 "data/scripts/item_ball_scripts.pory"
	end
# 465 "data/scripts/item_ball_scripts.pory"

# 466 "data/scripts/item_ball_scripts.pory"
SafariZone_Northwest_EventScript_ItemTM22:: @ 82912BC
# 467 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM22
# 468 "data/scripts/item_ball_scripts.pory"
	end
# 469 "data/scripts/item_ball_scripts.pory"

# 470 "data/scripts/item_ball_scripts.pory"
SafariZone_North_EventScript_ItemCalcium:: @ 82912C9
# 471 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_CALCIUM
# 472 "data/scripts/item_ball_scripts.pory"
	end
# 473 "data/scripts/item_ball_scripts.pory"

# 474 "data/scripts/item_ball_scripts.pory"
SafariZone_Southwest_EventScript_ItemMaxRevive:: @ 82912D6
# 475 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MAX_REVIVE
# 476 "data/scripts/item_ball_scripts.pory"
	end
# 477 "data/scripts/item_ball_scripts.pory"

# 478 "data/scripts/item_ball_scripts.pory"
SafariZone_Northeast_EventScript_ItemNugget:: @ 82912E3
# 479 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_NUGGET
# 480 "data/scripts/item_ball_scripts.pory"
	end
# 481 "data/scripts/item_ball_scripts.pory"

# 482 "data/scripts/item_ball_scripts.pory"
SafariZone_Southeast_EventScript_ItemBigPearl:: @ 82912F0
# 483 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_BIG_PEARL
# 484 "data/scripts/item_ball_scripts.pory"
	end
# 485 "data/scripts/item_ball_scripts.pory"

# 486 "data/scripts/item_ball_scripts.pory"
MtPyre_2F_EventScript_ItemUltraBall:: @ 82912FD
# 487 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ULTRA_BALL
# 488 "data/scripts/item_ball_scripts.pory"
	end
# 489 "data/scripts/item_ball_scripts.pory"

# 490 "data/scripts/item_ball_scripts.pory"
MtPyre_3F_EventScript_ItemSuperRepel:: @ 829130A
# 491 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_SUPER_REPEL
# 492 "data/scripts/item_ball_scripts.pory"
	end
# 493 "data/scripts/item_ball_scripts.pory"

# 494 "data/scripts/item_ball_scripts.pory"
MtPyre_4F_EventScript_ItemSeaIncense:: @ 8291317
# 495 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_SEA_INCENSE
# 496 "data/scripts/item_ball_scripts.pory"
	end
# 497 "data/scripts/item_ball_scripts.pory"

# 498 "data/scripts/item_ball_scripts.pory"
MtPyre_5F_EventScript_ItemLaxIncense:: @ 8291324
# 499 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_LAX_INCENSE
# 500 "data/scripts/item_ball_scripts.pory"
	end
# 501 "data/scripts/item_ball_scripts.pory"

# 502 "data/scripts/item_ball_scripts.pory"
MtPyre_6F_EventScript_ItemTM30:: @ 8291331
# 503 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM30
# 504 "data/scripts/item_ball_scripts.pory"
	end
# 505 "data/scripts/item_ball_scripts.pory"

# 506 "data/scripts/item_ball_scripts.pory"
MtPyre_Exterior_EventScript_ItemMaxPotion:: @ 829133E
# 507 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MAX_POTION
# 508 "data/scripts/item_ball_scripts.pory"
	end
# 509 "data/scripts/item_ball_scripts.pory"

# 510 "data/scripts/item_ball_scripts.pory"
MtPyre_Exterior_EventScript_ItemTM48:: @ 829134B
# 511 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM48
# 512 "data/scripts/item_ball_scripts.pory"
	end
# 513 "data/scripts/item_ball_scripts.pory"

# 514 "data/scripts/item_ball_scripts.pory"
AquaHideout_B1F_EventScript_ItemMasterBall:: @ 8291358
# 515 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POKE_BALL
# 516 "data/scripts/item_ball_scripts.pory"
	end
# 517 "data/scripts/item_ball_scripts.pory"

# 518 "data/scripts/item_ball_scripts.pory"
AquaHideout_B1F_EventScript_ItemNugget:: @ 8291365
# 519 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_NUGGET
# 520 "data/scripts/item_ball_scripts.pory"
	end
# 521 "data/scripts/item_ball_scripts.pory"

# 522 "data/scripts/item_ball_scripts.pory"
AquaHideout_B1F_EventScript_ItemMaxElixir:: @ 8291372
# 523 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MAX_ELIXIR
# 524 "data/scripts/item_ball_scripts.pory"
	end
# 525 "data/scripts/item_ball_scripts.pory"

# 526 "data/scripts/item_ball_scripts.pory"
AquaHideout_B2F_EventScript_ItemNestBall:: @ 829137F
# 527 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_NEST_BALL
# 528 "data/scripts/item_ball_scripts.pory"
	end
# 529 "data/scripts/item_ball_scripts.pory"

# 530 "data/scripts/item_ball_scripts.pory"
AquaHideout_B2F_EventScript_ItemMasterBall:: @ 829138C
# 531 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POKE_BALL      // Unused
# 532 "data/scripts/item_ball_scripts.pory"
	end
# 533 "data/scripts/item_ball_scripts.pory"

# 534 "data/scripts/item_ball_scripts.pory"
Route119_EventScript_ItemNugget:: @ 8291399
# 535 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_NUGGET
# 536 "data/scripts/item_ball_scripts.pory"
	end
# 537 "data/scripts/item_ball_scripts.pory"

# 538 "data/scripts/item_ball_scripts.pory"
Route119_EventScript_ItemMaxElixir:: @ 82913A6
# 539 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MAX_ELIXIR
# 540 "data/scripts/item_ball_scripts.pory"
	end
# 541 "data/scripts/item_ball_scripts.pory"

# 542 "data/scripts/item_ball_scripts.pory"
Route119_EventScript_ItemNestBall:: @ 82913B3
# 543 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_NEST_BALL
# 544 "data/scripts/item_ball_scripts.pory"
	end
# 545 "data/scripts/item_ball_scripts.pory"

# 546 "data/scripts/item_ball_scripts.pory"
ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl:: @ 82913C0
# 547 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_BIG_PEARL
# 548 "data/scripts/item_ball_scripts.pory"
	end
# 549 "data/scripts/item_ball_scripts.pory"

# 550 "data/scripts/item_ball_scripts.pory"
ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy:: @ 82913CD
# 551 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_STARDUST
# 552 "data/scripts/item_ball_scripts.pory"
	end
# 553 "data/scripts/item_ball_scripts.pory"

# 554 "data/scripts/item_ball_scripts.pory"
ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal:: @ 82913DA
# 555 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ICE_HEAL
# 556 "data/scripts/item_ball_scripts.pory"
	end
# 557 "data/scripts/item_ball_scripts.pory"

# 558 "data/scripts/item_ball_scripts.pory"
ShoalCave_LowTideIceRoom_EventScript_ItemTM07:: @ 82913E7
# 559 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM07
# 560 "data/scripts/item_ball_scripts.pory"
	end
# 561 "data/scripts/item_ball_scripts.pory"

# 562 "data/scripts/item_ball_scripts.pory"
ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce:: @ 82913F4
# 563 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_NEVER_MELT_ICE
# 564 "data/scripts/item_ball_scripts.pory"
	end
# 565 "data/scripts/item_ball_scripts.pory"

# 566 "data/scripts/item_ball_scripts.pory"
SeafloorCavern_Room9_EventScript_ItemTM26:: @ 8291401
# 567 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM26
# 568 "data/scripts/item_ball_scripts.pory"
	end
# 569 "data/scripts/item_ball_scripts.pory"

# 570 "data/scripts/item_ball_scripts.pory"
Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail:: @ 829140E
# 571 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ORANGE_MAIL
# 572 "data/scripts/item_ball_scripts.pory"
	end
# 573 "data/scripts/item_ball_scripts.pory"

# 574 "data/scripts/item_ball_scripts.pory"
Route110_TrickHousePuzzle2_EventScript_ItemHarborMail:: @ 829141B
# 575 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_HARBOR_MAIL
# 576 "data/scripts/item_ball_scripts.pory"
	end
# 577 "data/scripts/item_ball_scripts.pory"

# 578 "data/scripts/item_ball_scripts.pory"
Route110_TrickHousePuzzle2_EventScript_ItemWaveMail:: @ 8291428
# 579 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_WAVE_MAIL
# 580 "data/scripts/item_ball_scripts.pory"
	end
# 581 "data/scripts/item_ball_scripts.pory"

# 582 "data/scripts/item_ball_scripts.pory"
Route110_TrickHousePuzzle3_EventScript_ItemShadowMail:: @ 8291435
# 583 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_SHADOW_MAIL
# 584 "data/scripts/item_ball_scripts.pory"
	end
# 585 "data/scripts/item_ball_scripts.pory"

# 586 "data/scripts/item_ball_scripts.pory"
Route110_TrickHousePuzzle3_EventScript_ItemWoodMail:: @ 8291442
# 587 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_WOOD_MAIL
# 588 "data/scripts/item_ball_scripts.pory"
	end
# 589 "data/scripts/item_ball_scripts.pory"

# 590 "data/scripts/item_ball_scripts.pory"
Route110_TrickHousePuzzle4_EventScript_ItemMechMail:: @ 829144F
# 591 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MECH_MAIL
# 592 "data/scripts/item_ball_scripts.pory"
	end
# 593 "data/scripts/item_ball_scripts.pory"

# 594 "data/scripts/item_ball_scripts.pory"
Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail:: @ 829145C
# 595 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_GLITTER_MAIL
# 596 "data/scripts/item_ball_scripts.pory"
	end
# 597 "data/scripts/item_ball_scripts.pory"

# 598 "data/scripts/item_ball_scripts.pory"
Route110_TrickHousePuzzle7_EventScript_ItemTropicMail:: @ 8291469
# 599 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TROPIC_MAIL
# 600 "data/scripts/item_ball_scripts.pory"
	end
# 601 "data/scripts/item_ball_scripts.pory"

# 602 "data/scripts/item_ball_scripts.pory"
Route110_TrickHousePuzzle8_EventScript_ItemBeadMail:: @ 8291476
# 603 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_BEAD_MAIL
# 604 "data/scripts/item_ball_scripts.pory"
	end
# 605 "data/scripts/item_ball_scripts.pory"

# 606 "data/scripts/item_ball_scripts.pory"
VictoryRoad_1F_EventScript_ItemMaxElixir:: @ 8291483
# 607 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MAX_ELIXIR
# 608 "data/scripts/item_ball_scripts.pory"
	end
# 609 "data/scripts/item_ball_scripts.pory"

# 610 "data/scripts/item_ball_scripts.pory"
VictoryRoad_1F_EventScript_ItemPPUp:: @ 8291490
# 611 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POKE_BALL
# 612 "data/scripts/item_ball_scripts.pory"
	end
# 613 "data/scripts/item_ball_scripts.pory"

# 614 "data/scripts/item_ball_scripts.pory"
VictoryRoad_B1F_EventScript_ItemTM29:: @ 829149D
# 615 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM29
# 616 "data/scripts/item_ball_scripts.pory"
	end
# 617 "data/scripts/item_ball_scripts.pory"

# 618 "data/scripts/item_ball_scripts.pory"
VictoryRoad_B1F_EventScript_ItemFullRestore:: @ 82914AA
# 619 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_FULL_RESTORE
# 620 "data/scripts/item_ball_scripts.pory"
	end
# 621 "data/scripts/item_ball_scripts.pory"

# 622 "data/scripts/item_ball_scripts.pory"
VictoryRoad_B2F_EventScript_ItemFullHeal:: @ 82914B7
# 623 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_FULL_HEAL
# 624 "data/scripts/item_ball_scripts.pory"
	end
# 625 "data/scripts/item_ball_scripts.pory"

# 626 "data/scripts/item_ball_scripts.pory"
ArtisanCave_B1F_EventScript_ItemHPUp:: @ 82914C4
# 627 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_HP_UP
# 628 "data/scripts/item_ball_scripts.pory"
	end
# 629 "data/scripts/item_ball_scripts.pory"

# 630 "data/scripts/item_ball_scripts.pory"
ArtisanCave_1F_EventScript_ItemCarbos:: @ 82914D1
# 631 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_CARBOS
# 632 "data/scripts/item_ball_scripts.pory"
	end
# 633 "data/scripts/item_ball_scripts.pory"

# 634 "data/scripts/item_ball_scripts.pory"
MagmaHideout_1F_EventScript_ItemRareCandy:: @ 82914DE
# 635 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_STARDUST
# 636 "data/scripts/item_ball_scripts.pory"
	end
# 637 "data/scripts/item_ball_scripts.pory"

# 638 "data/scripts/item_ball_scripts.pory"
MagmaHideout_2F_2R_EventScript_MaxElixir:: @ 82914EB
# 639 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MAX_ELIXIR
# 640 "data/scripts/item_ball_scripts.pory"
	end
# 641 "data/scripts/item_ball_scripts.pory"

# 642 "data/scripts/item_ball_scripts.pory"
MagmaHideout_2F_2R_EventScript_ItemFullRestore:: @ 82914F8
# 643 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_FULL_RESTORE
# 644 "data/scripts/item_ball_scripts.pory"
	end
# 645 "data/scripts/item_ball_scripts.pory"

# 646 "data/scripts/item_ball_scripts.pory"
MagmaHideout_3F_1R_EventScript_ItemNugget:: @ 8291505
# 647 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_NUGGET
# 648 "data/scripts/item_ball_scripts.pory"
	end
# 649 "data/scripts/item_ball_scripts.pory"

# 650 "data/scripts/item_ball_scripts.pory"
MagmaHideout_3F_2R_EventScript_ItemPPMax:: @ 8291512
# 651 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_POKE_BALL
# 652 "data/scripts/item_ball_scripts.pory"
	end
# 653 "data/scripts/item_ball_scripts.pory"

# 654 "data/scripts/item_ball_scripts.pory"
MagmaHideout_4F_EventScript_MaxRevive:: @ 829151F
# 655 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MAX_REVIVE
# 656 "data/scripts/item_ball_scripts.pory"
	end
# 657 "data/scripts/item_ball_scripts.pory"

# 658 "data/scripts/item_ball_scripts.pory"
MagmaHideout_3F_3R_EventScript_ItemEscapeRope:: @ 829152C
# 659 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ESCAPE_ROPE
# 660 "data/scripts/item_ball_scripts.pory"
	end
# 661 "data/scripts/item_ball_scripts.pory"

# 662 "data/scripts/item_ball_scripts.pory"
ScorchedSlab_EventScript_ItemTyranitarite::
# 663 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TYRANITARITE
# 664 "data/scripts/item_ball_scripts.pory"
	end
# 665 "data/scripts/item_ball_scripts.pory"
	
# 666 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemBeedrillite::
# 667 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_BEEDRILLITE
# 668 "data/scripts/item_ball_scripts.pory"
	end
# 669 "data/scripts/item_ball_scripts.pory"
	
# 670 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemSteelixite::
# 671 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_STEELIXITE
# 672 "data/scripts/item_ball_scripts.pory"
	end
# 673 "data/scripts/item_ball_scripts.pory"
	
# 674 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemSablenite::
# 675 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_SABLENITE
# 676 "data/scripts/item_ball_scripts.pory"
	end
# 677 "data/scripts/item_ball_scripts.pory"
	
# 678 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemMawilite::
# 679 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MAWILITE
# 680 "data/scripts/item_ball_scripts.pory"
	end
# 681 "data/scripts/item_ball_scripts.pory"
	
# 682 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemSharpedoite::
# 683 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_SHARPEDONITE
# 684 "data/scripts/item_ball_scripts.pory"
	end
# 685 "data/scripts/item_ball_scripts.pory"
	
# 686 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemCameruptite::
# 687 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_CAMERUPTITE
# 688 "data/scripts/item_ball_scripts.pory"
	end
# 689 "data/scripts/item_ball_scripts.pory"
	
# 690 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemAltarianite::
# 691 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ALTARIANITE
# 692 "data/scripts/item_ball_scripts.pory"
	end
# 693 "data/scripts/item_ball_scripts.pory"
	
# 694 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemGlailite::
# 695 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_GLALITITE
# 696 "data/scripts/item_ball_scripts.pory"
	end
# 697 "data/scripts/item_ball_scripts.pory"
	
# 698 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemSalamancite::
# 699 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_SALAMENCITE
# 700 "data/scripts/item_ball_scripts.pory"
	end
# 701 "data/scripts/item_ball_scripts.pory"
	
# 702 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemMetagrossite::
# 703 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_METAGROSSITE
# 704 "data/scripts/item_ball_scripts.pory"
	end
# 705 "data/scripts/item_ball_scripts.pory"
	
# 706 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemLopunnite::
# 707 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_LOPUNNITE
# 708 "data/scripts/item_ball_scripts.pory"
	end
# 709 "data/scripts/item_ball_scripts.pory"
	
# 710 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemGalladite::
# 711 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_GALLADITE
# 712 "data/scripts/item_ball_scripts.pory"
	end
# 713 "data/scripts/item_ball_scripts.pory"
	
# 714 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemAudinite::
# 715 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_AUDINITE
# 716 "data/scripts/item_ball_scripts.pory"
	end
# 717 "data/scripts/item_ball_scripts.pory"
	
# 718 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemGardevoirite::
# 719 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_GARDEVOIRITE
# 720 "data/scripts/item_ball_scripts.pory"
	end
# 721 "data/scripts/item_ball_scripts.pory"
	
# 722 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemCharizardite_X::
# 723 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_CHARIZARDITE_X
# 724 "data/scripts/item_ball_scripts.pory"
	end
# 725 "data/scripts/item_ball_scripts.pory"
	
# 726 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemGengarite::
# 727 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_GENGARITE
# 728 "data/scripts/item_ball_scripts.pory"
	end
# 729 "data/scripts/item_ball_scripts.pory"
	
# 730 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemGyaradosite::
# 731 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_GYARADOSITE
# 732 "data/scripts/item_ball_scripts.pory"
	end
# 733 "data/scripts/item_ball_scripts.pory"
	
# 734 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemManectricite::
# 735 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MANECTITE
# 736 "data/scripts/item_ball_scripts.pory"
	end
# 737 "data/scripts/item_ball_scripts.pory"
	
# 738 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_ItemBanetite::
# 739 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_BANETTITE
# 740 "data/scripts/item_ball_scripts.pory"
	end
# 741 "data/scripts/item_ball_scripts.pory"
	
# 742 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_Ampharosite::
# 743 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_AMPHAROSITE
# 744 "data/scripts/item_ball_scripts.pory"
	end
# 745 "data/scripts/item_ball_scripts.pory"
	
# 746 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_Lucarionite::
# 747 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_LUCARIONITE
# 748 "data/scripts/item_ball_scripts.pory"
	end
# 749 "data/scripts/item_ball_scripts.pory"
	
# 750 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_Garchompite::
# 751 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_GARCHOMPITE
# 752 "data/scripts/item_ball_scripts.pory"
	end
# 753 "data/scripts/item_ball_scripts.pory"
	
# 754 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_Medichamite::
# 755 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MEDICHAMITE
# 756 "data/scripts/item_ball_scripts.pory"
	end	
# 757 "data/scripts/item_ball_scripts.pory"
	
# 758 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_Absolite::
# 759 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ABSOLITE
# 760 "data/scripts/item_ball_scripts.pory"
	end	
# 761 "data/scripts/item_ball_scripts.pory"

# 762 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_Pinsirite::
# 763 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_PINSIRITE
# 764 "data/scripts/item_ball_scripts.pory"
	end	
# 765 "data/scripts/item_ball_scripts.pory"
	
# 766 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_Scizorite::
# 767 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_SCIZORITE
# 768 "data/scripts/item_ball_scripts.pory"
	end	
# 769 "data/scripts/item_ball_scripts.pory"
	
# 770 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_Abomasite::
# 771 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ABOMASITE
# 772 "data/scripts/item_ball_scripts.pory"
	end	
# 773 "data/scripts/item_ball_scripts.pory"
	
# 774 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_Alakazite::
# 775 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_ALAKAZITE
# 776 "data/scripts/item_ball_scripts.pory"
	end
# 777 "data/scripts/item_ball_scripts.pory"
	
# 778 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_Mewtwonite_Y::
# 779 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_MEWTWONITE_Y
# 780 "data/scripts/item_ball_scripts.pory"
	end	
# 781 "data/scripts/item_ball_scripts.pory"
	
# 782 "data/scripts/item_ball_scripts.pory"
MegaStone_EventScript_Drednawite::
# 783 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_DREDNAWITE
# 784 "data/scripts/item_ball_scripts.pory"
	end	
# 785 "data/scripts/item_ball_scripts.pory"
	
# 786 "data/scripts/item_ball_scripts.pory"
PrimevalForest_EventScript_ItemGrassKnot::
# 787 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM86
# 788 "data/scripts/item_ball_scripts.pory"
	end	
# 789 "data/scripts/item_ball_scripts.pory"
	
# 790 "data/scripts/item_ball_scripts.pory"
PrimevalForest_EventScript_ItemShinyStone::
# 791 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_SHINY_STONE
# 792 "data/scripts/item_ball_scripts.pory"
	end
# 793 "data/scripts/item_ball_scripts.pory"
	
# 794 "data/scripts/item_ball_scripts.pory"
MagmaHideout_3F_3R_EventScript_ItemRedOrb::
# 795 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_RED_ORB
# 796 "data/scripts/item_ball_scripts.pory"
	end
# 797 "data/scripts/item_ball_scripts.pory"
	
# 798 "data/scripts/item_ball_scripts.pory"
RelicCave_EventScript_ItemFossil::
# 799 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_HELIX_FOSSIL
# 800 "data/scripts/item_ball_scripts.pory"
	end
# 801 "data/scripts/item_ball_scripts.pory"
	
# 802 "data/scripts/item_ball_scripts.pory"
Oldale_Ruins_EventScript_ItemTM80::
# 803 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM80
# 804 "data/scripts/item_ball_scripts.pory"
	end
# 805 "data/scripts/item_ball_scripts.pory"
	
# 806 "data/scripts/item_ball_scripts.pory"
Route106_EventScript_ItemTM99::
# 807 "data/scripts/item_ball_scripts.pory"
	addscaleditem ITEM_TM99
# 808 "data/scripts/item_ball_scripts.pory"
	end
# 809 "data/scripts/item_ball_scripts.pory"

# 810 "data/scripts/item_ball_scripts.pory"
Common_EventScript_FindItem::
# 811 "data/scripts/item_ball_scripts.pory"
	callnative GetObjectEventTrainerRangeFromTemplate
# 812 "data/scripts/item_ball_scripts.pory"
	finditem VAR_RESULT
# 813 "data/scripts/item_ball_scripts.pory"
	end
