# 1 "data/scripts/movement.pory"
Common_Movement_QuestionMark:
# 2 "data/scripts/movement.pory"
	emote_question_mark
	step_end

# 5 "data/scripts/movement.pory"
Common_Movement_ExclamationMark:
# 6 "data/scripts/movement.pory"
	emote_exclamation_mark
	step_end

# 9 "data/scripts/movement.pory"
Common_Movement_Delay48:
# 10 "data/scripts/movement.pory"
	delay_16
# 11 "data/scripts/movement.pory"
	delay_16
# 12 "data/scripts/movement.pory"
	delay_16
	step_end

# 15 "data/scripts/movement.pory"
Common_Movement_FacePlayer:
# 16 "data/scripts/movement.pory"
	face_player
	step_end

# 19 "data/scripts/movement.pory"
Common_Movement_FaceAwayPlayer:
# 20 "data/scripts/movement.pory"
	face_away_player
	step_end

# 23 "data/scripts/movement.pory"
Common_Movement_FaceOriginalDirection:
# 24 "data/scripts/movement.pory"
	face_original_direction
	step_end

# 27 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFastestLeft:
# 28 "data/scripts/movement.pory"
	walk_in_place_fastest_left
	step_end

# 31 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFastestUp:
# 32 "data/scripts/movement.pory"
	walk_in_place_fastest_up
	step_end

# 35 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFastestRight:
# 36 "data/scripts/movement.pory"
	walk_in_place_fastest_right
	step_end

# 39 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFastestDown:
# 40 "data/scripts/movement.pory"
	walk_in_place_fastest_down
	step_end

# 43 "data/scripts/movement.pory"
Common_Movement_FaceRight:
# 44 "data/scripts/movement.pory"
	face_right
	step_end

# 47 "data/scripts/movement.pory"
Common_Movement_FaceLeft:
# 48 "data/scripts/movement.pory"
	face_left
	step_end

# 51 "data/scripts/movement.pory"
Common_Movement_FaceDown:
# 52 "data/scripts/movement.pory"
	face_down
	step_end

# 55 "data/scripts/movement.pory"
Common_Movement_FaceUp:
# 56 "data/scripts/movement.pory"
	face_up
	step_end

# 59 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceDown:
# 60 "data/scripts/movement.pory"
	walk_in_place_down
	step_end

# 63 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceLeft:
# 64 "data/scripts/movement.pory"
	walk_in_place_left
	step_end

# 67 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceRight:
# 68 "data/scripts/movement.pory"
	walk_in_place_right
	step_end

# 71 "data/scripts/movement.pory"
Common_Movement_WalkUp6:
# 72 "data/scripts/movement.pory"
	walk_up
# 73 "data/scripts/movement.pory"
	walk_up
# 74 "data/scripts/movement.pory"
	walk_up
# 75 "data/scripts/movement.pory"
	walk_up
# 76 "data/scripts/movement.pory"
	walk_up
# 77 "data/scripts/movement.pory"
	walk_up
	step_end

# 80 "data/scripts/movement.pory"
Common_Movement_WalkUp4:
# 81 "data/scripts/movement.pory"
	walk_up
# 82 "data/scripts/movement.pory"
	walk_up
# 83 "data/scripts/movement.pory"
	walk_up
# 84 "data/scripts/movement.pory"
	walk_up
	step_end

# 87 "data/scripts/movement.pory"
Common_Movement_Delay32:
# 88 "data/scripts/movement.pory"
	delay_16
# 89 "data/scripts/movement.pory"
	delay_16
	step_end

# 92 "data/scripts/movement.pory"
Common_Movement_WalkUp:
# 93 "data/scripts/movement.pory"
	walk_up
	step_end

# 97 "data/scripts/movement.pory"

# 98 "data/scripts/movement.pory"
Common_Movement_WalkUp2::
# 99 "data/scripts/movement.pory"
	walk_up
# 100 "data/scripts/movement.pory"
	walk_up
# 101 "data/scripts/movement.pory"
	step_end
