# 1 "data/scripts/new_game.pory"

# 2 "data/scripts/new_game.pory"
EventScript_ResetAllBerries::
# 3 "data/scripts/new_game.pory"
	@ Route 102
# 4 "data/scripts/new_game.pory"
	setberrytree 2, ITEM_TO_BERRY(ITEM_ORAN_BERRY), BERRY_STAGE_BERRIES
# 5 "data/scripts/new_game.pory"
	setberrytree 1, ITEM_TO_BERRY(ITEM_PECHA_BERRY), BERRY_STAGE_BERRIES
# 6 "data/scripts/new_game.pory"

# 7 "data/scripts/new_game.pory"
	@ Route 104
# 8 "data/scripts/new_game.pory"
	setberrytree 11, ITEM_TO_BERRY(ITEM_ORAN_BERRY), BERRY_STAGE_BERRIES
# 9 "data/scripts/new_game.pory"
	setberrytree 13, ITEM_TO_BERRY(ITEM_PECHA_BERRY), BERRY_STAGE_BERRIES
# 10 "data/scripts/new_game.pory"
	setberrytree 4, ITEM_TO_BERRY(ITEM_ORAN_BERRY), BERRY_STAGE_BERRIES
# 11 "data/scripts/new_game.pory"
	setberrytree 76, ITEM_TO_BERRY(ITEM_CHERI_BERRY), BERRY_STAGE_BERRIES
# 12 "data/scripts/new_game.pory"
	setberrytree 8, ITEM_TO_BERRY(ITEM_CHERI_BERRY), BERRY_STAGE_BERRIES
# 13 "data/scripts/new_game.pory"
	setberrytree 10, ITEM_TO_BERRY(ITEM_LEPPA_BERRY), BERRY_STAGE_BERRIES
# 14 "data/scripts/new_game.pory"

# 15 "data/scripts/new_game.pory"
	@ Route 116
# 16 "data/scripts/new_game.pory"
	setberrytree 25, ITEM_TO_BERRY(ITEM_PINAP_BERRY), BERRY_STAGE_BERRIES
# 17 "data/scripts/new_game.pory"
	setberrytree 26, ITEM_TO_BERRY(ITEM_CHESTO_BERRY), BERRY_STAGE_BERRIES
# 18 "data/scripts/new_game.pory"
	setberrytree 66, ITEM_TO_BERRY(ITEM_CHESTO_BERRY), BERRY_STAGE_BERRIES
# 19 "data/scripts/new_game.pory"
	setberrytree 67, ITEM_TO_BERRY(ITEM_PINAP_BERRY), BERRY_STAGE_BERRIES
# 20 "data/scripts/new_game.pory"

# 21 "data/scripts/new_game.pory"
	@ Route 115
# 22 "data/scripts/new_game.pory"
	setberrytree 69, ITEM_TO_BERRY(ITEM_KELPSY_BERRY), BERRY_STAGE_BERRIES
# 23 "data/scripts/new_game.pory"
	setberrytree 70, ITEM_TO_BERRY(ITEM_KELPSY_BERRY), BERRY_STAGE_BERRIES
# 24 "data/scripts/new_game.pory"
	setberrytree 71, ITEM_TO_BERRY(ITEM_KELPSY_BERRY), BERRY_STAGE_BERRIES
# 25 "data/scripts/new_game.pory"
	setberrytree 55, ITEM_TO_BERRY(ITEM_BLUK_BERRY), BERRY_STAGE_BERRIES
# 26 "data/scripts/new_game.pory"
	setberrytree 56, ITEM_TO_BERRY(ITEM_BLUK_BERRY), BERRY_STAGE_BERRIES
# 27 "data/scripts/new_game.pory"

# 28 "data/scripts/new_game.pory"
	@ Route 103
# 29 "data/scripts/new_game.pory"
	setberrytree 5, ITEM_TO_BERRY(ITEM_CHERI_BERRY), BERRY_STAGE_BERRIES
# 30 "data/scripts/new_game.pory"
	setberrytree 6, ITEM_TO_BERRY(ITEM_LEPPA_BERRY), BERRY_STAGE_BERRIES
# 31 "data/scripts/new_game.pory"
	setberrytree 7, ITEM_TO_BERRY(ITEM_CHERI_BERRY), BERRY_STAGE_BERRIES
# 32 "data/scripts/new_game.pory"

# 33 "data/scripts/new_game.pory"
	@ Route 110
# 34 "data/scripts/new_game.pory"
	setberrytree 16, ITEM_TO_BERRY(ITEM_NANAB_BERRY), BERRY_STAGE_BERRIES
# 35 "data/scripts/new_game.pory"
	setberrytree 17, ITEM_TO_BERRY(ITEM_NANAB_BERRY), BERRY_STAGE_BERRIES
# 36 "data/scripts/new_game.pory"
	setberrytree 18, ITEM_TO_BERRY(ITEM_NANAB_BERRY), BERRY_STAGE_BERRIES
# 37 "data/scripts/new_game.pory"

# 38 "data/scripts/new_game.pory"
	@ Route 117
# 39 "data/scripts/new_game.pory"
	setberrytree 29, ITEM_TO_BERRY(ITEM_WEPEAR_BERRY), BERRY_STAGE_BERRIES
# 40 "data/scripts/new_game.pory"
	setberrytree 28, ITEM_TO_BERRY(ITEM_WEPEAR_BERRY), BERRY_STAGE_BERRIES
# 41 "data/scripts/new_game.pory"
	setberrytree 27, ITEM_TO_BERRY(ITEM_WEPEAR_BERRY), BERRY_STAGE_BERRIES
# 42 "data/scripts/new_game.pory"

# 43 "data/scripts/new_game.pory"
	@ Route 112
# 44 "data/scripts/new_game.pory"
	setberrytree 24, ITEM_TO_BERRY(ITEM_RAWST_BERRY), BERRY_STAGE_BERRIES
# 45 "data/scripts/new_game.pory"
	setberrytree 23, ITEM_TO_BERRY(ITEM_PECHA_BERRY), BERRY_STAGE_BERRIES
# 46 "data/scripts/new_game.pory"
	setberrytree 22, ITEM_TO_BERRY(ITEM_PECHA_BERRY), BERRY_STAGE_BERRIES
# 47 "data/scripts/new_game.pory"
	setberrytree 21, ITEM_TO_BERRY(ITEM_RAWST_BERRY), BERRY_STAGE_BERRIES
# 48 "data/scripts/new_game.pory"

# 49 "data/scripts/new_game.pory"
	@ Route 111
# 50 "data/scripts/new_game.pory"
	setberrytree 19, ITEM_TO_BERRY(ITEM_RAZZ_BERRY), BERRY_STAGE_BERRIES
# 51 "data/scripts/new_game.pory"
	setberrytree 20, ITEM_TO_BERRY(ITEM_RAZZ_BERRY), BERRY_STAGE_BERRIES
# 52 "data/scripts/new_game.pory"
	setberrytree 80, ITEM_TO_BERRY(ITEM_ORAN_BERRY), BERRY_STAGE_BERRIES
# 53 "data/scripts/new_game.pory"
	setberrytree 81, ITEM_TO_BERRY(ITEM_ORAN_BERRY), BERRY_STAGE_BERRIES
# 54 "data/scripts/new_game.pory"

# 55 "data/scripts/new_game.pory"
	@ Route 114
# 56 "data/scripts/new_game.pory"
	setberrytree 77, ITEM_TO_BERRY(ITEM_PERSIM_BERRY), BERRY_STAGE_BERRIES
# 57 "data/scripts/new_game.pory"
	setberrytree 78, ITEM_TO_BERRY(ITEM_PERSIM_BERRY), BERRY_STAGE_BERRIES
# 58 "data/scripts/new_game.pory"
	setberrytree 68, ITEM_TO_BERRY(ITEM_PERSIM_BERRY), BERRY_STAGE_BERRIES
# 59 "data/scripts/new_game.pory"

# 60 "data/scripts/new_game.pory"
	@ Route 118
# 61 "data/scripts/new_game.pory"
	setberrytree 31, ITEM_TO_BERRY(ITEM_SITRUS_BERRY), BERRY_STAGE_BERRIES
# 62 "data/scripts/new_game.pory"
	setberrytree 33, ITEM_TO_BERRY(ITEM_SITRUS_BERRY), BERRY_STAGE_BERRIES
# 63 "data/scripts/new_game.pory"

# 64 "data/scripts/new_game.pory"
	@ Route 119
# 65 "data/scripts/new_game.pory"
	setberrytree 34, ITEM_TO_BERRY(ITEM_POMEG_BERRY), BERRY_STAGE_BERRIES
# 66 "data/scripts/new_game.pory"
	setberrytree 35, ITEM_TO_BERRY(ITEM_POMEG_BERRY), BERRY_STAGE_BERRIES
# 67 "data/scripts/new_game.pory"
	setberrytree 36, ITEM_TO_BERRY(ITEM_POMEG_BERRY), BERRY_STAGE_BERRIES
# 68 "data/scripts/new_game.pory"
	setberrytree 83, ITEM_TO_BERRY(ITEM_HONDEW_BERRY), BERRY_STAGE_BERRIES
# 69 "data/scripts/new_game.pory"
	setberrytree 84, ITEM_TO_BERRY(ITEM_HONDEW_BERRY), BERRY_STAGE_BERRIES
# 70 "data/scripts/new_game.pory"
	setberrytree 85, ITEM_TO_BERRY(ITEM_SITRUS_BERRY), BERRY_STAGE_BERRIES
# 71 "data/scripts/new_game.pory"
	setberrytree 86, ITEM_TO_BERRY(ITEM_LEPPA_BERRY), BERRY_STAGE_BERRIES
# 72 "data/scripts/new_game.pory"

# 73 "data/scripts/new_game.pory"
	@ Route 120
# 74 "data/scripts/new_game.pory"
	setberrytree 37, ITEM_TO_BERRY(ITEM_ASPEAR_BERRY), BERRY_STAGE_BERRIES
# 75 "data/scripts/new_game.pory"
	setberrytree 38, ITEM_TO_BERRY(ITEM_ASPEAR_BERRY), BERRY_STAGE_BERRIES
# 76 "data/scripts/new_game.pory"
	setberrytree 39, ITEM_TO_BERRY(ITEM_ASPEAR_BERRY), BERRY_STAGE_BERRIES
# 77 "data/scripts/new_game.pory"
	setberrytree 40, ITEM_TO_BERRY(ITEM_PECHA_BERRY), BERRY_STAGE_BERRIES
# 78 "data/scripts/new_game.pory"
	setberrytree 41, ITEM_TO_BERRY(ITEM_PECHA_BERRY), BERRY_STAGE_BERRIES
# 79 "data/scripts/new_game.pory"
	setberrytree 42, ITEM_TO_BERRY(ITEM_PECHA_BERRY), BERRY_STAGE_BERRIES
# 80 "data/scripts/new_game.pory"
	setberrytree 46, ITEM_TO_BERRY(ITEM_WEPEAR_BERRY), BERRY_STAGE_BERRIES
# 81 "data/scripts/new_game.pory"
	setberrytree 45, ITEM_TO_BERRY(ITEM_PINAP_BERRY), BERRY_STAGE_BERRIES
# 82 "data/scripts/new_game.pory"
	setberrytree 44, ITEM_TO_BERRY(ITEM_NANAB_BERRY), BERRY_STAGE_BERRIES
# 83 "data/scripts/new_game.pory"
	setberrytree 43, ITEM_TO_BERRY(ITEM_RAZZ_BERRY), BERRY_STAGE_BERRIES
# 84 "data/scripts/new_game.pory"

# 85 "data/scripts/new_game.pory"
	@ Route 121
# 86 "data/scripts/new_game.pory"
	setberrytree 47, ITEM_TO_BERRY(ITEM_PERSIM_BERRY), BERRY_STAGE_BERRIES
# 87 "data/scripts/new_game.pory"
	setberrytree 48, ITEM_TO_BERRY(ITEM_ASPEAR_BERRY), BERRY_STAGE_BERRIES
# 88 "data/scripts/new_game.pory"
	setberrytree 49, ITEM_TO_BERRY(ITEM_RAWST_BERRY), BERRY_STAGE_BERRIES
# 89 "data/scripts/new_game.pory"
	setberrytree 50, ITEM_TO_BERRY(ITEM_CHESTO_BERRY), BERRY_STAGE_BERRIES
# 90 "data/scripts/new_game.pory"
	setberrytree 52, ITEM_TO_BERRY(ITEM_NANAB_BERRY), BERRY_STAGE_BERRIES
# 91 "data/scripts/new_game.pory"
	setberrytree 53, ITEM_TO_BERRY(ITEM_NANAB_BERRY), BERRY_STAGE_BERRIES
# 92 "data/scripts/new_game.pory"

# 93 "data/scripts/new_game.pory"
	@ Route 123
# 94 "data/scripts/new_game.pory"
	setberrytree 62, ITEM_TO_BERRY(ITEM_LEPPA_BERRY), BERRY_STAGE_BERRIES
# 95 "data/scripts/new_game.pory"
	setberrytree 64, ITEM_TO_BERRY(ITEM_LEPPA_BERRY), BERRY_STAGE_BERRIES
# 96 "data/scripts/new_game.pory"
	setberrytree 58, ITEM_TO_BERRY(ITEM_POMEG_BERRY), BERRY_STAGE_BERRIES
# 97 "data/scripts/new_game.pory"
	setberrytree 59, ITEM_TO_BERRY(ITEM_POMEG_BERRY), BERRY_STAGE_BERRIES
# 98 "data/scripts/new_game.pory"
	setberrytree 60, ITEM_TO_BERRY(ITEM_GREPA_BERRY), BERRY_STAGE_BERRIES
# 99 "data/scripts/new_game.pory"
	setberrytree 61, ITEM_TO_BERRY(ITEM_GREPA_BERRY), BERRY_STAGE_BERRIES
# 100 "data/scripts/new_game.pory"
	setberrytree 79, ITEM_TO_BERRY(ITEM_QUALOT_BERRY), BERRY_STAGE_BERRIES
# 101 "data/scripts/new_game.pory"
	setberrytree 14, ITEM_TO_BERRY(ITEM_QUALOT_BERRY), BERRY_STAGE_BERRIES
# 102 "data/scripts/new_game.pory"
	setberrytree 15, ITEM_TO_BERRY(ITEM_POMEG_BERRY), BERRY_STAGE_BERRIES
# 103 "data/scripts/new_game.pory"
	setberrytree 30, ITEM_TO_BERRY(ITEM_POMEG_BERRY), BERRY_STAGE_BERRIES
# 104 "data/scripts/new_game.pory"
	setberrytree 65, ITEM_TO_BERRY(ITEM_GREPA_BERRY), BERRY_STAGE_BERRIES
# 105 "data/scripts/new_game.pory"
	setberrytree 72, ITEM_TO_BERRY(ITEM_GREPA_BERRY), BERRY_STAGE_BERRIES
# 106 "data/scripts/new_game.pory"
	setberrytree 73, ITEM_TO_BERRY(ITEM_QUALOT_BERRY), BERRY_STAGE_BERRIES
# 107 "data/scripts/new_game.pory"
	setberrytree 74, ITEM_TO_BERRY(ITEM_QUALOT_BERRY), BERRY_STAGE_BERRIES
# 108 "data/scripts/new_game.pory"
	setberrytree 87, ITEM_TO_BERRY(ITEM_PECHA_BERRY), BERRY_STAGE_BERRIES
# 109 "data/scripts/new_game.pory"
	setberrytree 88, ITEM_TO_BERRY(ITEM_SITRUS_BERRY), BERRY_STAGE_BERRIES
# 110 "data/scripts/new_game.pory"
	setberrytree 89, ITEM_TO_BERRY(ITEM_RAWST_BERRY), BERRY_STAGE_BERRIES
# 111 "data/scripts/new_game.pory"

# 112 "data/scripts/new_game.pory"
	@ Mirage Island
# 113 "data/scripts/new_game.pory"
	setberrytree 82, ITEM_TO_BERRY(ITEM_LIECHI_BERRY), BERRY_STAGE_BERRIES
# 114 "data/scripts/new_game.pory"
	return
# 115 "data/scripts/new_game.pory"

# 116 "data/scripts/new_game.pory"
EventScript_ResetAllMapFlags::
# 117 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_CONTEST_POKE_BALL
# 118 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_111_VICTORIA_WINSTRATE
# 119 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_111_VIVI_WINSTRATE
# 120 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_111_VICKY_WINSTRATE
# 121 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_BIRCH
# 122 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_RIVAL
# 123 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_DRATINI
# 124 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_GIBLE
# 125 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_AXEW
# 126 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_PETALBURG_CITY_WALLY
# 127 "data/scripts/new_game.pory"
	setflag FLAG_UNKNOWN_0x363
# 128 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_RUSTBORO_CITY_AQUA_GRUNT
# 129 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_RUSTBORO_CITY_DEVON_EMPLOYEE_1
# 130 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_RUSTBORO_CITY_RIVAL
# 131 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_RUSTBORO_CITY_SCIENTIST
# 132 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_FAT_MAN
# 133 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_BRINEYS_HOUSE_MR_BRINEY
# 134 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_BRINEYS_HOUSE_PEEKO
# 135 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_104_MR_BRINEY
# 136 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MR_BRINEY_DEWFORD_TOWN
# 137 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_109_MR_BRINEY
# 138 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MR_BRINEY_BOAT_DEWFORD_TOWN
# 139 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_109_MR_BRINEY_BOAT
# 140 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_104_WHITE_HERB_FLORIST
# 141 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_110_BIRCH
# 142 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILYCOVE_CONTEST_HALL_CONTEST_ATTENDANT_1
# 143 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILYCOVE_CONTEST_HALL_CONTEST_ATTENDANT_2
# 144 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_1
# 145 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_2
# 146 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_3
# 147 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_4
# 148 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILYCOVE_MUSEUM_TOURISTS
# 149 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_PETALBURG_GYM_GREETER
# 150 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_PETALBURG_GYM_WALLYS_DAD
# 151 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_BRENDAN
# 152 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MAY
# 153 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_BEDROOM
# 154 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_BEDROOM
# 155 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_PLAYERS_HOUSE_DAD
# 156 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_PICHU_DOLL
# 157 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_SWABLU_DOLL
# 158 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_FANCLUB_OLD_LADY
# 159 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_FANCLUB_BOY
# 160 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_FANCLUB_LITTLE_BOY
# 161 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_FANCLUB_LADY
# 162 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILYCOVE_FAN_CLUB_INTERVIEWER
# 163 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_118_GABBY_AND_TY_1
# 164 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_120_GABBY_AND_TY_1
# 165 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_111_GABBY_AND_TY_3
# 166 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_118_GABBY_AND_TY_2
# 167 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_120_GABBY_AND_TY_2
# 168 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_111_GABBY_AND_TY_2
# 169 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_118_GABBY_AND_TY_3
# 170 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_CONTEST_REPORTER
# 171 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILYCOVE_CONTEST_HALL_REPORTER
# 172 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLY
# 173 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WANDAS_BOYFRIEND
# 174 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLYS_UNCLE
# 175 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WANDA
# 176 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_VERDANTURF_TOWN_SCOTT
# 177 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_PETALBURG_CITY_WALLYS_DAD
# 178 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_PETALBURG_GYM_WALLY
# 179 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_STERNS_SHIPYARD_MR_BRINEY
# 180 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_ARCHIE
# 181 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAXIE
# 182 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAGMA_GRUNTS
# 183 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_KYOGRE_1
# 184 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MAGMA_HIDEOUT_4F_GROUDON_1
# 185 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_HARBOR_CAPTAIN_STERN
# 186 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_HARBOR_AQUA_GRUNT
# 187 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_HARBOR_ARCHIE
# 188 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_HARBOR_SS_TIDAL
# 189 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILYCOVE_HARBOR_SSTIDAL
# 190 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_GABBY_AND_TY
# 191 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_CAPTAIN_STERN
# 192 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_HARBOR_SUBMARINE_SHADOW
# 193 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_119_RIVAL
# 194 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_119_SCOTT
# 195 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SOOTOPOLIS_CITY_STEVEN
# 196 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SOOTOPOLIS_CITY_WALLACE
# 197 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LANETTES_HOUSE_LANETTE
# 198 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_TRICK_HOUSE_ENTRANCE_MAN
# 199 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MT_CHIMNEY_TRAINERS
# 200 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MT_CHIMNEY_LAVA_COOKIE_LADY
# 201 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_RUSTURF_TUNNEL_BRINEY
# 202 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_116_MR_BRINEY
# 203 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_RUSTURF_TUNNEL_PEEKO
# 204 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_RUSTURF_TUNNEL_AQUA_GRUNT
# 205 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_RUSTURF_TUNNEL_WANDAS_BOYFRIEND
# 206 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_RUSTURF_TUNNEL_WANDA
# 207 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_ARCHIE
# 208 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_1
# 209 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_2
# 210 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_MUSEUM_POPULATION
# 211 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_BATTLE_TOWER_OPPONENT
# 212 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_MOM_OUTSIDE
# 213 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLE_ROOT_TOWN_PLAYERS_BEDROOM_MOM
# 214 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_RIVAL
# 215 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BIRCH
# 216 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_WEATHER_INSTITUTE_1F_WORKERS
# 217 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_UNKNOWN_0x380
# 218 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_101_BIRCH
# 219 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_103_BIRCH
# 220 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILYCOVE_HARBOR_FERRY_SAILOR
# 221 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILYCOVE_HARBOR_EVENT_TICKET_TAKER
# 222 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SOUTHERN_ISLAND_EON_STONE
# 223 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SOUTHERN_ISLAND_UNCHOSEN_EON_DUO_MON
# 224 "data/scripts/new_game.pory"
	setflag FLAG_UNKNOWN_0x393
# 225 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MT_PYRE_SUMMIT_MAXIE
# 226 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MAUVILLE_CITY_WATTSON
# 227 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MAUVILLE_CITY_SCOTT
# 228 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_CHAMPIONS_ROOM_RIVAL
# 229 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_CHAMPIONS_ROOM_BIRCH
# 230 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_110_RIVAL_ON_BIKE
# 231 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_119_RIVAL_ON_BIKE
# 232 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_104_RIVAL
# 233 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILCOVE_MOTEL_GAME_DESIGNERS
# 234 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LAVARIDGE_TOWN_RIVAL
# 235 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LAVARIDGE_TOWN_RIVAL_ON_BIKE
# 236 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MOSSDEEP_CITY_HOUSE_2_WINGULL
# 237 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_METEOR_FALLS_TEAM_AQUA
# 238 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_DEWFORD_HALL_SLUDGE_BOMB_MAN
# 239 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_FALLARBOR_HOUSE_PROF_COZMO
# 240 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_WEATHER_INSTITUTE_2F_AQUA_GRUNT_M
# 241 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_128_STEVEN
# 242 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_128_ARCHIE
# 243 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_128_MAXIE
# 244 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_116_DEVON_EMPLOYEE
# 245 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_TM_SALESMAN
# 246 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SLATEPORT_CITY_SCOTT
# 247 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_VICTORY_ROAD_ENTRANCE_WALLY
# 248 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_VICTORY_ROAD_EXIT_WALLY
# 249 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SS_TIDAL_CORRIDOR_MR_BRINEY
# 250 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_STEVEN
# 251 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_BELDUM_POKEBALL
# 252 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_INVISIBLE_NINJA_BOY
# 253 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_OLDALE_TOWN_RIVAL
# 254 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_101_BOY
# 255 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_PETALBURG_CITY_SCOTT
# 256 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SOOTOPOLIS_CITY_RAYQUAZA
# 257 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SOOTOPOLIS_CITY_KYOGRE
# 258 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SOOTOPOLIS_CITY_GROUDON
# 259 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SOOTOPOLIS_CITY_RESIDENTS
# 260 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SOOTOPOLIS_CITY_ARCHIE
# 261 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SOOTOPOLIS_CITY_MAXIE
# 262 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_111_DESERT_FOSSIL
# 263 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_ROUTE_111_PLAYER_DESCENT
# 264 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_DESERT_UNDERPASS_FOSSIL
# 265 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MOSSDEEP_CITY_TEAM_MAGMA
# 266 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_1F_TEAM_MAGMA
# 267 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_TEAM_MAGMA
# 268 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_STEVEN
# 269 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER
# 270 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_DEOXYS
# 271 "data/scripts/new_game.pory"
	clearflag FLAG_SHOWN_SAFARI_PASS
# 272 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_FALLARBOR_TOWN_BATTLE_TENT_SCOTT
# 273 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_EVER_GRANDE_POKEMON_CENTER_1F_SCOTT
# 274 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_SKY_PILLAR_WALLACE
# 275 "data/scripts/new_game.pory"
	setflag FLAG_HIDE_RAYQUAZA_SKY_TOWER_SUMMIT
# 276 "data/scripts/new_game.pory"
	call EventScript_ResetAllBerries
# 277 "data/scripts/new_game.pory"
	end
