FourIsland_LoreleisHouse_EventScript_Lorelei::
# 4 "data/scripts/sevii_scripts.pory"
	lock
# 5 "data/scripts/sevii_scripts.pory"
	faceplayer
# 6 "data/scripts/sevii_scripts.pory"
	msgbox FourIsland_LoreleisHouse_EventScript_Lorelei_Text_0, MSGBOX_DEFAULT
# 7 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FourIsland_LoreleisHouse_EventScript_Doll::
# 12 "data/scripts/sevii_scripts.pory"
	lock
# 13 "data/scripts/sevii_scripts.pory"
	msgbox FourIsland_LoreleisHouse_EventScript_Doll_Text_0, MSGBOX_DEFAULT
# 14 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FourIsland_House1_EventScript_FatMan::
# 19 "data/scripts/sevii_scripts.pory"
	lock
# 20 "data/scripts/sevii_scripts.pory"
	faceplayer
# 21 "data/scripts/sevii_scripts.pory"
	msgbox FourIsland_House1_EventScript_FatMan_Text_0, MSGBOX_DEFAULT
# 22 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FourIsland_House1_EventScript_BodySlamTutor::
# 27 "data/scripts/sevii_scripts.pory"
	lock
# 28 "data/scripts/sevii_scripts.pory"
	faceplayer
# 29 "data/scripts/sevii_scripts.pory"
	msgbox FourIsland_House1_EventScript_FatMan_Text_0, MSGBOX_DEFAULT
# 30 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FourIsland_House2_EventScript_StickerMan::
# 35 "data/scripts/sevii_scripts.pory"
	lock
# 36 "data/scripts/sevii_scripts.pory"
	faceplayer
# 37 "data/scripts/sevii_scripts.pory"
	msgbox FourIsland_House2_EventScript_StickerMan_Text_0, MSGBOX_DEFAULT
# 38 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FiveIsland_PokemonCenter_1F_EventScript_Chef::
# 44 "data/scripts/sevii_scripts.pory"
	lock
# 45 "data/scripts/sevii_scripts.pory"
	faceplayer
# 46 "data/scripts/sevii_scripts.pory"
	msgbox FiveIsland_PokemonCenter_1F_EventScript_Chef_Text_0, MSGBOX_DEFAULT
# 47 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FiveIsland_PokemonCenter_1F_EventScript_CooltrainerF::
# 52 "data/scripts/sevii_scripts.pory"
	lock
# 53 "data/scripts/sevii_scripts.pory"
	faceplayer
# 54 "data/scripts/sevii_scripts.pory"
	msgbox FiveIsland_PokemonCenter_1F_EventScript_CooltrainerF_Text_0, MSGBOX_DEFAULT
# 55 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FiveIsland_House1_EventScript_Woman::
# 60 "data/scripts/sevii_scripts.pory"
	lock
# 61 "data/scripts/sevii_scripts.pory"
	faceplayer
# 62 "data/scripts/sevii_scripts.pory"
	msgbox FiveIsland_House1_EventScript_Woman_Text_0, MSGBOX_DEFAULT
# 63 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FiveIsland_House2_EventScript_OldMan::
# 68 "data/scripts/sevii_scripts.pory"
	lock
# 69 "data/scripts/sevii_scripts.pory"
	faceplayer
# 70 "data/scripts/sevii_scripts.pory"
	msgbox FiveIsland_House2_EventScript_OldMan_Text_0, MSGBOX_DEFAULT
# 71 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_EventScript_Boy::
# 77 "data/scripts/sevii_scripts.pory"
	lock
# 78 "data/scripts/sevii_scripts.pory"
	faceplayer
# 79 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_EventScript_Boy_Text_0, MSGBOX_DEFAULT
# 80 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_EventScript_Hiker::
# 85 "data/scripts/sevii_scripts.pory"
	lock
# 86 "data/scripts/sevii_scripts.pory"
	faceplayer
# 87 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_EventScript_Hiker_Text_0, MSGBOX_DEFAULT
# 88 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_PokemonCenter_1F_EventScript_OldMan::
# 94 "data/scripts/sevii_scripts.pory"
	lock
# 95 "data/scripts/sevii_scripts.pory"
	faceplayer
# 96 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_PokemonCenter_1F_EventScript_OldMan_Text_0, MSGBOX_DEFAULT
# 97 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_PokemonCenter_1F_EventScript_Hiker::
# 102 "data/scripts/sevii_scripts.pory"
	lock
# 103 "data/scripts/sevii_scripts.pory"
	faceplayer
# 104 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_PokemonCenter_1F_EventScript_Hiker_Text_0, MSGBOX_DEFAULT
# 105 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_Mart_EventScript_Picnicker::
# 111 "data/scripts/sevii_scripts.pory"
	lock
# 112 "data/scripts/sevii_scripts.pory"
	faceplayer
# 113 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_Mart_EventScript_Picnicker_Text_0, MSGBOX_DEFAULT
# 114 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_Mart_EventScript_OldWoman::
# 119 "data/scripts/sevii_scripts.pory"
	lock
# 120 "data/scripts/sevii_scripts.pory"
	faceplayer
# 121 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_Mart_EventScript_OldWoman_Text_0, MSGBOX_DEFAULT
# 122 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_House_EventScript_OldMan::
# 128 "data/scripts/sevii_scripts.pory"
	lock
# 129 "data/scripts/sevii_scripts.pory"
	faceplayer
# 130 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_House_EventScript_OldMan_Text_0, MSGBOX_DEFAULT
# 131 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_EventScript_Scientist::
# 137 "data/scripts/sevii_scripts.pory"
	lock
# 138 "data/scripts/sevii_scripts.pory"
	faceplayer
# 139 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_EventScript_Scientist_Text_0, MSGBOX_DEFAULT
# 140 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_EventScript_SwordsDanceTutor::
# 145 "data/scripts/sevii_scripts.pory"
	lock
# 146 "data/scripts/sevii_scripts.pory"
	faceplayer
# 147 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_EventScript_SwordsDanceTutor_Text_0, MSGBOX_DEFAULT
# 148 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_EventScript_OldWoman::
# 153 "data/scripts/sevii_scripts.pory"
	lock
# 154 "data/scripts/sevii_scripts.pory"
	faceplayer
# 155 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_EventScript_OldWoman_Text_0, MSGBOX_DEFAULT
# 156 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_PokemonCenter_1F_EventScript_Beauty::
# 162 "data/scripts/sevii_scripts.pory"
	lock
# 163 "data/scripts/sevii_scripts.pory"
	faceplayer
# 164 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_PokemonCenter_1F_EventScript_Beauty_Text_0, MSGBOX_DEFAULT
# 165 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_PokemonCenter_1F_EventScript_OldMan::
# 170 "data/scripts/sevii_scripts.pory"
	lock
# 171 "data/scripts/sevii_scripts.pory"
	faceplayer
# 172 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_PokemonCenter_1F_EventScript_OldMan_Text_0, MSGBOX_DEFAULT
# 173 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_PokemonCenter_1F_EventScript_Sailor::
# 178 "data/scripts/sevii_scripts.pory"
	lock
# 179 "data/scripts/sevii_scripts.pory"
	faceplayer
# 180 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_PokemonCenter_1F_EventScript_Sailor_Text_0, MSGBOX_DEFAULT
# 181 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_Mart_EventScript_Hiker::
# 187 "data/scripts/sevii_scripts.pory"
	lock
# 188 "data/scripts/sevii_scripts.pory"
	faceplayer
# 189 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_Mart_EventScript_Hiker_Text_0, MSGBOX_DEFAULT
# 190 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_Mart_EventScript_Fisher::
# 195 "data/scripts/sevii_scripts.pory"
	lock
# 196 "data/scripts/sevii_scripts.pory"
	faceplayer
# 197 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_Mart_EventScript_Fisher_Text_0, MSGBOX_DEFAULT
# 198 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_Mart_EventScript_Lass::
# 203 "data/scripts/sevii_scripts.pory"
	lock
# 204 "data/scripts/sevii_scripts.pory"
	faceplayer
# 205 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_Mart_EventScript_Lass_Text_0, MSGBOX_DEFAULT
# 206 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_House_Room1_EventScript_OldWoman::
# 212 "data/scripts/sevii_scripts.pory"
	lock
# 213 "data/scripts/sevii_scripts.pory"
	faceplayer
# 214 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_House_Room1_EventScript_OldWoman_Text_0, MSGBOX_DEFAULT
# 215 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_WaterPath_House1_EventScript_Beauty::
# 220 "data/scripts/sevii_scripts.pory"
	lock
# 221 "data/scripts/sevii_scripts.pory"
	faceplayer
# 222 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_WaterPath_House1_EventScript_Beauty_Text_0, MSGBOX_DEFAULT
# 223 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_WaterPath_House2_EventScript_Man::
# 228 "data/scripts/sevii_scripts.pory"
	lock
# 229 "data/scripts/sevii_scripts.pory"
	faceplayer
# 230 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_WaterPath_House2_EventScript_Man_Text_0, MSGBOX_DEFAULT
# 231 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_SevaultCanyon_House_EventScript_BaldingMan::
# 236 "data/scripts/sevii_scripts.pory"
	lock
# 237 "data/scripts/sevii_scripts.pory"
	faceplayer
# 238 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_SevaultCanyon_House_EventScript_BaldingMan_Text_0, MSGBOX_DEFAULT
# 239 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_SevaultCanyon_House_EventScript_Chansey::
# 244 "data/scripts/sevii_scripts.pory"
	lock
# 245 "data/scripts/sevii_scripts.pory"
	faceplayer
# 246 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_SevaultCanyon_House_EventScript_Chansey_Text_0, MSGBOX_DEFAULT
# 247 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign::
# 253 "data/scripts/sevii_scripts.pory"
	lock
# 254 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign_Text_0, MSGBOX_DEFAULT
# 255 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_SevaultCanyon_EventScript_RouteSign::
# 260 "data/scripts/sevii_scripts.pory"
	lock
# 261 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_SevaultCanyon_EventScript_RouteSign_Text_0, MSGBOX_DEFAULT
# 262 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_GreenPath_EventScript_LeftRouteSign::
# 267 "data/scripts/sevii_scripts.pory"
	lock
# 268 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_GreenPath_EventScript_LeftRouteSign_Text_0, MSGBOX_DEFAULT
# 269 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_GreenPath_EventScript_RightRouteSign::
# 274 "data/scripts/sevii_scripts.pory"
	lock
# 275 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_GreenPath_EventScript_RightRouteSign_Text_0, MSGBOX_DEFAULT
# 276 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_EventScript_IslandSign::
# 281 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_EventScript_IslandSign_Text_0, MSGBOX_SIGN
	end


SevenIsland_EventScript_IslandSign::
# 286 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_EventScript_IslandSign_Text_0, MSGBOX_SIGN
	end


SixIsland_WaterPathEventScript_RouteSign::
# 291 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_WaterPathEventScript_RouteSign_Text_0, MSGBOX_SIGN
	end


FourIsland_LoreleisHouse_EventScript_Lorelei_Text_0:
# 6 "data/scripts/sevii_scripts.pory"
	.string "My niece Lorelei is a famous trainer in\n"
	.string "Kanto, she really likes Ice-type\l"
	.string "Pokémon.$"

FourIsland_LoreleisHouse_EventScript_Doll_Text_0:
# 13 "data/scripts/sevii_scripts.pory"
	.string "It's a Poké-Doll.$"

FourIsland_House1_EventScript_FatMan_Text_0:
# 21 "data/scripts/sevii_scripts.pory"
	.string "There! Boing! You're awfully heavy!$"

FourIsland_House2_EventScript_StickerMan_Text_0:
# 37 "data/scripts/sevii_scripts.pory"
	.string "Giggle… I collected a ton of Stickers, I\n"
	.string "wish I could show them off….$"

FiveIsland_PokemonCenter_1F_EventScript_Chef_Text_0:
# 46 "data/scripts/sevii_scripts.pory"
	.string "I'm on my way to prepare a meal for a\n"
	.string "certain high-society person.$"

FiveIsland_PokemonCenter_1F_EventScript_CooltrainerF_Text_0:
# 54 "data/scripts/sevii_scripts.pory"
	.string "You're on a quest to catch every single\n"
	.string "kind of Pokémon? …How incredible.\l"
	.string "Please tell me if you catch a strong\l"
	.string "one!.$"

FiveIsland_House1_EventScript_Woman_Text_0:
# 62 "data/scripts/sevii_scripts.pory"
	.string "Don't worry about buying anything for\n"
	.string "dinner tonight! …That's what my\l"
	.string "husband said when he went off fishing\l"
	.string "today. I'm not sure if I can count on him\l"
	.string "to live up to that promise..$"

FiveIsland_House2_EventScript_OldMan_Text_0:
# 70 "data/scripts/sevii_scripts.pory"
	.string "That Meadow has belonged to our family\n"
	.string "for generations. I should have had a\l"
	.string "giant mansion built on it. It would be\l"
	.string "preferable to having those thugs run\l"
	.string "wild on it!.$"

SixIsland_EventScript_Boy_Text_0:
# 79 "data/scripts/sevii_scripts.pory"
	.string "When you're this far away from the city,\n"
	.string "the sky at night is fantastic..$"

SixIsland_EventScript_Hiker_Text_0:
# 87 "data/scripts/sevii_scripts.pory"
	.string "Keep going this way and you'll get to\n"
	.string "the Water Path. Stay on that and you'll\l"
	.string "get to the Ruin Valley.$"

SixIsland_PokemonCenter_1F_EventScript_OldMan_Text_0:
# 96 "data/scripts/sevii_scripts.pory"
	.string "You know of Pokémon that evolve only\n"
	.string "upon trading, yes? But did you know\l"
	.string "that there are still others? Some\l"
	.string "Pokémon evolve only when traded while\l"
	.string "holding specific items.$"

SixIsland_PokemonCenter_1F_EventScript_Hiker_Text_0:
# 104 "data/scripts/sevii_scripts.pory"
	.string "For ten years, I've searched for Ruins.\n"
	.string "No, make that twenty years. I get this\l"
	.string "feeling that there's something hidden\l"
	.string "on this island..$"

SixIsland_Mart_EventScript_Picnicker_Text_0:
# 113 "data/scripts/sevii_scripts.pory"
	.string "I should buy some Mail and write him a\n"
	.string "letter…$"

SixIsland_Mart_EventScript_OldWoman_Text_0:
# 121 "data/scripts/sevii_scripts.pory"
	.string "Play with Pokémon lots and live a long\n"
	.string "life! Take Agatha, for example. She set\l"
	.string "a record for being the oldest-ever\l"
	.string "Elite Four member. She spurs me to do\l"
	.string "bigger things..$"

SixIsland_House_EventScript_OldMan_Text_0:
# 130 "data/scripts/sevii_scripts.pory"
	.string "There's nothing that young people'd\n"
	.string "find exciting here on this island. But,\l"
	.string "this is a good place in terms of nature\l"
	.string "and history. Relax and enjoy your stay..$"

SevenIsland_EventScript_Scientist_Text_0:
# 139 "data/scripts/sevii_scripts.pory"
	.string "This island has been left virtually\n"
	.string "untouched in its natural state. It\l"
	.string "could be a little difficult to hike\l"
	.string "around because of that..$"

SevenIsland_EventScript_SwordsDanceTutor_Text_0:
# 147 "data/scripts/sevii_scripts.pory"
	.string "I saw some Tentacools that were\n"
	.string "walking on land, that's a really strange\l"
	.string "thing to happen since they are\l"
	.string "Water-type Pokémon...$"

SevenIsland_EventScript_OldWoman_Text_0:
# 155 "data/scripts/sevii_scripts.pory"
	.string "These islands are called the Sevii\n"
	.string "Islands because there are seven. …Or at\l"
	.string "least that's what the young people\l"
	.string "believe. The truth is, these islands are\l"
	.string "so named because they are said to have\l"
	.string "been made in seven days.$"

SevenIsland_PokemonCenter_1F_EventScript_Beauty_Text_0:
# 164 "data/scripts/sevii_scripts.pory"
	.string "If you're confident, you should check\n"
	.string "out Trainer Tower.$"

SevenIsland_PokemonCenter_1F_EventScript_OldMan_Text_0:
# 172 "data/scripts/sevii_scripts.pory"
	.string "On this island, different events occur\n"
	.string "depending on connections. What are\l"
	.string "those connections? They are for you to\l"
	.string "discover on your own..$"

SevenIsland_PokemonCenter_1F_EventScript_Sailor_Text_0:
# 180 "data/scripts/sevii_scripts.pory"
	.string "Did you ride a Seagallop ferry to get\n"
	.string "here? There are at least ten of those\l"
	.string "high-speed ships. I don't know where\l"
	.string "they all go, though.$"

SevenIsland_Mart_EventScript_Hiker_Text_0:
# 189 "data/scripts/sevii_scripts.pory"
	.string "Okay, preparations are complete for me\n"
	.string "to explore the Ruins.$"

SevenIsland_Mart_EventScript_Fisher_Text_0:
# 197 "data/scripts/sevii_scripts.pory"
	.string "I need to fish on Seven Island. That\n"
	.string "will complete my fishing tour of the\l"
	.string "Sevii Islands. I'd better stock up on\l"
	.string "some Poké Balls first, though.$"

SevenIsland_Mart_EventScript_Lass_Text_0:
# 205 "data/scripts/sevii_scripts.pory"
	.string "Pokémon have personalities of their\n"
	.string "own, just like people. My Pikachu has a\l"
	.string "Hasty nature, so it grew to be a speedy\l"
	.string "Pokémon.$"

SevenIsland_House_Room1_EventScript_OldWoman_Text_0:
# 214 "data/scripts/sevii_scripts.pory"
	.string "I may not look like much now, but when I\n"
	.string "was younger… I flew everywhere,\l"
	.string "challenging Trainers wherever I found\l"
	.string "them. Now, my only source of enjoyment\l"
	.string "is reminiscing about the past while\l"
	.string "watching battles..$"

SixIsland_WaterPath_House1_EventScript_Beauty_Text_0:
# 222 "data/scripts/sevii_scripts.pory"
	.string "Hera, hera, Heracross!\n"
	.string "Big and shiny, it's the bug boss!\l"
	.string "Love it, need it, Heracross!$"

SixIsland_WaterPath_House2_EventScript_Man_Text_0:
# 230 "data/scripts/sevii_scripts.pory"
	.string "My height is 67.0 inches on the button.\p"
	.string "I know it is this precisely because my\n"
	.string "neighbor measured me.$"

SevenIsland_SevaultCanyon_House_EventScript_BaldingMan_Text_0:
# 238 "data/scripts/sevii_scripts.pory"
	.string "Dance, dance!\n"
	.string "Chansey Dance!\p"
	.string "You join in, too!\n"
	.string "Dance, dance!$"

SevenIsland_SevaultCanyon_House_EventScript_Chansey_Text_0:
# 246 "data/scripts/sevii_scripts.pory"
	.string "Chansey: Chansi! Chansi!$"

SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign_Text_0:
# 254 "data/scripts/sevii_scripts.pory"
	.string "Sevault Canyon Entrance trainers are\n"
	.string "asked to refrain from damaging plants\l"
	.string "in the Canyon.$"

SevenIsland_SevaultCanyon_EventScript_RouteSign_Text_0:
# 261 "data/scripts/sevii_scripts.pory"
	.string "Sevault Canyon Tanoby Ruins ahead$"

SixIsland_GreenPath_EventScript_LeftRouteSign_Text_0:
# 268 "data/scripts/sevii_scripts.pory"
	.string "Green Path Pattern Bush Ahead$"

SixIsland_GreenPath_EventScript_RightRouteSign_Text_0:
# 275 "data/scripts/sevii_scripts.pory"
	.string "Green Path, Think Green, Keep Nature\n"
	.string "Clean!$"

SixIsland_EventScript_IslandSign_Text_0:
# 281 "data/scripts/sevii_scripts.pory"
	.string "Six Island\n"
	.string "Fortune Island of Aged Wisdom$"

SevenIsland_EventScript_IslandSign_Text_0:
# 286 "data/scripts/sevii_scripts.pory"
	.string "Seven Island\n"
	.string "Quest Island of Infinity$"

SixIsland_WaterPathEventScript_RouteSign_Text_0:
# 291 "data/scripts/sevii_scripts.pory"
	.string "Water Path\n"
	.string "Leads Ruin Valley$"

@ additional blocks pulled in for the Sevii maps

Common_EventScript_Colress::
# 157 "data/scripts/flying_taxi.pory"
	switch VAR_VISITED_SEVII
# 158 "data/scripts/flying_taxi.pory"
	case 0, Common_EventScript_Colress_3
# 161 "data/scripts/flying_taxi.pory"
	case 1, Common_EventScript_Colress_4
# 162 "data/scripts/flying_taxi.pory"
	case 2, Common_EventScript_Colress_4
# 163 "data/scripts/flying_taxi.pory"
	case 3, Common_EventScript_Colress_4
# 164 "data/scripts/flying_taxi.pory"
	case 4, Common_EventScript_Colress_4
# 165 "data/scripts/flying_taxi.pory"
	case 5, Common_EventScript_Colress_4
# 166 "data/scripts/flying_taxi.pory"
	case 6, Common_EventScript_Colress_4
# 169 "data/scripts/flying_taxi.pory"
	case 7, Common_EventScript_Colress_5
# 170 "data/scripts/flying_taxi.pory"
	case 8, Common_EventScript_Colress_5

Common_EventScript_Colress_1:
	end


Common_EventScript_Colress_3:
# 159 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter
	goto Common_EventScript_Colress_1


Common_EventScript_Colress_4:
# 167 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_Second_Encounter
	goto Common_EventScript_Colress_1


Common_EventScript_Colress_5:
# 171 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_Final_Encounter
	goto Common_EventScript_Colress_1



Common_EventScript_Colress_AskForWarping::
# 422 "data/scripts/flying_taxi.pory"
	call Common_EventScript_Colress_SetTicketFlag
# 423 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_AskForWarping_Text_0, MSGBOX_YESNO
# 424 "data/scripts/flying_taxi.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_Colress_AskForWarping_2
# 428 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_WarpToSevii

Common_EventScript_Colress_AskForWarping_1:
# 430 "data/scripts/flying_taxi.pory"
	waitstate
# 431 "data/scripts/flying_taxi.pory"
	release
	end


Common_EventScript_Colress_AskForWarping_2:
# 425 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_NoWarp
	goto Common_EventScript_Colress_AskForWarping_1



Common_EventScript_Colress_AskForWarping_Text_0:
# 423 "data/scripts/flying_taxi.pory"
	.string "I'm on my way back to that Island do you\n"
	.string "want to go there with me?$"


Common_EventScript_Colress_Final_Encounter::
# 193 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_Final_Encounter_Text_0, MSGBOX_DEFAULT
# 194 "data/scripts/flying_taxi.pory"
	giveitem ITEM_SHOCK_DRIVE
# 195 "data/scripts/flying_taxi.pory"
	giveitem ITEM_BURN_DRIVE
# 196 "data/scripts/flying_taxi.pory"
	giveitem ITEM_CHILL_DRIVE
# 197 "data/scripts/flying_taxi.pory"
	giveitem ITEM_DOUSE_DRIVE
# 198 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_Final_Encounter_Text_1, MSGBOX_YESNO
# 199 "data/scripts/flying_taxi.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_Colress_Final_Encounter_2
# 203 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_Final_Encounter_Text_3, MSGBOX_DEFAULT

Common_EventScript_Colress_Final_Encounter_1:
# 205 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_Final_Encounter_Text_4, MSGBOX_DEFAULT
# 206 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_Final_Encounter_Text_5, MSGBOX_DEFAULT
# 207 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_Final_Encounter_Text_6, MSGBOX_DEFAULT
# 208 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_Final_Encounter_Text_7, MSGBOX_DEFAULT
# 209 "data/scripts/flying_taxi.pory"
	call Common_EventScript_Colress_SetTicketFlag
# 210 "data/scripts/flying_taxi.pory"
	warp MAP_LITTLEROOT_TOWN, 192, 192, 192
	return


Common_EventScript_Colress_Final_Encounter_2:
# 200 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_Final_Encounter_Text_2, MSGBOX_DEFAULT
	goto Common_EventScript_Colress_Final_Encounter_1



Common_EventScript_Colress_Final_Encounter_Text_0:
# 193 "data/scripts/flying_taxi.pory"
	.string "{PLAYER} this is so exciting! I finally\n"
	.string "completed my research here. The\l"
	.string "regional variations occur because of\l"
	.string "the unique environments you helped me\l"
	.string "explore. As a token of appreciation for\l"
	.string "your hard work, I have some prizes for\l"
	.string "you!!$"


Common_EventScript_Colress_Final_Encounter_Text_1:
# 198 "data/scripts/flying_taxi.pory"
	.string "Do you know of the Pokémon called\n"
	.string "Genesect?$"


Common_EventScript_Colress_Final_Encounter_Text_2:
# 200 "data/scripts/flying_taxi.pory"
	.string "Then allow me to inform you!$"


Common_EventScript_Colress_Final_Encounter_Text_3:
# 203 "data/scripts/flying_taxi.pory"
	.string "Then I have no choice but to admit that\n"
	.string "you are all I would expect you to be!$"


Common_EventScript_Colress_Final_Encounter_Text_4:
# 205 "data/scripts/flying_taxi.pory"
	.string "Genesect is a Pokémon that lived 300\n"
	.string "million years ago. Then an organization\l"
	.string "called Team Plasma modified it,\l"
	.string "attaching a cannon to its back.$"


Common_EventScript_Colress_Final_Encounter_Text_5:
# 206 "data/scripts/flying_taxi.pory"
	.string "The cannon's abilities could be\n"
	.string "activated using certain drives created\l"
	.string "by the scientists in the P2 Laboratory.\l"
	.string "I think that you might be able to use\l"
	.string "them as they should be used.$"


Common_EventScript_Colress_Final_Encounter_Text_6:
# 207 "data/scripts/flying_taxi.pory"
	.string "Simply believing in your Pokémon will\n"
	.string "not guarantee that you can do\l"
	.string "everything you want. But there are many\l"
	.string "things that are guaranteed to fail if\l"
	.string "you do not believe in them. It is the\l"
	.string "trust between a Trainer and a Pokémon\l"
	.string "alone that can overcome those hurdles!$"


Common_EventScript_Colress_Final_Encounter_Text_7:
# 208 "data/scripts/flying_taxi.pory"
	.string "My next quest will be looking for\n"
	.string "Genesect, I hope our paths cross again,\l"
	.string "thanks for everything!$"


Common_EventScript_Colress_First_Encounter::
# 180 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_Text_0, MSGBOX_DEFAULT
# 181 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_Text_1, MSGBOX_DEFAULT
# 182 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_Text_2, MSGBOX_DEFAULT
# 183 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_Text_3, MSGBOX_DEFAULT
# 184 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland
	return



Common_EventScript_Colress_First_Encounter_ChooseIsland::
# 214 "data/scripts/flying_taxi.pory"
	scrollingmultichoice SCROLLING_SEVII_TICKET, 0, 0, 4, TRUE
# 215 "data/scripts/flying_taxi.pory"
	switch VAR_RESULT
# 216 "data/scripts/flying_taxi.pory"
	case 0, Common_EventScript_Colress_First_Encounter_ChooseIsland_2
# 241 "data/scripts/flying_taxi.pory"
	case 1, Common_EventScript_Colress_First_Encounter_ChooseIsland_3
# 266 "data/scripts/flying_taxi.pory"
	case 2, Common_EventScript_Colress_First_Encounter_ChooseIsland_4
# 291 "data/scripts/flying_taxi.pory"
	case 3, Common_EventScript_Colress_First_Encounter_ChooseIsland_5
# 316 "data/scripts/flying_taxi.pory"
	case 4, Common_EventScript_Colress_First_Encounter_ChooseIsland_6
# 341 "data/scripts/flying_taxi.pory"
	case 5, Common_EventScript_Colress_First_Encounter_ChooseIsland_7
# 366 "data/scripts/flying_taxi.pory"
	case 6, Common_EventScript_Colress_First_Encounter_ChooseIsland_8
# 391 "data/scripts/flying_taxi.pory"
	case 7, Common_EventScript_Colress_First_Encounter_ChooseIsland_9
	return


Common_EventScript_Colress_First_Encounter_ChooseIsland_10:
	return


Common_EventScript_Colress_First_Encounter_ChooseIsland_11:
# 221 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_0, MSGBOX_DEFAULT
# 222 "data/scripts/flying_taxi.pory"
	giveitem ITEM_SEVII_TICKET_1
# 223 "data/scripts/flying_taxi.pory"
	addvar VAR_VISITED_SEVII, 1
# 225 "data/scripts/flying_taxi.pory"
	compare VAR_VISITED_SEVII, 1
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_59

Common_EventScript_Colress_First_Encounter_ChooseIsland_12:
# 231 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_2, MSGBOX_DEFAULT
# 232 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 233 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_10


Common_EventScript_Colress_First_Encounter_ChooseIsland_16:
	return


Common_EventScript_Colress_First_Encounter_ChooseIsland_17:
# 246 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_5, MSGBOX_DEFAULT
# 247 "data/scripts/flying_taxi.pory"
	giveitem ITEM_SEVII_TICKET_2
# 248 "data/scripts/flying_taxi.pory"
	addvar VAR_VISITED_SEVII, 1
# 250 "data/scripts/flying_taxi.pory"
	compare VAR_VISITED_SEVII, 1
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_62

Common_EventScript_Colress_First_Encounter_ChooseIsland_18:
# 256 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_2, MSGBOX_DEFAULT
# 257 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 258 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_16


Common_EventScript_Colress_First_Encounter_ChooseIsland_2:
# 218 "data/scripts/flying_taxi.pory"
	checkitem ITEM_SEVII_TICKET_1, 1
# 219 "data/scripts/flying_taxi.pory"
	setvar VAR_TEMP_A, 0
# 220 "data/scripts/flying_taxi.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_11
# 230 "data/scripts/flying_taxi.pory"
	compare VAR_CURRENT_SEVII, 0
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_12
# 236 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_4, MSGBOX_DEFAULT
# 237 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 238 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland

Common_EventScript_Colress_First_Encounter_ChooseIsland_22:
	return


Common_EventScript_Colress_First_Encounter_ChooseIsland_23:
# 271 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_6, MSGBOX_DEFAULT
# 272 "data/scripts/flying_taxi.pory"
	giveitem ITEM_SEVII_TICKET_3
# 273 "data/scripts/flying_taxi.pory"
	addvar VAR_VISITED_SEVII, 1
# 275 "data/scripts/flying_taxi.pory"
	compare VAR_VISITED_SEVII, 1
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_65

Common_EventScript_Colress_First_Encounter_ChooseIsland_24:
# 281 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_2, MSGBOX_DEFAULT
# 282 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 283 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_22


Common_EventScript_Colress_First_Encounter_ChooseIsland_28:
	return


Common_EventScript_Colress_First_Encounter_ChooseIsland_29:
# 296 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_7, MSGBOX_DEFAULT
# 297 "data/scripts/flying_taxi.pory"
	giveitem ITEM_SEVII_TICKET_4
# 298 "data/scripts/flying_taxi.pory"
	addvar VAR_VISITED_SEVII, 1
# 300 "data/scripts/flying_taxi.pory"
	compare VAR_VISITED_SEVII, 1
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_68

Common_EventScript_Colress_First_Encounter_ChooseIsland_3:
# 243 "data/scripts/flying_taxi.pory"
	checkitem ITEM_SEVII_TICKET_2, 1
# 244 "data/scripts/flying_taxi.pory"
	setvar VAR_TEMP_A, 1
# 245 "data/scripts/flying_taxi.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_17
# 255 "data/scripts/flying_taxi.pory"
	compare VAR_CURRENT_SEVII, 1
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_18
# 261 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_4, MSGBOX_DEFAULT
# 262 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 263 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland

Common_EventScript_Colress_First_Encounter_ChooseIsland_30:
# 306 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_2, MSGBOX_DEFAULT
# 307 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 308 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_28


Common_EventScript_Colress_First_Encounter_ChooseIsland_34:
	return


Common_EventScript_Colress_First_Encounter_ChooseIsland_35:
# 321 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_8, MSGBOX_DEFAULT
# 322 "data/scripts/flying_taxi.pory"
	giveitem ITEM_SEVII_TICKET_5
# 323 "data/scripts/flying_taxi.pory"
	addvar VAR_VISITED_SEVII, 1
# 325 "data/scripts/flying_taxi.pory"
	compare VAR_VISITED_SEVII, 1
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_71

Common_EventScript_Colress_First_Encounter_ChooseIsland_36:
# 331 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_2, MSGBOX_DEFAULT
# 332 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 333 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_34


Common_EventScript_Colress_First_Encounter_ChooseIsland_4:
# 268 "data/scripts/flying_taxi.pory"
	checkitem ITEM_SEVII_TICKET_3, 1
# 269 "data/scripts/flying_taxi.pory"
	setvar VAR_TEMP_A, 2
# 270 "data/scripts/flying_taxi.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_23
# 280 "data/scripts/flying_taxi.pory"
	compare VAR_CURRENT_SEVII, 2
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_24
# 286 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_4, MSGBOX_DEFAULT
# 287 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 288 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland

Common_EventScript_Colress_First_Encounter_ChooseIsland_40:
	return


Common_EventScript_Colress_First_Encounter_ChooseIsland_41:
# 346 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_9, MSGBOX_DEFAULT
# 347 "data/scripts/flying_taxi.pory"
	giveitem ITEM_SEVII_TICKET_6
# 348 "data/scripts/flying_taxi.pory"
	addvar VAR_VISITED_SEVII, 1
# 350 "data/scripts/flying_taxi.pory"
	compare VAR_VISITED_SEVII, 1
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_74

Common_EventScript_Colress_First_Encounter_ChooseIsland_42:
# 356 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_2, MSGBOX_DEFAULT
# 357 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 358 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_40


Common_EventScript_Colress_First_Encounter_ChooseIsland_46:
	return


Common_EventScript_Colress_First_Encounter_ChooseIsland_47:
# 371 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_10, MSGBOX_DEFAULT
# 372 "data/scripts/flying_taxi.pory"
	giveitem ITEM_SEVII_TICKET_7
# 373 "data/scripts/flying_taxi.pory"
	addvar VAR_VISITED_SEVII, 1
# 375 "data/scripts/flying_taxi.pory"
	compare VAR_VISITED_SEVII, 1
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_77

Common_EventScript_Colress_First_Encounter_ChooseIsland_48:
# 381 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_2, MSGBOX_DEFAULT
# 382 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 383 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_46


Common_EventScript_Colress_First_Encounter_ChooseIsland_5:
# 293 "data/scripts/flying_taxi.pory"
	checkitem ITEM_SEVII_TICKET_4, 1
# 294 "data/scripts/flying_taxi.pory"
	setvar VAR_TEMP_A, 3
# 295 "data/scripts/flying_taxi.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_29
# 305 "data/scripts/flying_taxi.pory"
	compare VAR_CURRENT_SEVII, 3
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_30
# 311 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_4, MSGBOX_DEFAULT
# 312 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 313 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland

Common_EventScript_Colress_First_Encounter_ChooseIsland_52:
	return


Common_EventScript_Colress_First_Encounter_ChooseIsland_53:
# 396 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_11, MSGBOX_DEFAULT
# 397 "data/scripts/flying_taxi.pory"
	delay 90
# 398 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_12, MSGBOX_DEFAULT
# 399 "data/scripts/flying_taxi.pory"
	giveitem ITEM_SEVII_TICKET_8
# 400 "data/scripts/flying_taxi.pory"
	addvar VAR_VISITED_SEVII, 1
# 402 "data/scripts/flying_taxi.pory"
	compare VAR_VISITED_SEVII, 1
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_80

Common_EventScript_Colress_First_Encounter_ChooseIsland_54:
# 408 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_2, MSGBOX_DEFAULT
# 409 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 410 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_52


Common_EventScript_Colress_First_Encounter_ChooseIsland_58:
# 228 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_AskForWarping
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_10


Common_EventScript_Colress_First_Encounter_ChooseIsland_59:
# 226 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_1, MSGBOX_DEFAULT
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_58


Common_EventScript_Colress_First_Encounter_ChooseIsland_6:
# 318 "data/scripts/flying_taxi.pory"
	checkitem ITEM_SEVII_TICKET_5, 1
# 319 "data/scripts/flying_taxi.pory"
	setvar VAR_TEMP_A, 4
# 320 "data/scripts/flying_taxi.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_35
# 330 "data/scripts/flying_taxi.pory"
	compare VAR_CURRENT_SEVII, 4
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_36
# 336 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_4, MSGBOX_DEFAULT
# 337 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 338 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland

Common_EventScript_Colress_First_Encounter_ChooseIsland_61:
# 253 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_AskForWarping
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_16


Common_EventScript_Colress_First_Encounter_ChooseIsland_62:
# 251 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_1, MSGBOX_DEFAULT
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_61


Common_EventScript_Colress_First_Encounter_ChooseIsland_64:
# 278 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_AskForWarping
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_22


Common_EventScript_Colress_First_Encounter_ChooseIsland_65:
# 276 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_1, MSGBOX_DEFAULT
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_64


Common_EventScript_Colress_First_Encounter_ChooseIsland_67:
# 303 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_AskForWarping
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_28


Common_EventScript_Colress_First_Encounter_ChooseIsland_68:
# 301 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_1, MSGBOX_DEFAULT
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_67


Common_EventScript_Colress_First_Encounter_ChooseIsland_7:
# 343 "data/scripts/flying_taxi.pory"
	checkitem ITEM_SEVII_TICKET_6, 1
# 344 "data/scripts/flying_taxi.pory"
	setvar VAR_TEMP_A, 5
# 345 "data/scripts/flying_taxi.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_41
# 355 "data/scripts/flying_taxi.pory"
	compare VAR_CURRENT_SEVII, 5
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_42
# 361 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_4, MSGBOX_DEFAULT
# 362 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 363 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland

Common_EventScript_Colress_First_Encounter_ChooseIsland_70:
# 328 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_AskForWarping
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_34


Common_EventScript_Colress_First_Encounter_ChooseIsland_71:
# 326 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_1, MSGBOX_DEFAULT
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_70


Common_EventScript_Colress_First_Encounter_ChooseIsland_73:
# 353 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_AskForWarping
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_40


Common_EventScript_Colress_First_Encounter_ChooseIsland_74:
# 351 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_1, MSGBOX_DEFAULT
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_73


Common_EventScript_Colress_First_Encounter_ChooseIsland_76:
# 378 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_AskForWarping
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_46


Common_EventScript_Colress_First_Encounter_ChooseIsland_77:
# 376 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_1, MSGBOX_DEFAULT
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_76


Common_EventScript_Colress_First_Encounter_ChooseIsland_79:
# 405 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_AskForWarping
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_52


Common_EventScript_Colress_First_Encounter_ChooseIsland_8:
# 368 "data/scripts/flying_taxi.pory"
	checkitem ITEM_SEVII_TICKET_7, 1
# 369 "data/scripts/flying_taxi.pory"
	setvar VAR_TEMP_A, 6
# 370 "data/scripts/flying_taxi.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_47
# 380 "data/scripts/flying_taxi.pory"
	compare VAR_CURRENT_SEVII, 6
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_48
# 386 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_4, MSGBOX_DEFAULT
# 387 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 388 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland

Common_EventScript_Colress_First_Encounter_ChooseIsland_80:
# 403 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_1, MSGBOX_DEFAULT
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland_79



Common_EventScript_Colress_First_Encounter_ChooseIsland_9:
# 393 "data/scripts/flying_taxi.pory"
	checkitem ITEM_SEVII_TICKET_8, 1
# 394 "data/scripts/flying_taxi.pory"
	setvar VAR_TEMP_A, 7
# 395 "data/scripts/flying_taxi.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_53
# 407 "data/scripts/flying_taxi.pory"
	compare VAR_CURRENT_SEVII, 7
	goto_if_eq Common_EventScript_Colress_First_Encounter_ChooseIsland_54
# 413 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_4, MSGBOX_DEFAULT
# 414 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3, MSGBOX_DEFAULT
# 415 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland

Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_0:
# 221 "data/scripts/flying_taxi.pory"
	.string "One Island huh? I think there is a giant\n"
	.string "volcano there, it could lead to some\l"
	.string "interesting information for my\l"
	.string "research, so let's see each other over\l"
	.string "there!$"


Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_1:
# 226 "data/scripts/flying_taxi.pory"
	.string "That's right, you will help me with my\n"
	.string "research since you seem like an\l"
	.string "interesting Trainer.$"


Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_10:
# 371 "data/scripts/flying_taxi.pory"
	.string "Seven Island huh? I think there is a\n"
	.string "Canyon in there, it could lead to some\l"
	.string "interesting information for my\l"
	.string "research, so let's see each other over\l"
	.string "there!$"


Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_11:
# 396 "data/scripts/flying_taxi.pory"
	.string "Eight Island?, first time I heard of\n"
	.string "such Island, let me search for\l"
	.string "information on it...$"


Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_12:
# 398 "data/scripts/flying_taxi.pory"
	.string "I see so that island was recently\n"
	.string "discovered by a famous Dragon Tamer,\l"
	.string "seems like an interesting place, let's\l"
	.string "see each other over there!$"


Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_2:
# 231 "data/scripts/flying_taxi.pory"
	.string "But we are already there, take this more\n"
	.string "seriously!$"


Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_3:
# 232 "data/scripts/flying_taxi.pory"
	.string "{PLAYER} what Sevii Island I should\n"
	.string "visit next?$"


Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_4:
# 236 "data/scripts/flying_taxi.pory"
	.string "But we already visited that Island,\n"
	.string "take this more seriously!$"


Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_5:
# 246 "data/scripts/flying_taxi.pory"
	.string "Two Island huh? I think there is a\n"
	.string "swamp route there, it could lead to some\l"
	.string "interesting information for my\l"
	.string "research, so let's see each other over\l"
	.string "there!$"


Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_6:
# 271 "data/scripts/flying_taxi.pory"
	.string "Three Island huh? I think there is a\n"
	.string "Forest full of berries there, it could\l"
	.string "lead to some interesting information\l"
	.string "for my research, so let's see each other\l"
	.string "over there!$"


Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_7:
# 296 "data/scripts/flying_taxi.pory"
	.string "Four Island huh? I think there is a\n"
	.string "really cold cave in there, it could lead\l"
	.string "to some interesting information for my\l"
	.string "research, so let's see each other over\l"
	.string "there!$"


Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_8:
# 321 "data/scripts/flying_taxi.pory"
	.string "Five Island huh? I think there is a\n"
	.string "Water Labrynth in there, it could lead\l"
	.string "to some interesting information for my\l"
	.string "research, so let's see each other over\l"
	.string "there!$"


Common_EventScript_Colress_First_Encounter_ChooseIsland_Text_9:
# 346 "data/scripts/flying_taxi.pory"
	.string "Six Island huh? I think there are some\n"
	.string "Ruins in there, it could lead to some\l"
	.string "interesting information for my\l"
	.string "research, so let's see each other over\l"
	.string "there!$"


Common_EventScript_Colress_First_Encounter_Text_0:
# 180 "data/scripts/flying_taxi.pory"
	.string "Oh, excuse me! I am a scientist. My name\n"
	.string "is Colress. My research focuses on\l"
	.string "regional variations between species.\l"
	.string "For example, Vulpix from Kanto has\l"
	.string "developed differently compared to\l"
	.string "those found in Alola. It seems a similar\l"
	.string "phenomenon is occurring here in the\l"
	.string "Sevii Islands.$"


Common_EventScript_Colress_First_Encounter_Text_1:
# 181 "data/scripts/flying_taxi.pory"
	.string "Thats why I came to these islands, to\n"
	.string "uncover the reasons behind why this\l"
	.string "happens.$"


Common_EventScript_Colress_First_Encounter_Text_2:
# 182 "data/scripts/flying_taxi.pory"
	.string "Now that I think of it, I never asked\n"
	.string "your name...$"


Common_EventScript_Colress_First_Encounter_Text_3:
# 183 "data/scripts/flying_taxi.pory"
	.string "{PLAYER}, is it? I'll remember your\n"
	.string "name. To commemorate our encounter, I\l"
	.string "will let you decide which Sevii Island I\l"
	.string "should visit next!$"


Common_EventScript_Colress_NoWarp::
# 466 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_NoWarp_Text_0, MSGBOX_DEFAULT
# 467 "data/scripts/flying_taxi.pory"
	warp MAP_LITTLEROOT_TOWN, 192, 192, 192
# 468 "data/scripts/flying_taxi.pory"
	waitstate
# 469 "data/scripts/flying_taxi.pory"
	release
	end



Common_EventScript_Colress_NoWarp_Text_0:
# 466 "data/scripts/flying_taxi.pory"
	.string "Well then, {PLAYER}, I hope to see you\n"
	.string "again in there.$"


Common_EventScript_Colress_Second_Encounter::
# 188 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_Second_Encounter_Text_0, MSGBOX_DEFAULT
# 189 "data/scripts/flying_taxi.pory"
	goto Common_EventScript_Colress_First_Encounter_ChooseIsland
	return



Common_EventScript_Colress_Second_Encounter_Text_0:
# 188 "data/scripts/flying_taxi.pory"
	.string "Oh {PLAYER}, I was just finishing\n"
	.string "organizing the data that I found here,\l"
	.string "but I'm already excited on what I will\l"
	.string "find next so help me decide what Sevii\l"
	.string "Island I should visit next!$"


Common_EventScript_Colress_SetTicketFlag::
# 436 "data/scripts/flying_taxi.pory"
	switch VAR_CURRENT_SEVII
# 437 "data/scripts/flying_taxi.pory"
	case 0, Common_EventScript_Colress_SetTicketFlag_3
# 440 "data/scripts/flying_taxi.pory"
	case 1, Common_EventScript_Colress_SetTicketFlag_4
# 443 "data/scripts/flying_taxi.pory"
	case 2, Common_EventScript_Colress_SetTicketFlag_5
# 446 "data/scripts/flying_taxi.pory"
	case 3, Common_EventScript_Colress_SetTicketFlag_6
# 449 "data/scripts/flying_taxi.pory"
	case 4, Common_EventScript_Colress_SetTicketFlag_7
# 452 "data/scripts/flying_taxi.pory"
	case 5, Common_EventScript_Colress_SetTicketFlag_8
# 455 "data/scripts/flying_taxi.pory"
	case 6, Common_EventScript_Colress_SetTicketFlag_9
# 458 "data/scripts/flying_taxi.pory"
	case 7, Common_EventScript_Colress_SetTicketFlag_10

Common_EventScript_Colress_SetTicketFlag_1:
	return


Common_EventScript_Colress_SetTicketFlag_10:
# 459 "data/scripts/flying_taxi.pory"
	setflag FLAG_GOT_SEVII_TICKET_8
	goto Common_EventScript_Colress_SetTicketFlag_1



Common_EventScript_Colress_SetTicketFlag_3:
# 438 "data/scripts/flying_taxi.pory"
	setflag FLAG_GOT_SEVII_TICKET_1
	goto Common_EventScript_Colress_SetTicketFlag_1


Common_EventScript_Colress_SetTicketFlag_4:
# 441 "data/scripts/flying_taxi.pory"
	setflag FLAG_GOT_SEVII_TICKET_2
	goto Common_EventScript_Colress_SetTicketFlag_1


Common_EventScript_Colress_SetTicketFlag_5:
# 444 "data/scripts/flying_taxi.pory"
	setflag FLAG_GOT_SEVII_TICKET_3
	goto Common_EventScript_Colress_SetTicketFlag_1


Common_EventScript_Colress_SetTicketFlag_6:
# 447 "data/scripts/flying_taxi.pory"
	setflag FLAG_GOT_SEVII_TICKET_4
	goto Common_EventScript_Colress_SetTicketFlag_1


Common_EventScript_Colress_SetTicketFlag_7:
# 450 "data/scripts/flying_taxi.pory"
	setflag FLAG_GOT_SEVII_TICKET_5
	goto Common_EventScript_Colress_SetTicketFlag_1


Common_EventScript_Colress_SetTicketFlag_8:
# 453 "data/scripts/flying_taxi.pory"
	setflag FLAG_GOT_SEVII_TICKET_6
	goto Common_EventScript_Colress_SetTicketFlag_1


Common_EventScript_Colress_SetTicketFlag_9:
# 456 "data/scripts/flying_taxi.pory"
	setflag FLAG_GOT_SEVII_TICKET_7
	goto Common_EventScript_Colress_SetTicketFlag_1


Common_EventScript_Colress_WarpToSevii::
# 474 "data/scripts/flying_taxi.pory"
	msgbox Common_EventScript_Colress_WarpToSevii_Text_0, MSGBOX_DEFAULT
# 476 "data/scripts/flying_taxi.pory"
	switch VAR_TEMP_A
# 477 "data/scripts/flying_taxi.pory"
	case 0, Common_EventScript_Colress_WarpToSevii_3
# 480 "data/scripts/flying_taxi.pory"
	case 1, Common_EventScript_Colress_WarpToSevii_4
# 483 "data/scripts/flying_taxi.pory"
	case 2, Common_EventScript_Colress_WarpToSevii_5
# 486 "data/scripts/flying_taxi.pory"
	case 3, Common_EventScript_Colress_WarpToSevii_6
# 489 "data/scripts/flying_taxi.pory"
	case 4, Common_EventScript_Colress_WarpToSevii_7
# 492 "data/scripts/flying_taxi.pory"
	case 5, Common_EventScript_Colress_WarpToSevii_8
# 495 "data/scripts/flying_taxi.pory"
	case 6, Common_EventScript_Colress_WarpToSevii_9
# 498 "data/scripts/flying_taxi.pory"
	case 7, Common_EventScript_Colress_WarpToSevii_10

Common_EventScript_Colress_WarpToSevii_1:
# 502 "data/scripts/flying_taxi.pory"
	waitstate
# 503 "data/scripts/flying_taxi.pory"
	release
	end


Common_EventScript_Colress_WarpToSevii_10:
# 499 "data/scripts/flying_taxi.pory"
	warp MAP_EIGHT_ISLAND, 255, 20, 33
	goto Common_EventScript_Colress_WarpToSevii_1



Common_EventScript_Colress_WarpToSevii_3:
# 478 "data/scripts/flying_taxi.pory"
	warp MAP_ONE_ISLAND, 255, 28, 17
	goto Common_EventScript_Colress_WarpToSevii_1


Common_EventScript_Colress_WarpToSevii_4:
# 481 "data/scripts/flying_taxi.pory"
	warp MAP_TWO_ISLAND, 255, 10, 7
	goto Common_EventScript_Colress_WarpToSevii_1


Common_EventScript_Colress_WarpToSevii_5:
# 484 "data/scripts/flying_taxi.pory"
	warp MAP_THREE_ISLAND_PORT, 255, 12, 12
	goto Common_EventScript_Colress_WarpToSevii_1


Common_EventScript_Colress_WarpToSevii_6:
# 487 "data/scripts/flying_taxi.pory"
	warp MAP_FOUR_ISLAND, 255, 10, 27
	goto Common_EventScript_Colress_WarpToSevii_1


Common_EventScript_Colress_WarpToSevii_7:
# 490 "data/scripts/flying_taxi.pory"
	warp MAP_FIVE_ISLAND, 255, 23, 23
	goto Common_EventScript_Colress_WarpToSevii_1


Common_EventScript_Colress_WarpToSevii_8:
# 493 "data/scripts/flying_taxi.pory"
	warp MAP_SIX_ISLAND, 255, 27, 22
	goto Common_EventScript_Colress_WarpToSevii_1


Common_EventScript_Colress_WarpToSevii_9:
# 496 "data/scripts/flying_taxi.pory"
	warp MAP_SEVEN_ISLAND, 255, 19, 12
	goto Common_EventScript_Colress_WarpToSevii_1


Common_EventScript_Colress_WarpToSevii_Text_0:
# 474 "data/scripts/flying_taxi.pory"
	.string "Splendid! Let's get out of here!$"


EightIsland_House1_EventScript_BattleMart_HeldItems::
# 216 "data/maps/OldaleTown_BattleMart/scripts.pory"
	lock
# 217 "data/maps/OldaleTown_BattleMart/scripts.pory"
	faceplayer
# 218 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_TYPE, MART_TYPE_NORMAL
# 219 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_MONEY_TYPE, MART_MONEY_TYPE_BATTLE_POINTS
# 220 "data/maps/OldaleTown_BattleMart/scripts.pory"
	message OldaleTown_House1_EventScript_BattleMart_Text_0
# 221 "data/maps/OldaleTown_BattleMart/scripts.pory"
	waitmessage
# 222 "data/maps/OldaleTown_BattleMart/scripts.pory"
	pokemart OldaleTown_House1_EventScript_Pokemart_HeldItems
# 223 "data/maps/OldaleTown_BattleMart/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 224 "data/maps/OldaleTown_BattleMart/scripts.pory"
	release
	end



EightIsland_House1_EventScript_BattleMart_TMs::
# 203 "data/maps/OldaleTown_BattleMart/scripts.pory"
	lock
# 204 "data/maps/OldaleTown_BattleMart/scripts.pory"
	faceplayer
# 205 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_TYPE, MART_TYPE_NORMAL
# 206 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_MONEY_TYPE, MART_MONEY_TYPE_BATTLE_POINTS
# 207 "data/maps/OldaleTown_BattleMart/scripts.pory"
	message OldaleTown_House1_EventScript_BattleMart_Text_0
# 208 "data/maps/OldaleTown_BattleMart/scripts.pory"
	waitmessage
# 209 "data/maps/OldaleTown_BattleMart/scripts.pory"
	pokemart OldaleTown_House1_EventScript_Pokemart_TMs
# 210 "data/maps/OldaleTown_BattleMart/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 211 "data/maps/OldaleTown_BattleMart/scripts.pory"
	release
	end



MartEnergyGuruMons:
# 84 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte SPECIES_ABRA
# 85 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte SPECIES_CLEFFA
# 86 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte SPECIES_MIMEJR
# 87 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte SPECIES_DRATINI
# 88 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte SPECIES_EEVEE
# 89 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte SPECIES_PORYGON
	.2byte ITEM_NONE


MauvilleCity_GameCorner_EventScript_Mons::
# 127 "data/maps/OldaleTown_BattleMart/scripts.pory"
	lock
# 128 "data/maps/OldaleTown_BattleMart/scripts.pory"
	faceplayer
# 129 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_TYPE, MART_TYPE_MONS
# 130 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_MONEY_TYPE, MART_MONEY_TYPE_BATTLE_POINTS
# 131 "data/maps/OldaleTown_BattleMart/scripts.pory"
	message MauvilleCity_GameCorner_EventScript_Mons_Text_0
# 132 "data/maps/OldaleTown_BattleMart/scripts.pory"
	waitmessage
# 133 "data/maps/OldaleTown_BattleMart/scripts.pory"
	pokemart MartEnergyGuruMons
# 134 "data/maps/OldaleTown_BattleMart/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 135 "data/maps/OldaleTown_BattleMart/scripts.pory"
	release
	end


	.align 2
# 139 "data/maps/OldaleTown_BattleMart/scripts.pory"

MauvilleCity_GameCorner_EventScript_Mons_Text_0:
# 131 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.string "I'm currently selling some Pokémon for\n"
	.string "BP!, How may I serve you?$"

OldaleTown_House1_EventScript_BattleMart_Text_0:
# 105 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.string "Welcome to my Battle Mart!, How may I\n"
	.string "serve you?$"


OldaleTown_House1_EventScript_Pokemart_HeldItems:
# 140 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SOOTHE_BELL
# 141 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_AMULET_COIN
# 142 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_EVERSTONE
# 143 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_LUCKY_EGG
# 144 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_NORMAL_GEM
# 145 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_QUICK_CLAW
# 146 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_CHOICE_BAND
# 147 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_CHOICE_SCARF
# 148 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_CHOICE_SPECS
# 149 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SCOPE_LENS
# 150 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_LIFE_ORB
# 151 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TOXIC_ORB
# 152 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_FLAME_ORB
# 153 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_FOCUS_SASH
# 154 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_WHITE_HERB
# 155 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_POWER_HERB
# 156 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_MENTAL_HERB
# 157 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_BLACK_SLUDGE
# 158 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_ASSAULT_VEST
# 159 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_UTILITY_UMBRELLA
# 160 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_WEAKNESS_POLICY
# 161 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_HEAVY_DUTY_BOOTS
# 162 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_ROCKY_HELMET
# 163 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_FOCUS_BAND
# 164 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_LUM_BERRY
# 165 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_POWER_BRACER
# 166 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_POWER_BELT
# 167 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_POWER_LENS
# 168 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_POWER_BAND
# 169 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_POWER_ANKLET
# 170 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_MACHO_BRACE
# 171 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TERRAIN_EXTENDER
# 172 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_WIDE_LENS
# 173 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SHELL_BELL
# 174 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_ZOOM_LENS
# 175 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_EXPERT_BELT
# 176 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_METRONOME
# 177 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SHED_SHELL
# 178 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_RED_CARD
# 179 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SAFETY_GOGGLES
# 180 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_ADRENALINE_ORB
# 181 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_PROTECTIVE_PADS
	.2byte ITEM_NONE

	.align 2
# 185 "data/maps/OldaleTown_BattleMart/scripts.pory"

OldaleTown_House1_EventScript_Pokemart_TMs:
# 186 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM14
# 187 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM15
# 188 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM25
# 189 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM38
# 190 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM59
# 191 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM30
# 192 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM66
# 193 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM75
# 194 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM82
# 195 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM84
# 196 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM97
# 197 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM109
# 198 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM115
	.2byte ITEM_NONE


