-- GENERATED by gen_anchors.py from pokeemerald.map -- do not hand-edit.
return {
    mapDigest = "d8946ef358adf666",
    gCharacterModeSelftestResult = 0x0203F2CC,
    gPlayerParty = 0x020250DC,
    gPlayerPartyCount = 0x020250D9,
    gEnemyParty = 0x02025334,
    gSaveBlock1Ptr = 0x03004B7C,
    gSaveBlock2Ptr = 0x03004B80,
    gPokemonStoragePtr = 0x03004B84,
    gCharacters = 0x08CB4578,
    gMain = 0x03002C10,
    CB2_Overworld = 0x080AF520,
}
