-- Prove ENCOUNTERS.md's model matches the ENGINE, not just itself.
--
-- ENCOUNTERS.md is generated by tools/character_mode/emit_encounter_docs.py,
-- which reimplements CharacterMode_PickEvolutionStageForLevel in Python in order
-- to work out which evolution stage a wild roster spawn comes out as at a given
-- level. A generator agreeing with its own model proves nothing -- that is
-- exactly how ROSTERS.md and the ROM drifted apart in both directions until the
-- 2026-07-24 resync (194 families the docs promised that the catch gate refused,
-- ~2500 the ROM allowed that the docs never listed).
--
-- So the generator writes tools/character_mode/encounter_probes.json alongside
-- the doc, and this replays every probe against the real in-ROM function via
-- CM_REQ_PICK_STAGE. The picker chooses at RANDOM among equally-valid branches
-- (Eevee at Lv16 can be any of eight), so each probe is sampled repeatedly and
-- the observed set is compared against the predicted set:
--
--   * every observed stage must be in the predicted set  -- catches a doc that
--     promises too little, i.e. the ROM can spawn something undocumented
--   * every predicted stage must be observed              -- catches a doc that
--     promises too much, i.e. it lists a stage that cannot actually appear
--
-- The second direction is the one a naive test drops, and it is the one that
-- matters: a doc listing families the ROM cannot spawn is the failure the spec
-- explicitly warns about when it says never to build this from
-- rosters_mapped.json.
--
-- Run (no CM_SAV -- drives a real new game):
--   timeout 200 <mgba-headless> \
--     --script tools/mgba_scripts/encounter_doc_e2e.lua pokeemerald.gba \
--     > /tmp/encdoc.log 2>&1

local H = dofile("tools/mgba_scripts/harness.lua")
local D = dofile("tools/mgba_scripts/intro_drive.lua")(H)

-- Probes are (species id, level, {expected species ids}). Species CONSTANTS are
-- resolved to ids by the generator, so this file carries no name table.
local PROBES = dofile("tools/mgba_scripts/encounter_probes.lua")

-- ⚠️ HARD FLOOR. Every assertion in this run lives inside the loop over PROBES,
-- so a generator that emitted five rows instead of thirty would report
-- "PASSED 10 / RESULT: PASS" and look healthy -- the empty-set shape that has
-- passed vacuously in this repo four times. run_suite.sh now pins this run's
-- tally at 60 and would also catch it, but a script should not depend on its
-- caller to notice that it checked almost nothing.
local MIN_PROBES = 25
if #PROBES < MIN_PROBES then
    H.assertTrue(string.format(
        "encounter_probes.lua yielded %d probes, expected at least %d -- "
        .. "regenerate with emit_encounter_docs.py", #PROBES, MIN_PROBES), false)
    H.finish()
    return
end

-- Enough samples that an eight-way branch is very unlikely to miss a member:
-- P(a given one of 8 unseen in 120 draws) = (7/8)^120 ~ 1e-7.
local SAMPLES = 120

D.driveNewGameCharacterMode()

local function setToList(t)
    local out = {}
    for k in pairs(t) do out[#out + 1] = k end
    table.sort(out)
    return table.concat(out, ",")
end

for _, probe in ipairs(PROBES) do
    local species, level, expect = probe[1], probe[2], probe[3]

    local expectSet = {}
    for _, s in ipairs(expect) do expectSet[s] = true end

    local seen = {}
    local drawn = 0
    local label = string.format("species %d at Lv%d", species, level)

    D.addStep(label, function() D.mbRequest(D.REQ.PICK_STAGE, species, level) end,
        function(f)
            if D.mbStatus() ~= D.STATUS_DONE then
                if f - D.stepStart() > 4000 then
                    H.assertTrue(label .. " (mailbox answered)", false)
                    return true
                end
                return false
            end

            seen[D.mbResult()] = true
            drawn = drawn + 1
            if drawn < SAMPLES then
                D.mbRequest(D.REQ.PICK_STAGE, species, level)
                return false
            end

            -- Direction 1: the ROM never produced anything the doc omits.
            local unexpected = {}
            for s in pairs(seen) do
                if not expectSet[s] then unexpected[s] = true end
            end
            H.assertTrue(label .. ": ROM produced only documented stages (extra: "
                         .. setToList(unexpected) .. ")",
                         next(unexpected) == nil)

            -- Direction 2: everything the doc promises really can appear.
            local missing = {}
            for _, s in ipairs(expect) do
                if not seen[s] then missing[s] = true end
            end
            H.assertTrue(label .. ": every documented stage actually appeared "
                         .. "(missing: " .. setToList(missing) .. ")",
                         next(missing) == nil)

            H.log(string.format("%s: predicted {%s} observed {%s}",
                                label, setToList(expectSet), setToList(seen)))
            return true
        end)
end

D.run()
