-- GENERATED by tools/character_mode/emit_encounter_docs.py.
-- Do not hand-edit. Replayed against the real in-ROM stage
-- picker by tools/mgba_scripts/encounter_doc_e2e.lua, so that
-- ENCOUNTERS.md is checked against the ENGINE and not merely
-- against the generator's own model of it.
-- Each row is {species id, level, {every stage that may result}}.
return {
    {1, 5, {1}},  -- Bulbasaur Lv5 -> Bulbasaur
    {1, 16, {2}},  -- Bulbasaur Lv16 -> Ivysaur
    {1, 30, {2}},  -- Bulbasaur Lv30 -> Ivysaur
    {1, 50, {3}},  -- Bulbasaur Lv50 -> Venusaur
    {1, 100, {3}},  -- Bulbasaur Lv100 -> Venusaur
    {133, 5, {133}},  -- Eevee Lv5 -> Eevee
    {133, 16, {196, 136, 471, 135, 470, 700, 197, 134}},  -- Eevee Lv16 -> Espeon, Flareon, Glaceon, Jolteon, Leafeon, Sylveon, Umbreon, Vaporeon
    {133, 30, {196, 136, 471, 135, 470, 700, 197, 134}},  -- Eevee Lv30 -> Espeon, Flareon, Glaceon, Jolteon, Leafeon, Sylveon, Umbreon, Vaporeon
    {133, 50, {196, 136, 471, 135, 470, 700, 197, 134}},  -- Eevee Lv50 -> Espeon, Flareon, Glaceon, Jolteon, Leafeon, Sylveon, Umbreon, Vaporeon
    {133, 100, {196, 136, 471, 135, 470, 700, 197, 134}},  -- Eevee Lv100 -> Espeon, Flareon, Glaceon, Jolteon, Leafeon, Sylveon, Umbreon, Vaporeon
    {261, 5, {261}},  -- Poochyena Lv5 -> Poochyena
    {261, 16, {261}},  -- Poochyena Lv16 -> Poochyena
    {261, 30, {262}},  -- Poochyena Lv30 -> Mightyena
    {261, 50, {262}},  -- Poochyena Lv50 -> Mightyena
    {261, 100, {262}},  -- Poochyena Lv100 -> Mightyena
    {144, 5, {144}},  -- Articuno Lv5 -> Articuno
    {144, 16, {144}},  -- Articuno Lv16 -> Articuno
    {144, 30, {144}},  -- Articuno Lv30 -> Articuno
    {144, 50, {144}},  -- Articuno Lv50 -> Articuno
    {144, 100, {144}},  -- Articuno Lv100 -> Articuno
    {129, 5, {129}},  -- Magikarp Lv5 -> Magikarp
    {129, 16, {129}},  -- Magikarp Lv16 -> Magikarp
    {129, 30, {130}},  -- Magikarp Lv30 -> Gyarados
    {129, 50, {130}},  -- Magikarp Lv50 -> Gyarados
    {129, 100, {130}},  -- Magikarp Lv100 -> Gyarados
    {194, 5, {194}},  -- Wooper Lv5 -> Wooper
    {194, 16, {194}},  -- Wooper Lv16 -> Wooper
    {194, 30, {195}},  -- Wooper Lv30 -> Quagsire
    {194, 50, {195}},  -- Wooper Lv50 -> Quagsire
    {194, 100, {195}},  -- Wooper Lv100 -> Quagsire
}
