#!/usr/bin/env python3
"""Generate anchors.lua from pokeemerald.map.

ROWE is a source build, so unlike the Lazarus/Seaglass harnesses (which had to
reverse-engineer every RAM address) the exact addresses of every global come
straight from the linker map. Re-run after any build whose EWRAM/IWRAM layout
may have shifted (the harness scripts assert on a map checksum to catch a
stale anchors.lua).

Usage: python3 tools/mgba_scripts/gen_anchors.py
"""
import hashlib
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
MAP = os.path.join(TARGET, "pokeemerald.map")

SYMBOLS = [
    "gCharacterModeSelftestResult",
    "gCharacterModeTestMailbox",
    "gPlayerParty",
    "gPlayerPartyCount",
    "gEnemyParty",
    "gSaveBlock1Ptr",
    "gSaveBlock2Ptr",
    "gPokemonStoragePtr",
    "gCharacters",
    "gMain",
    "CB2_Overworld",
    "BattleMainCB2",
    "gBattleOutcome",
    "gBattlescriptCurrInstr",
    "gActionSelectionCursor",
    "BattleScript_CharacterBallBlock",
    "gTestMenuPtr",
    "CB2_StartWallClock",
    "Common_Eventscript_Gym_Leader_Falkner",
    "gBattleMons",
    "gBattleResults",
    "gMoveSelectionCursor",
    "gSelectionBattleScripts",
    "BattleScript_SelectingTormentedMove",
    "gBattlerControllerFuncs",
    # Struct-layout beacon (src/character_mode_selftest.c). Read it through
    # H.off.* rather than hardcoding any struct offset in a test.
    "gTestStructOffsets",
]

# static (file-local) symbols never reach the linker map; resolve them from
# the ELF with nm instead. Duplicate names get _2, _3... suffixes in
# address order.
LOCAL_SYMBOLS = [
    "HandleInputChooseAction",
    "HandleInputChooseMove",
]


def mailbox_requests():
    """CM_REQ_* name -> id, read straight from the enum in
    src/character_mode_selftest.c.

    The Lua side used to mirror these ids by hand, and the enum is POSITIONAL --
    so inserting a request in the middle silently renumbered every later one and
    a passing test carried on asking for something else entirely. That happened
    four times in one session. Deriving them removes the possibility.
    """
    src = os.path.join(TARGET, "src/character_mode_selftest.c")
    with open(src, encoding="utf-8", errors="replace") as f:
        text = f.read()
    m = re.search(r"enum\s*\{\s*CM_REQ_NONE = 0,(.*?)\};", text, re.S)
    if not m:
        raise SystemExit("gen_anchors: could not find the CM_REQ enum in %s" % src)
    names = re.findall(r"^\s*(CM_REQ_[A-Z0-9_]+),", m.group(1), re.M)
    if len(names) < 10:
        raise SystemExit("gen_anchors: parsed only %d mailbox requests -- the "
                         "enum shape changed and every test would send the "
                         "wrong id" % len(names))
    return [(n[len("CM_REQ_"):], i + 1) for i, n in enumerate(names)]


def main():
    with open(MAP, encoding="utf-8", errors="replace") as f:
        text = f.read()

    found = {}
    for sym in SYMBOLS:
        m = re.search(r"0x([0-9a-f]{8,16})\s+%s( |\n|\s*=)" % re.escape(sym), text)
        if m:
            found[sym] = int(m.group(1), 16) & 0xFFFFFFFF

    missing = [s for s in SYMBOLS if s not in found]
    if missing:
        raise SystemExit("symbols not in map: %s" % ", ".join(missing))

    if LOCAL_SYMBOLS:
        import subprocess
        elf = os.path.join(TARGET, "pokeemerald.elf")
        nm = subprocess.run(["arm-none-eabi-nm", elf], capture_output=True,
                            text=True, check=True).stdout
        for sym in LOCAL_SYMBOLS:
            addrs = sorted(int(m.group(1), 16) for m in re.finditer(
                r"^([0-9a-f]+) [tTdDbB] %s$" % re.escape(sym), nm, re.M))
            if not addrs:
                raise SystemExit("local symbol not in elf: %s" % sym)
            for i, a in enumerate(addrs):
                found[sym if i == 0 else "%s_%d" % (sym, i + 1)] = a
                SYMBOLS.append(sym if i == 0 else "%s_%d" % (sym, i + 1))

    reqs = mailbox_requests()

    digest = hashlib.sha1(text.encode("utf-8", "replace")).hexdigest()[:16]
    out = os.path.join(HERE, "anchors.lua")
    with open(out, "w") as f:
        f.write("-- GENERATED by gen_anchors.py from pokeemerald.map"
                " -- do not hand-edit.\n")
        f.write("return {\n")
        f.write('    mapDigest = "%s",\n' % digest)
        for sym in SYMBOLS:
            f.write("    %s = 0x%08X,\n" % (sym, found[sym]))
        f.write("    -- Mailbox request ids, derived from the enum in\n")
        f.write("    -- src/character_mode_selftest.c. Never hand-mirror these.\n")
        f.write("    REQ = {\n")
        for name, rid in reqs:
            f.write("        %s = %d,\n" % (name, rid))
        f.write("    },\n")
        f.write("}\n")
    print("wrote %s (%d symbols, %d mailbox requests, map digest %s)"
          % (out, len(found), len(reqs), digest))


if __name__ == "__main__":
    main()
