#!/usr/bin/env python3
"""Generate anchors.lua from pokeemerald.map.

ROWE is a source build, so unlike the Lazarus/Seaglass harnesses (which had to
reverse-engineer every RAM address) the exact addresses of every global come
straight from the linker map. Re-run after any build whose EWRAM/IWRAM layout
may have shifted (the harness scripts assert on a map checksum to catch a
stale anchors.lua).

Usage: python3 tools/mgba_scripts/gen_anchors.py
"""
import hashlib
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.abspath(os.path.join(HERE, "..", ".."))
MAP = os.path.join(TARGET, "pokeemerald.map")

SYMBOLS = [
    "gCharacterModeSelftestResult",
    "gCharacterModeTestMailbox",
    "gPlayerParty",
    "gPlayerPartyCount",
    "gEnemyParty",
    "gSaveBlock1Ptr",
    "gSaveBlock2Ptr",
    "gPokemonStoragePtr",
    "gCharacters",
    "gMain",
    "CB2_Overworld",
    "BattleMainCB2",
    "gBattleOutcome",
    "gBattlescriptCurrInstr",
    "gActionSelectionCursor",
    "BattleScript_CharacterBallBlock",
    "gTestMenuPtr",
    "CB2_StartWallClock",
    "Common_Eventscript_Gym_Leader_Falkner",
]


def main():
    with open(MAP, encoding="utf-8", errors="replace") as f:
        text = f.read()

    found = {}
    for sym in SYMBOLS:
        m = re.search(r"0x([0-9a-f]{8,16})\s+%s( |\n|\s*=)" % re.escape(sym), text)
        if m:
            found[sym] = int(m.group(1), 16) & 0xFFFFFFFF

    missing = [s for s in SYMBOLS if s not in found]
    if missing:
        raise SystemExit("symbols not in map: %s" % ", ".join(missing))

    digest = hashlib.sha1(text.encode("utf-8", "replace")).hexdigest()[:16]
    out = os.path.join(HERE, "anchors.lua")
    with open(out, "w") as f:
        f.write("-- GENERATED by gen_anchors.py from pokeemerald.map"
                " -- do not hand-edit.\n")
        f.write("return {\n")
        f.write('    mapDigest = "%s",\n' % digest)
        for sym in SYMBOLS:
            f.write("    %s = 0x%08X,\n" % (sym, found[sym]))
        f.write("}\n")
    print("wrote %s (%d symbols, map digest %s)" % (out, len(found), digest))


if __name__ == "__main__":
    main()
