-- Pokemon ROWE Character Mode -- headless mGBA test harness.
--
-- Ported back from the Lazarus/Seaglass binary-hack harness, with the big
-- simplification a source build allows: every RAM anchor comes from the
-- linker map (anchors.lua, regenerated by gen_anchors.py) instead of from
-- reverse engineering. Deterministic frame-exact input replaces the old
-- xdotool/mgba-qt drive (which suffered dropped taps and host focus stealing
-- -- see CLAUDE.md's Testing section for that history).
--
-- Usage from a test script (run from the repo root):
--   local H = dofile("tools/mgba_scripts/harness.lua")
--   H.press(H.KEY.A, 4)
--   H.onFrame(function(f) ... end)
--   H.assertEq("thing", H.rd8(H.anchors.gPlayerPartyCount), 1)
--   H.finish()
--
-- Run (Seaglass's patched build; MGBA_HEADLESS_DEBUGGER=1 only for
-- breakpoint runs -- emulation single-steps while breakpoints are armed):
--   timeout 120 "../Character Hacks/Seaglass-Character-Mode/tools/mgba_src/build/mgba-headless" \
--     --script tools/mgba_scripts/<test>.lua pokeemerald.gba > /tmp/test.log 2>&1
--
-- Gotchas inherited from the sibling projects (do not relearn):
--   * H.finish() does NOT stop the emulator -- always run under `timeout`.
--   * Never pipe headless output through grep/head -- redirect to a file.
--   * Bulk-read RAM with emu:readRange, never per-byte loops.
--   * ~1800 fps headless: bound every wait with a frame check.

local H = {}

H.anchors = dofile("tools/mgba_scripts/anchors.lua")

-- GBA key bit indices (mgba include/mgba/internal/gba/input.h)
H.KEY = {
    A = 0, B = 1, SELECT = 2, START = 3,
    RIGHT = 4, LEFT = 5, UP = 6, DOWN = 7,
    R = 8, L = 9,
}

-- ------------------------------------------------------------------- plumbing

local frame = 0
local frameHooks = {}
local passes, failures = 0, {}

function H.log(msg)
    console:log("HARNESS " .. tostring(msg))
end

function H.frame() return frame end

function H.onFrame(fn)
    table.insert(frameHooks, fn)
end

-- ------------------------------------------------------- struct offsets
--
-- NEVER hardcode a struct offset in a test. `gTestStructOffsets`
-- (src/character_mode_selftest.c) is a compiler-generated table of offsetof()
-- values, so these track the build.
--
-- This exists because the hardcoded ones DID drift, silently:
-- POKEMON_NAME_LENGTH 10 -> 12 grew playerMon1Name inside struct BattleResults,
-- moving battleTurnCounter 0x13 -> 0x15 and lastUsedMovePlayer 0x22 -> 0x26.
-- gigaton_reselect_e2e went on reading the old addresses, saw a turn counter
-- frozen at 0 and a last-move frozen at 0, and reported a WORKING feature as
-- broken -- which was then written up as a release-blocking red suite.
-- Order must match the C array.

H.off = {}

do
    local base = H.anchors.gTestStructOffsets
    local names = {
        "battleResults_turnCounter",
        "battleResults_lastUsedMovePlayer",
        "battleMon_size",
        "battleMon_hp",
        "battleMon_maxHP",
        "battleMon_moves",
        "battleMon_nickname",
        "battleMon_otName",
    }
    if base then
        for i, n in ipairs(names) do
            H.off[n] = emu:read16(base + (i - 1) * 2)
        end
    end
end

-- ------------------------------------------------------------------- memory

function H.rd8(a)  return emu:read8(a)  end
function H.rd16(a) return emu:read16(a) end
function H.rd32(a) return emu:read32(a) end
function H.wr8(a, v)  emu:write8(a, v)  end
function H.wr16(a, v) emu:write16(a, v) end
function H.wr32(a, v) emu:write32(a, v) end

function H.hex(v, width)
    return string.format("0x%0" .. (width or 8) .. "X", v)
end

-- ---------------------------------------------------------------- assertions

function H.assertEq(what, got, want)
    if got == want then
        passes = passes + 1
        H.log("PASS " .. what .. " = " .. tostring(got))
        return true
    end
    local msg = what .. ": got " .. tostring(got) .. ", want " .. tostring(want)
    table.insert(failures, msg)
    H.log("FAIL " .. msg)
    return false
end

function H.assertTrue(what, cond)
    return H.assertEq(what, cond and true or false, true)
end

function H.finish()
    H.log("---- SUMMARY ----")
    H.log(string.format("PASSED %d, FAILED %d", passes, #failures))
    for _, f in ipairs(failures) do
        H.log("  FAILURE: " .. f)
    end
    if #failures == 0 then
        H.log("RESULT: PASS")
    else
        H.log("RESULT: FAIL")
    end
end

-- --------------------------------------------------------------------- input
--
-- Frame-exact scripted pad input (replaces xdotool keypresses).

local pending = {}
local active = nil
local activeUntil = 0

-- Hold `key` for `frames` (default 4), release, wait `gap` (default 6).
function H.press(key, frames, gap)
    table.insert(pending, { key = key, frames = frames or 4, gap = gap or 6 })
end

function H.sequence(steps)
    for _, s in ipairs(steps) do
        H.press(s[1] or s.key, s[2] or s.frames, s[3] or s.gap)
    end
end

-- Alternate press/release of `key` every `every` frames in [fromFrame, toFrame]
-- (dialogue of unknown length).
function H.mash(key, fromFrame, toFrame, every)
    every = every or 20
    local held = false
    H.onFrame(function(f)
        if f >= fromFrame and f <= toFrame and (f % every) == 0 then
            if held then emu:clearKey(key) else emu:addKey(key) end
            held = not held
        elseif f == toFrame + 1 and held then
            emu:clearKey(key)
            held = false
        end
    end)
end

local function pumpInput()
    if active then
        if frame >= activeUntil then
            emu:clearKey(active.key)
            activeUntil = frame + active.gap
            active = nil
        end
        return
    end
    if frame < activeUntil then return end
    local step = table.remove(pending, 1)
    if step then
        emu:addKey(step.key)
        active = step
        activeUntil = frame + step.frames
    end
end

-- --------------------------------------------------------------- breakpoints
--
-- REQUIRES MGBA_HEADLESS_DEBUGGER=1 (the Seaglass headless patch): stock
-- headless never creates core->debugger, so setBreakpoint returns -1 and
-- silently never fires. Single-steps while armed -- arm late, detach early.

function H.breakpoint(name, addr, fn)
    local id = emu:setBreakpoint(function()
        local pc = emu:readRegister("pc")
        H.log(string.format("BP %-16s frame=%-5d pc=%s r0=%s r1=%s",
            name, frame, H.hex(pc), H.hex(emu:readRegister("r0")),
            H.hex(emu:readRegister("r1"))))
        if fn then fn(frame) end
    end, addr)
    if not id or id < 0 then
        error("H.breakpoint('" .. name .. "') failed to register (id=" ..
            tostring(id) .. ") -- run with MGBA_HEADLESS_DEBUGGER=1")
    end
    return id
end

-- -------------------------------------------------------------------- driver

callbacks:add("frame", function()
    frame = frame + 1
    pumpInput()
    for _, fn in ipairs(frameHooks) do
        fn(frame)
    end
end)

return H
