// Character Mode roster/appearance table.
// GENERATED by tools/character_mode/emit_characters.py - do not hand-edit.
// Sources: Bulbapedia (rosters), in-ROM assets (sprites).

static const u16 sRoster_Red[] =
{
    SPECIES_ARTICUNO,
    SPECIES_BULBASAUR,
    SPECIES_CATERPIE,
    SPECIES_CHARMANDER,
    SPECIES_CHIKORITA,
    SPECIES_CYNDAQUIL,
    SPECIES_DEOXYS,
    SPECIES_DRATINI,
    SPECIES_EEVEE,
    SPECIES_ENTEI,
    SPECIES_GROWLITHE,
    SPECIES_LAPRAS,
    SPECIES_LARVESTA,
    SPECIES_MACHOP,
    SPECIES_MUNCHLAX,
    SPECIES_NOIBAT,
    SPECIES_NOSEPASS,
    SPECIES_PICHU,
    SPECIES_RAIKOU,
    SPECIES_REGIGIGAS,
    SPECIES_SCYTHER,
    SPECIES_SLAKOTH,
    SPECIES_SQUIRTLE,
    SPECIES_SUICUNE,
    SPECIES_TAUROS,
    SPECIES_TOTODILE,
    SPECIES_WAILMER,
    SPECIES_WOOPER,
    SPECIES_NONE,
};

static const u8 sName_Red[] = _("Red");

static const u16 sRoster_Leaf[] =
{
    SPECIES_BULBASAUR,
    SPECIES_CHARMANDER,
    SPECIES_CLEFFA,
    SPECIES_EEVEE,
    SPECIES_GROUDON,
    SPECIES_MOLTRES,
    SPECIES_PICHU,
    SPECIES_SQUIRTLE,
    SPECIES_NONE,
};

static const u8 sName_Leaf[] = _("Leaf");

static const u16 sRoster_Ethan[] =
{
    SPECIES_AZURILL,
    SPECIES_CYNDAQUIL,
    SPECIES_HO_OH,
    SPECIES_LUGIA,
    SPECIES_PHANPY,
    SPECIES_RAIKOU,
    SPECIES_RATTATA,
    SPECIES_NONE,
};

static const u8 sName_Ethan[] = _("Ethan");

static const u16 sRoster_Kris[] =
{
    SPECIES_BONSLY,
    SPECIES_CHIKORITA,
    SPECIES_CYNDAQUIL,
    SPECIES_EEVEE,
    SPECIES_ENTEI,
    SPECIES_FARFETCHD,
    SPECIES_HO_OH,
    SPECIES_IGGLYBUFF,
    SPECIES_MAGIKARP,
    SPECIES_MAREEP,
    SPECIES_MUNCHLAX,
    SPECIES_RAIKOU,
    SPECIES_SLOWPOKE,
    SPECIES_SUICUNE,
    SPECIES_TOTODILE,
    SPECIES_VOLTORB,
    SPECIES_NONE,
};

static const u8 sName_Kris[] = _("Kris");

static const u16 sRoster_Lyra[] =
{
    SPECIES_AZURILL,
    SPECIES_CELEBI,
    SPECIES_CHIKORITA,
    SPECIES_EEVEE,
    SPECIES_ENTEI,
    SPECIES_IGGLYBUFF,
    SPECIES_PHANPY,
    SPECIES_RATTATA,
    SPECIES_SENTRET,
    SPECIES_NONE,
};

static const u8 sName_Lyra[] = _("Lyra");

static const u16 sRoster_Brendan[] =
{
    SPECIES_ARON,
    SPECIES_BAGON,
    SPECIES_BALTOY,
    SPECIES_ELECTRIKE,
    SPECIES_GROUDON,
    SPECIES_LARVITAR,
    SPECIES_LATIAS,
    SPECIES_LATIOS,
    SPECIES_LOTAD,
    SPECIES_MAGBY,
    SPECIES_MUDKIP,
    SPECIES_NUMEL,
    SPECIES_PICHU,
    SPECIES_RHYHORN,
    SPECIES_SEEDOT,
    SPECIES_SHROOMISH,
    SPECIES_SLUGMA,
    SPECIES_SOLROCK,
    SPECIES_TAILLOW,
    SPECIES_TORCHIC,
    SPECIES_TREECKO,
    SPECIES_TROPIUS,
    SPECIES_WAILMER,
    SPECIES_WHISMUR,
    SPECIES_WINGULL,
    SPECIES_ZIGZAGOON,
    SPECIES_NONE,
};

static const u8 sName_Brendan[] = _("Brendan");

static const u16 sRoster_May[] =
{
    SPECIES_ARON,
    SPECIES_AUDINO,
    SPECIES_BAGON,
    SPECIES_BALTOY,
    SPECIES_BUNEARY,
    SPECIES_KYOGRE,
    SPECIES_LATIAS,
    SPECIES_LATIOS,
    SPECIES_LOTAD,
    SPECIES_MUDKIP,
    SPECIES_NOSEPASS,
    SPECIES_NUMEL,
    SPECIES_PICHU,
    SPECIES_RAYQUAZA,
    SPECIES_SHROOMISH,
    SPECIES_SLUGMA,
    SPECIES_SWABLU,
    SPECIES_TAILLOW,
    SPECIES_TORCHIC,
    SPECIES_TORKOAL,
    SPECIES_TREECKO,
    SPECIES_TROPIUS,
    SPECIES_WAILMER,
    SPECIES_WHISMUR,
    SPECIES_WINGULL,
    SPECIES_WURMPLE,
    SPECIES_NONE,
};

static const u8 sName_May[] = _("May");

static const u16 sRoster_Lucas[] =
{
    SPECIES_ABRA,
    SPECIES_ABSOL,
    SPECIES_BIDOOF,
    SPECIES_BURMY,
    SPECIES_CHIMCHAR,
    SPECIES_CLEFFA,
    SPECIES_CRANIDOS,
    SPECIES_DIALGA,
    SPECIES_DUNSPARCE,
    SPECIES_DUSKULL,
    SPECIES_EEVEE,
    SPECIES_FEEBAS,
    SPECIES_GLAMEOW,
    SPECIES_GLIGAR,
    SPECIES_KABUTO,
    SPECIES_LILEEP,
    SPECIES_MAGBY,
    SPECIES_PALKIA,
    SPECIES_PIPLUP,
    SPECIES_PORYGON,
    SPECIES_RALTS,
    SPECIES_RHYHORN,
    SPECIES_ROTOM,
    SPECIES_STARLY,
    SPECIES_TANGELA,
    SPECIES_TAUROS,
    SPECIES_TURTWIG,
    SPECIES_NONE,
};

static const u8 sName_Lucas[] = _("Lucas");

static const u16 sRoster_Dawn[] =
{
    SPECIES_ABRA,
    SPECIES_AIPOM,
    SPECIES_BIDOOF,
    SPECIES_BUNEARY,
    SPECIES_BURMY,
    SPECIES_CHIMCHAR,
    SPECIES_CLAMPERL,
    SPECIES_CLEFFA,
    SPECIES_CRESSELIA,
    SPECIES_CYNDAQUIL,
    SPECIES_DIALGA,
    SPECIES_FEEBAS,
    SPECIES_GROWLITHE,
    SPECIES_LICKITUNG,
    SPECIES_MAGBY,
    SPECIES_MILCERY,
    SPECIES_MIMEJR,
    SPECIES_MURKROW,
    SPECIES_ODDISH,
    SPECIES_ORICORIO,
    SPECIES_PALKIA,
    SPECIES_PIPLUP,
    SPECIES_SNORUNT,
    SPECIES_SQUIRTLE,
    SPECIES_STARLY,
    SPECIES_SWINUB,
    SPECIES_TANGELA,
    SPECIES_TOGEPI,
    SPECIES_TREECKO,
    SPECIES_TURTWIG,
    SPECIES_ZUBAT,
    SPECIES_NONE,
};

static const u8 sName_Dawn[] = _("Dawn");

static const u16 sRoster_Hilbert[] =
{
    SPECIES_EEVEE,
    SPECIES_GENESECT,
    SPECIES_KYUREM,
    SPECIES_OSHAWOTT,
    SPECIES_POOCHYENA,
    SPECIES_RESHIRAM,
    SPECIES_THUNDURUS,
    SPECIES_ZEKROM,
    SPECIES_NONE,
};

static const u8 sName_Hilbert[] = _("Hilbert");

static const u16 sRoster_Hilda[] =
{
    SPECIES_CLOBBOPUS,
    SPECIES_DIANCIE,
    SPECIES_EEVEE,
    SPECIES_IRON_LEAVES,
    SPECIES_MIENFOO,
    SPECIES_RESHIRAM,
    SPECIES_TEPIG,
    SPECIES_TORNADUS,
    SPECIES_VICTINI,
    SPECIES_ZEKROM,
    SPECIES_NONE,
};

static const u8 sName_Hilda[] = _("Hilda");

static const u16 sRoster_Nate[] =
{
    SPECIES_AXEW,
    SPECIES_GROWLITHE,
    SPECIES_OSHAWOTT,
    SPECIES_PANPOUR,
    SPECIES_PANSAGE,
    SPECIES_PANSEAR,
    SPECIES_RIOLU,
    SPECIES_RUFFLET,
    SPECIES_SEVIPER,
    SPECIES_SNIVY,
    SPECIES_TEPIG,
    SPECIES_NONE,
};

static const u8 sName_Nate[] = _("Nate");

static const u16 sRoster_Rosa[] =
{
    SPECIES_DEERLING,
    SPECIES_DELIBIRD,
    SPECIES_LILLIPUP,
    SPECIES_MELOETTA,
    SPECIES_OSHAWOTT,
    SPECIES_PANPOUR,
    SPECIES_PANSAGE,
    SPECIES_PANSEAR,
    SPECIES_SHAYMIN,
    SPECIES_SNIVY,
    SPECIES_TEPIG,
    SPECIES_NONE,
};

static const u8 sName_Rosa[] = _("Rosa");

static const u16 sRoster_Calem[] =
{
    SPECIES_CHARMANDER,
    SPECIES_CHESPIN,
    SPECIES_EEVEE,
    SPECIES_ESPURR,
    SPECIES_FENNEKIN,
    SPECIES_FROAKIE,
    SPECIES_GOLETT,
    SPECIES_XERNEAS,
    SPECIES_YVELTAL,
    SPECIES_NONE,
};

static const u8 sName_Calem[] = _("Calem");

static const u16 sRoster_Serena[] =
{
    SPECIES_ABSOL,
    SPECIES_BUNNELBY,
    SPECIES_CHESPIN,
    SPECIES_CLEFFA,
    SPECIES_COTTONEE,
    SPECIES_EEVEE,
    SPECIES_ESPURR,
    SPECIES_FENNEKIN,
    SPECIES_FLETCHLING,
    SPECIES_FROAKIE,
    SPECIES_RHYHORN,
    SPECIES_SWABLU,
    SPECIES_XERNEAS,
    SPECIES_YVELTAL,
    SPECIES_ZYGARDE,
    SPECIES_NONE,
};

static const u8 sName_Serena[] = _("Serena");

static const u16 sRoster_Elio[] =
{
    SPECIES_BLACEPHALON,
    SPECIES_COSMOG,
    SPECIES_EEVEE,
    SPECIES_EXEGGCUTE,
    SPECIES_FROAKIE,
    SPECIES_JANGMO_O,
    SPECIES_LITTEN,
    SPECIES_NECROZMA,
    SPECIES_NIHILEGO,
    SPECIES_PICHU,
    SPECIES_POPPLIO,
    SPECIES_ROCKRUFF,
    SPECIES_ROTOM,
    SPECIES_ROWLET,
    SPECIES_SPEAROW,
    SPECIES_STAKATAKA,
    SPECIES_TAPU_KOKO,
    SPECIES_TYPE_NULL,
    SPECIES_YUNGOOS,
    SPECIES_NONE,
};

static const u8 sName_Elio[] = _("Elio");

static const u16 sRoster_Selene[] =
{
    SPECIES_BLACEPHALON,
    SPECIES_COSMOG,
    SPECIES_EEVEE,
    SPECIES_EXEGGCUTE,
    SPECIES_LITTEN,
    SPECIES_NECROZMA,
    SPECIES_NIHILEGO,
    SPECIES_PINSIR,
    SPECIES_POPPLIO,
    SPECIES_ROTOM,
    SPECIES_ROWLET,
    SPECIES_SCYTHER,
    SPECIES_SPEAROW,
    SPECIES_STAKATAKA,
    SPECIES_TAPU_KOKO,
    SPECIES_TYPE_NULL,
    SPECIES_YUNGOOS,
    SPECIES_NONE,
};

static const u8 sName_Selene[] = _("Selene");

static const u16 sRoster_Victor[] =
{
    SPECIES_ETERNATUS,
    SPECIES_FARFETCHD_GALARIAN,
    SPECIES_GROOKEY,
    SPECIES_SKWOVET,
    SPECIES_SOBBLE,
    SPECIES_SPECTRIER,
    SPECIES_ZACIAN,
    SPECIES_ZAMAZENTA,
    SPECIES_NONE,
};

static const u8 sName_Victor[] = _("Victor");

static const u16 sRoster_Gloria[] =
{
    SPECIES_GROOKEY,
    SPECIES_KUBFU,
    SPECIES_SCORBUNNY,
    SPECIES_SOBBLE,
    SPECIES_ZACIAN,
    SPECIES_NONE,
};

static const u8 sName_Gloria[] = _("Gloria");

static const u16 sRoster_Blue[] =
{
    SPECIES_ABRA,
    SPECIES_AERODACTYL,
    SPECIES_BULBASAUR,
    SPECIES_CHARMANDER,
    SPECIES_CLEFFA,
    SPECIES_DRATINI,
    SPECIES_EEVEE,
    SPECIES_EKANS,
    SPECIES_ELEKID,
    SPECIES_EXEGGCUTE,
    SPECIES_GASTLY,
    SPECIES_GROWLITHE,
    SPECIES_HERACROSS,
    SPECIES_HORSEA,
    SPECIES_HOUNDOUR,
    SPECIES_LAPRAS,
    SPECIES_LARVITAR,
    SPECIES_MACHOP,
    SPECIES_MAGIKARP,
    SPECIES_MAGNEMITE,
    SPECIES_MILTANK,
    SPECIES_PICHU,
    SPECIES_PIDGEY,
    SPECIES_PINSIR,
    SPECIES_RHYHORN,
    SPECIES_SANDSHREW,
    SPECIES_SCYTHER,
    SPECIES_SHELLDER,
    SPECIES_SLOWPOKE,
    SPECIES_SQUIRTLE,
    SPECIES_SWINUB,
    SPECIES_TAUROS,
    SPECIES_TOTODILE,
    SPECIES_VULPIX,
    SPECIES_ZAPDOS,
    SPECIES_NONE,
};

static const u8 sName_Blue[] = _("Blue");

static const u16 sRoster_Lance[] =
{
    SPECIES_AERODACTYL,
    SPECIES_ARCEUS,
    SPECIES_AXEW,
    SPECIES_BAGON,
    SPECIES_CHARMANDER,
    SPECIES_CLEFFA,
    SPECIES_DEINO,
    SPECIES_DRATINI,
    SPECIES_ELEKID,
    SPECIES_ENTEI,
    SPECIES_EXEGGCUTE,
    SPECIES_GIBLE,
    SPECIES_GROWLITHE,
    SPECIES_HORSEA,
    SPECIES_KANGASKHAN,
    SPECIES_LAPRAS,
    SPECIES_LARVITAR,
    SPECIES_LUGIA,
    SPECIES_MAGIKARP,
    SPECIES_MUNCHLAX,
    SPECIES_ONIX,
    SPECIES_RAIKOU,
    SPECIES_RHYHORN,
    SPECIES_SNEASEL,
    SPECIES_SQUIRTLE,
    SPECIES_SUICUNE,
    SPECIES_SWABLU,
    SPECIES_TOTODILE,
    SPECIES_TRAPINCH,
    SPECIES_NONE,
};

static const u8 sName_Lance[] = _("Lance");

static const u16 sRoster_Steven[] =
{
    SPECIES_AERODACTYL,
    SPECIES_ANORITH,
    SPECIES_ARCHEN,
    SPECIES_ARON,
    SPECIES_BALTOY,
    SPECIES_BELDUM,
    SPECIES_CARBINK,
    SPECIES_DEOXYS,
    SPECIES_DIANCIE,
    SPECIES_DRILBUR,
    SPECIES_HOOPA,
    SPECIES_LILEEP,
    SPECIES_LILLIPUP,
    SPECIES_MAWILE,
    SPECIES_MUDKIP,
    SPECIES_PINECO,
    SPECIES_RAYQUAZA,
    SPECIES_REGICE,
    SPECIES_REGIROCK,
    SPECIES_REGISTEEL,
    SPECIES_RELICANTH,
    SPECIES_SANDSHREW,
    SPECIES_SKARMORY,
    SPECIES_TORCHIC,
    SPECIES_TREECKO,
    SPECIES_WAILMER,
    SPECIES_NONE,
};

static const u8 sName_Steven[] = _("Steven");

static const u16 sRoster_Iris[] =
{
    SPECIES_ARCHEN,
    SPECIES_ARON,
    SPECIES_AXEW,
    SPECIES_BAGON,
    SPECIES_CRYOGONAL,
    SPECIES_DEINO,
    SPECIES_DRUDDIGON,
    SPECIES_JOLTIK,
    SPECIES_LAPRAS,
    SPECIES_POIPOLE,
    SPECIES_RUFFLET,
    SPECIES_TIRTOUGA,
    SPECIES_NONE,
};

static const u8 sName_Iris[] = _("Iris");

static const u16 sRoster_Kukui[] =
{
    SPECIES_BRUXISH,
    SPECIES_CELESTEELA,
    SPECIES_COSMOG,
    SPECIES_DRAMPA,
    SPECIES_FOMANTIS,
    SPECIES_GRUBBIN,
    SPECIES_GUZZLORD,
    SPECIES_LITTEN,
    SPECIES_MAGNEMITE,
    SPECIES_MUNCHLAX,
    SPECIES_PICHU,
    SPECIES_PIKIPEK,
    SPECIES_POPPLIO,
    SPECIES_ROCKRUFF,
    SPECIES_ROTOM,
    SPECIES_ROWLET,
    SPECIES_RUFFLET,
    SPECIES_TAPU_BULU,
    SPECIES_TAPU_KOKO,
    SPECIES_TYPE_NULL,
    SPECIES_VULPIX,
    SPECIES_NONE,
};

static const u8 sName_Kukui[] = _("Kukui");

static const u16 sRoster_Koga[] =
{
    SPECIES_ARTICUNO,
    SPECIES_CHARMANDER,
    SPECIES_CHINCHOU,
    SPECIES_CLEFFA,
    SPECIES_CROAGUNK,
    SPECIES_CUBONE,
    SPECIES_DITTO,
    SPECIES_DRATINI,
    SPECIES_DROWZEE,
    SPECIES_EKANS,
    SPECIES_GASTLY,
    SPECIES_GLIGAR,
    SPECIES_GRIMER,
    SPECIES_GULPIN,
    SPECIES_HAPPINY,
    SPECIES_KOFFING,
    SPECIES_LAPRAS,
    SPECIES_MAGBY,
    SPECIES_MOLTRES,
    SPECIES_NIDORAN_F,
    SPECIES_NIDORAN_M,
    SPECIES_PARAS,
    SPECIES_PICHU,
    SPECIES_PIDGEY,
    SPECIES_PINECO,
    SPECIES_PSYDUCK,
    SPECIES_RHYHORN,
    SPECIES_SCYTHER,
    SPECIES_SPINARAK,
    SPECIES_STANTLER,
    SPECIES_STUNKY,
    SPECIES_TANGELA,
    SPECIES_TENTACOOL,
    SPECIES_VENONAT,
    SPECIES_VOLTORB,
    SPECIES_VULPIX,
    SPECIES_ZAPDOS,
    SPECIES_ZUBAT,
    SPECIES_NONE,
};

static const u8 sName_Koga[] = _("Koga");

static const u16 sRoster_Flint[] =
{
    SPECIES_BUIZEL,
    SPECIES_BUNEARY,
    SPECIES_CHARMANDER,
    SPECIES_CHIMCHAR,
    SPECIES_DRIFLOON,
    SPECIES_EEVEE,
    SPECIES_ELEKID,
    SPECIES_GIBLE,
    SPECIES_GROWLITHE,
    SPECIES_HOUNDOUR,
    SPECIES_MAGBY,
    SPECIES_MISDREAVUS,
    SPECIES_ONIX,
    SPECIES_PICHU,
    SPECIES_PIPLUP,
    SPECIES_PONYTA,
    SPECIES_REGIGIGAS,
    SPECIES_SHINX,
    SPECIES_VULPIX,
    SPECIES_NONE,
};

static const u8 sName_Flint[] = _("Flint");

static const u16 sRoster_Brock[] =
{
    SPECIES_AERODACTYL,
    SPECIES_BONSLY,
    SPECIES_CATERPIE,
    SPECIES_CHARMANDER,
    SPECIES_CLEFFA,
    SPECIES_CRANIDOS,
    SPECIES_CROAGUNK,
    SPECIES_CUBONE,
    SPECIES_DIGLETT,
    SPECIES_GASTLY,
    SPECIES_GEODUDE,
    SPECIES_HERACROSS,
    SPECIES_KABUTO,
    SPECIES_LARVITAR,
    SPECIES_MACHOP,
    SPECIES_MAREEP,
    SPECIES_MUNCHLAX,
    SPECIES_NIDORAN_M,
    SPECIES_OMANYTE,
    SPECIES_ONIX,
    SPECIES_PICHU,
    SPECIES_PINECO,
    SPECIES_PINSIR,
    SPECIES_RATTATA,
    SPECIES_RELICANTH,
    SPECIES_RHYHORN,
    SPECIES_SHUCKLE,
    SPECIES_SLOWPOKE,
    SPECIES_SPEAROW,
    SPECIES_SUICUNE,
    SPECIES_TEDDIURSA,
    SPECIES_VULPIX,
    SPECIES_ZUBAT,
    SPECIES_NONE,
};

static const u8 sName_Brock[] = _("Brock");

static const u16 sRoster_Misty[] =
{
    SPECIES_BUIZEL,
    SPECIES_CHARMANDER,
    SPECIES_CHINCHOU,
    SPECIES_CLEFFA,
    SPECIES_DIGLETT,
    SPECIES_DRATINI,
    SPECIES_DUCKLETT,
    SPECIES_EEVEE,
    SPECIES_EXEGGCUTE,
    SPECIES_FEEBAS,
    SPECIES_FRILLISH,
    SPECIES_GEODUDE,
    SPECIES_GOLDEEN,
    SPECIES_HORSEA,
    SPECIES_IGGLYBUFF,
    SPECIES_LAPRAS,
    SPECIES_MAGIKARP,
    SPECIES_MAREEP,
    SPECIES_MILTANK,
    SPECIES_NIDORAN_F,
    SPECIES_OMANYTE,
    SPECIES_POLIWAG,
    SPECIES_PSYDUCK,
    SPECIES_RHYHORN,
    SPECIES_SEEL,
    SPECIES_SHELLDER,
    SPECIES_SLOWPOKE,
    SPECIES_SQUIRTLE,
    SPECIES_STARYU,
    SPECIES_SUICUNE,
    SPECIES_SUNKERN,
    SPECIES_TENTACOOL,
    SPECIES_TIRTOUGA,
    SPECIES_TOGEPI,
    SPECIES_WOOPER,
    SPECIES_NONE,
};

static const u8 sName_Misty[] = _("Misty");

static const u16 sRoster_LtSurge[] =
{
    SPECIES_ABRA,
    SPECIES_BELLSPROUT,
    SPECIES_CHARMANDER,
    SPECIES_CHINCHOU,
    SPECIES_CLEFFA,
    SPECIES_DODUO,
    SPECIES_EEVEE,
    SPECIES_ELECTRIKE,
    SPECIES_ELEKID,
    SPECIES_EXEGGCUTE,
    SPECIES_GASTLY,
    SPECIES_HORSEA,
    SPECIES_HOUNDOUR,
    SPECIES_KRABBY,
    SPECIES_LICKITUNG,
    SPECIES_MAGIKARP,
    SPECIES_MAGNEMITE,
    SPECIES_MAREEP,
    SPECIES_MISDREAVUS,
    SPECIES_ONIX,
    SPECIES_PACHIRISU,
    SPECIES_PICHU,
    SPECIES_POLIWAG,
    SPECIES_PORYGON,
    SPECIES_RAIKOU,
    SPECIES_SEEL,
    SPECIES_TANGELA,
    SPECIES_VOLTORB,
    SPECIES_WOOPER,
    SPECIES_ZAPDOS,
    SPECIES_NONE,
};

static const u8 sName_LtSurge[] = _("Lt. Surge");

static const u16 sRoster_Erika[] =
{
    SPECIES_BELLSPROUT,
    SPECIES_BUDEW,
    SPECIES_BULBASAUR,
    SPECIES_CHARMANDER,
    SPECIES_CLEFFA,
    SPECIES_COMFEY,
    SPECIES_COTTONEE,
    SPECIES_CUBONE,
    SPECIES_DROWZEE,
    SPECIES_EEVEE,
    SPECIES_EXEGGCUTE,
    SPECIES_FOMANTIS,
    SPECIES_GRIMER,
    SPECIES_HAPPINY,
    SPECIES_HOPPIP,
    SPECIES_LILEEP,
    SPECIES_MANTYKE,
    SPECIES_ODDISH,
    SPECIES_PARAS,
    SPECIES_PETILIL,
    SPECIES_PICHU,
    SPECIES_PINSIR,
    SPECIES_PORYGON,
    SPECIES_SEEDOT,
    SPECIES_SEEL,
    SPECIES_SHELLDER,
    SPECIES_SNOVER,
    SPECIES_SWINUB,
    SPECIES_TANGELA,
    SPECIES_VULPIX,
    SPECIES_NONE,
};

static const u8 sName_Erika[] = _("Erika");

static const u16 sRoster_Sabrina[] =
{
    SPECIES_ABRA,
    SPECIES_ARTICUNO,
    SPECIES_BELDUM,
    SPECIES_CHARMANDER,
    SPECIES_CHINGLING,
    SPECIES_CLEFFA,
    SPECIES_CYNDAQUIL,
    SPECIES_DROWZEE,
    SPECIES_EEVEE,
    SPECIES_EXEGGCUTE,
    SPECIES_GASTLY,
    SPECIES_HERACROSS,
    SPECIES_IGGLYBUFF,
    SPECIES_LAPRAS,
    SPECIES_MEWTWO,
    SPECIES_MIMEJR,
    SPECIES_MOLTRES,
    SPECIES_MUNCHLAX,
    SPECIES_ODDISH,
    SPECIES_PSYDUCK,
    SPECIES_RALTS,
    SPECIES_SANDSHREW,
    SPECIES_SCYTHER,
    SPECIES_SENTRET,
    SPECIES_SHELLDER,
    SPECIES_SIGILYPH,
    SPECIES_SLOWPOKE,
    SPECIES_SMOOCHUM,
    SPECIES_TYROGUE,
    SPECIES_VENONAT,
    SPECIES_WOOBAT,
    SPECIES_WYNAUT,
    SPECIES_ZAPDOS,
    SPECIES_NONE,
};

static const u8 sName_Sabrina[] = _("Sabrina");

static const u16 sRoster_CrasherWake[] =
{
    SPECIES_BUIZEL,
    SPECIES_CARVANHA,
    SPECIES_CLAMPERL,
    SPECIES_FINNEON,
    SPECIES_HORSEA,
    SPECIES_LOTAD,
    SPECIES_MAGIKARP,
    SPECIES_PICHU,
    SPECIES_PIPLUP,
    SPECIES_POLIWAG,
    SPECIES_SHELLOS,
    SPECIES_TURTWIG,
    SPECIES_WOOPER,
    SPECIES_NONE,
};

static const u8 sName_CrasherWake[] = _("Crasher Wake");

static const u16 sRoster_Silver[] =
{
    SPECIES_ABRA,
    SPECIES_CHIKORITA,
    SPECIES_CYNDAQUIL,
    SPECIES_GASTLY,
    SPECIES_HO_OH,
    SPECIES_LARVITAR,
    SPECIES_LUGIA,
    SPECIES_MAGNEMITE,
    SPECIES_MEWTWO,
    SPECIES_NIDORAN_M,
    SPECIES_SNEASEL,
    SPECIES_SUICUNE,
    SPECIES_TOTODILE,
    SPECIES_ZUBAT,
    SPECIES_NONE,
};

static const u8 sName_Silver[] = _("Silver");

static const u16 sRoster_Wally[] =
{
    SPECIES_AZURILL,
    SPECIES_BUDEW,
    SPECIES_FLETCHLING,
    SPECIES_GIBLE,
    SPECIES_MAGNEMITE,
    SPECIES_RALTS,
    SPECIES_SKITTY,
    SPECIES_SWABLU,
    SPECIES_ZIGZAGOON,
    SPECIES_NONE,
};

static const u8 sName_Wally[] = _("Wally");

static const u16 sRoster_Barry[] =
{
    SPECIES_BUDEW,
    SPECIES_BUIZEL,
    SPECIES_CHIMCHAR,
    SPECIES_CRANIDOS,
    SPECIES_DRATINI,
    SPECIES_FEEBAS,
    SPECIES_HERACROSS,
    SPECIES_MUNCHLAX,
    SPECIES_PIPLUP,
    SPECIES_PONYTA,
    SPECIES_RHYHORN,
    SPECIES_STARLY,
    SPECIES_STUNKY,
    SPECIES_TURTWIG,
    SPECIES_NONE,
};

static const u8 sName_Barry[] = _("Barry");

static const u16 sRoster_Bianca[] =
{
    SPECIES_AUDINO,
    SPECIES_AXEW,
    SPECIES_HEATRAN,
    SPECIES_LILLIPUP,
    SPECIES_LITWICK,
    SPECIES_MIENFOO,
    SPECIES_MUNNA,
    SPECIES_OSHAWOTT,
    SPECIES_PANPOUR,
    SPECIES_PANSAGE,
    SPECIES_PANSEAR,
    SPECIES_PURRLOIN,
    SPECIES_SNIVY,
    SPECIES_TEPIG,
    SPECIES_TYNAMO,
    SPECIES_VIRIZION,
    SPECIES_NONE,
};

static const u8 sName_Bianca[] = _("Bianca");

static const u16 sRoster_Shauna[] =
{
    SPECIES_CHESPIN,
    SPECIES_EEVEE,
    SPECIES_FENNEKIN,
    SPECIES_FROAKIE,
    SPECIES_FURFROU,
    SPECIES_GOOMY,
    SPECIES_KLEFKI,
    SPECIES_SKITTY,
    SPECIES_NONE,
};

static const u8 sName_Shauna[] = _("Shauna");

static const u16 sRoster_Ash[] =
{
    SPECIES_BERGMITE,
    SPECIES_CHARMANDER,
    SPECIES_CHIMCHAR,
    SPECIES_CLOBBOPUS,
    SPECIES_COSMOG,
    SPECIES_DARKRAI,
    SPECIES_DRACOVISH,
    SPECIES_DRATINI,
    SPECIES_ETERNATUS,
    SPECIES_FARFETCHD_GALARIAN,
    SPECIES_FROAKIE,
    SPECIES_GASTLY,
    SPECIES_GIBLE,
    SPECIES_GOOMY,
    SPECIES_HOPPIP,
    SPECIES_LATIOS,
    SPECIES_LITTEN,
    SPECIES_LUGIA,
    SPECIES_MACHOP,
    SPECIES_MAGIKARP,
    SPECIES_MELTAN,
    SPECIES_MIMIKYU,
    SPECIES_MURKROW,
    SPECIES_ODDISH,
    SPECIES_PICHU,
    SPECIES_PIDOVE,
    SPECIES_RESHIRAM,
    SPECIES_RIOLU,
    SPECIES_ROCKRUFF,
    SPECIES_SCATTERBUG,
    SPECIES_SCRAGGY,
    SPECIES_STARLY,
    SPECIES_TAILLOW,
    SPECIES_TORCHIC,
    SPECIES_YUNGOOS,
    SPECIES_ZEKROM,
    SPECIES_ZYGARDE,
    SPECIES_NONE,
};

static const u8 sName_Ash[] = _("Ash");

static const u16 sRoster_MistyAnime[] =
{
    SPECIES_CATERPIE,
    SPECIES_CLAUNCHER,
    SPECIES_DRATINI,
    SPECIES_EKANS,
    SPECIES_FRILLISH,
    SPECIES_GOLDEEN,
    SPECIES_HATENNA,
    SPECIES_HOOTHOOT,
    SPECIES_HORSEA,
    SPECIES_KOFFING,
    SPECIES_LAPRAS,
    SPECIES_LATIOS,
    SPECIES_LICKITUNG,
    SPECIES_MAGIKARP,
    SPECIES_MANTYKE,
    SPECIES_MIMEJR,
    SPECIES_POLIWAG,
    SPECIES_PSYDUCK,
    SPECIES_SHELLDER,
    SPECIES_SHUPPET,
    SPECIES_SOBBLE,
    SPECIES_SPEAROW,
    SPECIES_STARYU,
    SPECIES_TENTACOOL,
    SPECIES_TOGEPI,
    SPECIES_WAILMER,
    SPECIES_YAMASK,
    SPECIES_NONE,
};

static const u8 sName_MistyAnime[] = _("Misty (A)");

static const u16 sRoster_BrockAnime[] =
{
    SPECIES_AIPOM,
    SPECIES_CHARMANDER,
    SPECIES_COMFEY,
    SPECIES_CROAGUNK,
    SPECIES_GEODUDE,
    SPECIES_HAPPINY,
    SPECIES_HATENNA,
    SPECIES_HOOTHOOT,
    SPECIES_KANGASKHAN,
    SPECIES_LOTAD,
    SPECIES_MAGIKARP,
    SPECIES_MAGNEMITE,
    SPECIES_MIMEJR,
    SPECIES_ODDISH,
    SPECIES_ONIX,
    SPECIES_PANSAGE,
    SPECIES_PICHU,
    SPECIES_ROCKRUFF,
    SPECIES_SEEDOT,
    SPECIES_STARLY,
    SPECIES_TAILLOW,
    SPECIES_TAUROS,
    SPECIES_TOTODILE,
    SPECIES_TURTONATOR,
    SPECIES_TURTWIG,
    SPECIES_VULPIX,
    SPECIES_WAILMER,
    SPECIES_YUNGOOS,
    SPECIES_NONE,
};

static const u8 sName_BrockAnime[] = _("Brock (A)");

static const u16 sRoster_MayAnime[] =
{
    SPECIES_EEVEE,
    SPECIES_LARVITAR,
    SPECIES_MUDKIP,
    SPECIES_MUNCHLAX,
    SPECIES_POOCHYENA,
    SPECIES_SKITTY,
    SPECIES_SQUIRTLE,
    SPECIES_SWABLU,
    SPECIES_TENTACOOL,
    SPECIES_TORCHIC,
    SPECIES_TYROGUE,
    SPECIES_WURMPLE,
    SPECIES_NONE,
};

static const u8 sName_MayAnime[] = _("May (A)");

static const u16 sRoster_DawnAnime[] =
{
    SPECIES_AIPOM,
    SPECIES_ARCEUS,
    SPECIES_BUNEARY,
    SPECIES_CARVANHA,
    SPECIES_CRESSELIA,
    SPECIES_DARKRAI,
    SPECIES_DIALGA,
    SPECIES_DODUO,
    SPECIES_DRATINI,
    SPECIES_EEVEE,
    SPECIES_FOONGUS,
    SPECIES_GEODUDE,
    SPECIES_GIBLE,
    SPECIES_GLAMEOW,
    SPECIES_GRIMER,
    SPECIES_HEATRAN,
    SPECIES_MINUN,
    SPECIES_OSHAWOTT,
    SPECIES_PACHIRISU,
    SPECIES_PALKIA,
    SPECIES_PANSAGE,
    SPECIES_PICHU,
    SPECIES_PIPLUP,
    SPECIES_PLUSLE,
    SPECIES_RALTS,
    SPECIES_RHYHORN,
    SPECIES_SPINARAK,
    SPECIES_SWINUB,
    SPECIES_TOGEPI,
    SPECIES_VENONAT,
    SPECIES_NONE,
};

static const u8 sName_DawnAnime[] = _("Dawn (A)");

static const u16 sRoster_SerenaAnime[] =
{
    SPECIES_BULBASAUR,
    SPECIES_BUNNELBY,
    SPECIES_CHESPIN,
    SPECIES_COMBEE,
    SPECIES_EEVEE,
    SPECIES_FENNEKIN,
    SPECIES_FLETCHLING,
    SPECIES_GASTLY,
    SPECIES_GIBLE,
    SPECIES_MAGNEMITE,
    SPECIES_PANCHAM,
    SPECIES_PICHU,
    SPECIES_RHYHORN,
    SPECIES_SHINX,
    SPECIES_SKIDDO,
    SPECIES_SNEASEL,
    SPECIES_SWINUB,
    SPECIES_VENIPEDE,
    SPECIES_NONE,
};

static const u8 sName_SerenaAnime[] = _("Serena (A)");

static const u16 sRoster_IrisAnime[] =
{
    SPECIES_AXEW,
    SPECIES_CUBCHOO,
    SPECIES_DEINO,
    SPECIES_DRATINI,
    SPECIES_DRILBUR,
    SPECIES_DRUDDIGON,
    SPECIES_EMOLGA,
    SPECIES_GIBLE,
    SPECIES_GOLETT,
    SPECIES_MINCCINO,
    SPECIES_PANSAGE,
    SPECIES_PATRAT,
    SPECIES_PICHU,
    SPECIES_RAYQUAZA,
    SPECIES_SAWK,
    SPECIES_SNIVY,
    SPECIES_SWABLU,
    SPECIES_VANILLITE,
    SPECIES_VENIPEDE,
    SPECIES_VIRIZION,
    SPECIES_WOOBAT,
    SPECIES_YAMASK,
    SPECIES_NONE,
};

static const u8 sName_IrisAnime[] = _("Iris (A)");

static const u16 sRoster_CilanAnime[] =
{
    SPECIES_AIPOM,
    SPECIES_AXEW,
    SPECIES_BASCULIN,
    SPECIES_BUIZEL,
    SPECIES_CHESPIN,
    SPECIES_CORPHISH,
    SPECIES_DWEBBLE,
    SPECIES_FOONGUS,
    SPECIES_FRILLISH,
    SPECIES_HATENNA,
    SPECIES_LARVESTA,
    SPECIES_MAGIKARP,
    SPECIES_OSHAWOTT,
    SPECIES_PANSAGE,
    SPECIES_PANSEAR,
    SPECIES_PIPLUP,
    SPECIES_PURRLOIN,
    SPECIES_SNIVY,
    SPECIES_SNOVER,
    SPECIES_STUNFISK,
    SPECIES_TERRAKION,
    SPECIES_TIMBURR,
    SPECIES_TYNAMO,
    SPECIES_NONE,
};

static const u8 sName_CilanAnime[] = _("Cilan (A)");

static const u16 sRoster_ClemontAnime[] =
{
    SPECIES_BUNNELBY,
    SPECIES_CHESPIN,
    SPECIES_DEDENNE,
    SPECIES_DRACOVISH,
    SPECIES_FARFETCHD_GALARIAN,
    SPECIES_FENNEKIN,
    SPECIES_GASTLY,
    SPECIES_GIBLE,
    SPECIES_HELIOPTILE,
    SPECIES_INKAY,
    SPECIES_PANCHAM,
    SPECIES_PANSAGE,
    SPECIES_PUMPKABOO,
    SPECIES_SCATTERBUG,
    SPECIES_SHINX,
    SPECIES_SKIDDO,
    SPECIES_SWINUB,
    SPECIES_TORCHIC,
    SPECIES_TYNAMO,
    SPECIES_VENIPEDE,
    SPECIES_WEEDLE,
    SPECIES_ZAPDOS,
    SPECIES_ZYGARDE,
    SPECIES_NONE,
};

static const u8 sName_ClemontAnime[] = _("Clemont (A)");

static const u16 sRoster_LillieAnime[] =
{
    SPECIES_BOUNSWEET,
    SPECIES_CATERPIE,
    SPECIES_CLEFFA,
    SPECIES_COSMOG,
    SPECIES_EEVEE,
    SPECIES_GEODUDE,
    SPECIES_GRUBBIN,
    SPECIES_JANGMO_O,
    SPECIES_LAPRAS,
    SPECIES_LARVITAR,
    SPECIES_LILLIPUP,
    SPECIES_MAGEARNA,
    SPECIES_MANTYKE,
    SPECIES_MAREANIE,
    SPECIES_MUDBRAY,
    SPECIES_MUNCHLAX,
    SPECIES_NECROZMA,
    SPECIES_NIHILEGO,
    SPECIES_ORICORIO,
    SPECIES_PICHU,
    SPECIES_ROCKRUFF,
    SPECIES_SALANDIT,
    SPECIES_SANDSHREW,
    SPECIES_SWABLU,
    SPECIES_TAUROS,
    SPECIES_TYPE_NULL,
    SPECIES_VULPIX,
    SPECIES_ZORUA,
    SPECIES_NONE,
};

static const u8 sName_LillieAnime[] = _("Lillie (A)");

static const u16 sRoster_KiaweAnime[] =
{
    SPECIES_CHARMANDER,
    SPECIES_CORPHISH,
    SPECIES_COSMOG,
    SPECIES_CUBONE,
    SPECIES_ELEKID,
    SPECIES_GASTLY,
    SPECIES_GRUBBIN,
    SPECIES_LILLIPUP,
    SPECIES_MANTYKE,
    SPECIES_NECROZMA,
    SPECIES_ONIX,
    SPECIES_POPPLIO,
    SPECIES_ROCKRUFF,
    SPECIES_SALANDIT,
    SPECIES_SCORBUNNY,
    SPECIES_TAUROS,
    SPECIES_TURTONATOR,
    SPECIES_TYPE_NULL,
    SPECIES_WAILMER,
    SPECIES_YUNGOOS,
    SPECIES_ZUBAT,
    SPECIES_NONE,
};

static const u8 sName_KiaweAnime[] = _("Kiawe (A)");

static const u16 sRoster_LanaAnime[] =
{
    SPECIES_BLACEPHALON,
    SPECIES_BOUNSWEET,
    SPECIES_COSMOG,
    SPECIES_DEWPIDER,
    SPECIES_DHELMISE,
    SPECIES_DRAMPA,
    SPECIES_DRATINI,
    SPECIES_EEVEE,
    SPECIES_FEEBAS,
    SPECIES_KYOGRE,
    SPECIES_LAPRAS,
    SPECIES_LILLIPUP,
    SPECIES_LITTEN,
    SPECIES_MANAPHY,
    SPECIES_MANTYKE,
    SPECIES_MINIOR,
    SPECIES_MISDREAVUS,
    SPECIES_MUNCHLAX,
    SPECIES_NECROZMA,
    SPECIES_NIHILEGO,
    SPECIES_PETILIL,
    SPECIES_POPPLIO,
    SPECIES_SURSKIT,
    SPECIES_TAUROS,
    SPECIES_TOGEDEMARU,
    SPECIES_TRUBBISH,
    SPECIES_TURTONATOR,
    SPECIES_WAILMER,
    SPECIES_WIMPOD,
    SPECIES_WISHIWASHI,
    SPECIES_XURKITREE,
    SPECIES_NONE,
};

static const u8 sName_LanaAnime[] = _("Lana (A)");

const struct CharacterInfo gCharacters[] =
{
    {
        .name = sName_Red,
        .roster = sRoster_Red,
        .owGfxId = OBJ_EVENT_GFX_RED_NORMAL,
        .trainerFrontPic = TRAINER_PIC_RED,
        .backPic = TRAINER_BACK_PIC_RED,
    },
    {
        .name = sName_Leaf,
        .roster = sRoster_Leaf,
        .owGfxId = OBJ_EVENT_GFX_LEAF_NORMAL,
        .trainerFrontPic = TRAINER_PIC_LEAF,
        .backPic = TRAINER_BACK_PIC_LEAF,
    },
    {
        .name = sName_Ethan,
        .roster = sRoster_Ethan,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Kris,
        .roster = sRoster_Kris,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Lyra,
        .roster = sRoster_Lyra,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Brendan,
        .roster = sRoster_Brendan,
        .owGfxId = OBJ_EVENT_GFX_BRENDAN_NORMAL,
        .trainerFrontPic = TRAINER_PIC_BRENDAN,
        .backPic = TRAINER_BACK_PIC_BRENDAN,
    },
    {
        .name = sName_May,
        .roster = sRoster_May,
        .owGfxId = OBJ_EVENT_GFX_MAY_NORMAL,
        .trainerFrontPic = TRAINER_PIC_MAY,
        .backPic = TRAINER_BACK_PIC_MAY,
    },
    {
        .name = sName_Lucas,
        .roster = sRoster_Lucas,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Dawn,
        .roster = sRoster_Dawn,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Hilbert,
        .roster = sRoster_Hilbert,
        .owGfxId = OBJ_EVENT_GFX_HILBERT_NORMAL,
        .trainerFrontPic = TRAINER_PIC_HILBERT,
        .backPic = TRAINER_BACK_PIC_HILBERT,
    },
    {
        .name = sName_Hilda,
        .roster = sRoster_Hilda,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Nate,
        .roster = sRoster_Nate,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Rosa,
        .roster = sRoster_Rosa,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Calem,
        .roster = sRoster_Calem,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Serena,
        .roster = sRoster_Serena,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Elio,
        .roster = sRoster_Elio,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Selene,
        .roster = sRoster_Selene,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Victor,
        .roster = sRoster_Victor,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Gloria,
        .roster = sRoster_Gloria,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Blue,
        .roster = sRoster_Blue,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Lance,
        .roster = sRoster_Lance,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Steven,
        .roster = sRoster_Steven,
        .owGfxId = OBJ_EVENT_GFX_STEVEN,
        .trainerFrontPic = TRAINER_PIC_STEVEN,
        .backPic = TRAINER_BACK_PIC_STEVEN,
    },
    {
        .name = sName_Iris,
        .roster = sRoster_Iris,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Kukui,
        .roster = sRoster_Kukui,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Koga,
        .roster = sRoster_Koga,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Flint,
        .roster = sRoster_Flint,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Brock,
        .roster = sRoster_Brock,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Misty,
        .roster = sRoster_Misty,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_LtSurge,
        .roster = sRoster_LtSurge,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Erika,
        .roster = sRoster_Erika,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Sabrina,
        .roster = sRoster_Sabrina,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_CrasherWake,
        .roster = sRoster_CrasherWake,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Silver,
        .roster = sRoster_Silver,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Wally,
        .roster = sRoster_Wally,
        .owGfxId = OBJ_EVENT_GFX_WALLY,
        .trainerFrontPic = TRAINER_PIC_WALLY,
        .backPic = TRAINER_BACK_PIC_WALLY,
    },
    {
        .name = sName_Barry,
        .roster = sRoster_Barry,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Bianca,
        .roster = sRoster_Bianca,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Shauna,
        .roster = sRoster_Shauna,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_Ash,
        .roster = sRoster_Ash,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_MistyAnime,
        .roster = sRoster_MistyAnime,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_BrockAnime,
        .roster = sRoster_BrockAnime,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_MayAnime,
        .roster = sRoster_MayAnime,
        .owGfxId = OBJ_EVENT_GFX_MAY_NORMAL,
        .trainerFrontPic = TRAINER_PIC_MAY,
        .backPic = TRAINER_BACK_PIC_MAY,
    },
    {
        .name = sName_DawnAnime,
        .roster = sRoster_DawnAnime,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_SerenaAnime,
        .roster = sRoster_SerenaAnime,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_IrisAnime,
        .roster = sRoster_IrisAnime,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_CilanAnime,
        .roster = sRoster_CilanAnime,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_ClemontAnime,
        .roster = sRoster_ClemontAnime,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_LillieAnime,
        .roster = sRoster_LillieAnime,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_KiaweAnime,
        .roster = sRoster_KiaweAnime,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
    {
        .name = sName_LanaAnime,
        .roster = sRoster_LanaAnime,
        .owGfxId = CHAR_ASSET_NONE,
        .trainerFrontPic = CHAR_ASSET_NONE,
        .backPic = CHAR_ASSET_NONE_U8,
    },
};

#define NUM_CHARACTERS (ARRAY_COUNT(gCharacters))
